### ISSUE TITLE
Tmux is out of date and not a stable release

### ISSUE THREAD

**Issue by AgDude** [msys2/MSYS2-packages#1074]
The current package for tmux is not a stable release from tmux core. 

Tmux is currently not working for me, and troubleshooting is made more difficult by the fact that it is not pointing to a release. It should be updated to the 2.6 release tag, not the git master.

**Comment by ErichDonGubler** [comment]
This sounds like an excellent pull request! :) I know that I've been disconcerted by the "please use tmux 2.2+ for X feature" message whenever `continuum` does its job...

**Comment by fsworld009** [comment]
https://github.com/fsworld009/MSYS2-packages/tree/patch/tmux

I created a `tmux` package that points to stable releases, it can be built and installed under MSYS2 shell.
However, msys2 is not my main development environment so I have not used much for this build and I don't know if there is any issue.

**Comment by gena01** [comment]
Fixed by #1084

**Comment by eromoe** [comment]
Can you guys take a look at this tmux problem ? 
https://github.com/Alexpux/MSYS2-packages/issues/1107

**Comment by gena01** [comment]
@eromoe it's working for me with 2.6

Can this one be closed now that #1084 is merged?

**Comment by yashpalgoyal1304** [comment]
is this issue a close candidate?

**Comment by mati865** [comment]
Closing since tmux is up to date with upstream now.

**Comment by yashpalgoyal1304** [comment]
can https://github.com/msys2/MSYS2-packages/issues/3093 be related to this??
