### ISSUE TITLE
Installer does not run on Server 2016 Core

### ISSUE THREAD

**Issue by ghost** [msys2/MSYS2-packages#1092]
Trying to run the installer just returns to the command prompt, where nothing at all has happened.

![image](https://i.imgur.com/CdxPNza.png)

Any ideas?

**Comment by StarWolf3000** [comment]
Your Server 2016 Core lacks a GUI, so you are required to install the GUI for Server 2016 (via PowerShell or DISM for example) to support and access GUI applications.

**Comment by john-peterson** [comment]
It's not a GUI application

**Comment by john-peterson** [comment]
Are there other ways to install it? scoop?

**Comment by john-peterson** [comment]
The usual

```
msys.exe install --root c:\msys --confirm-command
```

is just non functional

**Comment by Biswa96** [comment]
Have you tried the .sfx.exe files from here https://github.com/msys2/msys2-installer/releases ?

**Comment by john-peterson** [comment]
I got a prompt!

```
msys.sfx.exe
msys2_shell.cmd -defterm -here -no-start -ucrt64
```

**Comment by Biswa96** [comment]
So, the issue is solved, right?

**Comment by john-peterson** [comment]
By the way a friendly neighbor helped me run it inside rdp

It runs as usual

It tells you a file is missing in a nice friendly window 

Opengl32.dll
