### ISSUE TITLE
repo.msys2.org very slow or unreachable

### ISSUE THREAD

**Issue by looeee** [msys2/MSYS2-packages#1098]
Seems like upgrading ruby on Windows just became much more complicated....

Anyway, my issues are, when running:
`ridk install 1`:

```js
Verify integrity of msys2-x86_64-20161025.exe ... Failed
Download http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe
  to C:\Users\looee\AppData\Local\Temp/msys2-x86_64-20161025.exe
Downloading msys2-x86_64-20161025.exe (  0%)
Verify integrity of msys2-x86_64-20161025.exe ... Failed
Download http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe
  to C:\Users\looee\AppData\Local\Temp/msys2-x86_64-20161025.exe
Downloading msys2-x86_64-20161025.exe (  0%)
Verify integrity of msys2-x86_64-20161025.exe ... Failed
Download http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe
  to C:\Users\looee\AppData\Local\Temp/msys2-x86_64-20161025.exe
```

Tried downloading `http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20161025.exe` manually and I was getting speeds of <1kb/s. 

After installing from a different location  and running `ridk install 2` - many errors such as 

```js
error: failed retrieving file 'pacman-5.0.1-4-x86_64.pkg.tar.xz' from repo.msys2.org : transfer closed with 7036272 bytes remaining to read
```

My internet connection is fine (speedtest around 30mbs and downloads from other sites work fine). 
Could this be a regional thing, since I am based in Vietnam?

**Comment by looeee** [comment]
OK, after waiting for hours and repeating multiple times while consistently getting download speeds <1kbs I've given up and reverted to Ruby 2.3.3, the lastest version that doesn't require msys2.

**Comment by laurenanyever** [comment]
the same thing is happening with me. 

In the initial MSYS2 installation, Mingw-w64 attempts to update from repo.msys2.org which is down or unavailable to my IP because of my internet provider? That seems strange considering that I nearly live in downtown Los Angeles.

I've tried pinging and building but every time it can't update anything from repo.msys2.org because it is unavailable to me. Is there a way I can point it to update everything from a mirror site?

This has been a known issue with people but it seems like there's no resolution really.
[repo.msys2.org down unreachable] (Alexpux/MSYS2-packages#849)

when pinging i get: 
$ ping repo.msys2.org

Pinging diablo.msys2.org [45.59.69.178] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 45.59.69.178:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),

**Comment by eromoe** [comment]
You need set mirror .

You can use below if you are near in China 

For example:

```
Server = http://mirrors.ustc.edu.cn/msys2/mingw/x86_64
Server = http://mirror.bit.edu.cn/msys2/REPOS/MINGW/x86_64
Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/x86_64
```

**Comment by looeee** [comment]
@eromoe is that documented anywhere? 

From my perspective this means that upgrading ruby on windows is currently broken for anybody in Asia. Which is a pretty huge portion of the world. This should really be automatic.

**Comment by eromoe** [comment]
I think not just ruby, the connection speed to repo.msys2.org is slow in your country . It is always slow in China, so we have to use a mirror repo for pacman , just like we need set mirror for ubuntu's apt-get.

**Comment by PhilLab** [comment]
Also not reachable for me (Europe, Germany)

and for https://downforeveryoneorjustme.com/msys2.org as well (don't know their server's location)

**Comment by MaverickTse** [comment]
This really needs to be fixed as other build systems that use msys2 are also affected, e.g. vcpkg. I can't access repo.msys2.org from Hong Kong and Japan either.

**Comment by c0d3h4x0r** [comment]
+1, hitting the same problem here.  Fix your server(s), please!

**Comment by slappycat2** [comment]
Same for me.

**Comment by rurban** [comment]
Which mirror to use for appveyor? It's down for a day.

**Comment by kode54** [comment]
Super slow from California, and it's not possible to set another mirror when at the msys2 installer stage.

**Comment by lazka** [comment]
Anyone having problems still? We have steadily tried to improve things over the past year.

**Comment by AzureMarker** [comment]
Seeing slowness today:
```
error: failed retrieving file 'mingw-w64-x86_64-libgccjit-11.2.0-2-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gcc-objc-11.2.0-2-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'mingw-w64-x86_64-gcc-11.2.0-2-any.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: too many errors from repo.msys2.org, skipping for the remainder of this transaction
warning: failed to retrieve some files
```

**Comment by lazka** [comment]
yeah, hetzner seems to be having problems

**Comment by AzureMarker** [comment]
The slowness seems to only be happening on those older packages. We're using them to downgrade to avoid https://github.com/msys2/MINGW-packages/issues/10295. But looks like the antivirus issue might be fixed.

**Comment by lazka** [comment]
> yeah, hetzner seems to be having problems right now
> 
> maybe related to https://status.hetzner.com/incident/b90d7054-17af-4eae-a861-7ea9bfc489db

things are back to normal here

**Comment by lazka** [comment]
I'm closing this so we don't spam users with this. If there are any related problems please file a new issue and I'll have a look.
