### ISSUE TITLE
msys2_shell.cmd has mixed newlines and causes cmd.exe to barf

### ISSUE THREAD

**Issue by jstine35** [msys2/MSYS2-packages#1171]
## Problem:
Running freshly installed `msys2-x86_64-20170918.exe`, updated via PacMan on 2/20/18.  When I try to run the `msys2_shell.cmd -conemu` option, I get the following error:

```C:\msys64>msys2_shell.cmd -conemu
The system cannot find the batch label specified - conemudetect
ConEmu not found. Exiting.
```

## Solution:
Please ensure all `*.cmd` files in the msys2 installer distro are normalized as `CRLF`.

## Details:
As per [information stated here](https://stackoverflow.com/questions/232651/why-the-system-cannot-find-the-batch-label-specified-is-thrown-even-if-label-e#232674), I decided to run the .cmd through `dos2unix`.  This fixed the problem on my local environment.

**Comment by ErichDonGubler** [comment]
This sounds like an easy PR!

**Comment by jstine35** [comment]
After some reflection - This should be best solved as either a `.gitattributes` rule for `.bat` and `.cmd` , or an installer script step that executes `unix2dos`.  I'm not sure offhand which makes more sense in the context of the MSYS2 software suite.  The least desirable solution is simply checking in a normalized version of the file -- it'll just get corrupted again the next time anyone modifies it.

**Comment by tanzislam** [comment]
I've added a `.gitattributes` entry in #1795.

**Comment by hiroakit** [comment]
@jstine35 
If you have been resolve the issue, would you close it?

@Alexpux 
Please check this issue.
PR https://github.com/msys2/MSYS2-packages/pull/1795 also merged.

**Comment by hiroakit** [comment]
@jstine35 
Thank you.
