### ISSUE TITLE
Maybe MSYSize patch not required

### ISSUE THREAD

**Issue by walker27460** [msys2/MSYS2-packages#1173]
If add their command in prepare() function
```bash

wget -O ${srcdir}/config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
wget -O ${srcdir}/config.sub 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD'
```
Maybe MSYSize Patch not required

**Comment by Biswa96** [comment]
msys-ize patches are being removed slowly. The plan is to reduce the difference between msys2 and cygwin projects. See the todo list here https://www.msys2.org/wiki/Devtopics/
