### ISSUE TITLE
Msys2 PATH is inherited from Windows PATH altough MSYS2_PATH_TYPE is not set

### ISSUE THREAD

**Issue by Youda008** [msys2/MSYS2-packages#1179]
I recently discovered, that my PATH variable inside Msys2 environment is full of Windows balast, that i don't want there, but i can't disable this behaviour. MSYS2_PATH_TYPE in my msys2.ini is commented out and when i print this var in bash, it's empty.
![msys2path](https://user-images.githubusercontent.com/20306543/36640484-f30686fc-1a1f-11e8-9733-3cd448d0f576.png)
Can someone help me diagnose this problem and possibly fix the bug in Msys files, so it doesn't happen again?

**Comment by niklasholm** [comment]
How do you start your terminal? Have you edited any files, for example /etc/profile or msys2_shell.cmd?

**Comment by Youda008** [comment]
I start it with a shortcut that contains command
C:\msys64\msys2_shell.cmd -msys
The script is original.

Today I have tested it on another machine. I installed a fresh Msys2 and only updated according to this: http://www.msys2.org/
Immediatelly after that, the PATH already contained entries from Windows.

**Comment by niklasholm** [comment]
Can't reproduce the issue. Please make sure your filesystem package is up-to-date (`pacman -Sy --needed filesystem`). If the issue persists please run the following command and attach bash-trace.txt to your answer.

```shell
$ bash -xlic exit &>bash-trace.txt
```

**Comment by Youda008** [comment]
Package `filesystem` is up to date.
[bash_trace.txt](https://pastebin.com/raw/RZANJXze)
When searching for the output file, i also found, my home directory ~ is set to `/c/Users/Youda` instead of `/home/Youda`, but i'm not sure if this is intended behaviour. Maybe it's related issue.

**Comment by Youda008** [comment]
Oh and by the way, running another pacman -Syu gives me this
![update_error](https://user-images.githubusercontent.com/20306543/36837811-a8fa0cf2-1d3d-11e8-845a-0db87f06971d.png)
It might have something to do with the fact i installed `git-for-windows/mingw-w64-x86_64-git`
according to these instructions: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

**Comment by niklasholm** [comment]
That's an unsupported configuration. Especially the git-extra package from gow does loads of stuff that messes with the environment, including [this](https://github.com/git-for-windows/build-extra/search?utf8=%E2%9C%93&q=MSYS2_PATH_TYPE&type=):

```sh
grep -q 'case "\${MSYS2_PATH_TYPE:-inherit}"' /etc/profile ||
sed -i 's/{MSYS2_PATH_TYPE:-[^}]*}/{MSYS2_PATH_TYPE:-inherit}/g' \
/etc/profile
```

There's your problem

**Comment by Youda008** [comment]
Damnit. And i thought that i will be able to use just one Msys installation for everything, instead of having one for Git (as Git-For-Windows) and another for everything else. That does not make sense, then when i open Git Bash, i can't use my installed Unix tools, because they are in the other Msys. Sure i can install SDK version and install the packages there too, but that's even more stupid to have them twice.
I guess i will be contacting them with request of a cleaner solution. 

Thanks for your help.

**Comment by BudiKusasi** [comment]
> I recently discovered, that my PATH variable inside Msys2 environment is full of Windows balast, that i don't want there, but i can't disable this behaviour. MSYS2_PATH_TYPE in my msys2.ini is commented out

It defaults to append it irrespective to  MSYS2_PATH_TYPE set or not
to really prevent it to do such, both must be on setting wiht PATH nullyfied by "" - double quote pair :

MSYS2_PATH_TYPE=inherit
PATH=""

**Comment by blueyed** [comment]
This issue can be closed.

**Comment by Youda008** [comment]
Yes
