### ISSUE TITLE
Current pacman refuses to run on Vista

### ISSUE THREAD

**Issue by okhlybov** [msys2/MSYS2-packages#1181]
Upgrading from latest binary [MSYS2](https://sourceforge.net/projects/msys2/files/Base/i686/msys2-i686-20170918.exe) package to current breaks pacman on Windows Vista due to undefined `BCryptDeriveKeyPBKDF2` entry point in `bcrypt.dll` which has been [introduced](https://msdn.microsoft.com/en-us/library/windows/desktop/dd433795(v=vs.85).aspx) in Windows 7.

**Comment by Alexpux** [comment]
Well this is from mingw-w64 runtime. Many peoples are thinking about dropping XP an Vista support

**Comment by okhlybov** [comment]
OK then. Isn't it a time to update introductory screen with new minimum OS requirements?
