### ISSUE TITLE
MSYS2 issues in GitHub project are disabled

### ISSUE THREAD

**Issue by Beep6581** [msys2/MSYS2-packages#1192]
The MSYS2 website says "file issues on GitHub", however https://github.com/msys2/msys2 has issues disabled. Where is one supposed to file MSYS2 issues?

**Comment by jtanx** [comment]
Here or https://github.com/alexpux/mingw-packages

**Comment by Beep6581** [comment]
@jtanx if MSYS2-**packages** is indeed the correct place to file MSYS2 bug reports unrelated to packages, then the website needs to be updated. Well, it needs to be update either way.

**Comment by jtanx** [comment]
From https://github.com/msys2/msys2:

> ## Issues must to be posted into MINGW or MSYS2 packages repositories ONLY.

**Comment by Beep6581** [comment]
From http://www.msys2.org/
> file issues on GitHub https://github.com/msys2/msys2/issues

**Comment by chhh** [comment]
From msys2 repo it looks like the project is dead with issue tracker closed. That comment in the end of README doesn't really help.  
Published a PR with better directions for future users with similar issues.

**Comment by AMDphreak** [comment]
Agree. Website should point here or at least not mislead anyone following the link. explicitly pointing people to a nonexistent issues page is unhelpful, even if it's just to see who reads the instructions and who doesn't. Need a new strategy.

**Comment by Biswa96** [comment]
Reporting issue is now easier. First, search the package here https://packages.msys2.org/search and click on the appropriate one. Click on the "Report Issue" link which will automatically redirect to issues page.
