### ISSUE TITLE
support windows 10 unprivileged symlinks

### ISSUE THREAD

**Issue by rkitover** [msys2/MSYS2-packages#1219]
Cygwin has added support for the new Windows 10 feature allowing unprivileged users to create symlinks, could we get this feature added in the msys2 runtime? It may be just a matter of updating the package to use newer cygwin sources.

**Comment by mirh** [comment]
Duplicate of #847

**Comment by saschanaz** [comment]
`ln -s` now works without an admin privilege, so this probably can be closed.

**Comment by mati865** [comment]
Yeah it works fine after commenting `set MSYS=winsymlinks:nativestrict` from `/msys2_shell.cmd`.

**Comment by rkitover** [comment]
Just to be sure, you did not have to turn on developer mode in settings for this to work?

**Comment by saschanaz** [comment]
Unprevileged symlinks need developer mode, so yes I did.

**Comment by rkitover** [comment]
Same thing in powershell anyway.
