### ISSUE TITLE
git-gui fails to execute due to missing resources

### ISSUE THREAD

**Issue by luismbo** [msys2/MSYS2-packages#124]
I've installed git-2.1.3-1 via pacman. Running `git gui` yields the following error:

![image](https://cloud.githubusercontent.com/assets/45759/5093498/cca600be-6f50-11e4-8cba-0db092ea25b2.png)

FWIW, commenting out that iconbitmap command, triggers another similar error referencing other missing files in `/usr/share/git-gui/lib`.

**Comment by wiiaboo** [comment]
I've found two ways of making `git gui` work with Msys Git.

One is changing `set oguirel {}` to `set oguirel {1}` so the script looks for path itself.

Another is setting and exporting $GIT_GUI_LIB_DIR, like
`export GIT_GUI_LIB_DIR=$(cygpath -w /usr/share/git-gui/lib)`
