### ISSUE TITLE
configure.ac error: possibly undefined macro: PKG_CHECK_MODULES

### ISSUE THREAD

**Issue by liudonghua123** [msys2/MSYS2-packages#1255]
When I want to compile https://github.com/GNOME/libgnome-games-support on my MSYS2, I have installed all the required library like gee/gio/glib/gtk, and I also updated/reinstalled libtool and pkg-config.
But When I execute `/.autogen.sh`. It gave me the following error message.
![image](https://user-images.githubusercontent.com/2276718/40152728-f52cf42e-59b8-11e8-90e1-d3d0d6dc6e5a.png)

I also have tried add `m4_pattern_allow(PKG_CHECK_MODULES)` to `configure.ac` like https://github.com/bitcoin/bitcoin/issues/6602. But it still not worked.

**Comment by liudonghua123** [comment]
Actually, I have already installed `mingw32/mingw-w64-i686-pkg-config`, and the version is `0.29.2`.
I tried to reinstall both packages. But the errors still exist.
![image](https://user-images.githubusercontent.com/2276718/40297434-7a978dd4-5d12-11e8-94ee-5b9abbad4719.png)

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/40297868-ce167c30-5d13-11e8-822f-91502e961c6d.png)

**Comment by Casper0513** [comment]
> ![image](https://user-images.githubusercontent.com/2276718/40297868-ce167c30-5d13-11e8-822f-91502e961c6d.png)

is this solved yet???

**Comment by Biswa96** [comment]
Can you provide the repository link to reproduce this issue?

**Comment by liudonghua123** [comment]
@Biswa96 @Casper0513 It is almost 4 years, I did not have that environment. I see https://github.com/GNOME/libgnome-games-support has changed a lot, maybe it has fixed this issue. I will close this issue. If I encounter the same issue later, I will go back and reopen this issue. 
Thanks! 😄
