### ISSUE TITLE
MSYS2 clang 3 too old with bugs

### ISSUE THREAD

**Issue by d3vv** [msys2/MSYS2-packages#1263]
$ clang++ -v
clang version 3.8.0 (/repo/sources/clang 1d5b05f1ef9d1b9889ddb5ad946944f224a7ba88) (/repo/sources/llvm 2aebced35905eb3891eba484e4d1902cf7399558)
Target: x86_64-pc-msys
Thread model: posix
InstalledDir: /usr/bin

So we have unusable clang  into MSYS2 and MINGW32:

BitBoards.cpp:2:10: fatal error: 'iostream' file not found
#include <iostream>
         ^
1 error generated.
Board.cpp:1:10: fatal error: 'locale' file not found
#include <locale>
         ^
1 error generated.
Eval.cpp:1:10: fatal error: 'algorithm' file not found
#include <algorithm>
Main.cpp:7:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^
1 error generated.
In file included from SEE.cpp:4:
In file included from ./BitBoards.h:4:
/usr/bin/../lib/clang/3.8.0/include/intrin.h:26:15: fatal error: 'Intrin.h' file not found
#include_next <Intrin.h>
              ^
1 error generated.

There is no issues into MINGW64 LLVM cause we have clang version 5.0.1 ..

**Comment by Alexpux** [comment]
@d3vv feel free to provide updates. MSYS-clang was experimental package and currently dont have any maintainer for it

**Comment by d3vv** [comment]
So, Cygwin has:
```
$ clang -v
clang version 5.0.1 (tags/RELEASE_501/final)
Target: x86_64-unknown-windows-cygnus
Thread model: posix
InstalledDir: /usr/bin
```

Could it possible to port it as MSYS2-package?

**Comment by Alexpux** [comment]
I’m not planning to provide clang for Msys, old will be removed. Use mingw clang
