### ISSUE TITLE
[PACKAGE REQUEST] agg library (antigrain)

### ISSUE THREAD

**Issue by franko** [msys2/MSYS2-packages#1281]
Hi all,

I am using MSYS2 since some time. It is an outstanding project that simplifies the development on Windows for those we don't use Visual Studio. Thank you for your great work.

I would like to request if possible to add a package for the AGG library (antigrain library). A package for archlinux exists so I guess that it can be added in MSYS2 quite easily.

Currently I compile the AGG library by myself but I would prefer to have a package. I could create a package myself but I don't know how to do and to learn would take me a lot of time so I was wondering if can be done by one of the MSYS2 experts.

In addition I have a question about the Freetype library. I have seen that in the MSYS2 freetype pulls in dependencies for many libraries like glib or gobject, not sure, and other libraries as well. I wonder if you may consider adding a freetype package with minimal dependencies on other libraries ?

Thank in advance for any help.

Kind regards
Francesco

**Comment by igagis** [comment]
Hi,

in case you are still interested, I have created an `agg` package in my own pacman repo for `msys2`.
See details here:
https://github.com/igagis/agg

**Comment by franko** [comment]
Hi @igagis, thank you for sharing.

Actually I have created my own antrigrain repository that use Meson to build (https://github.com/franko/antigrain) and I have developed a whole system to help to compile and install libraries on linux and on Windows:

https://github.com/franko/lhelper

Using lhelper I no longer rely on Msys2 package for development libraries but I use Msys2 only as a system to provide the compiler toolchain.
