### ISSUE TITLE
GIT error when cloning a repo using an URL with https://... schema

### ISSUE THREAD

**Issue by rhornig** [msys2/MSYS2-packages#133]
Using msys git 2.1.3 installed by pacman. When trying to clone a REPO using a http or https URL it complains:

fatal: Unable to find remote helper for 'https'

URLs starting with git@.. are working fine.

**Comment by yurikoles** [comment]
@Alexpux 
```pacman -S curl libcurl ca-certificate openssl libopenssl p11-kit```
there is a typo: ca-certificate**S**
