### ISSUE TITLE
pacman build error due to liblz4

### ISSUE THREAD

**Issue by jeroen** [msys2/MSYS2-packages#1420]
Currently trying to rebuild pacman from source fails with:

```
gcc -pedantic -D_GNU_SOURCE -Wall   -march=i686 -mtune=generic -O2 -pipe --static -pipe -o pactree.exe pactree.o -larchive -lcrypto -lnettle -lacl -lexpat -llzma -llz4 -lbz2 -lz -lbcrypt -lalpm -lm -larchive -lcrypto -lnettle -lacl -lexpat -llzma -lbz2 -lz -lbcrypt -lcrypto -lz -lcurl -lssl -lcrypto -lssl -lz -lcrypto -lz -lgdi32 -lz -lgpgme -lassuan -lgpg-error -lintl -liconv 
mv paccache.service.tmp paccache.service
/usr/lib/libarchive.a(archive_read_support_filter_lz4.o):(.text+0x5b2): undefined reference to `LZ4_decompress_safe'
/usr/lib/libarchive.a(archive_read_support_filter_lz4.o):(.text+0x88b): undefined reference to `LZ4_decompress_safe_usingDict'
/usr/lib/libarchive.a(archive_read_support_filter_lz4.o):(.text+0x8cf): undefined reference to `LZ4_decompress_safe'
collect2: error: ld returned 1 exit status
```

Probably related to [this change](https://github.com/Alexpux/MSYS2-packages/commit/24b89d97e4008459aa8e40628c06f82312fd1b21). I think the order of the linking libs may be the problem?

**Comment by jeroen** [comment]
Full build log here: https://ci.appveyor.com/api/buildjobs/4xdftoh0cjcbsplq/log

**Comment by piotrvv** [comment]
Pacman does not support lz4. This entry from the git repository says about it.
https://git.archlinux.org/pacman.git/commit/?id=0cbb128818726e4d41964ea8df8c42ee37697ef7

**Comment by lazka** [comment]
I guess that's fixed now.

Static linking errors still happen a lot because most upstreams don't test for it.
