### ISSUE TITLE
"script" utility is missing (after update to "util-linux-2.32.1-1-x86_64")

### ISSUE THREAD

**Issue by sskras** [msys2/MSYS2-packages#1441]
`scriptreplay.exe` is present but `script.exe` is missing:

```
$ pacman -Q util-linux
util-linux 2.32.1-1

$ pacman -Ql util-linux | grep -i script
util-linux /usr/bin/scriptreplay.exe
util-linux /usr/share/bash-completion/completions/scriptreplay
util-linux /usr/share/man/man1/scriptreplay.1.gz
```

I see only a single recent commit 2657cacd691a932f1f3283997af15e567496ee32 in [Alexpux/MSYS2-packages/commits/master/util-linux](https://github.com/Alexpux/MSYS2-packages/commit/2657cacd691a932f1f3283997af15e567496ee32#diff-eb95ebf993909eaa0d8620ec88f2f32c).

Can I have a quick workaround by downloading earlier version of the package?

**Comment by peterbud** [comment]
See: https://github.com/Alexpux/MINGW-packages/issues/4497

**Comment by sskras** [comment]
Thanks Peter, I worked around this by installing older version of the package:
http://repo.msys2.org/msys/x86_64/util-linux-2.26.2-1-x86_64.pkg.tar.xz

Can someone close this as a dup of [Alexpux/MINGW-packages#4497](https://github.com/Alexpux/MINGW-packages/issues/4497) issue please?

**Comment by piotrvv** [comment]
@sskras You can close the report of this error yourself.
There used to be a "New issue" button. Now there is the "close" button.

**Comment by sskras** [comment]
Duplicate of [MINGW-packages/issues/4497](https://github.com/Alexpux/MINGW-packages/issues/4497), closing.
