### ISSUE TITLE
Provided Texinfo fails to create documentation for recent binutils/gcc versions

### ISSUE THREAD

**Issue by cr1901** [msys2/MSYS2-packages#1460]
## Context
I've been having trouble building recent versions of `gcc` for cross-compilation/microcontroller purposes, under the `msys2` environment.

One such example is trying to compile is the official [riscv-toolchain](https://github.com/riscv/riscv-gnu-toolchain). To duplicate my bug, one can clone the riscv-toolchain repo, and run the following commands (the separate build directory and `configure` args I used most likely aren't actually important):

```
../riscv-gnu-toolchain/configure --prefix=/opt/dummy --with-arch=rv32i
make
```

## Actual Behavior
After invoking `make`, the build will start compiling binutils, and will make it relatively far into the compile before erroring out on building `info` pages.

The failing command, in full is:

```
William@William-THINK MINGW64 ~/src/build-bin-bug/build-binutils-newlib/ld
$ makeinfo --split-size=5000000 --split-size=5000000 -I /home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld -I /home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/../bfd/doc -I ../bfd/doc -I /home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/../libiberty  -I /home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld  -o ld.info /home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:362: table requires an argument: the formatter for @item
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:2523: table requires an argument: the formatter for @item
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:3003: table requires an argument: the formatter for @item
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:3035: table requires an argument: the formatter for @item
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:3063: table requires an argument: the formatter for @item
/home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:3086: table requires an argument: the formatter for @item
'home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:4748: unknown command `
'home/William/src/build-bin-bug/../riscv-gnu-toolchain/riscv-binutils/ld/ld.texinfo:4752: unknown command `

William@William-THINK MINGW64 ~/src/build-bin-bug/build-binutils-newlib/ld
```

## Expected Behavior
I would expect `texinfo` to not bomb while creating documentation. Is this a known issue with the provided `texinfo` when creating packages, and if so, is there a workaround or fix? Forcing the build to skip info files isn't an ideal solution (see Other Information).

## Other Information
_When I `touch ld.info` manually to skip this step, more `makeinfo` failures occur while building gcc. The instructions provided are just the quickest way to duplicate a failure IME.

Additionally, I submitted this error to [riscv-binutils-gdb](https://github.com/riscv/riscv-binutils-gdb) in [early 2017](https://github.com/riscv/riscv-binutils-gdb/issues/53), and was told they didn't touch the `info` pages. I've only _now_ just gotten around to filing a bug report :P.

### Makeinfo version
```
William@William-THINK MINGW64 ~/src/build-bin-bug/build-binutils-newlib/ld
$ makeinfo -V
texi2any (GNU texinfo) 6.3

Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### Pacman (and MSYS2?) version
```
William@William-THINK MINGW64 ~/src/build-bin-bug/build-binutils-newlib/ld
$ pacman -V

 .--.                  Pacman v5.1.0 - libalpm v11.0.0
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2018 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet
 '--'
                       This program may be freely redistributed under
                       the terms of the GNU General Public License.
```

**Comment by coldacid** [comment]
I've seen this elsewhere (and looked it up) and chances are it's a line-ending issue from when the files are checked out. Try `find -iname "*.texi" -exec dos2unix '{}' \;` before running Texinfo.

**Comment by cr1901** [comment]
>I've seen this elsewhere (and looked it up) and chances are it's a line-ending issue from when the files are checked out. Try find -iname "*.texi" -exec dos2unix '{}' \; before running Texinfo.

@coldacid This is the correct answer, thanks!

In this specific case, what I did was create attributes file for the repo and submodules, like so:

```
#!/bin/sh

cat << EOF > .gitattributes
* text=auto

*.texi text eol=lf
*.texinfo text eol=lf
EOF
git read-tree --empty
git reset --hard

for i in `grep path .gitmodules | sed 's/.*= //'`; do
  cat << EOF > .git/modules/$i/info/attributes
* text=auto

*.texi text eol=lf
*.texinfo text eol=lf
EOF

pushd $i
git read-tree --empty
git reset --hard
popd
done
```
