### ISSUE TITLE
Bash ANSI color support?

### ISSUE THREAD

**Issue by etamponi** [msys2/MSYS2-packages#1494]
Hello! When I use the bash.exe provided with msys2, I don't get a complete support for ANSI colors, which is strange since even cmd.exe supports them... is there something I am missing, or is it a limitation of the provided executable?

Thanks!

**Comment by dustwanderer** [comment]
Hello,
In my case, `echo`, and `printf` work fine inside mintty.

Inside Windows' `cmd.exe`: `bash.exe`, `echo.exe`, and `printf.exe` can display the dark colors, both background and foreground (ANSI escape codes 30-37 and 40-47). They can not display the bright colors 90-97 and 100-107.

Inside `cmd.exe`, MSYS2's programs can display the bright foreground colors by adding 1, the ANSI code for increased brightness. So: 31 displays dark red foreground. 91 does not change the display. 31;1 or 1;31 display bright red foreground. MSYS2's programs can display bright background colors by adding 7, the ANSI code for switch background/foreground. 1;31;7 displays bright red foreground.

Thanks

**Comment by dustwanderer** [comment]
Sorry, in my previous post I meant that 1;31;7 displays bright red background (not foreground).

**Comment by Luiz-Monad** [comment]
seems like ansi detection is broken now that windows has ansi support

**Comment by Biswa96** [comment]
How can I reproduce the issue?

**Comment by Luiz-Monad** [comment]
Looks like this problem https://github.com/microsoft/terminal/issues/2837

**Comment by Biswa96** [comment]
The command given in that thread is working fine. I am using mintty.

![image](https://user-images.githubusercontent.com/31443074/181154247-d5002d12-96fc-4763-8333-3dfa9787cf5b.png)

**Comment by Luiz-Monad** [comment]
Install microsoft-windows-terminal from chocolatey with `cinst microsoft-windows-terminal`
Install msys2 from chocolatey too. `cinst msys2`

Nevermind, I updated the dependency, now it works.

![image](https://user-images.githubusercontent.com/4574729/181154963-95bd06f0-727b-428e-abe1-f8222547cf6a.png)

**Comment by Luiz-Monad** [comment]
I think was using the borked version that came with some git app, sorry.

**Comment by Luiz-Monad** [comment]
Sorry about bothering again. I think I found the culprit. 

![image](https://user-images.githubusercontent.com/4574729/181160539-ab50948b-0e8b-4229-aa28-b5738fdc58be.png)

**Comment by Luiz-Monad** [comment]
Whatever is that's happening, its funny. 
![image](https://user-images.githubusercontent.com/4574729/181295178-450f8624-9617-447b-9de8-932178a48469.png)

POpen only duplicate file handles. I don't get why it doesn't work with msys2 bash.

**Comment by Biswa96** [comment]
As previous, it works in mintty 😄 

![image](https://user-images.githubusercontent.com/31443074/181298423-1079c832-8fb4-4d26-8319-f2ab08deb9eb.png)

There are many variables in your given setup. Windows Terminal and PowerShell have their own mindset. This issue may provide some hint https://github.com/msys2/MSYS2-packages/issues/2214.

**Comment by Luiz-Monad** [comment]
Want something funny ? 
![image](https://user-images.githubusercontent.com/4574729/181366530-655847c2-6313-4576-9ac5-5e958c529548.png)
left is powershell on linux, right is powershell on windows

powershell is clearly working exactly the same.

**Comment by Luiz-Monad** [comment]
I think pwsh does a flush in the file handle. https://github.com/PowerShell/PowerShell/blob/b780a34ad1a8b0fb4aa02c5a486d1e9a995615ab/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHost.cs#L514

This is how it sets up its VT https://github.com/PowerShell/PowerShell/blob/b780a34ad1a8b0fb4aa02c5a486d1e9a995615ab/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleHostUserInterface.cs#L57

**Comment by Luiz-Monad** [comment]
I finished another task of mine, and I had to take at it again.
I have some captures, the problem reproduces on python.

```python
print('\033[38;2;255;0;0mHi 0 \033[0m')
import subprocess
subprocess.check_call(['bash', '-c', ' printf \"\033[38;2;255;0;0mHi 1\033[0m\" '])
subprocess.check_call(['pwsh', '-nop', '-c', ' write-output \"\033[38;2;255;0;0mHi 1\033[0m\" '])
```

[http://www.rohitab.com/apimonitor](url)
[capture-msys.zip](https://github.com/msys2/MSYS2-packages/files/9205447/capture-msys.zip) 
 
The only difference I found is that pwsh doesn't do a FreeConsole().

Now I have something ! 
I thought I was going insane. It can't be just me, when I call msys from python, something crazy happen. 
Perhaps you don't need to do a FreeConsole if you detect you have access to VT.

FreeConsole is resetting something, at least that's what I think.


<details>
<summary>systeminfo</summary>

```
C:\Users\LuizMonad
λ systeminfo

Host Name:                 LUIZMONAD
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00329-00000-00003-AA160
Original Install Date:     2021-07-26, 2:45:24 AM
System Boot Time:          2022-07-25, 1:30:56 AM
System Manufacturer:       MSI
System Model:              MS-7885
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 63 Stepping 2 GenuineIntel ~3300 Mhz
BIOS Version:              American Megatrends Inc. 1.E0, 2018-06-15
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     32,668 MB
Available Physical Memory: 5,212 MB
Virtual Memory: Max Size:  46,572 MB
Virtual Memory: Available: 6,939 MB
Virtual Memory: In Use:    39,633 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    NETWORK
Logon Server:              \\LUIZMONAD
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5013889
                           [02]: KB5004567
                           [03]: KB5008295
                           [04]: KB5015814
                           [05]: KB5016353
Network Card(s):           4 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: VPN
                                 Status:          Hardware not present
                           [02]: VMware Virtual Ethernet Adapter for VMnet1
                                 Connection Name: VMware Network Adapter VMnet1
                                 Status:          Hardware not present
                           [03]: VMware Virtual Ethernet Adapter for VMnet8
                                 Connection Name: VMware Network Adapter VMnet8
                                 Status:          Hardware not present
                           [04]: Intel(R) Ethernet Connection (2) I218-V
                                 Connection Name: Ethernet
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.0.100
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

</details>
