### ISSUE TITLE
Merge -fuse-ld=lld support for gcc

### ISSUE THREAD

**Issue by bgamari** [msys2/MSYS2-packages#1531]
Debian has shipped `gcc` with a patch adding support for the LLD linker (in the form of a `-fuse-ld=lld` flag) for years now. This feature is arguably even more important on Windows, where `ld.bfd`'s poor performance can result in extremely long link times (in the case of the Glasgow Haskell Compiler, we are seeing 3+ hour builds on Windows with most of this time being spent in `ld.exe`; on Linux these builds tend to be an hour or so). It would be great if LLD support could be added to msys2's `gcc` distribution.

**Comment by bgamari** [comment]
A version of the patch can be found on GCC's [patchwork](https://patches-gcc.linaro.org/patch/11148/).

**Comment by bgamari** [comment]
Actually, it appears that the patch was proposed for merge again and this time was accepted upstream. It seems likely that `-fuse-ld=lld` will be available in GCC 9.

**Comment by mati865** [comment]
@bgamari mingw-w64 support by LLD isn't great until LLVM 8 release. It won't hurt to try but take it with a grain of salt.

**Comment by vladfaust** [comment]
Hey, both GCC 9 and LLVM 8 are released. I'd like to use LLD with mingw-w64 when building LLVM on Windows. Any chance to make it work?

**Comment by mati865** [comment]
This issue is solved becouse GCC 9 supports LLD.

> Any chance to make it work?

It should **rather** work for 64 bits, 32 bit support probably will be usable with LLD 9.

**Comment by vladfaust** [comment]
Yeah, the problem with mingw-w64 is that it is GCC 8 implementation (latest release in Oct 2018)...

**Comment by mati865** [comment]
GCC 9 package was released in May.
