### ISSUE TITLE
pacman hangs on system update

### ISSUE THREAD

**Issue by user41974** [msys2/MSYS2-packages#1542]
I installed mys64 using the file msys2-x86_64-20181211.exe. When I try to update according to the instructions, msys hangs and the process never completes. I've tried to repeat the process many times but it never works.

The output is:

$ pacman -Syuu
:: Synchronising package databases...
 mingw32                                          530.8 KiB   491K/s 00:01 [#########################################] 100%
 mingw64                                          532.0 KiB  2023K/s 00:00 [#########################################] 100%
 msys                                             178.2 KiB  6.00M/s 00:00 [#########################################] 100%
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (2) filesystem-2018.12-1  pacman-5.1.2-1

Total Download Size:   14.34 MiB
Total Installed Size:  46.13 MiB
Net Upgrade Size:       1.13 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 filesystem-2018.12-1-x86_64                       46.3 KiB  6.46M/s 00:00 [#########################################] 100%
 pacman-5.1.2-1-x86_64                             14.3 MiB  3.12M/s 00:05 [#########################################] 100%
(2/2) checking keys in keyring                                             [#########################################] 100%
(2/2) checking package integrity                                           [#########################################] 100%
(2/2) loading package files                                                [#########################################] 100%
(2/2) checking for file conflicts                                          [#########################################] 100%
(2/2) checking available disk space                                        [#########################################] 100%
warning: could not get file information for opt/
:: Processing package changes...
(1/2) upgrading filesystem   

[This is the last line on the terminal and the process never ends.]

How do I fix this thanks.

**Comment by user41974** [comment]
Update. My anti spyware software was blocking the process. Fixed now. Please delete issue.

**Comment by Realizm-C6GS** [comment]
Mine did the same thing. Kaspersky AV needed to be disabled.
