### ISSUE TITLE
MSYS2-runtime changes $arch

### ISSUE THREAD

**Issue by kevinfengcu** [msys2/MSYS2-packages#1578]
After installing msys2-runtime 3.0.1-1 via pacman, $arch changes from x86_64 to 86_64, which in turn (along with other potential issues in scripts quoting $arch) breaks pacman update since the mirrorlist uses $arch but the source address still uses x86_64 and thus generates 404 error.

**Comment by kevinfengcu** [comment]
btw, I am using Intel-based x64 system.

**Comment by Alexpux** [comment]
There are no 3.0.1 runtime from MSYS2 yet, so look what you do wtong

**Comment by kevinfengcu** [comment]
I see...then it is probably caused by another source I configured. Closing this issue for now.

**Comment by FlyingWombat** [comment]
Maybe the same issue: https://github.com/git-for-windows/git/issues/2081  
I'm sourcing the git-for-windows repos and getting the same error.

Work around is to set `Architecture = x86_64` in `/etc/pacman.conf`
