### ISSUE TITLE
error: failed retrieving file 'msys.db' (Solved on x86_64 Windows 10)

### ISSUE THREAD

**Issue by originalsurfmex** [msys2/MSYS2-packages#1581]
pacman.conf sets `Architecture = auto` and it appears that `auto` uses `uname -m` which results in `86_64`.
the msys mirror paths use `x86_64` not `86_64`
as a result I manually changed pacman.conf to say `Architecture = x86_64`.  This might be useful if posted somewhere for others having similar problems.

This was one example from the debug result of pacman -Syuv --debug
`
debug: response code: 404
error: failed retrieving file 'msys.db' from repo.msys2.org : The requested URL returned error: 404
debug: url: https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db
`
it should instead direct to:
`https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db`

**Comment by baysmith** [comment]
Thank you. This fixed the same issue for me.

**Comment by StarWolf3000** [comment]
For me `$ uname -m` gives `x86_64`, so I don't know what your problem is.

**Comment by orgads** [comment]
I have the same issue. `uname -m` gives `86_64` with msys2-runtime version 3.0.1.

**Comment by StarWolf3000** [comment]
There is no msys2-runtime with version 3.0.1. The latest is 2.11.2-1. See this comment: https://github.com/msys2/MSYS2-packages/issues/1578#issuecomment-465855990

**Comment by orgads** [comment]
Right. That's from GfW.

**Comment by StarWolf3000** [comment]
So, if you want Git for Windows and don't care about pacman, use the Git for Windows setup, otherwise install MSYS2 and then install the git package with pacman to make sure, everything is working as intended.
For some reason, the standalone setup is not in line with the release in MSYS2, breaking things afterwards.

**Comment by originalsurfmex** [comment]
the same thing just happened when updating my other laptop.  changing the `Architecture` line on pacman.conf was a pretty easy fix.  Almost reminded of the good ol' days when all I used was Arch Linux.

**Comment by StarWolf3000** [comment]
As stated, this is not an issue with the official repositories of MSYS2 and their mirrors. Report it at git-for-windows/msys2-runtime and git-for-windows/MSYS2-packages.

**Comment by originalsurfmex** [comment]
> 
> 
> As stated, this is not an issue with the official repositories of MSYS2 and their mirrors. Report it at https://github.com/git-for-windows/msys2-runtime and https://github.com/git-for-windows/MSYS2-packages.

sounds good, those repo's have no issues section so I just made pull requests.

**Comment by pjlbyrne** [comment]
New MSYS2 user here - this is still happening.

**Comment by marsteen** [comment]
@WhiteChairFromIkea
Thanks, this solved the problem for me, too!

**Comment by Kingnon6754** [comment]
i false to solve this proplem

**Comment by chucklu** [comment]
similar issue [Install gcc and ninja failed through the mirrors.tuna.tsinghua.edu.cn ](https://github.com/ejoy/ant/discussions/28)
file content of  C:\msys64\etc\pacman.d\mirrorlist.msys should contains $arch
[](Server = https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/$arch/)

**Comment by FOASHA** [comment]
> pacman.conf sets `Architecture = auto` and it appears that `auto` uses `uname -m` which results in `86_64`. the msys mirror paths use `x86_64` not `86_64` as a result I manually changed pacman.conf to say `Architecture = x86_64`. This might be useful if posted somewhere for others having similar problems.
> 
> This was one example from the debug result of pacman -Syuv --debug `debug: response code: 404 error: failed retrieving file 'msys.db' from repo.msys2.org : The requested URL returned error: 404 debug: url: https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db` it should instead direct to: `https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/86_64/msys.db


ااشكرك حقا
