### ISSUE TITLE
asciidoc segfaults

### ISSUE THREAD

**Issue by jeroen** [msys2/MSYS2-packages#1582]
Packages that use `asciidoc` seem to segfault sometimes. For example when building `pacman`:

```
Generating Sqlite3 output for file version.c
Generating Sqlite3 output for group alpm_misc
make[2]: *** [Makefile:821: doxygen.in] Segmentation fault (core dumped)
make[1]: *** [Makefile:983: all-recursive] Error 1
make: *** [Makefile:892: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

The problem disappears if we edit `PKGBUILD` and set `--disable-doc`.  Is there a workaround to build the docs anyway?

**Comment by piotrvv** [comment]
Try only to rebuild the doxygen package.

**Comment by peterbud** [comment]
I think it's similar to https://github.com/msys2/MINGW-packages/issues/4959

Try to install doxygen `1.8.14-3` and I guess that will solve your problem.

**Comment by jeroen** [comment]
Closing in favor of https://github.com/msys2/MSYS2-packages/pull/1593 and https://github.com/msys2/MINGW-packages/issues/4959
