### ISSUE TITLE
tmpfile() needs elevated privileges

### ISSUE THREAD

**Issue by pauloscustodio** [msys2/MSYS2-packages#1587]
The filename used by tmfpfile() is in the root of the C drive, causing tmpfile() to return NULL if the process is running without elevated privileges.

tmpfile() should create the temporary file in the directory pointed by %TEMP%.

**Comment by sio** [comment]
Related discussion from 20 years ago: https://mingw-users.narkive.com/L7VR1gxX/temporary-file-woes

Thread summary: some users loudly blamed Microsoft for breaking compatibility and no workaround was mentioned.

**Comment by pauloscustodio** [comment]
Thanks for the explanation.
