### ISSUE TITLE
mc (Midnight Commander) mouse not work if Term=xterm-256color

### ISSUE THREAD

**Issue by jack6th** [msys2/MSYS2-packages#1596]
Mintty -> options -> terminal -> type -> xterm-256color. 
It can use 256 color skins (mc -> F9 -> Options -> Appearance).  But mouse not works.
Mouse works when Term=xterm-vt220. But it cannot use 256 color skins.

**Comment by maehne** [comment]
I am observing exactly the same issue.

**Comment by ssgromov** [comment]
Same here, I finally opted for vt220 and used a custom color scheme from msys2 terminal.
Of course, it is not a substitute for 256 color terminal.

**Comment by vampirefrog** [comment]
I'm experiencing a similar problem, and if I try to use rxvt-256color the mouse works in mc, but the home and end keys don't. There's also a delay when pressing ESC ESC to exit mcedit, oddly enough. If I ssh to a linux box, the mc there works fine regardless of $TERM, with 256 colors.

**Comment by jack6th** [comment]
I solved it.   
It is not the problem of mc but terminfo.   
I patched terminfo with the command:   
`infocmp xterm-256color|sed -E 's/(kmous=\\E\[)</\1M/'|tic -o ~/.terminfo -`
Now mc works with xterm-256color.

**Comment by ssgromov** [comment]
> I solved it.
> It is not the problem of mc but terminfo.
> I patched terminfo with the command:
> `infocmp xterm-256color|sed -E 's/(kmous=\\E\[)</\1M/'|tic -o ~/.terminfo -`
> Now mc works with xterm-256color.

Hey @jack6th, thanks a mil -- that solved problems for me not only on msys, but also on WSL/SLES/opensuse terminals in OSes using new ncurses. Great!

**Comment by lazka** [comment]
This is fixed by #5205
