### ISSUE TITLE
Gedit cannot display CJK when I choose a latin font 

### ISSUE THREAD

**Issue by jack6th** [msys2/MSYS2-packages#1597]
On Linux gedit display CJK correctly when I choose a latin font.
On Windows it display some square.
Does gedit windows support .fonts.conf or something else I can choose fallback CJK font manually?
I do not want to use a unicode font with CJK characters. 
Because most of them are not monospace and some of them the latin characters are ugly.

**Comment by lazka** [comment]
`PANGOCAIRO_BACKEND=fc gedit` should force the fontconfig backend if you want to work with that.

**Comment by jack6th** [comment]
It works !
Very useful.
I solved the problem.

**Comment by lazka** [comment]
I guess font fallback needs to be improved in the pango win32 backend. If you care you can file a bug with pango describing your setup, your font settings and what you want to happen and what happens instead.
