### ISSUE TITLE
Can you build vim with lua interp on?

### ISSUE THREAD

**Issue by jchain** [msys2/MSYS2-packages#16]
I tried `makepkg` several times but failed. I noticed that you provides the patches but it didn't help much. Can you provide one (with lua, perl, python, ruby enabled) to `pacman` please? Thx a lot!

**Comment by joca-bt** [comment]
I am also obtaining

    fatal error: sys/wait.h: No such file or directory

when compiling another package for MSYS2 inclusion. How did you solve it?

**Comment by Mike-Now** [comment]
You have to change your path to NOT include mingw utilities (like gcc). Only msys ones. You can do it by temporarily renaming mingw to _mingw or by manipulating the $PATH variable.

**Comment by joca-bt** [comment]
I was using mingw-devel instead of msys2-devel, thanks.

**Comment by maonx** [comment]
Thanks, it's work.
```
Ok, managed to do it. Steps:
1. Download via pacman ncurses-devel ruby python2 python3 and lua source from web
2. Download and compile lua5.2 (cd src && make mingw && cd .. && make install )
3. For python3 support : download libint and make it visible by renaming msys-intl-8.dll to libintl.dll and putting it in /usr/lib
4. Run the following in vim/src:

./configure --prefix=/usr --with-tlib=ncursesw --enable-luainterp --with-lua-prefix=/usr/local --disable-gui --disable-tclinterp --enable-cscope --without-x CPPFLAGS="${CPPFLAGS} -I/usr/include/ncursesw" --enable-python3interp=dynamic --enable-rubyinterp=dynamic --enable-pythoninterp=dynamic --enable-multibyte && make
5. cd .. && make install
6. run vim and do :version
```
