### ISSUE TITLE
Failed to run make when compiling vulkan-loader

### ISSUE THREAD

**Issue by ycwan** [msys2/MSYS2-packages#1610]
15:54:41 ┌ vulkan-loader git ........................ [Recently updated]
15:54:42 ├ Running cmake...
15:54:48 ├ Running make...
Likely error:
  File "C:/mingw/build/vulkan-loader-git/scripts/loader_genvk.py", line 375, in genTarget
    reg.apiGen(options)
  File "C:/mingw/local64/share/vulkan/registry\reg.py", line 943, in apiGen
    regEmitExtensions = re.compile(self.genOpts.emitExtensions)
  File "C:/mingw/msys64/mingw64/lib/python3.7\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:/mingw/msys64/mingw64/lib/python3.7\re.py", line 285, in _compile
    raise TypeError("first argument must be string or compiled pattern")
TypeError: first argument must be string or compiled pattern
ninja: build stopped: subcommand failed.
make failed. Check C:/mingw/build/vulkan-loader-git/build-64bit/ab-suite.make.log
This is required for other packages, so this script will exit.
15:54:49   Creating diagnostics file...

All relevant logs have been anonymously uploaded to https://0x0.st/zPP0.zip

**Comment by StarWolf3000** [comment]
See KhronosGroup/Vulkan-Loader#167 and KhronosGroup/Vulkan-ValidationLayers#813.
