### ISSUE TITLE
Help how come a2p Awk to Perl not installed on my msys2 / ming64

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MSYS2-packages#1614]
Many not available on my msys2/ming64 such as a2p Awk to Perl not installed if I type

```
$ a2p
-bash: a2p: command not found

$ perldoc -f perlfunc
No documentation for perl function 'perlfunc' found

$ pacman -S perl
warning: perl-5.28.1-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) perl-5.28.1-2
Total Installed Size:  51.69 MiB
```
Perl base is installed.
How to get the missing needs ? please help!

**Comment by StarWolf3000** [comment]
No package in MSYS2 has this utility.

If you do `$ pacman -Qs a2p` or `$ pacman -Fs a2p` (the latter requires you to download the database files first with `$ pacman -Fy`) , you won't get any results.

**Comment by abdulbadii** [comment]
Solved!
install cpan `pacman -S cpan`
get a2p from there - get into cpan shell and follow some menu help..

**Comment by StarWolf3000** [comment]
There is no cpan package for MSYS2 pacman in the default repositories. So where did you get this?
