### ISSUE TITLE
mintty: Procedure entry point "uname_x" not found in DLL "msys-2.0.dll"

### ISSUE THREAD

**Issue by LigH-de** [msys2/MSYS2-packages#1617]
The very last version of mintty (1~3.0.0-1) does not run anymore, seems to require an API update of msys-2.0.dll

**Comment by LigH-de** [comment]
May be related to gnupg-2.2.15-1-x86_64 - the secure update of media-autobuild_suite dows not work anymore due to "GPGME error: Invalid Krypto Engine", so updating MSYS2 via GPG secured pacman must have been interrupted.

**Comment by Alexpux** [comment]
@LigH-de do you update msys2-runtime too?

**Comment by LigH-de** [comment]
I believe media-autobuild_suite failed updating it because it got the software repository corrupted. So I'm reinstalling it now...

**Comment by LigH-de** [comment]
Works after reinstallation.
