### ISSUE TITLE
How to do clipboard paste by a script function on msys/ming64

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MSYS2-packages#1618]
How to acquire clipboard-paste function to flawlessly work in mysy/mingw64 by whichever terminal

**Comment by StarWolf3000** [comment]
I don't think you can on Windows, without relying too much on platform-dependent functionality. There is also no real clipboard in bash or other shells. On X11-based environments, you can use `xclip` or `xsel` to read from or write to the X11 clipboard, but this does not work on Windows (nor are they available for Windows, for various obvious reasons).

mintty (the default terminal emulator in MSYS2), for example, utilizes the Windows API for its core (including clipboard access) and the Cygwin POSIX layer to communicate with the programs running inside it.

Without external command-line utilites (using Windows API or .NET Framework) or PowerShell, you cannot read from the clipboard on Windows (you can write to it using the Windows utility `clip.exe` though).

**Comment by cbrt64** [comment]
MSYS2 implements Cygwin's `/dev/clipboard`, a bi-directional text interface to the Windows clipboard. For a simple script to use frequently, see the comment by Greg at https://williammitchell.blogspot.com/2008/03/fun-with-cygwins-devclipboard.html.

**Comment by StarWolf3000** [comment]
@cbrt64 Wow, I didn't know this. I tested it out, and it works as expected in both directions (with text).

**Comment by hiroakit** [comment]
@lazka

I think that this issue has been resolved.

- https://github.com/msys2/MSYS2-packages/issues/1618#issuecomment-488093561

Would you like to close it?
