### ISSUE TITLE
Broken python2-2.7.16-1-x86_64.pkg.tar.xz

### ISSUE THREAD

**Issue by fabzzap** [msys2/MSYS2-packages#1623]
The package python2-2.7.16-1-x86_64.pkg.tar.xz from MinGW64, released today, is broken.

It contains /usr/bin/msys-python2.7.dll , that tries to load function `uname_x` from msys-2.0.dll . That function is not present in that DLL, at least not in the one from msys2-runtime 3.0.6-1.

**Comment by fabzzap** [comment]
Downgrading to python2-2.7.15-3-x86_64.pkg.tar.xz made things work again.

**Comment by Alexpux** [comment]
@fabzzap I don't see the issue. Verify that you have latest msys2-runtime from MSYS2 repository not from anywhere else
![python2-msys-dll-problem](https://user-images.githubusercontent.com/1898153/56785118-5a8b2a00-67fc-11e9-9880-6e11532d55df.png)

**Comment by fabzzap** [comment]
The installation of msys2-runtime must have been faulty, because reinstalling it indeed solved the problem. Thank you
