### ISSUE TITLE
mosh package needs recompilation

### ISSUE THREAD

**Issue by cybe** [msys2/MSYS2-packages#1625]
The mosh client needs recompilation for the [recently upgraded](https://github.com/msys2/MSYS2-packages/commit/d1ccc2bc91e19f65406dd6505586f5020e1d52d7) protobuf library:

```
$ mosh someone@somehost.net
C:/msys64/usr/bin/mosh-client.exe: error while loading shared libraries: msys-protobuf-17.dll: cannot open shared object file: No such file or directory
```
Thank you! :)

**Comment by cbrt64** [comment]
@Alexpux to the rescue! [mosh-1.3.2-4](http://repo.msys2.org/msys/x86_64/mosh-1.3.2-4-x86_64.pkg.tar.xz), 3166ee4.

**Comment by cybe** [comment]
Perfect, confirmed to be working.
