### ISSUE TITLE
How to change the default file '.emacs' location of Mingw64 Emacs 

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MSYS2-packages#1629]
How do we change the default file '.emacs' location of Mingw64 Emacs which point to %APPDATA% of Windows to that of Msys2 Emacs which is home, more precisely ~/.emacs

**Comment by Gei0r** [comment]
You have to change the HOME environment variable before starting emacs. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Windows-HOME.html

**Comment by abdulbadii** [comment]
Correct and nice !
