### ISSUE TITLE
MSYS2 crashing Windows with IRQL_NOT_LESS_OR_EQUAL

### ISSUE THREAD

**Issue by katananja** [msys2/MSYS2-packages#1637]
Hello everyone, I'm not a developer I'm just trying to collaborate the best way I can. I'm trying to compile the MAME source code (https://github.com/mamedev/mame) and make and clang++ is causing the Windows Pro (1803 - 17134.753 x64) to crash with **IRQL_NOT_LESS_OR_EQUAL** and **SYSTEM_SERVICE_EXCEPTION**. I've run Memtest86+ analysis and there is nothing wrong with my memory.

This is the options used to compile on Windows:
``make OVERRIDE_CC=/mingw64/bin/clang OVERRIDE_CXX=/mingw64/bin/clang++ SYMBOLS=1 SYMLEVEL=1 STRIP_SYMBOLS=1 PTR64=1 SSE3=1 ARCHOPTS=-march="bdver1" -mfpmath=sse NOWERROR=1 PRECOMPILE=0``

I don't know how to handle it so I'm posting the crashdumps: 
https://www.mediafire.com/file/m6b5og7e551bu9f/050219-33687-01.7z 
https://www.mediafire.com/file/w22pnss6wc9thd3/050219-33750-01.7z 
https://www.mediafire.com/file/czexpka6q6q11ro/analysis.zip

I've notice this problem after the previous mingw update from clang 7 to 8.

```
 ld -v
 GNU ld (GNU Binutils) 2.30
 
 uname -a
 MINGW64_NT-10.0-17134 Dragon 3.0.6-338.x86_64 2019-04-15 06:44 UTC x86_64 Msys
 
 make -v
 GNU Make 4.2.1
 Compilado para x86_64-pc-msys
 
 clang++ -v
 clang version 8.0.0 (tags/RELEASE_800/final)
 Target: x86_64-w64-windows-gnu
 Thread model: posix
 InstalledDir: D:\msys64\mingw64\bin
 
  gcc -v
 Using built-in specs.
 COLLECT_GCC=D:\msys64\mingw64\bin\gcc.exe
 COLLECT_LTO_WRAPPER=D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/lto-wrapper.exe
 Target: x86_64-w64-mingw32
 Configured with: ../gcc-8.3.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=ada,c,lto,c++,objc,obj-c++,fortran --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
 Thread model: posix
 gcc version 8.3.0 (Rev2, Built by MSYS2 project)
```

**Comment by fdik** [comment]
Hi, kernel errors may be triggered by msys2 but are most likely not coming from there. Beside hardware errors they're most likely caused by driver bugs.

https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0xa--irql-not-less-or-equal
https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/bug-check-0x3b--system-service-exception

**Comment by katananja** [comment]
Hi.
I don't know were to look, installing a previous version of MSYS2 it doesn't trigger the issue. I also did a test to compile the code over linux, standard and cross-compiling using a more aggressive approach with ``-j9`` with no issue.

I did a full hardware diagnostics, nothing show up.
I build this machine to compile code, it has nothing on it, all access is made by terminal services. Microsoft support say that they have nothing to do with it, I don't what to do now.

This is not a total loss for me because I can cross-compile the binary, however if there is a bug causing this, it will be pushed forward.

Thank you for your reply, fell free to close this ticket or leave it open if you feel someone else should take a look.
Thank you @fdik !

**Comment by katananja** [comment]
Just for reference, this MSYS2 version, doesn't make Windows to crash:
https://www.mamedev.org/tools/
https://github.com/mamedev/buildtools/releases/download/4.0/msys64-32-2019-03-25.exe

However if you update it, the issue start all over again.

Thank you.

**Comment by fdik** [comment]
FYI: I've got an actual msys2 installation running and no such problems. As I said there's two possible common sources for kernel problems:

- defect hardware
- kernel driver bugs

If you've got a kernel panic then this is resulting from a problem in kernel code, not from code in userland. Is there any kernel code in msys2?

**Comment by katananja** [comment]
Hi fdik!
I've also compile a full MAME binary with that image, no issues.

I'm not a developer, I believe there's nothing related with kernel here, all I've is gcc, g++, clang and all that comes with it. This is a previous update before the last update:
```
bash-completion-2.8-2  brotli-1.0.7-1  bsdcpio-3.3.3-3
                bsdtar-3.3.3-3  ca-certificates-20180409-1  coreutils-8.30-1
                curl-7.63.0-1  dash-0.5.10.2-1  dtc-1.4.7-1  file-5.35-1
                gawk-4.2.1-2  gcc-libs-7.4.0-1  glib2-2.54.3-1  gnupg-2.2.12-1
                grep-3.0-2  heimdal-libs-7.5.0-3  icu-62.1-1  info-6.5-2
                less-530-1  libarchive-3.3.3-3  libargp-20110921-2
                libassuan-2.5.2-1  libcrypt-2.1-2  libcurl-7.63.0-1
                libexpat-2.2.6-1  libffi-3.2.1-3  libgcrypt-1.8.4-1
                libgnutls-3.6.5-1  libgpg-error-1.33-1  libgpgme-1.12.0-1
                libhogweed-3.4.1-1  libidn2-2.0.5-1  libksba-1.3.5-1
                liblz4-1.8.3-1  liblzma-5.2.4-1  liblzo2-2.10-2  libnettle-3.4.1-1
                libnghttp2-1.35.1-1  libnpth-1.6-1  libopenssl-1.1.1.a-1
                libp11-kit-0.23.14-1  libpcre-8.42-1  libpcre16-8.42-1
                libpcre2_8-10.32-1  libpcre32-8.42-1  libpcrecpp-8.42-1
                libpcreposix-8.42-1  libpsl-0.20.2-1  libreadline-7.0.005-1
                libsqlite-3.21.0-4  libssh2-1.8.0-2  libunistring-0.9.10-1
                libutil-linux-2.32.1-1  libxml2-2.9.8-1  m4-1.4.18-2
                ncurses-6.1.20180908-1  nettle-3.4.1-1  openssl-1.1.1.a-1
                p11-kit-0.23.14-1  pcre-8.42-1  pinentry-1.1.0-2  pkgfile-19-1
                rebase-4.4.4-1  sed-4.7-1  time-1.9-1  ttyrec-1.0.8-2
                util-linux-2.32.1-1  wget-1.20-2  xz-5.2.4-1
```
I can force an update on that image and sent you a list?
Is there anything I can do to pin point what is causing this?

Thank you.

**Comment by fdik** [comment]
Blue Screens are Kernel Panics. IRQL_NOT_LESS_OR_EQUAL is one of a small list of kernel problems (the number gives which one). SYSTEM_SERVICE_EXCEPTION is a kernel problem while context switch. You're experiencing kernel panics.

**Comment by mati865** [comment]
MSYS2 doesn't install any drivers so it's unlikely to be able to crash kernel. It can be caused by some driver, in that case it should be easy to identify it by running it in Safe Mode.

Memtest86+ is a bit old, Passmark Memtest86 is generally better for newer hardware.

**Comment by katananja** [comment]
It doesn't hurt to try, I'll get ``Passmark Memtest86`` and latter try to compile something in safe mode, Windows doesn't use any drivers in that mode right?

Thanks.

**Comment by mati865** [comment]
Exactly, all third party drivers are disabled in Safe Mode.

**Comment by katananja** [comment]
Hello guys!
I left the machine running ``Passmark Memtest86`` all night with no issues, **all tests passed.** I've used the last MSYS2 image to compile MAME in ``Safe Mode`` and it didn't crash anything, all went as planned.

I was abe to locate the issue, it was a ASUS sound driver for [Essence STX II](https://www.asus.com/Sound-Cards/Essence_STX_II/) (?), once I remove the driver no more blue screen.

Is hard to me to understand why this drivers doesn't cause issues with a previous MSYS2 and it does after the update. Anyway, thank you guys for the time, I can take it from here.

Thank you.

**Comment by mati865** [comment]
You should contact ASUS support then. Maybe new version puts more stress on the system and the driver gets into race condition.

**Comment by katananja** [comment]
I've already contacted them before, it's a waste of time. We move the card to another machine to avoid further problems.

Thank you @mati865
