### ISSUE TITLE
avrdude under msys2 doesn't work, but WinAVR version does

### ISSUE THREAD

**Issue by clinton-r** [msys2/MSYS2-packages#1642]
Hello, I've been trying to use avrdude under msys2, but I haven't been able to make it work.  I finally installed WinAVR instead and the (old) avrdude it provides does work.  I'm running Windows 10 64-bit, but I tried both packages mingw-w64-x86_64-avrdude and mingw-w64-i686-avrdude.  The programmer I'm using is the Pocket AVR Programmer from SparkFun.  I'm attaching a file showing the output I get from each of the avrdude versions.  The first 3 commands just try to contact the AVR, the next 3 are trying to program it.
[avrdude_problems.txt](https://github.com/msys2/MSYS2-packages/files/3185253/avrdude_problems.txt)
Can anyone please tell me what could be wrong?  Thanks.

**Comment by StarWolf3000** [comment]
Remove all the `-v` options in the command line and try again. Make sure your board is the correct one selected. Also:
1) This repos is only for reporting problems with packages themselves, not with how to use them the correct way.
2) You are also posting in the wrong repos, the correct one is at msys2/MINGW-packages.

**Comment by clinton-r** [comment]
Hi StarWolf3000, thanks for your reply.  I've re-posted as #5396 under msys2/MINGW-packages.  I added a second file showing the output of the same commands but without the -v verbose output flags.
