### ISSUE TITLE
Odd warning when running nearly any pacman command.

### ISSUE THREAD

**Issue by BenKey** [msys2/MSYS2-packages#1650]
I am getting the following warning message for nearly every pacman command.

> error: invalid name for database entry '$Recycle.Bin'

**Comment by cbrt64** [comment]
I've noticed MSYS2 sometimes creates directories named `$Recycle.Bin` for some reason (maybe for deleting files with open handles? IDK). Anyway, look for `/var/lib/pacman/local/$Recycle.Bin` in your case.

**Comment by BenKey** [comment]
Hello,

I was not able to find a folder named $Recycle.Bin in /var/lib/pacman/local/.
I was also not able to find the string $Recycle.Bin in any file in my
msys64 directory or subdirectories.

**Comment by cbrt64** [comment]
There are only two places that error appears in pacman's source. Not that I fully understand it, but it seems to only apply to database directory names in `/var/lib/pacman/local/`, and database entry names in `/var/lib/pacman/sync/*.db` (which are .tar.gz format). In an MSYS2 console, could you try
```
find / -xdev -iname '*recycle.bin*'
```
and
```
for fn in /var/lib/pacman/sync/*.{db,files}; do
  echo -e "\n  $fn:";
  tar -tf $fn | fgrep -i recycle;
done
```
to check for both possibilities?

I also found #1253, which is relevant to my first comment. I have seen `$Recycle.Bin`'s appear other than in a drive's root directory, however; now I wish I had looked into it more.

**Comment by BenKey** [comment]
Hello,

I realized my mistake. A directory named *$Recycle.Bin* was in fact located
in /var/lib/pacman/local/. I did not see it because I was using Windows
Explorer, the *$Recycle.Bin* folder had the system attribute, and I forgot
to set the unset the Hide protected Operating System Files option in
Windows Explorer. When I unset that option I was able to see the directory
and delete it.

Thanks.
