### ISSUE TITLE
Pacman Retrieving packages error with QueryUnbiasedInterruptTime function call

### ISSUE THREAD

**Issue by rvasin** [msys2/MSYS2-packages#1651]
Hello,

I upgraded to the latest version pacman 5.1.3-1 and the latest version of msys-runtime

After running command: pacman -Syu 
It does connectly sync the database then it shows:

> :: Proceed with installation? [Y/n]
> :: Retrieving packages...
>       2 [main] pacman 192 C:\Programs\msys32\usr\bin\pacman.exe: *** fatal error - couldn't dynamically determine load address for 'QueryUnbiasedInterruptTime' (handle 0x762E0000), Win32 error 127
> Hangup

**Comment by Alexpux** [comment]
Yes I see this but still don’t understand what happen. Downgrading pacman and msys2-runtime not solve problem for me. So need to look

**Comment by genezx** [comment]
Me too. After pacman -Syu today on Win7, pacman is broken.

Debugging shows msys-2.0.dll is trying to load function QueryUnbiasedInterruptTime from kernelbase.dll which only exists in kernel32.dll in Windows 7.

**Comment by Alexpux** [comment]
@rvasin @genezx this is from autoload.cc:
````
/* MSDN claims these are exported by kernel32.dll, but only
   QueryUnbiasedInterruptTime actually is.  The others are only
   available via KernelBase.dll. */
LoadDLLfunc (QueryInterruptTime, 4, KernelBase)
LoadDLLfunc (QueryInterruptTimePrecise, 4, KernelBase)
LoadDLLfunc (QueryUnbiasedInterruptTime, 4, KernelBase)
LoadDLLfunc (QueryUnbiasedInterruptTimePrecise, 4, KernelBase)
````

Maybe something changed in Windows with updates...

**Comment by Alexpux** [comment]
Fixed msys2-runtime uploaded, also created new MSYS2 installers

**Comment by rvasin** [comment]
For everyone in this situation: it's needed to download the latest version of msys2-runtime? How to do it correctly way? Pacman does not download it because of the error. Thus the only way is to manually download zip of msys2-runtime and extract it? Or there is more correct way to do it?

**Comment by genezx** [comment]
> @rvasin @genezx this is from autoload.cc:
> 
> ```
> /* MSDN claims these are exported by kernel32.dll, but only
>    QueryUnbiasedInterruptTime actually is.  The others are only
>    available via KernelBase.dll. */
> LoadDLLfunc (QueryInterruptTime, 4, KernelBase)
> LoadDLLfunc (QueryInterruptTimePrecise, 4, KernelBase)
> LoadDLLfunc (QueryUnbiasedInterruptTime, 4, KernelBase)
> LoadDLLfunc (QueryUnbiasedInterruptTimePrecise, 4, KernelBase)
> ```
> 
> I dont have any of this functions in kernelbase under my Windows 7.
> Maybe something changed in Windows with updates...

I never see other 3 functions and only QueryUnbiasedInterruptTime in kernel32.dll.
And any of the all 4 functions is never in kernelbase.dll.
Every version from 6.1.7601.17514 to 6.1.7601.24441.
So it's not update issue.

And the latest [MSDN](https://docs.microsoft.com/en-us/windows/desktop/api/realtimeapiset/nf-realtimeapiset-queryunbiasedinterrupttime) is correct. I don't know where were the comments in the code from.

**Comment by Alexpux** [comment]
Fixed

**Comment by rvasin** [comment]
What is the simplest way to repair the installation? 
Installing previous version pacman -U msys2-runtime-3.0.6-1-i686.pkg.tar.xz does not work.
Besides instructions given in https://github.com/msys2/msys2/wiki/MSYS2-reinstallation

**Comment by Alexpux** [comment]
Well you can manually download 3.0.7-3 msys2-runtime package and unpack Msys-2.0.dll then upgrade packages to latest as usual

**Comment by rvasin** [comment]
Well I downloaded msys2-base-i686-20190524.tar.xz
and from that archive I copied \msys32\usr\bin\msys-2.0.dll to the same folder in my Windows:  \msys32\usr\bin\
It replaced old msys-2.0.dll  by this new one. Then running
 pacman -Syuu 
correctly installed 3.0.7-3 msys2-runtime and pacman over it. 
So it did work well. Thank you.

But after restart now it shows the messages:

> :: Starting full system upgrade...
> warning: grep: downgrading from version 3.1-1 to version 3.0-2
> warning: libgc: downgrading from version 8.0.0-1 to version 7.6.8-1
> warning: mingw-w64-i686-binutils: downgrading from version 2.31.1-2 to version 2.30-6
> :: Replace mingw-w64-i686-ncurses with mingw32/mingw-w64-i686-pdcurses? [Y/n]
> :: Replace mingw-w64-i686-termcap with mingw32/mingw-w64-i686-pdcurses? [Y/n]
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-ada
> :: installing mingw-w64-i686-gcc (9.1.0-1) breaks dependency 'mingw-w64-i686-gcc=7.4.0-1' required by mingw-w64-i686-gcc-objc
> 
> 

But this is another story (not related to the issue).

**Comment by jeroen** [comment]
Seeing this too, thanks for looking into it. Has this been reported upstream in cygwin?
