### ISSUE TITLE
Packages conflicts on update

### ISSUE THREAD

**Issue by kassane** [msys2/MSYS2-packages#1652]
Today after an ``msys-runtime`` update, there was a problem in the x86_64 packages (minizip and zlib) because of the dependence on the assimp package.

**Comment by weiby3** [comment]
same problem, some relative logs:
```
$ LANG=en_US.UTF-8 pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
warning: grep: local (3.1-1) is newer than msys (3.0-2)
warning: libgc: local (8.0.0-1) is newer than msys (7.6.8-1)
warning: mingw-w64-x86_64-binutils: local (2.31.1-2) is newer than mingw64 (2.30-5)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-zlib (1.2.11-7) breaks dependency 'mingw-w64-x86_64-minizip' required by mingw-w64-x86_64-assimp
```

**Comment by cbrt64** [comment]
`Minizip`, which `assimp` depends on, was until yesterday provided by `zlib` and was not an actual package. It is now provided by the new `minizip-git` package, which needs to be installed, but for whatever reason pacman is not figuring that out. @Alexpux, could this be a bug in pacman's dependency tracking code?

For now you can just `pacman -Syu mingw-w64-x86_64-minizip` to install it manually.

**Comment by cbrt64** [comment]
Duplicate of https://github.com/msys2/MINGW-packages/issues/5400.
