### ISSUE TITLE
Libgda doesn't contain providers(jdbc/mysql/postgres)

### ISSUE THREAD

**Issue by taozuhong** [msys2/MSYS2-packages#1655]
Libgda( mingw-w64-x86_64-libgda) doesn't contain providers(jdbc/mysql/postgres):
libgda-jdbc
libgda-mysql
libgda-postgres
libgda-sqlserver

due to lack of providers, this package doesn't work really.

**Comment by StarWolf3000** [comment]
This is the wrong repository for reporting issues with the mentioned package. Correct repository is at https://github.com/msys2/MINGW-packages.

Also it looks like support for MySQL (via libmariadbclient) and PostgreSQL is built into libgda, according to https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgda/PKGBUILD.

**Comment by taozuhong** [comment]
> This is the wrong repository for reporting issues with the mentioned package. Correct repository is at https://github.com/msys2/MINGW-packages.
> 
> Also it looks like support for MySQL (via libmariadbclient) and PostgreSQL is built into libgda, according to https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libgda/PKGBUILD.

thanks, it be moved to repository: https://github.com/msys2/MINGW-packages
