### ISSUE TITLE
mingw-w64-x86_64-imagemagick does not work at all.

### ISSUE THREAD

**Issue by t246246** [msys2/MSYS2-packages#1666]
On Windows 7, I tried both mingw-w64-x86_64-imagemagick and mingw-w64-i686-imagemagick.
Both does not work after recent update.

$ magick -version
$ echo $?
127

After some investigation
$ strace magick -version
shows dialog that says _free_locale is missng at msvcrt.dll

So It could be the same kind of problem with https://github.com/ImageMagick/ImageMagick6/issues/42

**Comment by lazka** [comment]
-> https://github.com/msys2/MINGW-packages/issues/5466
