### ISSUE TITLE
perl doesnt include bat scripts, or pl2bat or runperl.pl

### ISSUE THREAD

**Issue by jayvdb** [msys2/MSYS2-packages#1668]
It would be helpful to provide .bat wrappers for all of the scripts in core_perl, so that they can be executed from `cmd` and any other native process.

It would also be useful to include pl2bat.pl and runperl.pl . The mingw package does do this.
https://packages.msys2.org/package/mingw-w64-x86_64-perl?repo=mingw64

**Comment by Alexpux** [comment]
MSYS Perl is like Cygwin Perl and it will not provide bar wrappers

**Comment by jayvdb** [comment]
What about including pl2bat.pl and runperl.pl so people can roll their own .bat if they need it?

**Comment by Alexpux** [comment]
@jayvdb MSYS perl is "unix" perl so there will never be this files

**Comment by jayvdb** [comment]
So then these files should also be removed?

- /usr/lib/perl5/core_perl/Win32.pm
- /usr/lib/perl5/core_perl/Win32API/File.pm
- /usr/lib/perl5/core_perl/Win32CORE.pm
- /usr/lib/perl5/core_perl/auto/Win32/Win32.dll
- /usr/lib/perl5/core_perl/auto/Win32API/File/File.dll
- /usr/lib/perl5/core_perl/auto/Win32CORE/Win32CORE.a
- /usr/lib/perl5/core_perl/auto/Win32CORE/extralibs.ld
- /usr/share/man/man1/perlwin32.1perl.gz

There are also a lot of other platform specific files which are not included in my unix system perl packages.

- /usr/share/perl5/core_perl/ExtUtils/CBuilder/Platform/VMS.pm
- ...
- /usr/share/man/man1/perlvms.1perl.gz
- ...
- /usr/share/man/man3/ExtUtils.MM_VMS.3perl.gz
- ...

**Comment by Alexpux** [comment]
I think you need to ask Perl developers, this is how Cygwin Perl is building and installing

**Comment by mingwandroid** [comment]
> perl doesnt include bat scripts, or pl2bat or runperl.pl

The Cygwin shell is a posix shell. You are expected to use `sh`, `bash` etc.

> /usr/lib/perl5/core_perl/Win32.pm (and the rest of your comment).

The Cygwin perl provides access to the Win32 API as you would hope.
