### ISSUE TITLE
mingw-w64-x86_64-python3-colorama-0.4.1-2 is built against Python 2.7 instead of 3.7

### ISSUE THREAD

**Issue by sch-alex** [msys2/MSYS2-packages#1670]
$ pacman -Ql mingw-w64-x86_64-python3-colorama
mingw-w64-x86_64-python3-colorama /mingw64/
mingw-w64-x86_64-python3-colorama /mingw64/lib/
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama-0.4.1-py2.7.egg-info/
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama-0.4.1-py2.7.egg-info/dependency_links.txt
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama-0.4.1-py2.7.egg-info/PKG-INFO
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama-0.4.1-py2.7.egg-info/SOURCES.txt
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama-0.4.1-py2.7.egg-info/top_level.txt
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/__init__.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/__init__.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/__init__.pyo
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansi.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansi.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansi.pyo
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansitowin32.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansitowin32.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/ansitowin32.pyo
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/initialise.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/initialise.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/initialise.pyo
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/win32.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/win32.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/win32.pyo
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/winterm.py
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/winterm.pyc
mingw-w64-x86_64-python3-colorama /mingw64/lib/python2.7/site-packages/colorama/winterm.pyo
mingw-w64-x86_64-python3-colorama /mingw64/share/
mingw-w64-x86_64-python3-colorama /mingw64/share/licenses/
mingw-w64-x86_64-python3-colorama /mingw64/share/licenses/python3-colorama/
mingw-w64-x86_64-python3-colorama /mingw64/share/licenses/python3-colorama/COPYING

**Comment by Alexpux** [comment]
@sch-alex this need to be in MINGW-packages repository.
Ficed by https://github.com/msys2/MINGW-packages/commit/b6a357c600677483fd1f762ef661dbd0cac0ed74
