### ISSUE TITLE
GPG setup fail on Windows 2008 / Vista

### ISSUE THREAD

**Issue by jeroen** [msys2/MSYS2-packages#1674]
Initiating msys2 on Windows 2008 or Vista always give me the error below and then `pacman` does not work. Every time I start the shell, it does this again.

It seems to be unable to find the `trustdb.gpg` which should be in `/etc/pacman.d/gnupg/`. What could be causing this?

<img width="1281" alt="msys2-vista" src="https://user-images.githubusercontent.com/216319/59346334-59fa1480-8d12-11e9-9edc-c0f6b84698b8.png">

**Comment by dscho** [comment]
The curious line is the first one:

```
mkdir: cannot create directory '': No such file or directory
```

And then `gpg` complains about a missing directory. So it would seem that you may have an incorrect `GPG_HOME` or some such.

**Comment by jeroen** [comment]
So where would `GPG_HOME` get set or is supposed to be set?

This problem really only appears on Windows Vista / Windows 2008 so I think the underlying reason is something else.

**Comment by mati865** [comment]
You could try running MSYS2 shell instead of MINGW32, it could be trying to use `mingw-w64-gnupg` and `mingw-w64-*` packages are targeting Windows 7.

**Comment by jeroen** [comment]
I think the problem is the [BCryptDeriveKeyPBKDF2](https://docs.microsoft.com/en-us/windows/desktop/api/bcrypt/nf-bcrypt-bcryptderivekeypbkdf2) that is missing on vista:


<img width="1136" alt="Screen Shot 2019-06-21 at 1 52 45 PM" src="https://user-images.githubusercontent.com/216319/59920801-041d1f00-942c-11e9-8ed9-ed0c415d7196.png">

**Comment by mati865** [comment]
So it's https://github.com/msys2/MSYS2-packages/issues/1181 and is probably not going to be fixed.

**Comment by jeroen** [comment]
I'm using an older version of mingw-w64 (v5.0.4) so it is probably something else that links to it.

**Comment by jeroen** [comment]
Yes that sounds like it. Though must stuff actually works, I'd like to find the program that actually uses `BCryptDeriveKeyPBKDF2` so I can work around it.

**Comment by mati865** [comment]
`msys2-runtime` is build with [`mingw-w64-cross-crt-git`](https://github.com/msys2/MSYS2-packages/blob/2694b20600412cc8e2fb0d9d661f0b7b0a2f346b/msys2-runtime/PKGBUILD#L18) so the runtime is targeting Win7 unless you build your own `mingw-w64-cross-*` and runtime.

**Comment by jeroen** [comment]
> msys2-runtime is build with mingw-w64-cross-crt-git so the runtime is targeting Win7 unless you build your own mingw-w64-cross-* and runtime.

Yeah I know, but as a temporary solution until January when our Win2008 server is killed off, I'd like to find the program that actually needs `BCryptDeriveKeyPBKDF2`. Other than that I haven't found any of the tools that I need from the runtime which use Win7 apis.

**Comment by jeroen** [comment]
I think the problem is in libarchive (which pacman uses):

https://github.com/libarchive/libarchive/blob/21678590058e64bcf99442afa3235b1b60390cf1/libarchive/archive_cryptor.c#L78

**Comment by jeroen** [comment]
Yup that fixed it :D
<img width="1136" alt="Screen Shot 2019-06-21 at 3 22 04 PM" src="https://user-images.githubusercontent.com/216319/59925413-5bc18780-9438-11e9-9c24-5f8f311a3430.png">

**Comment by dscho** [comment]
Excellent analysis and fix, @jeroen!
