### ISSUE TITLE
TTF files in a path with non ascii characters can't be opened in FreeType

### ISSUE THREAD

**Issue by johanmattssonm** [msys2/MSYS2-packages#1675]
Hi 
I have found out that FreeType refuses to load a TTF font if the path has non ascii characters in it on Msys2 (Windows). It works fine on Linux.

Error code: 0x01, Cannot_Open_Resource. 

I have filed a bug in the tracker used by the FreeType project and got the reply from Werner Lemberg claiming that this is not a problem with FreeType but somewhere else in the software stack.

Here is a way to reproduce this probelm: http://birdfont.org/misc/freetypebug.zip

Regards
Johan

**Comment by jtanx** [comment]
Are you referring to the mingw freetype packages?

If so, my money is on it being a FreeType issue (sort of). If it's just using `fopen` to open the files, then it's a Windows limitation that it will only work with file paths that can be interpreted by the current/ansi code page. (This is very similar to fontforge/fontforge#2290)

You have to use the wide character apis e.g. `_wfopen` or `CreateFileW` to be able to open files on paths that contain non-ansi characters. So if FreeType is opening the files directly, then it needs some Windows specific code to deal with this.

A hack that will work is if you can convert the file path to a [short path](https://docs.microsoft.com/en-us/windows/desktop/api/fileapi/nf-fileapi-getshortpathnamew), you can pass the short path into FreeType and it should be able to open the path just fine.

**Comment by johanmattssonm** [comment]
Thank you for your solution. GetShortPathNameW made it possible to load paths with non ASCII characters in it. It also reminded me how old Windows really is.

**Comment by lemzwerg** [comment]
For the record: FreeType can be easily configured to use `_wfopen` instead of `fopen`; this is a compile-time option (in file `include/freetype/config/ftstdlib.h`).

**Comment by Alexpux** [comment]
@lemzwerg maybe you then provide pull request to fix this?

**Comment by jtanx** [comment]
@lemzwerg  it's unfortunately not that straightforward. The input into `_wfopen` is a wide character string (`wchar_t*`), so you need to convert to that first, from whatever encoding you started with.

Then if you're doing that, you probably need to also provide a contract that e.g. all paths into FreeType must be UTF-8 encoded, similar to the definition for [g_fopen](https://developer.gnome.org/glib/stable/glib-File-Utilities.html#g-fopen)

I guess you could configure FreeType to use `g_fopen`, but at the cost of introducing a dependency on glib and currently with [this caveat](https://github.com/msys2/MINGW-packages/issues/5150))

**Comment by lemzwerg** [comment]
Sorry, I'm not an msys2 user.  In FreeType's `ftstdlib.h` you can find

```
#define ft_fopen    fopen
```

Maybe it is sufficient for you to change that to

```
#define ft_fopen    _wfopen
```

together with adding the proper Windows header `#include` line.

**Comment by jtanx** [comment]
Yeah, my previous post just said it's not sufficient, because the function signatures are different.

**Comment by lemzwerg** [comment]
OK, thanks for the info.  I wasn't aware of `g_fopen`.

An alternative is to re-implement FreeType's file open routine `FT_Stream_Open` (in file `ftsystem.c`); the library is set up to make this rather straightforward.  As an example, see `builds/amiga/src/base/ftsystem.c`.
