### ISSUE TITLE
Error: "Could not fork child process" when starting msys_shell from Visual Studio's VC command prompt

### ISSUE THREAD

**Issue by bryanch** [msys2/MSYS2-packages#1676]
To repro:
1. Install MS Visual Studio 2019 VC tools
2. Open the vc command window via shortcut "x64 Native Tools Command Prompt for VS 2019"
3. In that window, execute the msys_shell.cmd
The error says:
```
Error: Could not fork child process: There are no available terminals (-1).
```
![image](https://user-images.githubusercontent.com/7624502/59560899-f8fe6500-8fcd-11e9-8344-f91ff7c3973c.png)

Any ideas or workarounds?

**Comment by bryanch** [comment]
never mind, it seems because that I already have another window opened with msys shell, once I clear all of them, this is unblocked.

**Comment by wildtang** [comment]
Today, I encounterd this problem too, I logged off then re-login, this problem disappeared.

**Comment by rickygai** [comment]
i set the c:\msys64\msys2.exe to run as administrator, on "pacman -Syu" shutdown and restart has no such problem anymore and upgraded to 3.6.10-3
