### ISSUE TITLE
[New Package Request]: youtube-dl python-sympy python-mpmath ... ... ... [See comment for full list]

### ISSUE THREAD

**Issue by evan0greenup** [msys2/MSYS2-packages#1680]
Please consider to add the following packages

# Internet:
- [youtube-dl](https://www.archlinux.org/packages/community/any/youtube-dl/) 
- [links](https://www.archlinux.org/packages/core/x86_64/links/)

# Scientific:
**I know that for scientific computing, mingw is much higher performance than msys2, However for some interactive usage, it would be more convenient and more flexible. And make it more similar to Unix/Linux**

- [python-sympy](https://www.archlinux.org/packages/community/any/python-sympy/)
- [python-mpmath](https://www.archlinux.org/packages/community/any/python-mpmath/)
- [python-numpy](https://www.archlinux.org/packages/extra/x86_64/python-numpy/)
- [python-pandas](https://www.archlinux.org/packages/community/x86_64/python-pandas/) 

# Development
## Code Processing
- [yapf](https://www.archlinux.org/packages/community/any/yapf/)
- [bandit](https://www.archlinux.org/packages/community/any/bandit/)
- [shellcheck](https://www.archlinux.org/packages/community/x86_64/shellcheck/)
- [python-pylint](https://www.archlinux.org/packages/extra/any/python-pylint/)

## Library
- [json-c](https://www.archlinux.org/packages/core/x86_64/json-c/)
- [ilbgit2](https://www.archlinux.org/packages/extra/x86_64/libgit2/)
- [python-progress](https://www.archlinux.org/packages/community/any/python-progress/)
- [python-tqdm](https://www.archlinux.org/packages/community/any/python-tqdm/)

## Utils
- [pkgconf](https://www.archlinux.org/packages/core/x86_64/pkgconf/)

# Writing and Publishing
- [pandoc](https://www.archlinux.org/packages/community/x86_64/pandoc/)
- [texlive-most](https://www.archlinux.org/groups/any/texlive-most/) **GROUP**
- [qpdf](https://www.archlinux.org/packages/extra/x86_64/qpdf/)
- [hunspell](https://www.archlinux.org/packages/extra/x86_64/hunspell/) 

# Multimedia
- [ffmpeg](https://www.archlinux.org/packages/extra/x86_64/ffmpeg/)
- [imagemagic](https://www.archlinux.org/packages/extra/x86_64/imagemagick/)

Thanks for consideration.

**Comment by Alexpux** [comment]
@evan0greenup **MSYS** is **Minimal** system for developing MINGW packages. I will not increase MSYS packages without good reason. For your need use **Cygwin** - it have all what you need
