### ISSUE TITLE
Cannot find feature windows_vulkan_sdk

### ISSUE THREAD

**Issue by yaoye** [msys2/MSYS2-packages#1681]
Got a message from Qt Creator after the latest Qt-5.12.4 upgrade:

`D:/msys64/mingw32/share/qt5/mkspecs/common/windows-vulkan.conf(1): Cannot find feature windows_vulkan_sdk`

`D:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf(1): Cannot find feature windows_vulkan_sdk`

`D:/msys64/mingw32/qt5-static/share/qt5/mkspecs/common/windows-vulkan.conf(1): Cannot find feature windows_vulkan_sdk`

`D:/msys64/mingw64/share/qt5/mkspecs/common/windows-vulkan.conf(1): Cannot find feature windows_vulkan_sdk`

**Comment by Alexpux** [comment]
Report it upstream to Qt

**Comment by Alexpux** [comment]
Report it upstream to Qt

**Comment by Alexpux** [comment]
@yaoye, first issues with mingw programs must be in MINGW-packages repository. Second, if you want to see it fixed - report to Qt upstream. This is just warning and I dont care

**Comment by Alexpux** [comment]
@yaoye, first issues with mingw programs must be in MINGW-packages repository. Second, if you want to see it fixed - report to Qt upstream. This is just warning and I dont care

**Comment by Martchus** [comment]
I couldn't find that you've been creating a bug so far so I created one. Just for reference: https://bugreports.qt.io/browse/QTBUG-76660

**Comment by mikehenry-se** [comment]
Please reopen. This issue is now solved upstream with Qt 5.13.2.
When will this version be released under MSYS2?

**Comment by Alexpux** [comment]
There are no near plans to update Qt5 as GCC segfat on building it

**Comment by cchessnz** [comment]
The fix here worked for me: https://forum.qt.io/topic/107833/cannot-find-feature-windows_vulkan_sdk

i.e. go to `mingw64/share/qt5/mkspecs/common`, edit windows-vulkan.conf and change `load(windows_vulkan_sdk)` to `load(win32/windows_vulkan_sdk)`

**Comment by 424778940z** [comment]
> There are no near plans to update Qt5 as GCC segfault on building it

fix it please... now we are on5.14.2 already...
