### ISSUE TITLE
Uname -s returns 'MSYS_NT-6.1-7601' instead of MSYS_NT-6.1'

### ISSUE THREAD

**Issue by kaloskagatos** [msys2/MSYS2-packages#1690]
Hi. Since a recent update, 'uname -s' returns 'MSYS_NT-6.1-7601' but a lot of cmake configurations or bash scripts don't recognize it, expecting only 'MSYS_NT-6.1' like it was before.

The msys2-x86_64-20181211.exe installer doesn't have the problem but running 'pacman -Suy' updates some core libs and the problem comes back.

The same behavior exists on Windows 7, and Window 10.

Is it a normal behavior or will it be corrected ?

Best regards,

Johan

**Comment by Alexpux** [comment]
This is normal since Cygwin 3.0 release

**Comment by kaloskagatos** [comment]
Well... thanks!
