### ISSUE TITLE
How do we get Tk configured correctly on Msys/Mingw64

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MSYS2-packages#1701]
How do we install Tk correctly on Msys/Mingw64, as

```
$ Pacman -S mingw-w64-x86_64-tk

warning: mingw-w64-x86_64-tk-8.6.9.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-tk-8.6.9.1-1
Total Installed Size:  5.39 MiB
```

but tried to run one having it as a dependency, then error:
```
$ ./DeDRM_App.pyw 'Scholastic dictionary of idioms.pdf'

Traceback (most recent call last):
  File "./DeDRM_App.pyw", line 53, in <module>
    import tkinter
  File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

```
How do we get Tk configured correctly ? 
Thanks, really appreciate it

**Comment by StarWolf3000** [comment]
`$ Pacman -S mingw-w64-x86_64-tk`
`$ ./DeDRM_App.pyw 'Scholastic dictionary of idioms.pdf'`
`File "/usr/lib/python3.7/tkinter/__init__.py", line 36, in <module>`
You are running the MSYS2 shell, but want to use a package of MINGW. Please don't do that. Read how MSYS2 and MINGW work, they're not supposed to be mixed up.

Do the following: Close the MSYS2 terminal and use the MINGW64 terminal instead to run `DeDRM_App.pyw`.

**Comment by abdulbadii** [comment]
almost not help, the same module problem here,

$ ./DeDRM_App.pyw 'Scholastic dictionary of idioms.pdf'

Traceback (most recent call last):
  File "./DeDRM_App.pyw", line 55, in <module>
    import Tkconstants
ModuleNotFoundError: No module named 'Tkconstants'

[DeDRM_App.zip](https://github.com/msys2/MSYS2-packages/files/3416653/DeDRM_App.zip)

**Comment by StarWolf3000** [comment]
Your script is probably not written for Python 3. In Python 3, `Tkconstants` is renamed to `tkinter.constants`.

Check http://python3porting.com/stdlib.html

**Comment by sevehub** [comment]
As far as I know, you have to install python from its Windows installer and not with Pacman. Then update the PATH variable in the .bashrc of your terminal. I have written some public available notes about it:  https://tessarinseve.pythonanywhere.com/pelican/msys2-windows-10s-best-friend.html .

**Comment by Biswa96** [comment]
> I have installed needed package, and trying to run Tk in the correct environment, but it still not working:

Are you using mingw python? Try to install mingw python using `pacman -S $MINGW_PACKAGE_PREFIX-python` comand.

**Comment by esaulenka** [comment]
thanks @Biswa96, it helped.

For some strange reason `python` command runs MSYS version. But this is correct one that supports Tk:
```
$ /mingw64/bin/python
Python 3.11.4 (main, Aug 22 2023, 21:54:38)  [GCC 13.2.0 64 bit (AMD64)] on win32
``` 
(note that `cygwin` is not mentioned here)

**Comment by Biswa96** [comment]
> For some strange reason `python` command runs MSYS version.

If you use the MSYS launcher, the `python` command will execute `/usr/bin/python` 
If you use the MINGW64 launcher, the `python` command will execute `/mingw64/bin/python` 

More info about various environment can be found here https://www.msys2.org/docs/environments/

The actual issue can not be reproduced now with latest mingw python.
