### ISSUE TITLE
pacman error: invalid PGP signature of Alexpux

### ISSUE THREAD

**Issue by LigH-de** [msys2/MSYS2-packages#1717]
@Alexpux – `msys: signature from "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" is invalid` while MABS updates MSYS2.

**Comment by Alexpux** [comment]
@LigH-de try some later as I just upload new packages and this can be error on server

**Comment by LigH-de** [comment]
Yes ... no more complaints. Strange how much uploading can interfere; possibly to avoid downloading incompletely uploaded packages?

Now reinstalling all the packages my local pacman removed in panic.
