### ISSUE TITLE
mq_notify api of mqueue.h does not work.

### ISSUE THREAD

**Issue by Nilesh1992** [msys2/MSYS2-packages#1718]
Hi,

I am using windows 10 and installed msys2 to have ENV same as my linux machine.
I have implemented an IPC mechanism based on mqueue Apis. I see few mqueue api's work properly like Create and send as I can see the "/my_queue_name" gets created under "/dev/mqueue/my_queue_name" and I see some data which I put there. But I see the behavior is kind of diff with msys2 on windows. 

**Windows Machine:**
           $ **ls -ltr**
           total 4
          -rw-r--r-- 1 ngharde Domain Users 1296 Aug 11 17:58 Niles
        $ **cat Niles**
            d▒▒1F734DB930DC569D000000001B1061BF▒) @2Tv▒▒This is nilesh string onep"This is 
             nilesh stting two nfnslfn"This is nilesh stting two nfnslfnX▒@▒(▒
            [**When I do cat I see this crap + my added data with send API**]

**LINUX machine Ubuntu 16.04.6 LTS**
          >**ls -ltr**
             total 0
            -rw-r--r-- 1 ngharde users 80 Aug  5 19:27 Niles
         > **cat Niles**
             QSIZE:0          NOTIFY:0     SIGNO:0     NOTIFY_PID:0
            [**Here I see info. about which PID is kind of waiting on this queue to get notified** ]
   
The behavior **where a process subscribe to get notified if there some msg in the queue** kind of works correctly in my Linux machine, but on windows with msys2 that behavior I am not able to achieve. 
code path: https://github.com/Nilesh1992/Personal_Project/blob/master/mq_ipc/src/mq_ipccore.cpp

Thanks in advance!

**Comment by Alexpux** [comment]
MSYS2 use Cygwin codebase, so report it to Cygwin

**Comment by Nilesh1992** [comment]
Hi Alexpux
Thanks would you be able to point me to the exact github project?
Thanks

**Comment by Alexpux** [comment]
You need post on Cygwin ML, there are no github project for it.

**Comment by Nilesh1992** [comment]
Thanks for your help!!
