### ISSUE TITLE
gnutls update error

### ISSUE THREAD

**Issue by jeroen** [msys2/MSYS2-packages#1719]
Since the latest gnutls update I see this on appveyor for each build:

```
:: Processing package changes...
upgrading libgnutls...
error: command (/usr/bin/bash /usr/bin/bash -c . /tmp/alpm_0qtKxd/.INSTALL; post_upgrade 3.6.9-1 3.6.8-2 ) failed to execute correctly
upgrading libzstd...
upgrading man-db...
/tmp/alpm_x9exsw/.INSTALL: line 9: vercmp: command not found
/tmp/alpm_x9exsw/.INSTALL: line 9: [: : integer expression expected
```

**Comment by lazka** [comment]
Note quite clear how this can happen,`vercmp` is part of pacman and is used in man-db

**Comment by mati865** [comment]
Maybe when `/usr/bin` is not in the PATH and pacman was called via `/usr/bin/pacman`?

**Comment by lazka** [comment]
could be, should we go for absolute paths in install scripts?

**Comment by mati865** [comment]
No idea but wonder if using hook instead of install script would solve this (and other issues).
@jeroen is there a way we can reproduce your issue?

**Comment by lazka** [comment]
Not sure of hooks are any different in this case, but we should try to move to them anyway

**Comment by lazka** [comment]
See #2015

I kinda tend towards not supporting running pacman without /usr/bin in PATH. It complicates things and it's easy to forget testing for that scenario. We can try on a best effort basis if anyone really wants it.
