### ISSUE TITLE
pactree -s not finding package

### ISSUE THREAD

**Issue by FlyingWombat** [msys2/MSYS2-packages#1720]
pactree isn't finding packages in sync databases. This persists after full system update; and Arch Linux has no problem doing it, so it's not an upstream problem.
```
$ pactree -u bash
bash
msys2-runtime
```
```
$ pactree -s -u bash
error: package 'bash' not found
```

System info:
```
pacman 5.1.3-3
msys2-runtime 3.0.7-6
```

**Comment by Alexpux** [comment]
It works for me:
````
Alexx@OFFICE MSYS /scripts/mingw-w64-qt5
$ pactree -u bash
bash
msys2-runtime

Alexx@OFFICE MSYS /scripts/mingw-w64-qt5
$ pactree -s -u bash
bash
msys2-runtime
````

**Comment by FlyingWombat** [comment]
I tried a fresh install, and it's still not working.
Any idea how I can troubleshoot this?

**Comment by StarWolf3000** [comment]
It's not working for me either, not even when I excplicitly tell `pactree` to use `/var/lib/pacman/sync` as database path:
```shell
$ pactree -su bash
error: package 'bash' not found

$ pactree -su -b /var/lib/pacman/sync bash
error: package 'bash' not found
```

`pacman` and `msys2-runtime` are both the same versions as FlyingWombat's.

**Comment by cbrt64** [comment]
This turns out to be an upstream bug: `pactree` neglects to set its gpg directory, so it chokes due to missing keys when verifying the repo databases. It's only working on Arch because their repos (at least the ones in my installation) don't have/use .sig files.

A harmless workaround for now is `rm /var/lib/pacman/sync/*.db.sig` after every `pacman -Sy`.

**Comment by FlyingWombat** [comment]
The workaround works for me. Thanks!
Closing, since this actually is an upstream problem.

**Comment by PlatinumLucario** [comment]
> This turns out to be an upstream bug: `pactree` neglects to set its gpg directory, so it chokes due to missing keys when verifying the repo databases. It's only working on Arch because their repos (at least the ones in my installation) don't have/use .sig files.
> 
> A harmless workaround for now is `rm /var/lib/pacman/sync/*.db.sig` after every `pacman -Sy`.

Sorry to revive this after so many years of it being closed, but your suggestion doesn't work anymore...

It still persists with the error, not sure why.
