### ISSUE TITLE
Almost of all package cannot be installed.

### ISSUE THREAD

**Issue by renkarsu** [msys2/MSYS2-packages#1721]
Dear msys2 developer,

I cannot install almost of all package.
Following picture's last line shows "package installing ..." in English.

I wrote "pacman -S mingw-w64-x86_64-toolchain", but msys2 doesn't work ,after it showed "package installing ...".

What should I do?

![image](https://user-images.githubusercontent.com/42439654/63009774-13669900-bec0-11e9-81c0-e3667559dc3c.png)

thank you

**Comment by renkarsu** [comment]
I use "msys2-x86_64-20190524.exe".

**Comment by renkarsu** [comment]
I reinstalled msys2.
Of course, I follow official website.

![image](https://user-images.githubusercontent.com/42439654/63015336-9b9e6b80-becb-11e9-8fc5-d700a7b63785.png)

**Comment by renkarsu** [comment]
If I delete `db.lck` in `C\msys64\var\lib\pacman`, MSYS2 shows follow picture.

![image](https://user-images.githubusercontent.com/42439654/63015791-e2d92c00-becc-11e9-9529-4652e4df3064.png)

**Comment by jtanx** [comment]
Can you reach http://repo.msys2.org?

What if you try reordering the mirror list in /etc/pacman.d/mirrorlist.mingw32 /  /etc/pacman.d/mirrorlist.mingw64 /  /etc/pacman.d/mirrorlist.msys

**Comment by renkarsu** [comment]
I tried `pacman -Syuu`, and I continue to write "pacman -Syuu" until msys2 says there are no packages to update.
But, It doesn't work.

**Comment by renkarsu** [comment]
OK, I will try

**Comment by renkarsu** [comment]
I'm sorry to bother you, but I reached.
What can I do?

What is the mirror list?


I got `msys2-x86_64-20190524.exe` from following picture, before I asked you.
![image](https://user-images.githubusercontent.com/42439654/63017725-0b175980-bed2-11e9-85b0-75eabd3e739a.png)

**Comment by jtanx** [comment]
Ah, ok then it's probably not related.

My suggestion was to try editing C\msys64\etc\pacman.d\mirrorlist.mingw32 (and mirrorlist.mingw64/mirrorlist.msys) so that instead of

```
Server = http://repo.msys2.org/mingw/i686/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/
Server = https://mirror.yandex.ru/mirrors/msys2/mingw/i686/
```

You have

```
Server = https://sourceforge.net/projects/msys2/files/REPOS/MINGW/i686/
Server = http://www2.futureware.at/~nickoe/msys2-mirror/mingw/i686/
Server = https://mirror.yandex.ru/mirrors/msys2/mingw/i686/
Server = http://repo.msys2.org/mingw/i686/
```

So it tries sourceforge.net first instead of repo.msys2.org

But if you can reach repo.msys2.org, then that's probably not the issue

**Comment by renkarsu** [comment]
I tried installing many times.
I usually got msys2 from `https://www.msys2.org/`.

**Comment by renkarsu** [comment]
now

![image](https://user-images.githubusercontent.com/42439654/63022303-95b18600-bedd-11e9-8ca3-8414b79a94b5.png)

**Comment by renkarsu** [comment]
oh

![image](https://user-images.githubusercontent.com/42439654/63022474-f9d44a00-bedd-11e9-88b9-af873c8d0b2b.png)
