### ISSUE TITLE
"ps -W" does not show correct PID

### ISSUE THREAD

**Issue by Taogle2018** [msys2/MSYS2-packages#1724]
Hi,

This is my first time reporting an issue. Hope I will do it right.
I used msys2 to debug qemu a lot. I usually use "ps -W | grep qemu" to find the pid and use "gdb -p PID" to attach to the process.
Today (8/15/2019) I updated all the packages using "pacman -Syu". And my workflow is broken. Eventually I found that "ps -W" was not showing the right PID.

Anyone know the solution or fix?

Right now, I am using Windows Task Manager to get the PID as an input to gdb.

Thanks!

**Comment by Taogle2018** [comment]
The noticeable difference is that now "ps -W" shows very big pid number. I used to get PID at most 1xxxx. Now most of the time, the PID is 7xxxx.

**Comment by cbrt64** [comment]
There was an [intended change](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=448cf5aa4b429d5a9cebf92a0da4ab4b5b6d23fe) in Cygwin 3.0.1; this change was introduced to msys2-runtime version 3.0.6-1, released 2019-04-15. Specifically, the `PID` column doesn't match `WINPID` anymore; `WINPID` is the one you'll want to use from now on.

**Comment by Taogle2018** [comment]
Thanks!
So I have to blame cygwin. No matter what is the reason of the change, breaking existing stuffs is stupid. Even a mistake should be kept there if it is widely accepted. I wonder whether the linux kernel always returns error code right? If not, do kernel developers and maintainers dare to make a correction if user space program already get used to that?

**Comment by mingwandroid** [comment]
We accept Cygwins decisions by default. Please raise this with them.
