### ISSUE TITLE
Unable to generate SSH key

### ISSUE THREAD

**Issue by orjanno** [msys2/MSYS2-packages#1731]
Hi,

Ref. reported issue [here](https://github.com/git-for-windows/git/issues/2299)

I have a problem generating SSH keys on Windows 7. I have tried Git for Windows (MINGW64) and also plain MSYS2. Same problem. 

Trying with this command; ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
Instead of waiting for my input (writing file name) it just gives me a new prompt.

Could this be related to some sort of privilege issue on my local computer? Strange thing is that it works on one Win7 machine, but two similar Win7 machines fails.

Thanks.

Br
Ørjan Nordvik

**Comment by StarWolf3000** [comment]
Alternatively, run `$ ldd ssh-keygen` and check, if there are any linked libraries with a sequence of question marks.

**Comment by dalethatcher** [comment]
I'm also seeing this issue under Windows 7 when I upgraded from openssh-7.6p1 to 8.0p1.  It doesn't just affect ssh-keygen but ssh as well which makes it impossible to use git via ssh.

I tried running using strace which gives lots of these errors before exiting:
Process 400, exception c0000005 at 00000001800614ac

Running in gbd does not seem to trigger the issue.  Any suggestions on how I can debug this?

**Comment by dalethatcher** [comment]
I've recently moved to a Windows 10 virtual machine and I'm getting the same behaviour.  So it's not just a Windows 7 thing.

**Comment by peterbud** [comment]
I had no problem running `ssh-keygen `:
```
$ ssh-keygen -t rsa -b 4096 -C "peterbudai@test.com"
Generating public/private rsa key pair.
Enter file in which to save the key (/home/peterbud/.ssh/id_rsa): peterbudaitestcom2
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in peterbudaitestcom2.
Your public key has been saved in peterbudaitestcom2.pub.
The key fingerprint is:
SHA256:[...] peterbudai@test.com

```

**Comment by cbrt64** [comment]
FWIW, I'm not able to reproduce this either.

It seems not unreasonable to think it's something particular to the affected systems. @dalethatcher, is there anything else you installed in the Win10 VM? Exception c0000005 has been known to be associated with interference from [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda); see https://sourceforge.net/p/msys2/tickets/212/, where it appears they used [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to track down the unwanted DLL that was being (successfully) injected. Running Windows in safe mode could be diagnostically useful as well.

Just my tuppence...

**Comment by dalethatcher** [comment]
Thanks for trying to reproduce.

I tried setting CYGWIN to "detect_bloda" (suggested in the Cygwin FAQ) but it didn't give any output.  I guess it's not implemented under msys2?

Unfortunately it's a work provided virtual desktop so has a whole bunch of stuff installed.  I'll try process monitor to see if I can figure anything more out.

**Comment by cbrt64** [comment]
It turns out `detect_bloda` was removed from cygwin three years ago, https://sourceware.org/git/?p=newlib-cygwin.git;a=commit;h=cb34fffe07e13fc5ccbcc5e9fb7f951eb7d5c2b8, but the FAQ was not updated. Oh well.

**Comment by Shwetanshu** [comment]
Is this issue resolved ? I am also getting this problem on Windows 7. Tried uninstalling and deleting all cache and reinstalling. But , no luck. It is exiting  soon after prompt of rsa key location: "Enter file in which to save the key (/h//.ssh/id_rsa):"

**Comment by dalethatcher** [comment]
Still not solved for me. I had to install an ancient version of Git for windows (2.15, https://github.com/git-for-windows/git/releases/tag/v2.15.1.windows.1).  Which doesn't have the issue on my virtual machine.

I've not had time to try and diagnose it further.

**Comment by aperez3-godaddy** [comment]
executed the same command from cmd.exe and it worked

**Comment by Biswa96** [comment]
The issue is no longer reproducible. Thank you.
