### ISSUE TITLE
gdbinit does not set up sys.path correctly for stdcxx

### ISSUE THREAD

**Issue by rrthomas** [msys2/MSYS2-packages#1732]
There seem to be two problems:

1. The package needs to be updated whenever the version of gcc changes, and has not been recently (gcc 9.2.0 is the current version; `/etc/gdbinit` current refers to 9.1.0).
2. The package appends to `sys.path[0]` but when I start up Python, that element is empty. The location to refer to is `/mingw64/share/%GCC_NAME%/python`, so would it be easier to get this as an absolute path, e.g. using `MSYSTEM_PREFIX`?

**Comment by StarWolf3000** [comment]
1. Current GCC release for MSYS2 is 9.1.0, so the script is correct.
2. Wrong environment, see 1. Don't mix up MSYS2 and MINGW environments and packages!

**Comment by rrthomas** [comment]
Thanks for the explanation, and sorry for my hastiness!
