### ISSUE TITLE
Package downloading stopped after 10 seconds

### ISSUE THREAD

**Issue by iesliuguohua** [msys2/MSYS2-packages#1733]
After a system reinstallation, I installed the msys2 today, then I use "pacman -Syu" to update, downloading seems OK, but after about 10s, it tells me "Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds". I'm sure the data is transfering in the past 10 seconds.  Also I get the same result when I attemp to install some packages like gcc.
![msys2](https://user-images.githubusercontent.com/34376968/64316216-c7060900-cfe6-11e9-93f9-7a88041e5398.gif)

**Comment by cbrt64** [comment]
This bug in pacman/curl has been [fixed](#1659) in msys2, but that was after the latest msys2 installer was made. Running `pacman -Syu --disable-download-timeout` (per https://github.com/msys2/MSYS2-packages/issues/1658#issuecomment-495955432) will install the newer fixed packages without "timing out".

**Comment by iesliuguohua** [comment]
Thanks @cbrt64 . After a "pacman -Syu --disable-download-timeout", everything seems OK.

**Comment by l-t-m-f** [comment]
I experienced this today. Took me a while because I've installed it before no problemo.
