### ISSUE TITLE
cloc - Missing Moo/Role.pm dependency

### ISSUE THREAD

**Issue by jmuehlenhoff** [msys2/MSYS2-packages#1742]
cloc used to work a while ago, at the moment I get this:

```
$ cloc .
Can't locate Moo/Role.pm in @INC (you may need to install the Moo::Role module) (@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/Parallel/ForkManager/Child.pm line 12.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Parallel/ForkManager/Child.pm line 12.
Compilation failed in require at /usr/share/perl5/vendor_perl/Parallel/ForkManager.pm line 12.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/Parallel/ForkManager.pm line 12.
Compilation failed in require at /usr/bin/cloc line 851.
BEGIN failed--compilation aborted at /usr/bin/cloc line 851.

```

**Comment by jmuehlenhoff** [comment]
Someone has a similar here with another dependency: https://github.com/msys2/MSYS2-packages/issues/1114

**Comment by herrmalte** [comment]
I just ran `cpan Moo` and after a couple of minutes of installations the dependency issue was fixed

**Comment by friederbluemle** [comment]
Thanks @herrmalte - I also ran `cpan Moo`. No idea what it did, but it fixed `cloc` for me. 😄 👍

**Comment by jmuehlenhoff** [comment]
This is only a workaround though.

The Moo module should be packaged and be made a dependency for the cloc package.

**Comment by Alexpux** [comment]
It already done, seems you don’t update your packages

**Comment by Alexpux** [comment]
See https://github.com/msys2/MSYS2-packages/commit/21266b893f0ff6a75ccda57c17cc34e124439a79

**Comment by jmuehlenhoff** [comment]
Or maybe it's a dependency of Parallel::ForkManager?
