### ISSUE TITLE
emacs msys2 msys-giofam.dll failure

### ISSUE THREAD

**Issue by craigmac** [msys2/MSYS2-packages#1743]
I get "Failed to load /usr/lib/gio/modules/msys-giofam.dll" when starting emacs 26.2-2. I can't find anything via google-fu and this issue track related to this dll specifically. Could any help point in the right direction to debugging this?  Emacs still starts, and seems to work... but I'm not sure when that failed dll is going to come back to bite while using it.

**Comment by StarWolf3000** [comment]
The DLL in question is part of the package `glib2`:
https://packages.msys2.org/package/glib2?repo=msys&variant=x86_64
https://packages.msys2.org/package/glib2?repo=msys&variant=i686
