### ISSUE TITLE
[pacman] GraphViz gone.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [msys2/MSYS2-packages#1744]
Greetings,

   Today I tried `pacman -Ss graphviz` to get the available GraphViz packages to download and it returned a blank list.  I recall two months ago I was able to obtain the package in another computer.  The precompiled libraries in GraphViz website are 32-bit, so it won't link against a 64-bit program.  How can I get it?

thanks in advance.

**Comment by PauloCarvalhoRJ** [comment]
I tried the instructions here:
https://packages.msys2.org/package/mingw-w64-x86_64-graphviz

But it fails.

**Comment by PauloCarvalhoRJ** [comment]
I was able to download the package file (`.pkg.tar.xz` file), but how do I install it after I install its dependencies?

**Comment by StarWolf3000** [comment]
There's no MSYS2 package named `graphviz`.

And you install the MINGW packages with `$ pacman -S mingw-w64-{i686,x86_64}-graphviz`. Questions for MINGW packages are asked at the MINGW-packages repository, not here.

**Comment by PauloCarvalhoRJ** [comment]
Please, reread my posts carefully.  I first tried, in MSYS2's console (so this is the right place to ask), `pacman -Ss graphviz`.  Notice the `s` appended to the `-S`.  `s` for search.  So that first command is supposed to return a list of packages.  Then, I'd enter the command with the sole `-S` and the full package name, which fails.  GraphViz is missing.

**Comment by StarWolf3000** [comment]
Then your local repository databse isn't up-to-date. Run `$ pacman -Syy` and try again.
The output of `$ pacman -Ss graphviz`should be the following:
```bash
$ pacman -Ss graphviz
mingw32/mingw-w64-i686-graphviz 2.40.1-10
    Graph Visualization Software (mingw-w64)
mingw64/mingw-w64-x86_64-graphviz 2.40.1-10
    Graph Visualization Software (mingw-w64)
```

**Comment by PauloCarvalhoRJ** [comment]
Thanks, friend.  Worked like charm.
