### ISSUE TITLE
MSYS2 terminal crashes under Windows 10.

### ISSUE THREAD

**Issue by PauloCarvalhoRJ** [msys2/MSYS2-packages#1747]
Whenever I try to open MSYS2's shell to download packages, the error below ensues.
![image](https://user-images.githubusercontent.com/6398896/65531481-5c066e80-ded0-11e9-96e8-1933989631e2.png)
Rendering it unusable.

**Comment by StarWolf3000** [comment]
Windows error code 5 determines "Access is denied", in most cases, either by requesting a privileged action, like admin access or trying to read and/or write to a directory/file you are not allowed to.

Code 11 from bash (reporting as POSIX error code) is "Resource temporarily unavailable".

Where is MSYS2 installed to?

**Comment by PauloCarvalhoRJ** [comment]
Here: `C:\Users\pcrv\Desktop\msys2`

I don't have (nor can have) admin privileges.  Well, all other programs work without admin privileges, I wonder why MSYS2 would.

**Comment by PauloCarvalhoRJ** [comment]
I plugged my laptop computer into another network (outside the coporate one).  MSYS2 seemed to run a lot of initialization tasks (most with error messages), restarted MSYS2 and I finally got to the prompt.  Then I tested with `pacman -Ss graphviz` and I got this:

```
$ pacman -Ss graphviz
      1 [main] pacman 1401 child_copy: stack write copy failed, 0xFFFFBE90..0x100000000, done 0, windows pid 2976, Win32 error 5
   8016 [main] pacman 1401 dofork: child 1402 - pid 7704, exitval 0x103, errno 11
 249361 [main] pacman 1401 child_copy: stack write copy failed, 0xFFFFBE90..0x100000000, done 0, windows pid 2976, Win32 error 5
 274496 [main] pacman 1401 dofork: child 1403 - pid 5440, exitval 0x103, errno 11
 509762 [main] pacman 1401 child_copy: stack write copy failed, 0xFFFFC2D0..0x100000000, done 0, windows pid 2976, Win32 error 5
 527229 [main] pacman 1401 dofork: child 1404 - pid 13092, exitval 0x103, errno 11
erro: Erro de GPGME: Motor de encriptação inválido
erro: Erro de GPGME: Motor de encriptação inválido
erro: Erro de GPGME: Motor de encriptação inválido
erro: "mingw32" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))
erro: "mingw64" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))
erro: "msys" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))
```

Translation of "Erro de GPGME: Motor de encriptação inválido": GPGME Error: invalid encryption engine.
Translation of last message: "msys" database is not valid (invalid database or corrupted (PGP fingerprint))

**Comment by mati865** [comment]
> Windows error code 5 determines "Access is denied", in most cases, either by requesting a privileged action, like admin access or trying to read and/or write to a directory/file you are not allowed to.

IMO most often it happens because there is open handle to the file (for an example executable that you want replace is running). On Windows file cannot be replaced or deleted unless all handles to it have been closed.

> Translation of "Erro de GPGME: Motor de encriptação inválido": GPGME Error: invalid encryption engine.

Most likely different program is breaking MSYS2. I'd guess it's your AV software but there are other possible causes:
https://github.com/msys2/MSYS2-packages/issues/393#issuecomment-159196510

**Comment by PauloCarvalhoRJ** [comment]
> 
> 
> > Windows error code 5 determines "Access is denied", in most cases, either by requesting a privileged action, like admin access or trying to read and/or write to a directory/file you are not allowed to.
> 
> IMO most often it happens because there is open handle to the file (for an example executable that you want replace is running). On Windows file cannot be replaced or deleted unless all handles to it have been closed.
> 
> > Translation of "Erro de GPGME: Motor de encriptação inválido": GPGME Error: invalid encryption engine.
> 
> Most likely different program is breaking MSYS2. I'd guess it's your AV software but there are other possible causes:
> [#393 (comment)](https://github.com/msys2/MSYS2-packages/issues/393#issuecomment-159196510)


>>>>This error can happen if there are conflicting gnupg installations in PATH. Try running pacman in a special shell like set PATH=, msys2_shell.bat.

Didn't work.

>>>>MacType can cause this. Put gpg.exe and pacman.exe lines under the [UnloadDll] section of your .ini file under C:\Program Files (x86)\MacType\ini or C:\Program Files\MacType\ini.

I don't have MacType installed.    

 >>>>Check BLODA.

This could be from a thousand sources... none of them, if this is the case, I can can disable because I'm not administrator of the machine nor the company's IT department is willing to.

 >>>>It can happen when the upgrade process reported failures (fork errors). Use update-core for system upgrades and take care to follow the instructions.

update-core?  What's this?  A command?  An executable?

>>>>Try re-installing gpgme libgpgme, gnupg and pacman packages (you can temporarily disable signature checking in /etc/pacman.conf).

How do I do reinstall them?
What should I do in /etc/pacman.conf to disable signature checking?  The file is not so obvious.

>>>>Try removing /etc/pacman.d/gnupg, then pacman-key --init, pacman-key --populate msys2, pacman-key --refresh-keys.

Last command resulted in:

      0 [main] gpg 1362 child_copy: stack write copy failed, 0xFFFFC190..0x100000000, done 0, windows pid 5892, Win32 error 5
    1927 [main] gpg 1362 dofork: child 1363 - pid 15100, exitval 0x103, errno 11
    gpg: error forking process: Resource temporarily unavailable
    gpg: failed to start the dirmngr '/usr/bin/dirmngr': Resource temporarily unavailable
    gpg: connecting dirmngr at '/etc/pacman.d/gnupg/S.dirmngr' failed: Resource temporarily unavailable
    gpg: keyserver refresh failed: Sem dirmngr

 and didn't work.

>>>>Maybe autorebase.bat is sometimes needed even for 64-bit MSYS2.

How do I use this?

>>>>Try debugging for GPGME by export GPGME_DEBUG=9 before running pacman ...something... 2> ~/gpgmelog and looking at the logfile ~/gpgmelog.

    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_debug: level=9
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version: call: 0=0x0 req_version=(null), VERSION=1.13.0-unknown
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version_internal: call: 0=0x0 req_version=(null), offset_sig_validity=60
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=2, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=6, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme-dinfo: gpgconf='/usr/bin/gpgconf'
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: enter: filedes=0xffffc21c inherit_idx=1 (GPGME uses it for reading)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: leave: read=0x5, write=0x6
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: enter: path=0x60004a240 path=/usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 0] = /usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 1] = --list-dirs
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 fd[0] = 0x6 -> 0x1
      0 [main] pacman 1471 child_copy: stack write copy failed, 0xFFFFBE90..0x100000000, done 0, windows pid 9820, Win32 error 5
      18779 [main] pacman 1471 dofork: child 1472 - pid 12960, exitval 0x103, errno 11
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn:493: error: Unknown error -1 (-1)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x5 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x6 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: enter: filedes=0xffffc21c inherit_idx=1 (GPGME uses it for reading)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: leave: read=0x5, write=0x6
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: enter: path=0x60004a240 path=/usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 0] = /usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 1] = --list-components
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 fd[0] = 0x6 -> 0x1
      40981 [main] pacman 1471 child_copy: stack write copy failed, 0xFFFFBE90..0x100000000, done 0, windows pid 9820, Win32 error 5
      43340 [main] pacman 1471 dofork: child 1473 - pid 10444, exitval 0x103, errno 11
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn:493: error: Unknown error -1 (-1)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x5 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x6 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: enter: filedes=0xffffc658 inherit_idx=1 (GPGME uses it for reading)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_pipe: leave: read=0x5, write=0x6
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: enter: path=0x60004a240 path=/usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 0] = /usr/bin/gpgconf
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 argv[ 1] = --version
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn: check: path=0x60004a240 fd[0] = 0x6 -> 0x1
      64940 [main] pacman 1471 child_copy: stack write copy failed, 0xFFFFC2D0..0x100000000, done 0, windows pid 9820, Win32 error 5
      67568 [main] pacman 1471 dofork: child 1474 - pid 16052, exitval 0x103, errno 11
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_spawn:493: error: Unknown error -1 (-1)
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x5 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: enter: fd=0x6 
    GPGME 2019-10-01 21:24:54 <0x05bf>  _gpgme_io_close: leave: result=0
    GPGME 2019-10-01 21:24:54 <0x05bf>  engine.c:162: returning error: Motor de encriptação inválido
    erro: Erro de GPGME: Motor de encriptação inválido
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version: call: 0=0x0 req_version=(null), VERSION=1.13.0-unknown
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version_internal: call: 0=0x0 req_version=(null), offset_sig_validity=60
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=2, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=6, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  engine.c:162: returning error: Motor de encriptação inválido
    erro: Erro de GPGME: Motor de encriptação inválido
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version: call: 0=0x0 req_version=(null), VERSION=1.13.0-unknown
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_check_version_internal: call: 0=0x0 req_version=(null), offset_sig_validity=60
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=2, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: enter: ctx=0x0 category=6, value=pt_BR.UTF-8
    GPGME 2019-10-01 21:24:54 <0x05bf>  gpgme_set_locale: leave: 
    GPGME 2019-10-01 21:24:54 <0x05bf>  engine.c:162: returning error: Motor de encriptação inválido
    erro: Erro de GPGME: Motor de encriptação inválido
    erro: "mingw32" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))
    erro: "mingw64" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))
    erro: "msys" base de dados não é válida (base de dados inválida ou corrompida (assinatura PGP))

Configure your favorite translator to Portuguese->English to get translations for the non-English messages above.

**Comment by PauloCarvalhoRJ** [comment]
I took this issue to IT department and they determined the anti-virus (Trend Micro Office Scan) was the cause.

**Comment by PauloCarvalhoRJ** [comment]
Problem returned. :(

**Comment by PauloCarvalhoRJ** [comment]
Whatever the system hook that was causing the problem, it was de-activaed and MSYS2 worked like charm.
