### ISSUE TITLE
OSTYPE is missing from `env` output

### ISSUE THREAD

**Issue by godsic** [msys2/MSYS2-packages#1756]
In `msys2` shell (`msys/msys2-runtime 3.0.7-6`) 
`echo $OSTYPE` gives `msys` 
while 
`env | grep OSTYPE` gives nothing.

Reading `OSTYPE` from the spawned process (e.g., via  `auto ostype_cstr = getenv("OSTYPE")`) gives nothing as well.

Is it intentional?

**Comment by lazka** [comment]
OSTYPE is a default bash variable and not an env var: https://linux.die.net/man/1/bash

```
OSTYPE

Automatically set to a string that describes the operating system on which bash is executing. The default is system-dependent. 
```

**Comment by hiroakit** [comment]
@lazka 

I agree. My understanding is the same [it](https://github.com/msys2/MSYS2-packages/issues/1756#issuecomment-573337028)
So, would you mind closing this issue.

**Comment by lazka** [comment]
thx
