### ISSUE TITLE
Proposals for missing packages?

### ISSUE THREAD

**Issue by loumalouomega** [msys2/MSYS2-packages#1757]
Greetings, how can we propose new packages? I would propose for example to include the development versions of python, python-dev and python3-dev.

**Comment by Alexpux** [comment]
I will not build debug versions of packages.

**Comment by loumalouomega** [comment]
Not debug version, devel. In order to have the includes. Right now it's not
possible to compile with cpython with the python included in the repo.
Impressive work anyway, very grateful.

**Comment by mati865** [comment]
@loumalouomega MSYS2 uses Arch Linux package manager called `pacman`.
MSYS2 just like Arch Linux has no dev packages in and everything is just merged into single package.

> Not debug version, devel. In order to have the includes.

You can see everything is included:
https://msys2.duckdns.org/package/python?repo=msys&variant=x86_64

**Comment by loumalouomega** [comment]
I see, therefore the includes are there but my cmake does not detect it?

**Comment by mati865** [comment]
Maybe you have mistaken MSYS2 packages/shell with MINGW?
https://github.com/msys2/msys2/wiki/MSYS2-introduction#subsystems

**Comment by loumalouomega** [comment]
No, I am using the MSYS2, but I didn't know it mimic the Arch linux path installation (I know that it uses pacman, but no that it was exactly the same). Thanks, I will close
