### ISSUE TITLE
Add GitHub's `hub` package (in Go)

### ISSUE THREAD

**Issue by XVilka** [msys2/MSYS2-packages#1759]
[`hub`](https://hub.github.com/) is a command line tool that wraps git in order to extend it with extra features and commands that make working with GitHub easier:

```sh
# clone your own project
$ hub clone dotfiles
→ git clone git://github.com/YOUR_USER/dotfiles.git

# clone another project
$ hub clone github/hub
→ git clone git://github.com/github/hub.git

# open the current project's issues page
$ hub browse -- issues
→ open https://github.com/github/hub/issues

# open another project's wiki
$ hub browse mojombo/jekyll wiki
→ open https://github.com/mojombo/jekyll/wiki
```
Their [repository](https://github.com/github/hub) is at GitHub.
There is an existing Arch Linux package - https://www.archlinux.org/packages/community/x86_64/hub/

**Comment by XVilka** [comment]
Trying to address it in https://github.com/msys2/MSYS2-packages/pull/1760

**Comment by hiroakit** [comment]
Please close.

**Comment by hiroakit** [comment]
Thank you.
