### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by tom66** [msys2/MSYS2-packages#1763]
I would really appreciate if Python 3.8 could be made available for MSYS2.  

I have a specific need for the Multiprocessing shared_memory module which is new to 3.8.  Python 3.8 is now stable and available for Windows.

I had a look at making the required changes to the existing 3.7.4 patches but I got out of my depth when needed packages couldn't be found.  I know when I'm beaten!

Kind regards.

**Comment by lazka** [comment]
Do you really mean the msys version or the mingw (native Windows) version?

**Comment by tom66** [comment]
When I attempted to install, via `pacman` on msys2 (AMD64), the latest version available was 3.7.4.

I attempted to build 3.8 and was successful, but could not get this to work with msys.  I was able to run basic programs, but nothing using useful modules like python-gobject would function correctly. I suspect this is a matter of configuration, but it is not my area of expertise.

**Comment by lazka** [comment]
You probably want the mingw version then (as python-gobject is only available there), https://packages.msys2.org/package/mingw-w64-x86_64-python3?repo=mingw64

As you can see here: https://github.com/msys2/MINGW-packages/commits/master the update is currently underway.

**Comment by tom66** [comment]
OK, thanks! I will take a look. Consider this issue resolved for the time being.

**Comment by tom66** [comment]
Great, thanks. Tom
