### ISSUE TITLE
[gcc]  version mismatch between MSYS2 website and pacman

### ISSUE THREAD

**Issue by GeneGeneGitHub** [msys2/MSYS2-packages#1767]
pacman -S gcc
reports that it will install 7.4.0-1

The MSYS2 packages list says it will install 9.1.0-2.

And pacman -S gcc  DOES install 7.4.0-1

**Comment by lazka** [comment]
I get this:

```
$ pacman -S gcc
warning: gcc-9.1.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) gcc-9.1.0-2

Total Download Size:    26.32 MiB
Total Installed Size:  112.06 MiB
Net Upgrade Size:        0.00 MiB
```

**Comment by lazka** [comment]
Make sure to run `pacman -Suy` before installing things

**Comment by GeneGeneGitHub** [comment]
ran pacman -Suy


===========================================
$ pacman -S gcc
resolving dependencies...
looking for conflicting packages...

Packages (2) gcc-libs-9.1.0-2  gcc-9.1.0-2

Total Download Size:    27.48 MiB
Total Installed Size:  116.69 MiB
Net Upgrade Size:       11.97 MiB

:: Proceed with installation? [Y/n]
===========================================

As you can see, I did the 7.x install, so it wanted to upgrade.

That seems to have resolved it.  Sorry for being lazy and not reading steps 5/6:

pacman - Suy
pacman -Su

I'm gonna reinstall MSYS2 as per the instructions, just so I'm clean.  Doesn't take long anyway.

Great job on MSYS2.  Seriously.  You guys are to be commended for making it easy to get a Linux environment up on Windows.  I've been dual-booting for the longest.


________________________________

**Comment by lazka** [comment]
We currently follow Arch Linux in that installing a package is only supported on a fully updated system (pacman -Suy is run before).

I think if you'd just update you should be fine though, no need to reinstall.
