### ISSUE TITLE
Issue #1651 came back : Pacman Retrieving packages error with QueryUnbiasedInterruptTime function call 

### ISSUE THREAD

**Issue by rdjondo** [msys2/MSYS2-packages#1783]
Hello,

After running pacman -Syuu, then pacman -Syuu again, I get the same issue as #1651.
Pacman returns the following error:
`pacman.exe: *** fatal error - couldn't dynamically determine load address for 'QueryUnbiasedInterruptTime' `

My pacman sources (`/etc/pacman.conf`) are configured to use the addresses as described in:
https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper

```
[git-for-windows]
Server = https://wingit.blob.core.windows.net/x86-64 
```

My pacman version is : pacman --version :   Pacman v5.2.1 - libalpm v12.0.1

Could the solution be fixed in the code as suggested in issue #1651?

**Comment by StarWolf3000** [comment]
Looks more like the modified `msys2-runtime` is not compatible with our `pacman`. They should check, if `msys2-runtime` is up-to-date with ours to implement their patches, not the other way around. And since they refuse to send their patches upstream, no help can be given from MSYS2 team.

**Comment by rdjondo** [comment]
Thanks, I will submit the issue to the https://github.com/git-for-windows/git/ project.
