### ISSUE TITLE
libpthread uses GetTickCount64 even if WINVER=0x0501 define used

### ISSUE THREAD

**Issue by r4sas** [msys2/MSYS2-packages#1784]
Application built with `CXXFLAGS += -DWINVER=0x0501 -D_WIN32_WINNT=0x0501`

![image](https://user-images.githubusercontent.com/7023612/68811422-aa8aea80-0681-11ea-99ab-83dd658b2702.png)
![image](https://user-images.githubusercontent.com/7023612/68811467-c2626e80-0681-11ea-892a-b8e1f3bdd2e7.png)

Target OS is WinXP, where GetTickCount64 is not available in kernel32.dll.

**Comment by StarWolf3000** [comment]
Please post this at msys2/MINGW-packages, it's a MINGW (native Windows) issue, not an MSYS2 (POSIX compatibility) issue.

**Comment by Alexpux** [comment]
@r4sas we not support XP compatibility anymore, so it will not be fixed in any case

**Comment by r4sas** [comment]
Which version was latest with XP support? How can we use it?

**Comment by mati865** [comment]
@r4sas you can change targeted OS for your local packages here https://github.com/msys2/MINGW-packages/blob/cbafe098c09efac962b63b359e78bca733a6e1cb/mingw-w64-headers-git/PKGBUILD#L58 and then rebuild headers->crt->winpthreads in that order.

**Comment by r4sas** [comment]
@mati865 thanks! Will try that way.
