### ISSUE TITLE
mpv missing library, unknown which one

### ISSUE THREAD

**Issue by Tatsh** [msys2/MSYS2-packages#1789]
```
$ ./mpv.exe
C:/msys64/mingw64/bin/mpv.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```

This is a new install of MSYS2.

**Comment by StarWolf3000** [comment]
Not an MSYS2 package, is a MINGW package (so you should've asked at msys2/MINGW-packages instead). Use `ldd /mingw64/bin/mpv.exe` or run the mpv.exe from a Windows command prompt to get the missing libraries.

**Comment by Tatsh** [comment]
Thanks. I reported it to the right place.
