### ISSUE TITLE
Can't load '/usr/lib/perl5/site_perl/auto/threads/shared/shared.dll

### ISSUE THREAD

**Issue by abdulbadii** [msys2/MSYS2-packages#1797]
Error when tried to bootstrap with intention to build **sed** from checkout/latest source code :
```
./bootstrap

Can't load '/usr/lib/perl5/site_perl/auto/threads/shared/shared.dll' for module threads::shared: No such file or directory at /usr/share/perl5/core_perl/XSLoader.pm line 93.
 at /usr/lib/perl5/site_perl/threads/shared.pm line 24.
Compilation failed in require at /usr/share/perl5/site_perl/Thread/Queue.pm line 9.
BEGIN failed--compilation aborted at /usr/share/perl5/site_perl/Thread/Queue.pm line 9.
....
...
```
What seems to mitigate this ? Thanks much

**Comment by StarWolf3000** [comment]
That file does not exist at this location. It is instead at `/usr/lib/perl5/core_perl/auto/threads/shared/shared.dll` and this is part of the `perl` package (at least in 5.30.x).

What is your installed `perl` version?

**Comment by abdulbadii** [comment]
Thanks outright correct and..
the culprit is in sed repo itself is ugly old repo
