### ISSUE TITLE
Feature request: Small change in prompt

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#1798]
I wonder if you can change the prompt definition in this way (`/etc/bash.bashrc`)

```
-[[ $(declare -p PS1 2>/dev/null | cut -c 1-11) = 'declare -x ' ]] || \
  export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '

+[[ $(declare -p PS1 2>/dev/null | cut -c 1-11) = 'declare -x ' ]] || \
  export PS1='\[\e]0;\u@\h: \w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\]: \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '
```

(just this: `...\[\e]0;\u@\h \w\a\]\n...`) so that `USER@HOST CURR_PATH` shows up in the window  terminal (MinTTY and friends) bar title, near the icon...

**Comment by hiroakit** [comment]
@angelog0 
Maybe, it's ok. 
See also, how to use of bash.
https://www.gnu.org/software/bash/manual/html_node/Controlling-the-Prompt.html

Finally, this ticket isn't feature request or bug report. 
So, would you be able to close this ticket?

**Comment by angelog0** [comment]
@hiroakit wrote:

> See also, how to use of bash.

I know how to use Bash and how to configure it to get the changes in prompt I flagged

> Finally, this ticket isn't feature request

**It is precisely a request for that feature!!**

May be you prefer this:

Can you add this patch to `/etc/bash.bashrc`:

```
-[[ $(declare -p PS1 2>/dev/null | cut -c 1-11) = 'declare -x ' ]] || \
  export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '

+[[ $(declare -p PS1 2>/dev/null | cut -c 1-11) = 'declare -x ' ]] || \
  export PS1='\[\e]0;\u@\h: \w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\]: \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '
```

? 

Thanks.

**Comment by hiroakit** [comment]
@angelog0 
Thank you for your comment.
I recognized that this issue is a request for feature.

If you send a PR to this repository, your patches may be adopted.

Why did you think that you needed this issue?
And, would you are able to share your goal?

**Comment by angelog0** [comment]
@hiroakit wrote:

> If you send a PR to this repository, your patches may be adopted.

This could be the patch (I have gzipped because GitHub does not accept `.diff`)

[bash.bashrc.diff.gz](https://github.com/msys2/MSYS2-packages/files/4291980/bash.bashrc.diff.gz)

It adds `USER@PCNAME: CURRENT_WORK_PATH` to the the tabs or window title of the terminal.

I have seen other GNU/Linux distributions to adopt that by defaul.

**Comment by yashpalgoyal1304** [comment]
@angelog0 it would be good if you "edit" the file here on github itself, it will automatically show you how to create PR

**Comment by Biswa96** [comment]
I wonder if that PS1 change is required to be set as default because users may have different choice. One can change the prompt text in their own .bashrc file.

**Comment by yashpalgoyal1304** [comment]
i don't know what the suggesstion is! (as no screenshot)

i saw that it's approved, and stale with a concrete scope of improvement, and i said about that!

i stumbled on this issue as i was having some issues with prompt myself - have forgotten where did i define my custom prompt, or even if i did it in the first place or not 😵😵 - lots of prompt files there...

oh yeah, i will share my suspected config files (2-5) in some time, then can u help me find their defaults in this repo?

**Comment by angelog0** [comment]
That was just a suggestion.. I solved this with a script in `/etc/profile.d`... 

If non has objections, I will close this in less than 24 hours.

**Comment by yashpalgoyal1304** [comment]
@angelog0 can you post a screenshot of the results? so that if it seems interested, someone else can pick??

**Comment by Biswa96** [comment]
You can copy-paste the `export PS1` command in running bash shell and execute it to see the result.
