### ISSUE TITLE
Building Python 3.8 for MinGW

### ISSUE THREAD

**Issue by falhumai96** [msys2/MSYS2-packages#1801]
Hello devs,

What patch set (and what version/release of the source code) you have used to build Python 3.8 for MinGW?

**Comment by Biswa96** [comment]
* For msys2, it's python 3.7.4: https://github.com/msys2/MSYS2-packages/blob/master/python3
* For mingw, it's python 3.8: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python3

**Comment by falhumai96** [comment]
Hello @Biswa96,

Can you give me the right link where you grabbed the Python 3.8 release for MinGW, because I don't want to download the wrong version as the patches might not be compatible with the wrong version downloaded.

**Comment by Biswa96** [comment]
See the pkgbuild file in mingw-w64-python3 as provided above. The package can be built with `makepkg -s` command which automatically download the tarball from python. The actual link may be this `https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tar.xz`.
