### ISSUE TITLE
Howto interact with msys2 filesytem layout ?

### ISSUE THREAD

**Issue by sancelot** [msys2/MSYS2-packages#1827]
Hi,
I don't understand how programs are interacting with filesystem layout withing msys2 .

using python, I was looking for files in /mingw64 directory , but failed :

```
import os
os.path.exists("/mingw64") # replies False

```
I tried 
```
import os
os.listdir("/") 

```

I noticed it was replying with the windows system dir, not the msys2 in can see using ls.

What is the workaround ?????

**Comment by lazka** [comment]
I guess you are using the mingw python, which works with Windows Paths. Under Windows `/mingw64` resolves to `C:\mingw64` and `/` resolves to `C:\`.

What are you trying to do?

**Comment by sancelot** [comment]
I have always similar problem. I want to build a mingw64 package.

Do I need to switch to msys2 shell for this task ? (I am in mingw64 one at the moment)

**Comment by lazka** [comment]
> I have always similar problem. I want to build a mingw64 package.
> 
> Do I need to switch to msys2 shell for this task ? (I am in mingw64 one at the moment).

mingw64 should work fine

> But if I do this, I will have problems finding needed compilers (python+c ext)........

what's the error?
