### ISSUE TITLE
Connection to MSYS2 does not work

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#1831]
Today the connection to the primary `pacman` repo does not work and so the connection to MSYS2 web site... do you confirm?

**Comment by mati865** [comment]
Works fine from Poland.

**Comment by angelog0** [comment]
Today I wired connected an Android tablet. After it returned to be wireless, there was this issue with MSYS2 sites on the other PCs (the PC with W10 Pro and GNU/Linux, the MBP and another tablet with W10 Home). Instead the Android tablet worked with MSYS2 sites!

So, I did a reset of the router and now all seems to work.
