### ISSUE TITLE
gsound

### ISSUE THREAD

**Issue by aadhilrf** [msys2/MSYS2-packages#1834]
I am trying to compile some Gnome Games in Msys2. Most depend on 'gsound' https://cygwin.com/packages/summary/gsound.html. Is this available in Msys2?

**Comment by StarWolf3000** [comment]
It requires libcanberra and several other dependencies, which are not available on MSYS2. Also you would probably use MINGW (the above mentioned applies here too, so cannot compiled yet) instead of MSYS2, if you want native running programs.

**Comment by lazka** [comment]
As per https://github.com/msys2/msys2/wiki/Creating-Packages#which-subsystem not something we would want in msys, so closing.
