### ISSUE TITLE
make is broken

### ISSUE THREAD

**Issue by omichel** [msys2/MSYS2-packages#1838]
After upgrading the `make` package our Makefile got broken.
This is because the following lines don't compute the same thing as before:
```
space :=
space +=
WEBOTS_HOME_PATH=$(subst $(space),\ ,$(strip $(subst \,/,$(WEBOTS_HOME))))
```
With the new version of `make` (4.3), a space is added at the end of the `WEBOTS_HOME_PATH` string. This was not the case with the previous version of `make` (4.2.1). Of course we can fix our Makefiles (see below), but I am wondering whether it's a bug in `make`. If so, I am not sure if the bug is in `make` 4.3 or is specific to the msys2 build.

I could fix the problem in my Makefile with:
```
null :=
space := $(null) $(null)
WEBOTS_HOME_PATH=$(subst $(space),\ ,$(strip $(subst \,/,$(WEBOTS_HOME))))
```

**Comment by omichel** [comment]
This may not be a bug after all...

**Comment by tanzislam** [comment]
[It's a feature, not a bug](https://lwn.net/Articles/810071/):

>* WARNING: Backward-incompatibility!
  Previously appending using '+=' to an empty variable would result in a value
  starting with a space.  Now the initial space is only added if the variable
  already contains some value.  Similarly, appending an empty string does not
  add a trailing space.
