### ISSUE TITLE
Is it possible to build static apps using msys2-devel group toolchain?

### ISSUE THREAD

**Issue by XhstormR** [msys2/MSYS2-packages#1842]
I use the msys2-devel group toolchain to develop programs that use the POSIX API. I want to compile a fully static program without any external libraries, but the compiled program always depends on the msys-2.0.dll dynamic link library.

I found that the [msys2-runtime-devel package](https://packages.msys2.org/package/msys2-runtime-devel) in the [msys2-devel group toolchain](https://packages.msys2.org/group/msys2-devel) has the libmsys-2.0.a static library, which contains the same functions required by the program as msys-2.0.dll dynamic link library.

So I want to explicitly specify that the libmsys-2.0.a library is statically linked, but it doesn't work. Is there a way to do this? Thank you.

```c
// 123.c
#include <stdio.h>

int main() {
  printf("%d\n", 123);
  return 0;
}
```

```
XhstormR@DESKTOP-U2UHBO6 MSYS /d/Download/2
$ gcc 123.c -s -static -lmsys-2.0

XhstormR@DESKTOP-U2UHBO6 MSYS /d/Download/2
$ ldd a.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffdb2ea0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffdb27e0000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffdaf360000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
```

**Comment by Alexpux** [comment]
@XhstormR you can’t build fully static program.

**Comment by StarWolf3000** [comment]
You can only build programs statically, that use native functionality of the underlying operating system and kernel technology. Which means, on Windows you cannot build fully static programs, that use POSIX functionality, as they require a compatibility layer (msys-2.0.dll for MSYS2 and cygwin1.dll for Cygwin).

All binaries and libraries within MSYS2 subsystem use POSIX functionality (even if they actually don't), so they're linked to msys-2.0.dll.

**Comment by XhstormR** [comment]
ok, I get it. So what is the libmsys-2.0.a static library used for, or how to use the libmsys-2.0.a static library?

**Comment by StarWolf3000** [comment]
> ok, I get it. So what is the libmsys-2.0.a static library used for, or how to use the libmsys-2.0.a static library?

If you link against it, your application will require `msys-2.0.dll` to be able to run properly. And you're also required to link against it, when using the MSYS2 subsystem.

Programs written with MINGW link directly to msvcrt, the Windows native runtime library.
