### ISSUE TITLE
scons: Support Python 3

### ISSUE THREAD

**Issue by pal1000** [msys2/MSYS2-packages#1849]
Mesa3D intends to drop Python 2 support with [this merge request](https://gitlab.freedesktop.org/mesa/mesa/merge_requests/3674) which will demolish Mesa3D build with Scons in MSYS2 due to [scons depending on Python 2](https://packages.msys2.org/package/scons?repo=msys&variant=x86_64). While it's true I migrated mingw-w64-mesa package to Meson, the migrated package is affected by [this problem](https://gitlab.freedesktop.org/mesa/mesa/issues/2012). While this is not a big deal when Mesa built with MSYS2 is used inside MSYS2, it becomes a problem when used outside.

**Comment by lazka** [comment]
Sounds good.

**Comment by lazka** [comment]
turns out this isn't that easy, things like nsis ship their own scons scripts that only work with Python 2.

**Comment by lazka** [comment]
done

**Comment by lazka** [comment]
new scons is now in the repo

**Comment by pal1000** [comment]
I know. I am testing Mesa build with it and it looks like there won't be problems.
