### ISSUE TITLE
Building MOAB in Msys2 (ERROR msys is not supported)

### ISSUE THREAD

**Issue by DaleKramer** [msys2/MSYS2-packages#1850]
I am trying to build MOAB ( https://bitbucket.org/fathomteam/moab/src/master/ ) in Msys2 but the ./configure command says msys is not supported.

kc@DESKTOP-3FIT2JC MSYS /usr/moab510
$ ./configure
configure: loading site script /etc/config.site
checking build system type... x86_64-pc-msys
checking host system type... x86_64-pc-msys
checking target system type... x86_64-pc-msys
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for sed... sed
configure: **_error: "OS msys is not supported"_**

Is there something that I am doing incorrectly?

Is there another way to build MOAB in Msys2?

**Comment by lazka** [comment]
Replace cygwin with msys in configure.ac and run `autoreconf -fi`. For everything else best ask the developers of MOAB.
