### ISSUE TITLE
wiki: bug fix on page 'MSYS2 reinstallation'

### ISSUE THREAD

**Issue by jannick0** [msys2/MSYS2-packages#1864]
Wiki page [MSYS2 reinstallation](https://github.com/msys2/msys2/wiki/MSYS2-reinstallation): In the code line
~~~
pacman -S --needed --force $(cat /c/packages.txt)
~~~
the option `--force` should be dropped, since `pacman` complains about it.

@lazka Would you be able again (akin the last time) to change this, since I could not find a repo to submit a PR to.  Many thanks.

**Comment by lazka** [comment]
done, thanks!
