### ISSUE TITLE
repo.msys2.org is not accessible

### ISSUE THREAD

**Issue by bogdanlytvynovskyi** [msys2/MSYS2-packages#1884]
Tried building FFMPEG using vcpkg, and failed due to error while downloading msys2 package:

Acquiring MSYS2...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz...
-- Downloading http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20181211.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

After that tried accessing downloads from msys2.org and got same issue with chrome on download links: http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe
ERR_CONNECTION_REFUSED

**Comment by Biswa96** [comment]
This error seems to be similar as mentioned in this https://github.com/msys2/MSYS2-packages/issues/1098 thread.

**Comment by bogdanlytvynovskyi** [comment]
That thread mentioned Asia a lot. My report is coming from USA, WA. Also I get refused connection right away rather than super slow speeds

**Comment by apockill** [comment]
I am also experiencing this issue for all of my packages

**Comment by Biswa96** [comment]
I have this issue too. There are some discussion in Gitter chat from maintainers. As a workaround, comment out the `repo.msys2.org` line in every mirrorlist files in `/etc/pacman.d` folder. Other mirrors work well in my case.

**Comment by bogdanlytvynovskyi** [comment]
That is not working when one needs to download base image of msys2

**Comment by theAltaran** [comment]
Its on sourceforge, where I just got my copy.

**Comment by Biswa96** [comment]
base images can also be downloaded from msys2-isntaller GitHub release page. Link https://github.com/msys2/msys2-installer/releases

**Comment by lazka** [comment]
We are trying to get in contact with the person sponsoring the server.

**Comment by lazka** [comment]
Work has started on restoring the server, but it might take a while.

**Comment by birgersp** [comment]
> I have this issue too. There are some discussion in Gitter chat from maintainers. As a workaround, comment out the `repo.msys2.org` line in every mirrorlist files in `/etc/pacman.d` folder. Other mirrors work well in my case.

For anyone doing this, I think it is important to restart the msys2 shell. I experimented with this but all I got was errors in the shell. Once I realised I had to close and restart the shell, it works like it should.

**Comment by b9AcE** [comment]
@lazka Any progress update?

**Comment by GarrisonJohnston123** [comment]
The server seems to be back up for me.

**Comment by b9AcE** [comment]
Yes, repo.msys2.org is up for me too now.
Thanks, server-admin! <3

**Comment by kr5ture** [comment]
Unfortunately I still cannot download installer from `repo.msys2.org` (link taken from http://msys2.org main page):
```
$ wget --connect-timeout 10 http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe
```
```
--2020-03-08 22:56:39--  http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe
Resolving repo.msys2.org (repo.msys2.org)... 45.59.69.178
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80... failed: Connection timed out.
Retrying.

--2020-03-08 22:56:50--  (try: 2)  http://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe
Connecting to repo.msys2.org (repo.msys2.org)|45.59.69.178|:80... failed: Connection timed out.
Retrying.
```

**Comment by b9AcE** [comment]
@kr5ture No, it went down again in the process of further fixing.
We're back to patience...

**Comment by b9AcE** [comment]
...and it's up again.
Should remain up at least for the immediate future, is my understanding.

**Comment by ylluminate** [comment]
After downloading the nightly from `https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-x86_64-latest.exe`, installing and executing `pacman -Syu` I'm still having failures such as:
```
# pacman -Syu
:: Synchronizing package databases...
error: failed retrieving file 'mingw32.db' from repo.msys2.org : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from sourceforge.net : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from www2.futureware.at : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from mirror.yandex.ru : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from mirrors.tuna.tsinghua.edu.cn : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from mirrors.ustc.edu.cn : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw32.db' from mirror.bit.edu.cn : Resolving timed out after 10000 milliseconds
error: failed to update mingw32 (download library error)
error: failed retrieving file 'mingw64.db' from repo.msys2.org : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw64.db' from sourceforge.net : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'mingw64.db' from www2.futureware.at : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'mingw64.db' from mirror.yandex.ru : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'mingw64.db' from mirrors.tuna.tsinghua.edu.cn : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'mingw64.db' from mirrors.ustc.edu.cn : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'mingw64.db' from mirror.bit.edu.cn : Resolving timed out after 10000 milliseconds
error: failed to update mingw64 (download library error)
error: failed retrieving file 'msys.db' from repo.msys2.org : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'msys.db' from sourceforge.net : Resolving timed out after 10001 milliseconds
error: failed retrieving file 'msys.db' from www2.futureware.at : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'msys.db' from mirror.yandex.ru : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'msys.db' from mirrors.tuna.tsinghua.edu.cn : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'msys.db' from mirrors.ustc.edu.cn : Resolving timed out after 10000 milliseconds
error: failed retrieving file 'msys.db' from mirror.bit.edu.cn : Resolving timed out after 10000 milliseconds
error: failed to update msys (download library error)
error: failed to synchronize all databases
```

**Comment by Delagen** [comment]
@ylluminate Check your DNS and internet connection

**Comment by lazka** [comment]
Maybe some proxy?

**Comment by ylluminate** [comment]
Hmmm... @Delagen I have even statically set DNS servers and flushed the DNS cache (`ipconfig /flushdns` as admin cmd.exe). Ping:
```
C:\Windows\System32>ping repo.msys2.org

Pinging diablo.msys2.org [45.59.69.178] with 32 bytes of data:
Reply from 45.59.69.178: bytes=32 time=82ms TTL=49
...
```

**Comment by Lewiscowles1986** [comment]
This has just happened again. Are there commands and documentation on running a mirror?

**Comment by BigslimVdub** [comment]
Looks like it is down again. Can't even download from https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20200903.exe

**Comment by Biswa96** [comment]
There is a recent reboot happen in that server and no answer from it. Installer can be downloaded from this release page https://github.com/msys2/msys2-installer/releases

**Comment by BigslimVdub** [comment]
> There is a recent reboot happen in that server and no answer from it. Installer can be downloaded from this release page https://github.com/msys2/msys2-installer/releases

Thanks! I was actually looking to update pacman and it was timing out so thought I'd just DL the latest. I will check in a while to see or maybe tomorrow. Are there mirrors available by any chance?

**Comment by jeremyd2019** [comment]
> Are there mirrors available by any chance?

https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors installed to /etc/pacman.d

**Comment by jamesseanwright** [comment]
> 
> 
> > Are there mirrors available by any chance?
> 
> https://github.com/msys2/MSYS2-packages/tree/master/pacman-mirrors installed to /etc/pacman.d

These mirrorlists match the default ones that came with my MSYS2 installation, and the SourceForge mirror is unsuitable as it has a relatively small maximum file download size. I was therefore able to strip these two entries from the respective lists with `cat` and `tail`:

```sh
$ cat /etc/pacman.d/mirrorlist.mingw32 | tail -n 6 > /etc/pacman.d/mirrorlist.mingw32
$ cat /etc/pacman.d/mirrorlist.mingw64 | tail -n 6 > /etc/pacman.d/mirrorlist.mingw64
$ cat /etc/pacman.d/mirrorlist.msys | tail -n 6 > /etc/pacman.d/mirrorlist.msys
```

The remaining mirrors work for me.

**Comment by Biswa96** [comment]
Doing that you will loose the mirror url. Just open those files in any text editor and put `#` before the mirror you want to comment it out.

**Comment by systemhalted** [comment]
Any idea when this is going to get fixed?

**Comment by Biswa96** [comment]
As far as I know know, there is no timeline. Comment out the msys2 and sourceforge mirrors and you are good to go. If you want to know the exact time of the fix, just do `ping repo.msys2.org` until you get response.

**Comment by krader1961** [comment]
@Biswa96, Note that updating the mirror list in the various `/etc/pacman.d/mirrorlist.m*` files won't work if you, like me, have a moderately old installation. In that case you'll see errors like the following rather than a simple timeout:

```
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
:: Import PGP key 4A6129F4E4B84AE46ED7F635628F528CF3053E04? [Y/n]
error: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" could not be looked up remotely
error: mingw64: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown
```

Something is seriously broken with respect to package signatures and mirrors.

**Comment by Biswa96** [comment]
In that case, you can download a stable installer from this release page https://github.com/msys2/msys2-installer/releases. Then install it in another location, install the packages and move configurations from old one. I have done it some times, jsut takes 1-2 minutes depending on network speed.

**Comment by Biswa96** [comment]
In that case, you can download a stable installer from this release page https://github.com/msys2/msys2-installer/releases. Then install it in another location, install the packages and move configurations from old one. I have done it some times, just takes 1-2 minutes depending on network speed.

**Comment by jeremyd2019** [comment]
I think you should have gotten those same errors against the primary, it looks like #2058/https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by jamesseanwright** [comment]
> Doing that you will loose the mirror url. Just open those files in any text editor and put `#` before the mirror you want to comment it out.

That's easier said than done when MSYS2 doesn't come with a text editor by default (unless I was looking in the wrong place)! 😉
