### ISSUE TITLE
using msys2 shell in jenkins

### ISSUE THREAD

**Issue by sancelot** [msys2/MSYS2-packages#1890]
I have got a mixed environment pipeline ,unfortuantely  I am not able to use msys2 shell

the shell is launched, but next commands are not executed in this shell

```
sh("""E:/msys2/msys2_shell.cmd -mingw64
                        echo running in msys-jenkins 
                        cmake -G"MSYS Makefiles" -DCMAKE_TOOLCHAIN_FILE=toolchain.mingw64.cmake -DCMAKE_BUILD_TYPE=Release   ..
	  		            make   all 
	  		            make install 
                        """)

```

**Comment by lazka** [comment]
You can't just pass your script as process arguments.

Write the script to a bash script and run `./msys2_shell.cmd myscript.sh`

For more infor look here: https://github.com/msys2/msys2/wiki/Launchers

**Comment by Tectu** [comment]
For anyone coming across this in the future: There's a much easier way which simply requires running the Jenkins build agent directly within MSYS2. All commands will then be ran inside the MSYS2 environment.

I've created a blog post detailing this process: https://silizium.io/post/jenkins_msys2/

**Comment by lazka** [comment]
thanks, https://www.msys2.org/docs/ci/#other-systems might also be useful
