### ISSUE TITLE
How to mirror msys2?

### ISSUE THREAD

**Issue by carrotIndustries** [msys2/MSYS2-packages#1898]
As I couldn't find any rsync servers for the msys2 repo, I tried mirroring from http://repo.msys2.org with `wget -m`, but this turned out to be far from optimal as a almost-do-nothing run takes 3 hours.

If there's a better way (rsync preferred) to mirror msys2, I could arrange mirroring at http://mirror.selfnet.de/ (arch linux tier 1: https://www.archlinux.org/mirrors/selfnet.de/ and IPv6 enabled) We could provide public rsync as well.

Looking at the current mirrorlist, this project could really benefit from another mirror in central europe.

**Comment by Alexpux** [comment]
@carrotIndustries repo.msys2.org allow mirroring via rsync

**Comment by lazka** [comment]
From what I see `rsync://repo.msys2.org/builds` works. We should create a wiki page re mirrors.

**Comment by lazka** [comment]
I've create a basic wiki page: https://github.com/msys2/msys2/wiki/Mirrors

@carrotIndustries is there any information missing on that page?

**Comment by carrotIndustries** [comment]
Thanks, that all I needed to set up the mirror. We now have a new mirror at http://mirror.selfnet.de/msys2/ that mirrors once a day from repo.msys2.org. rsync is available at `rsync://mirror.selfnet.de/msys2`

**Comment by lazka** [comment]
cool, thanks
