### ISSUE TITLE
msys2 distrib tgz package format

### ISSUE THREAD

**Issue by Fabien-Chouteau** [msys2/MSYS2-packages#1901]
(I am not sure if this is the right place to open this issue, excuse me if it's not)

I plan to have a tool that installs msys2 automatically, so I was looking at the archives in `http://repo.msys2.org/distrib/`.

Unfortunately the only archive format is XZ which requires an external tool to be extracted.
Which means I cannot automate the installation on a bare Windows system.

Is it possible to produce other format of archives for the distrib so that they can be extracted on a bare Windows system?

**Comment by hiroakit** [comment]
For example, what format do you expect?

**Comment by Biswa96** [comment]
As you are installing msys2 which is also an "external tool", why not install another "external tool" tool to extract it? The compression ratio is bigger in XZ compression compared to bare Windows supported ones e.g. zip, cab etc.

**Comment by Biswa96** [comment]
As you are installing msys2 which is also an "external tool", why not install another "external tool" tool to extract it? The compression ratio is bigger in XZ compression compared to bare Windows supported ones e.g. zip, cab etc.

**Comment by Biswa96** [comment]
As you are installing msys2 which is also an "external tool", why not install another "external tool" tool to extract it?

**Comment by Biswa96** [comment]
As you are installing msys2 which is also an "external tool", why not install another "external tool" to extract it?

**Comment by Fabien-Chouteau** [comment]
> For example, what format do you expect?

tgz is natively supported by the tar shipped in Windows.

**Comment by Fabien-Chouteau** [comment]
> As you are installing msys2 which is also an "external tool", why not install another "external tool" to extract it?

That's an option, I would like to avoid it because it doubles the complexity, doubles the dependencies.

I am asking this because I imagined that the release process is automated and adding a new archive format is not too complicated. I am willing to contribute the change of course. If it is complicated to do then you can ignore my request.

Another solution for me would be to be able to use the installer, but I didn't manager to get it to install without user input. I can give it another shot.

Thanks for your answers.

**Comment by Fabien-Chouteau** [comment]
I switched to using the installer. See https://github.com/msys2/msys2-installer/pull/2.

Feel free to close the issue.

**Comment by hiroakit** [comment]
@Alexpux @lazka 

Would you close this issue?
