### ISSUE TITLE
[BUG] Python update to 3.8.2 broke gdb

### ISSUE THREAD

**Issue by petrochenkov** [msys2/MSYS2-packages#1926]
## Describe the bug

GDB wants a library named `msys-python3.7m.dll` which is no longer there after the Python update.

## Steps to Reproduce the Problem

Run
```sh
$ gdb --version
C:/msys64/usr/bin/gdb.exe: error while loading shared libraries: msys-python3.7m.dll: cannot open shared object file: No such file or directory
```

Expected behavior: the GDB version is printed.

**Comment by Alexpux** [comment]
Fixed by https://github.com/msys2/MSYS2-packages/commit/fb12aa852304a9f1dd5fcafe905932ac9f44278a

**Comment by petrochenkov** [comment]
Confirmed.
Thanks!
