### ISSUE TITLE
[scons] Multiple issues when using scons 3.1.2-3

### ISSUE THREAD

**Issue by gbaudic** [msys2/MSYS2-packages#1928]
I have been using Scons for a while on one of my projects, but the latest version (3.1.2-3, fetched from the msys2 repo with pacman) no longer works. 3.1.2-2 worked just fine, so I assume this is a MSYS2 packaging issue, maybe due to the transition to Python 3.8 -- please correct me if not. 
More precisely, on a MINGW64 shell, this now happens:

``` 
$ scons  
SCons import failed. Unable to find engine files in:
  C:/msys64/mingw64/scons-3.1.2
  C:/msys64/mingw64/scons
Traceback (most recent call last):
  File "C:/msys64/usr/bin/scons", line 195, in <module>
    import SCons.Script
ModuleNotFoundError: No module named 'SCons'
```
The same command works much better under a MSYS shell.

After some digging, it seems that the paths where scons is being looked for include `/mingw64/lib/python3.8/site-packages` but not `/usr/lib/python3.8/site-packages` where the files are actually installed. As a workaround, I tried to use `PYTHONPATH=$PYTHONPATH:/usr/lib/python3.8/site-packages`, which solved the issue above, but things kept going downhill from here. 

Here is the (working) build output I have been used to seeing with scons <= 3.1.2-2:
```
scons: Reading SConscript files ...
Checking for pkg-config... yes
Checking for gl... no
Checking for sdl2... yes
Checking for SDL2_image... yes
Checking for SDL2_ttf... yes
=========================================
 Guisan build
 SDL 2.0 support.............. 1
 OpenGL support............... 0
-----------------------------------------
 Installation target
 Prefix....................... /mingw64
 Includes..................... /mingw64/include
 Libraries.................... /mingw64/lib
=========================================
scons: done reading SConscript files.
scons: Building targets ...
g++ -o examples/sdl2widgets.o -c -pipe -g -Dmain=SDL_main -Iinclude -I/mingw64/include/SDL2 examples/sdl2widgets.cpp
...
(following lines omitted for brevity)
```

With 3.1.2-3, this becomes:
```
scons: Reading SConscript files ...
Checking for pkg-config... yes
Checking for gl... no
Checking for sdl2... yes
Checking for SDL2_image... yes
Checking for SDL2_ttf... yes
=========================================
 Guisan build

 SDL 2.0 support.............. 1
 OpenGL support............... 0
-----------------------------------------
 Installation target

 Prefix....................... C:/msys64/mingw64
 Includes..................... C:/msys64/mingw64/include
 Libraries.................... C:/msys64/mingw64/lib

=========================================
scons: done reading SConscript files.
scons: Building targets ...
cl /Foexamples/sdl2widgets.obj /c examples/sdl2widgets.cpp /TP /nologo -pipe -g /Dmain=SDL_main /Iinclude /IC:/mingw64/include/SDL2
cl : Command line warning D9002 : ignoring unknown option '-pipe'
cl : Command line warning D9002 : ignoring unknown option '-g'
sdl2widgets.cpp
include\guisan/sdl/sdlgraphics.hpp(60): fatal error C1083: Cannot open include file: 'SDL.h': No such file or directory
scons: *** [examples/sdl2widgets.obj] Error 2
scons: building terminated because of errors.
```

There are multiple issues here. 
* The target paths have been expanded to their actual Windows path on my system.
* The compilation command line uses the MSVC compiler instead of gcc/g++, despite no change in my code or in the command being used to launch Scons. 
* The include path for SDL2, correctly returned as `/mingw64/include/SDL2` by pkg-config, has somehow been turned into `C:/mingw64/include/SDL2`, which does not exist (correct location would be `C:/msys64/mingw64/include/SDL2`). 

Any ideas on this ? Thanks. 

If this can help, the project in question is https://github.com/gbaudic/guisan and the actual compilation line used to launch scons can be seen in the `appveyor.yml` file or in the CI results.

**Comment by Alexpux** [comment]
@gbaudic look into /usr/bin/scons script. What she bang it have? If something like /usr/vin/env python then try 
export PYTHON=/usr/bin/python 
Before scons call

**Comment by gbaudic** [comment]
The shebang is `/usr/bin/env python`, but setting the PYTHON environment variable as you suggest does not fix the error.

**Comment by Alexpux** [comment]
@gbaudic are you sure you call python scons script and not scons.bat

**Comment by gbaudic** [comment]
Yes. 
```
$ which scons
/usr/bin/scons
$ scons
SCons import failed. Unable to find engine files in:
  C:/msys64/mingw64/scons-3.1.2
  C:/msys64/mingw64/scons
Traceback (most recent call last):
  File "C:/msys64/usr/bin/scons", line 195, in <module>
    import SCons.Script
ModuleNotFoundError: No module named 'SCons'
$ /usr/bin/scons
SCons import failed. Unable to find engine files in:
  C:/msys64/mingw64/scons-3.1.2
  C:/msys64/mingw64/scons
Traceback (most recent call last):
  File "C:/msys64/usr/bin/scons", line 195, in <module>
    import SCons.Script
ModuleNotFoundError: No module named 'SCons'
$ /usr/bin/scons.bat
scons: *** No SConstruct file found.
File "/usr/lib/python3.8/site-packages/SCons/Script/Main.py", line 940, in _main
```

**Comment by Alexpux** [comment]
@gbaudic try update packages

**Comment by gbaudic** [comment]
I can no longer reproduce this error with scons 2.1.3-4. Thank you!
