### ISSUE TITLE
[BUG] znc does not start

### ISSUE THREAD

**Issue by 1480c1** [msys2/MSYS2-packages#1931]
## Describe the bug

`msys/znc-git r5083.65bce1c5-1` does not start when trying to run `znc.exe`

Running from mintty prints
```none
D:/msys64/usr/bin/znc.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
```
Running from PowerShell prints nothing

Double-clicking znc.exe prints
```none
The code execution cannot proceed because msys-icuuc64.dll was not found. Reinstalling the program may fix this problem,
```

Already ran pacman to update, but nothing changed.

I have these icu packages installed
```none
mingw64/mingw-w64-x86_64-icu 65.1-1
mingw64/mingw-w64-x86_64-icu-debug-libs 65.1-1
msys/icu 65.1-1
````

I will try to see if compiling znc-git will help when I have time

## Steps to Reproduce the Problem

1. pacman -S znc-git
2. znc --help

Alternatively
1. Open to the usr/bin folder from explorer
2. double-click znc.exe

Expected behavior: Something other than an error

## Additional Context: Operating System, Screenshots

![image](https://user-images.githubusercontent.com/8345542/80444411-55f9c580-88d7-11ea-84c1-e01f06f3d67f.png)

- OS: Windows 10 Pro version 1909 64 bit
- OS Build: 18363.778

**Comment by StarWolf3000** [comment]
It needs to be rebuilt with current `icu-devel` and also requires a dependency on `icu` (why it isn't listed at all is beyond me).

#1932
