### ISSUE TITLE
Invalid configuration `x86_64-pc-msys'

### ISSUE THREAD

**Issue by IdrisKalp** [msys2/MSYS2-packages#1933]
When I try to build a program with MSYS2, I'm getting this error. 

```
./configure --prefix=/usr
configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for library containing strerror... none required
checking build system type... Invalid configuration `x86_64-pc-msys': system `msys' not recognized
configure: error: /bin/sh ./config.sub x86_64-pc-msys failed
```
Where do I do wrong?

**Comment by Biswa96** [comment]
Then the project may not support msys2 building environment. You can edit the automake/autoconf file to add msys2 support. See this repository and you'll find `msysize.patch` file which will help you. Also try to build in mingw environment.

**Comment by IdrisKalp** [comment]
The program I'm trying to build cannot be build with Mingw. I'm using MSYS2 for first time.

**Comment by Biswa96** [comment]
As said previously, the autoconf/automake build files may need some changes to support msys2 platform. See this patch file as an example https://github.com/msys2/MSYS2-packages/blob/master/file/file-5.38-msys2.patch

**Comment by acmacneil** [comment]
I am getting the same error on initial use of MSYS2 trying to install COIN-OR

https://www.coin-or.org/svn/CoinBinary/OptimizationSuite/stable/1.8/README.md

` 
   cd COIN-1.8
   ./get.AllThirdParty
   mkdir build
   cd build
   ../configure --with-gmpl --enable-gnu-packages
   make install
`

**Comment by Kreijstal** [comment]
> As said previously, the autoconf/automake build files may need some changes to support msys2 platform. See this patch file as an example https://github.com/msys2/MSYS2-packages/blob/master/file/file-5.38-msys2.patch

can you add a permalink for that patch, it 404s now

**Comment by Biswa96** [comment]
This is an old issue and OP did not provide any step to reproduce it. The msysize.patch is not required anymore. The configure script can be run as following.

```
  local CYGWIN_CHOST="${CHOST/-msys/-cygwin}"
  ./configure \
    --prefix=/usr \
    --build=${CYGWIN_CHOST} \
    --host=${CYGWIN_CHOST} \
    --target=${CYGWIN_CHOST}
```

See https://github.com/msys2/MSYS2-packages/blob/master/file/PKGBUILD
