### ISSUE TITLE
gnome-doc-utils: depends on removed Python 2 support for libxml2

### ISSUE THREAD

**Issue by revelator** [msys2/MSYS2-packages#1935]
Some packages like gnome-doc-utils still need it, we can skip the numpy dependency without any problems as far as i have been able to determine (atleast for gnome-doc-utils).
fedora has released a patch updating gnome-doc-utils for python3 support, unfortunatly it seems its not working correctly on windows (utf8 error).

**Comment by revelator** [comment]
heres the error im getting, interrested if you get the same.

`Traceback (most recent call last):
  File "F:/mingw-w64-gnome-doc-utils/src/build-x86_64-w64-mingw32/doc/xslt/../../xml2po/xml2po/xml2po", line 191, in <module>
    main(sys.argv[1:])
  File "F:/mingw-w64-gnome-doc-utils/src/build-x86_64-w64-mingw32/doc/xslt/../../xml2po/xml2po/xml2po", line 174, in main
    xml2po_main.merge(mofile, filenames[0])
  File "F:/mingw-w64-gnome-doc-utils/src/gnome-doc-utils-0.20.10/xml2po/xml2po/__init__.py", line 611, in merge
    self.out.write(doc.doc.serialize('utf-8', 1))
  File "C:/Msys64/mingw64/lib/python3.8/encodings/cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 3643-3648: character maps to <undefined>`

**Comment by revelator** [comment]
From what i can glean it seems related to windows command processor not treating utf-8 well.

**Comment by revelator** [comment]
and finally found a fix...

export PYTHONIOENCODING=UTF-8 <- put this in the pkgbuild script just before  PYTHON=${MINGW_PREFIX}/bin/python3

and it builds and works with python3

**Comment by revelator** [comment]
Can close this issue now if you like i just built the few dependent packages with the patched version and my fix and all works well.

**Comment by lazka** [comment]
> and finally found a fix...
> 
> export PYTHONIOENCODING=UTF-8 <- put this in the pkgbuild script just before PYTHON=${MINGW_PREFIX}/bin/python3
> 
> and it builds and works with python3 after using the fedora patch.

Yeah, that's the usual porting bug for code assuming a utf-8 locale on Linux.

> Can close this issue now if you like i just built the few dependent packages with the patched version and my fix and all works well.

I'll create a PR, since the fix seems easy enough.

**Comment by lazka** [comment]
uh, there are lots of cases not ported actually

**Comment by lazka** [comment]
See #1938

**Comment by revelator** [comment]
good catch :+1:  i had a feeling there might be more places needing attention in the original patch.

**Comment by lazka** [comment]
gnome-doc-utils in the repo is using Python 3 now. If there are any more problems please open a separate issue for that. Thanks!
