### ISSUE TITLE
[BUG] coreutils: mkfifo hangs when file permissions are supplied

### ISSUE THREAD

**Issue by sio** [msys2/MSYS2-packages#1936]
## Describe the bug

Updating coreutils from 8.31 to 8.32 causes `mkfifo` to fail with arguments that worked before. [Upstream mkfifo code](https://github.com/coreutils/coreutils/commits/master/src/mkfifo.c) has not changed since 2016, so the issue may be with how it's built here.

Named pipe creation with `mkfifo` hangs indefinitely if `-m` value is provided to specify file permissions. Writing into the named pipe at that moment triggers hanged mkfifo to error out:

```
mkfifo: cannot set permissions of 'helloworld': Invalid argument
Exit code: 1
```

Running mkfifo without `-m` argument succeeds. I've tried to understand the reasons by reading straces, but that's above my level. Here they are:

- Success: [`mkfifo helloworld`][log-success.txt]
- Failure: [`mkfifo -m 600 helloworld`][log-failure.txt]

The differences start around line 500 in failure log.

Line 540 `fhandler_pipe::create: pipe write handle NULL` is where it hangs until someone tries to write into named pipe.

Failure happens probably here, but I can not decipher it. Lines 540-547

```
  103   34722 [main] mkfifo 2287 fhandler_pipe::create: pipe write handle NULL
5810129 5844851 [main] mkfifo 2287 fhandler_fifo::open: res 0
  135 5844986 [main] mkfifo 2287 open: 3 = open(helloworld, 0x2148000)
  104 5845090 [main] mkfifo 2287 __set_errno: int fstatat(int, const char*, stat*, int):4808 setting errno 22
   74 5845164 [main] mkfifo 2287 close: close(3)
   93 5845257 [main] mkfifo 2287 fhandler_base::close: closing '/helloworld' handle 0x1CC
   96 5845353 [main] mkfifo 2287 close: 0 = close(3)
 1048 5846401 [main] mkfifo 2287 open: open(/usr/share/locale/locale.alias, 0x0)
```

[log-failure.txt]: https://github.com/git-for-windows/git/files/4550824/log-failure.txt
[log-success.txt]: https://github.com/git-for-windows/git/files/4550825/log-success.txt

```
$ mkfifo --version
mkfifo (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

## Steps to Reproduce the Problem

1. Run `mkfifo -m 600 helloworld`
2. mkfifo hangs
3. Run `echo abcde > helloworld` from another terminal
4. mkfifo errors out (exit code 1):
    `mkfifo: cannot set permissions of 'helloworld': Invalid argument`

**Expected behavior**: At step 2 mkfifo should return immediately after creating the named pipe. Exit code should be 0. Step 3 should not cause any errors.

## Additional Context: 

- OS: Microsoft Windows 10 64-bit [Version 10.0.18362.30], Russian version
- Cyrillic letters appear in Windows user name, but not in path to test directory
- First encountered in Git for Windows ([issue #2605](https://github.com/git-for-windows/git/issues/2605)), confirmed with MSYS2 clean install from 20200426 nightly

**Comment by lazka** [comment]
Can you try again, there were lots of fifo changes in cygwin in the last few weeks.

**Comment by sio** [comment]
I've just tried [2020-06-02 nightly](https://github.com/msys2/msys2-installer/releases/tag/2020-06-02) - the problem appears to be fixed. Thank you.

I've caught a segfault the first time I've tried reading from fifo, but I can not reproduce it again. Must be some random cosmic rays thing :)

**Comment by lazka** [comment]
Thanks for testing.
