### ISSUE TITLE
MSYS2 installation error

### ISSUE THREAD

**Issue by lorenzznerol** [msys2/MSYS2-packages#1949]
Installation error with MSYS2 at about 70 % of the installation. After error, the installation is built back.

error message:  
#####
Fehler
Konnte Daten des Verwaltungswerkzeugs nicht nach C:\Users\Admin\AppData\Local\Temp\mysis2-x86_64-20190524.yxiPTr schreiben: Unbekannter Fehler
#####
auto-translated to English (this is probably not the exact error message):
error
Could not write administration tool data to C:\Users\Admin\AppData\Local\Temp\mysis2-x86_64-20190524.yxiPTr: Unknown error

The installation file is called msys2-x86_64-20190524.exe.
It is a download from msys2.org, picture of the error is attached.
I need it for MinGW which is already installed in order to run a makefile in C.

This issue has been raised before and was not solved then:
https://github.com/msys2/MSYS2-packages/issues/1821

My disk is NTFS formatted
Windows 10 Home version 1903 64bit
<img width="503" alt="installation error" src="https://user-images.githubusercontent.com/52793248/81921323-baf13300-95da-11ea-94c2-c1fa857c0d3c.png">

**Comment by lazka** [comment]
Can you test if the nightly installer works: https://github.com/msys2/msys2-installer/releases/download/nightly-x86_64/msys2-x86_64-20200510.exe ?

**Comment by lorenzznerol** [comment]
Yes, this has worked, thank you for the quick help. The download is unsigned and Windows Defender threw a lot of warnings that this is not a trusted source. Of course I trusted you ;)

**Comment by lazka** [comment]
Thanks for testing!

**Comment by lazka** [comment]
This will be fixed once we release a new installer. I'm closing this in favor of #1948.
