### ISSUE TITLE
MSYS2 broken after run-time update

### ISSUE THREAD

**Issue by omichel** [msys2/MSYS2-packages#1961]
After running `pacman -Syuu` a few minutes ago, I got an update that required to close the MSYS2 console. I closed it and try to re-open a MSYS2 console, with it fails and is unable to open.
How can I fix this?

**Comment by omichel** [comment]
I am getting this error when trying to start it from a DOS console:
```CMD
C:\Users\Olivier>D:\msys64\usr\bin\bash.exe
      0 [main] bash (13784) shared_info::initialize: size of shared memory region changed from 51128 to 40888
```

**Comment by omichel** [comment]
Rebooting my computer fixed the problem (still, it may be good to know).

**Comment by Optiligence** [comment]
needed to reboot too
i would leave this issue open, because even if required the help text should be updated in that regard
not sure if it’s also possible to do something other than rebooting

**Comment by k-takata** [comment]
Maybe, some processes that use old runtime were alive. Killing such processes will fix the issue. If you are not sure which process to kill, rebooting would be the easiest way.

**Comment by Optiligence** [comment]
for this update it’s sadly not a »maybe« anymore tho
