### ISSUE TITLE
[BUG] bash.exe crashed after upgrading msys2-runtime to version 3.1.4-1

### ISSUE THREAD

**Issue by xq114** [msys2/MSYS2-packages#1966]
## Describe the bug

After upgrading msys2-runtime with pacman, bash.exe crashed with this message:

```
      0 [main] bash (5852) shared_info::initialize: size of shared memory region changed from 51128 to 40888
```

## Steps to Reproduce the Problem

1. Download msys2-x86_64-20200517.exe and install
2. run `pacman -Syu`, select Yes
3. close window to perform the core system update
4. open bash.exe in cmd(any other program just crashed without a message)

Expected behavior: msys2 works without a crash.

## Additional Context: Operating System, Screenshots

- OS: [Windows 10 Pro version 1909 64bit]
- CPU: Intel core i5 6200U

Screenshots:
![image](https://user-images.githubusercontent.com/42310255/82349299-83481800-9a2c-11ea-8684-94f07eea6223.png)

**Comment by 0xb8** [comment]
Kill all running MSYS2 processes and try again, this worked for me.

**Comment by xq114** [comment]
> Kill all running MSYS2 processes and try again, this worked for me.

That works. Thanks a lot!

**Comment by csdvrx** [comment]
Note to those experiencing the same problem even after closing msys2: dirmnger and gpg-agent may be running in the background.

Close them with the task manager, or reboot.

**Comment by MooglyGuy** [comment]
So, the fact that the "fix" requires the user to Google for this issue, find this particular issue filing, and follow the instructions given is considered acceptable, and not a reason to actually investigate why gpg-agent.exe and other MSYS2-provided executables don't properly terminate when the user closes the terminal window? That's amazing. No, seriously, I'm impressed by the downright level of user antipathy exhibited by the fact that this issue was closed with this so-called "fix".

**Comment by 1480c1** [comment]
not much anyone can do here since that's just how nix programs on windows sort of work when they need to go through something like cygwin and need to daemonize themselves to run in the background, I believe it's now handled through pacman whenever upgrading, but only with newer pacmans I think

**Comment by MooglyGuy** [comment]
That's actually a decent explanation. Thank you for taking the time to give it.

If it's not an issue with newer pacman distributions, then I completely understand that the issue must be worked around by those of us who are upgrading from relatively old distributions (if you consider 9 months "old").

I was simply baffled that it seemed like the devs were acknowledging the issue while also closing out the issue without stating that there had also been work done to rectify it on the project's end. Thank you again for the clarification.

**Comment by l-l-l-l-l-l** [comment]
Same issue, this time with pacman.exe.
