### ISSUE TITLE
[BUG] msys2-runtime-3.1.4-2 causes immediate crash

### ISSUE THREAD

**Issue by AstralStorm** [msys2/MSYS2-packages#1972]
## Describe the bug

After upgrading msys2-runtime, MSYS2 no longer starts. Force downgrading by manually extracting old runtime 3.0.7-6 makes it launch fine again.

## Steps to Reproduce the Problem

1. pacman -Syuu or pacman -S bash pacman pacman-mirrors msys2-runtime
2. restart MSYS2 shell as ordered.
3. Note shell no longer starts.

## Additional Context: Operating System, Screenshots

Windows 10 2004 build 19631.1

**Comment by mati865** [comment]
Duplicate of https://github.com/msys2/MSYS2-packages/issues/1966

**Comment by AstralStorm** [comment]
Indeed, somehow search missed that one.
