### ISSUE TITLE
[BUG]pacman -Syuu is totally broken on my system.

### ISSUE THREAD

**Issue by dcorbit** [msys2/MSYS2-packages#1973]
## Describe the bug
After execution of pacman -Syuu I can no longer run msys2

## Steps to Reproduce the Problem
run the 64 bit msys2 shell and execute pacman -Syuu.  You will see this:

You will see this:
# pacman -Syuu
:: Synchronizing package databases...
 mingw32                                                                    462.4 KiB  56.4 MiB/s 00:00 [############################################################] 100%
 mingw32.sig                                                                119.0   B  0.00   B/s 00:00 [############################################################] 100%
 mingw64                                                                    465.0 KiB  56.8 MiB/s 00:00 [############################################################] 100%
 mingw64.sig                                                                119.0   B  0.00   B/s 00:00 [############################################################] 100%
 msys                                                                       183.3 KiB  59.7 MiB/s 00:00 [############################################################] 100%
 msys.sig                                                                   119.0   B  0.00   B/s 00:00 [############################################################] 100%
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (3) mintty-1~3.1.6-1  msys2-runtime-3.1.4-3  pacman-5.2.1-8

Total Download Size:   16.79 MiB
Total Installed Size:  52.89 MiB
Net Upgrade Size:       1.15 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 msys2-runtime-3.1.4-3-x86_64                                                 2.7 MiB  78.7 MiB/s 00:00 [############################################################] 100%
 mintty-1~3.1.6-1-x86_64                                                    678.5 KiB  73.6 MiB/s 00:00 [############################################################] 100%
 pacman-5.2.1-8-x86_64                                                       13.4 MiB  2.84 MiB/s 00:05 [############################################################] 100%
(3/3) checking keys in keyring                                                                          [############################################################] 100%
(3/3) checking package integrity                                                                        [############################################################] 100%
(3/3) loading package files                                                                             [############################################################] 100%
(3/3) checking for file conflicts                                                                       [############################################################] 100%
(3/3) checking available disk space                                                                     [############################################################] 100%
:: Processing package changes...
(1/3) upgrading msys2-runtime                                                                           [############################################################] 100%
(2/3) upgrading mintty                                                                                  [############################################################] 100%
(3/3) upgrading pacman                                                                                  [############################################################] 100%
warning: terminate MSYS2 without returning to shell and check for updates again
warning: for example close your terminal window instead of calling exit

After you follow the instructions and kill the shell, when you restart you will get the Mingw-w64 Win64 Shell, but no bash window.  If you try to execute any command from the Mingw-w64 Win64 Shell window, you will get the same error for any command:
c:\msys64>bash
      0 [main] bash (18932) shared_info::initialize: size of shared memory region changed from 51128 to 40888

c:\msys64>
but nothing visible appears

Expected behavior:
Normal upgrade of out of date applications, bash shell still works.  The only way out of the hole this thing digs is to completely uninstall MSYS2 and reinstall.  Then add missing components one at a time, but do NOT run pacman -Syuu because it will crush the system again.

## Additional Context: Operating System, Screenshots
- OS: Windows Server 2012 R2

**Comment by mati865** [comment]
Duplicate of https://github.com/msys2/MSYS2-packages/issues/1966
