### ISSUE TITLE
[BUG] msys2 terminal no longer starts after updating

### ISSUE THREAD

**Issue by szhorvat** [msys2/MSYS2-packages#1978]
## Describe the bug

msys2 terminal fails to start after update.

## Steps to Reproduce the Problem

I updated packages using `pacman -Syuu`. As is common with certain updates, it asked to close the terminal before proceeding. I did.

After this, running msys2.exe pops up a command window for a split second, but mintty does not start. There is no error message displayed.

## Additional Context: Operating System, Screenshots

OS is Windows 7.

After this happened on one computer, I tried on a second one. The very same thing happened: after updating, the msys2 terminal no longer starts up.

**Comment by elieux** [comment]
See [FAQ](https://www.msys2.org/wiki/FAQ/) entry no. 6.  Essentially kill all MSYS2 processes or just relog/reboot.

**Comment by szhorvat** [comment]
Thanks, a reboot worked. This has never happened to me before, so I was confused.
