### ISSUE TITLE
Missing packge with standard library function?

### ISSUE THREAD

**Issue by laheller** [msys2/MSYS2-packages#1980]
Hi!

What package I am missing in **msys2** when the **ld** command (via make) reports following error:
``
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: libpm.o:libpm.c:(.text+0x8b8): undefined reference to `setmode'
``

**Comment by Biswa96** [comment]
There may be some library linking option is missing i.e. `-l` (small L).

**Comment by laheller** [comment]
> There may be some library linking option is missing i.e. `-l` (small L).

OK, but which one :-)

BTW I am trying to build [netpbm](https://github.com/t6/netpbm) library on **msys2**.

**Comment by laheller** [comment]
@Biswa96 
OK, I fixed it by specifying some CFLAGS and LDFLAGS in library's config.mk file.
Thanks for the hint which lead me to the solution!

**Comment by Biswa96** [comment]
Eager to know the changes.

**Comment by laheller** [comment]
> Eager to know the changes.

```
CFLAGS = -I/usr/include -I/mingw64/include -Dsetmode=_setmode -D_vsnprintf=vsnprintf -D_strdup=strdup 

LDFLAGS += -L/usr/lib -L/mingw64/lib 

```

**Comment by StarWolf3000** [comment]
> > Eager to know the changes.
> 
> ```
> CFLAGS = -I/usr/include -I/mingw64/include -Dsetmode=_setmode -D_vsnprintf=vsnprintf -D_strdup=strdup 
> 
> LDFLAGS += -L/usr/lib -L/mingw64/lib 
> ```

Never do that, when working with msys2 and ming-w64!

**Comment by elieux** [comment]
We discussed this on Gitter and OP went on to try with full-fledged Cygwin.
