### ISSUE TITLE
binutils 2.34 PR24511 PR25447

### ISSUE THREAD

**Issue by bll123** [msys2/MSYS2-packages#1989]
binutils has a couple of serious bugs that have been fixed upstream.
These bugs are causing problems for 32-bit linking with shared libraries.

Is there any way to get a patched version of binutils pushed?

https://sourceware.org/bugzilla/show_bug.cgi?id=24511
https://sourceware.org/bugzilla/show_bug.cgi?id=25447

https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=40bfb9762747f8336b17c70a0173d10200fa62eb
https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=82f439d028c65663a0baf0a17ef5c4a2ea5c84a7

**Comment by Alexpux** [comment]
@bll123 create pull request with backported patches

**Comment by lazka** [comment]
This got fixed in bfc9d3bcb82d17bfb
