### ISSUE TITLE
Make new Base package more visible

### ISSUE THREAD

**Issue by nu8** [msys2/MSYS2-packages#1990]
On the repo site, these Base packages are available:

- <http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20190524.tar.xz>
- <http://repo.msys2.org/msys/x86_64/base-20200530-1-any.pkg.tar.zst>

However the Zst file is perhaps not useful, as most users wont have ability to
extract Zst before installing MSYS2 for the first time. And the XZ file is
perhaps not useful, as it doesnt include Zst extractor, and many packages are
now Zst. I found this as well:

<https://github.com/msys2/msys2-installer/releases>

It might be helpful if `msys2-base-x86_64-20200522.tar.xz` and similar were
moved or copied to <http://repo.msys2.org>, as I suspect people assume it to be
there.

**Comment by mati865** [comment]
> http://repo.msys2.org/msys/x86_64/base-20200530-1-any.pkg.tar.zst

This is empty Pacman metapackage (hence it's 0.02 MiB size), installing it will download other dependencies that are considered as minimum.

**Comment by eine** [comment]
It seems that latest tarballs are now available at http://repo.msys2.org/distrib. I guess this issue can be closed...
