### ISSUE TITLE
[BUG]missing _mm_cvtsi128_si64

### ISSUE THREAD

**Issue by dangyajun** [msys2/MSYS2-packages#2005]
## Describe the bug

missing _mm_cvtsi128_si64

## Steps to Reproduce the Problem
CODE:
inline int popcnt128(__m128i n) {
    const __m128i n_hi = _mm_unpackhi_epi64(n, n);

    return __popcnt64(_mm_cvtsi128_si64(n)) + __popcnt64(_mm_cvtsi128_si64(n_hi));
  }
COMPILING:
clang -msse2 -mavx -c -Wall test.c

ERROR:
use of undeclared identifier '_mm_cvtsi128_si64'
    return __popcnt64(_mm_cvtsi128_si64(n)) + __popcnt64(_mm_cvtsi128_si64(n_hi));

Expected behavior: 
     Function "_mm_cvtsi128_si64" should be included in "emmintrin.h", but it is truely missing.

**Comment by mati865** [comment]
Cannot reproduce:
```
$ clang -msse2 -mavx -c -Wall sse.c

$ cat sse.c
#include <emmintrin.h>
#include <intrin.h>

inline int popcnt128(__m128i n) {
  const __m128i n_hi = _mm_unpackhi_epi64(n, n);

  return __popcnt64(_mm_cvtsi128_si64(n)) + __popcnt64(_mm_cvtsi128_si64(n_hi));
}
```

**Comment by dangyajun** [comment]
`#include <emmintrin.h>
#include <intrin.h>

static inline  int popcnt128(__m128i n) {
        const __m128i n_hi = _mm_unpackhi_epi64(n, n);
        return __builtin_popcountll(_mm_cvtsi128_si64(n)) + __builtin_popcountll(_mm_cvtsi128_si64(n_hi));
}


#include <stdio.h>
#include <stdlib.h>
int main(){
        __m128i  p = _mm_set1_epi32(9);
        int v = popcnt128(p);
        printf("v =  %d\n", v);
        return 0;
}

`
compile command:  clang -msse2 -mavx  --std=c99   sse.c
clang output: 
sse.c:6:30: warning: implicit declaration of function '_mm_cvtsi128_si64' is invalid in C99 [-Wimplicit-function-declaration]
        return __builtin_popcountll(_mm_cvtsi128_si64(n)) + __builtin_popcountll(_mm_cvtsi128_si64(n_hi));
                                    ^
1 warning generated.
C:\msys32\mingw32\bin\ld: C:\Users\DANGYA~1\AppData\Local\Temp\sse-3f636e.o:sse.c:(.text+0xde): undefined reference to `_mm_cvtsi128_si64'
C:\msys32\mingw32\bin\ld: C:\Users\DANGYA~1\AppData\Local\Temp\sse-3f636e.o:sse.c:(.text+0xfc): undefined reference to `_mm_cvtsi128_si64'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by mati865** [comment]
`_mm_cvtsi128_si64` is available only for 64 bit targets:
https://github.com/gcc-mirror/gcc/blob/4a3895903c29ed85da6fcb886f31ff23d4c6e935/gcc/config/i386/emmintrin.h#L231
https://github.com/llvm/llvm-project/blob/08fab9ebecf72a682279d75489dc2460121cbeed/clang/lib/Headers/emmintrin.h#L3515

**Comment by dangyajun** [comment]
Thank you!
