### ISSUE TITLE
After update any shell does not start and closes without messages

### ISSUE THREAD

**Issue by rmottola** [msys2/MSYS2-packages#2011]
## Describe the bug

After updating with "pacman -Syu", which ended successfully up to the message where it says the shell can be closed, no shell opens for me anymore.
MSYS, MINGW32, MINGW64 will quickly open a shell which immediately closes

## Additional Context: Operating System, Screenshots

I am unable to find logs or events with details of what is malfunctioning.

- OS: Windows 7 pro SP1 64bit

**Comment by lazka** [comment]
https://www.msys2.org/news/#2020-05-22-msys2-fails-to-start-after-a-msys2-runtime-upgrade

**Comment by rmottola** [comment]
Strange - I should have no sshd or other daemeons explicitly started by me running and all consoles where closed.
However... a hard reboot fixed everything.

Thanks

**Comment by lazka** [comment]
Some are started during an update automatically.

**Comment by rmottola** [comment]
Oh thank you, didn't know that. Well, problem "the windows way" (=reboot) solved, all is fine. Good to know there is a cleaner solution next time.

**Comment by jdeokkim** [comment]
![antivirus](https://user-images.githubusercontent.com/28700668/143890395-56c8f153-9f02-4830-8f8f-35fb416e651d.png)

For those who have an antivirus software and are struggling with MSYS2 not launching even after a reboot: you may need to add the installation path of MSYS2 to the antivirus scan exclusion list. (Screenshot from my antivirus software marking MSYS2 as a false positive)
