### ISSUE TITLE
Allowing others to build/upload packages

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2014]
@Alexpux wants to focus on other things than MSYS2 (source: gitter chat) but is currently the only person doing builds/uploads to the repo. For the project to continue we'd need someone to take over that job. Ideally more than one.

I still expect things to slow down because @Alexpux has put a lot of work into keeping things running. He said he'll still be available if we have questions in the future.

As a first step we need to figure out what is required to build/upload and who is willing to help.

* [ ] Have public GPG key in the keyring
* [ ] Have write access to the repo server (public SSH key)
* [ ] Have write access to sourceforge file uploads
* [ ] Have push access to https://github.com/msys2/MSYS2-packages and https://github.com/msys2/MINGW-packages.
* [ ] ...?

@elieux @dscho

**Comment by elieux** [comment]
- [ ] Have push access to https://github.com/msys2/MSYS2-packages and https://github.com/msys2/MINGW-packages.

**Comment by mati865** [comment]
To make things easier ideally most of the packages should be built on the CI and the big ones locally in chroot to make the builds reproducible. But is it even doable right now?
I have 2700X CPU so I could help with at least some of the big packages.

**Comment by elieux** [comment]
I agree with CI and reproducible builds and I plan to work towards that (with Johannes's help if possible).

**Comment by mati865** [comment]
For CI something would have to detect if reverse dependencies are not broken. That could be https://github.com/maximbaz/rebuild-detector with some changes (like `ldd` -> `ntldd`).

**Comment by elieux** [comment]
Cool, that might be useful. I was also thinking about using Abigail (if that's even possible) for detecting smaller changes.

**Comment by elieux** [comment]
Also ALPM is supposed to have automatic dependencies on shared objects, which if adapted to DLLs could help tremendously.

**Comment by lazka** [comment]
Any progress?

**Comment by elieux** [comment]
I should now have upload access to both repo.msys2.org and SF.net, although I still need to check the latter.  Push access has been there for a long time.  I'm currently waiting for someone to check https://github.com/msys2/MSYS2-keyring/pull/1 and @alexey to approve it.

**Comment by lazka** [comment]
Thanks for the update :)

**Comment by elieux** [comment]
First attempt wasn't great, hopefully the second will be a success: https://github.com/msys2/MSYS2-keyring/pull/2

**Comment by dscho** [comment]
> I agree with CI and reproducible builds and I plan to work towards that (with Johannes's help if possible).

Sure! I am a bit under water, work-wise, but I will do my best to assist.

**Comment by lazka** [comment]
Everything should be in place: https://www.msys2.org/news/#2020-06-29-new-packagers
