### ISSUE TITLE
Unable to start some programs

### ISSUE THREAD

**Issue by BFamzz** [msys2/MSYS2-packages#2017]
Hi, 

I was able to run some programs (glade, gtk3-demo, etc) in Msys2 shell successfully, but I upgraded my Msys2 with `pacman -Syu` and `pacman -Su` and since the upgrade, I've been unable to run the aforementioned programs. I keep getting this error message `bash: glade: command not found`

Please how can I fix it?

Thanks.

**Comment by Biswa96** [comment]
Try to run it from the mingw64 shortcut (blue icon) for 64bit or mingw32 shortcut (grey icon) for 32bit.

**Comment by BFamzz** [comment]
@Biswa96 Thanks for your reply. The programs are running very well. I tried compiling a program with makefile but it was giving an error message. `C:/msys64/mingw64/include/glib-2.0/glib-unix.h:29:10: fatal error: sys/wait.h: No such file or directory`

But the <sys/wait.h> file is in the `C:\msys64\usr\include directory`.

How can I fix this please? 

Thanks.

**Comment by lazka** [comment]
that likely means you are using the wrong compiler. Try installing `mingw-w64-x86_64-toolchain`

**Comment by BFamzz** [comment]
Hi @lazka 

Thanks for your response. 

Yes I have installed the `mingw-w64-x86_64-toolchain`. Please see screenshot below.

![image](https://user-images.githubusercontent.com/38426051/85262999-7329bb00-b466-11ea-832c-32ec7ecf410a.png)

**Comment by Alexpux** [comment]
@BFamzz @lazka goo-unix can’t be used under Windows, need to use goo-win32

**Comment by BFamzz** [comment]
Thanks @Alexpux 

It's a [GStreamer Demo (sendonly)](https://github.com/centricular/gstwebrtc-demos) I am trying to run.  How can I fix this?

Thanks.

**Comment by lazka** [comment]
Ask @nirbheek if Windows is supported at all :)

**Comment by nirbheek** [comment]
@lazka I agree with the answer here: https://github.com/centricular/gstwebrtc-demos/issues/203

However, if @BFamzz wants to use MSYS2, they need to ensure that the `MSYS2 MinGW 64-bit` terminal is used when building, not the `MSYS2 MSYS` terminal: 

![image](https://user-images.githubusercontent.com/75801/85281654-03d4bb00-b4a8-11ea-961c-5c1ce67c74b4.png)

I don't really know if MSYS2 ships with all the required dependencies for gstwebrtc-demos though. The cerbero win32 binaries are the best bet: https://gstreamer.freedesktop.org/download/

**Comment by lazka** [comment]
ok, thanks!

**Comment by BFamzz** [comment]
Thanks @nirbheek @lazka for your responses. 

I will try out building with Cerbero. @nirbheek the error message I got was from the mingw-64 terminal. See screenshot below.

![image](https://user-images.githubusercontent.com/38426051/85283082-af6c1400-b484-11ea-982f-c4dd494a08e8.png)

I am just a bit  concerned about compatibility because the project I'm working is based on MSYS2 packages and I plan to use GStreamer in the project.

**Comment by nirbheek** [comment]
That build error is either an MSYS2 bug or something incorrect in how you're using it. It has nothing to do with gstreamer.

**Comment by lazka** [comment]
https://github.com/centricular/gstwebrtc-demos/blob/000cfb6cd817ca0f07d761795b352a8b8b9074f8/sendonly/webrtc-recvonly-h264.c unconditionally includes glib-unix.h so I doubt it supports Windows.

**Comment by nirbheek** [comment]
Ah, hm, that's a mistake. I'll fix it. It's only used for adding the signal handlers, and the [sendrecv example does not use it](https://github.com/centricular/gstwebrtc-demos/blob/000cfb6cd817ca0f07d761795b352a8b8b9074f8/sendrecv/gst/webrtc-sendrecv.c).

**Comment by nirbheek** [comment]
@BFamzz can you try https://github.com/centricular/gstwebrtc-demos/pull/204?

**Comment by BFamzz** [comment]
Hi @nirbheek It compiles successfully. Thanks.
