### ISSUE TITLE
libxml2, link error during static compilation.

### ISSUE THREAD

**Issue by dft2000** [msys2/MSYS2-packages#2023]
I compile the project statically。
Error message：
...relocation truncated to fit: R_X86_64_PC32 against undefined symbol `__imp_xmlFree'....
How to solve，plz

**Comment by Biswa96** [comment]
May you provide some more info about this issue? For example, which environment you used e.g. msys2 or mingw64 or mingw32, what the compiler is, which project you've compiled etc.

**Comment by dft2000** [comment]
Need to add in CFLAGS add -DLIBXML_STATIC
