### ISSUE TITLE
How to make cygdrive path compatible with both MSYS2 and WSL?

### ISSUE THREAD

**Issue by nobk** [msys2/MSYS2-packages#2026]
MSYS2's default cygdrive path are /c /d /e /f.
WSL1|2's are /mnt/c /mnt/d /mnt/e /mnt/f.
I need those two way on both side for script path compatible.

On WSL side, to make script cygdrive path compatible with MSYS2, just make symlink
`ln -s /mnt/c /c`.

But on MSYS2 side, if edit /etc/fstab make two cygdrive mount points
```
# For a description of the file format, see the Users Guide
# https://cygwin.com/cygwin-ug-net/using.html#mount-table

# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
none / cygdrive binary,posix=0,noacl,user 0 0
none /mnt cygdrive binary,posix=0,noacl,user 0 0

```
only the last one /mnt/c take effect, /c none exist.
And make symlink `ln -s /mnt/c /c` in MSYS2 return error.
I am also try 
`mount -o bind /mnt/c /c`
/c becomes accessible but /mnt/c disappear.

Is there any way to configure /mnt/c and /c both exists in MSYS2?

**Comment by Biswa96** [comment]
Why do you need both mount path? Just stick to one option, either `/c` or `/mnt/c`.

**Comment by nobk** [comment]
@Biswa96 because I need.

**Comment by Alexpux** [comment]
@nobk it not possible currently, use Cygwin

**Comment by nobk** [comment]
@Alexpux I must tell you I just do it, of cause it is possible.
Just one command in CMD.exe
`D:\msys64\mnt>mklink /D c C:\`

**Comment by Alexpux** [comment]
It not possible by fstab as described in issue

**Comment by Biswa96** [comment]
If you are not sure about the mount point, you can convert Windows style path to *nix style using `cygpath` (in msys2) or `wslpath` (in WSL) tool in shell script. Also check if those tool exists before execution to differentiate between cygwin and WSL environment.

**Comment by nobk** [comment]
I write a script to make all cygdrive symlinks for MSYS2.
Important note: never do `DEL D:\msys64\mnt\c` it will delete data in C:\! To remove link mnt\c, use `RMDIR D:\msys64\mnt\c`

```
#!/bin/sh
mkdir -p /mnt
cd /mnt
cat /proc/partitions | awk '/:\\/ {print $5}' | sort | sed 's/^\([A-Z]\)\(.*\)$/\L\1 \U\1\2/' | xargs -d '\n' -i cmd.exe //C echo "mklink /D {}"
ls -l

```
