### ISSUE TITLE
When only linked to msys, the program cannot run.GDB：Thread 1 received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by dft2000** [msys2/MSYS2-packages#2043]
When only linked to msys, the program cannot run

Example：
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]){
printf ("Hello world!");
}
Compile：
_gcc hello.c -o hello -g -L/usr/lib -lmsys-2.0_

Use gdb debug output

gdb ./hello.exe
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./hello.exe...
(gdb) run
Starting program: J:\msys2\home\cc\src\posixthread\hello.exe
[New Thread 1304.0x2bb0]
[New Thread 1304.0x1a0]
[New Thread 1304.0x1c54]
warning: cYgFFFFFFFF 1802666E0 0
[New Thread 1304.0x6ec]

Thread 1 received signal SIGSEGV, Segmentation fault.
_sigfe () at sigfe.s:31
31      sigfe.s: No such file or directory.
Others:
Operating system win10 18363.
Msys2 runtime is the latest version.

Excuse me, what is this question?Is there a solution?

**Comment by Alexpux** [comment]
@dft2000 use MSYS GDB to debug MSYS programs, not MINGW GDB

**Comment by dft2000** [comment]
Ok.
Gdb  output：
# /usr/bin/gdb hello.exe
GNU gdb (GDB) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-msys".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'libstdcxx'
/etc/gdbinit:6: Error in sourced command file:
Error while executing Python code.
Reading symbols from hello.exe...
(gdb) run
Starting program: /home/cc/src/posixthread/hello.exe
[New Thread 6236.0x2f38]
[New Thread 6236.0x274c]
[New Thread 6236.0x1a54]
[New Thread 6236.0x2254]
[Thread 6236.0x1a54 exited with code 3221225477]
[Thread 6236.0x2c70 exited with code 3221225477]
[Thread 6236.0x2254 exited with code 3221225477]
[Thread 6236.0x274c exited with code 3221225477]
[Inferior 1 (process 6236) exited with code 030000000005]

**Comment by dft2000** [comment]
Use msys2 gcc to compile msys2 applications.
My environment is mingw64-gcc by default.
Gcc version is different
