### ISSUE TITLE
[BUG] Searching pacman for makeinfo does not suggest texinfo

### ISSUE THREAD

**Issue by MenaceInc** [msys2/MSYS2-packages#2053]
## Describe the bug

Searching pacman for makeinfo does not suggest the texinfo package

## Steps to Reproduce the Problem

1. Run 'pacman -Ss makeinfo'
2. Get no results

Expected behavior: results that show
"msys/texinfo 6.7-2 (base-devel)
    Utilities to work with and produce manuals, ASCII text, and on-line documentation from a single source file"

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Version 2004, build 19041.388
- fresh install of MSYS2 using 20200720 installed and updated using 'pacman -Syyuu'

**Comment by MenaceInc** [comment]
Same thing with libtoolize and the libtool package

**Comment by Biswa96** [comment]
`texinfo` is a package name and `makeinfo` is a program of that package. So, pacman, the pacakge manager, will show only package name by default... until you add `-F` command line option. Use `pacman -Fy` to download the database files. Then use `pacman -F filepath` to search the package name. For example,

```
$ pacman -F makeinfo
msys/texinfo 6.7-2 (base-devel) [installed]
    usr/bin/makeinfo
```

See this ArchLinux Wiki page for further details https://wiki.archlinux.org/index.php/Pacman#Search_for_a_package_that_contains_a_specific_file

**Comment by Biswa96** [comment]
`texinfo` is a package name and `makeinfo` is a program of that package. So, pacman, the pacakge manager, will show only package name by default... until you add `-F` command line option. Use `pacman -Fy` to download the database files. Then use `pacman -F filepath` to search the package name. For example,

```
$ pacman -F makeinfo
msys/texinfo 6.7-2 (base-devel) [installed]
    usr/bin/makeinfo
```

And with `libtoolize`:

```
$ pacman -F libtoolize
mingw32/mingw-w64-i686-libtool 2.4.6-17
    mingw32/bin/libtoolize
mingw64/mingw-w64-x86_64-libtool 2.4.6-17 [installed]
    mingw64/bin/libtoolize
msys/libtool 2.4.6-9 (base-devel) [installed]
    usr/bin/libtoolize
```

See this ArchLinux Wiki page for further details https://wiki.archlinux.org/index.php/Pacman#Search_for_a_package_that_contains_a_specific_file

**Comment by MenaceInc** [comment]
Well don't I feel silly. I appreciate the info @Biswa96 . I was used to using -Ss but I guess I'll be using -F from now on. Thank you.
