### ISSUE TITLE
[BUG] symlink() on a directory leaks handles

### ISSUE THREAD

**Issue by evangreen** [msys2/MSYS2-packages#2060]
## Describe the bug

Running symlink() when the target of a link is a directory results in leaked handles.

## Steps to Reproduce the Problem

```
cat > symdir.c <<_EOF
#include <stdio.h>
#include <unistd.h>
#include <errno.h>

int main() {
        mkdir("dir1");
        mkdir("dir1/dir2");
        mkdir("dir1/dir2/dir3");
        symlink("dir1", "symlink_to_dir1");
        perror("That worked");
        rename("dir1", "dir4");
        perror("That didn't work");
        return 0;
}
_EOF

$ gcc -o symdir symdir.c
$ ./symdir
That worked: No error
That didn't work: Permission denied

```

Expected behavior: The rename should have succeeded. Instead it did not because handles are still open to dir1/dir2 and dir1/dir2/dir3.

## Additional Context: Operating System, Screenshots

My guess is the patch at 0006-Do-not-create-cygwin-symlinks.-Instead-use-deep-copy.patch should be calling FindClose() to close the handles opened by FindFirstFile().

[1] https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findclose

**Comment by cbrt64** [comment]
```
$ ./symdir
That worked: No error
That didn't work: No error

$ find
.
./dir4
./dir4/dir2
./dir4/dir2/dir3
./symdir.c
./symdir.exe
./symlink_to_dir1
./symlink_to_dir1/dir2
./symlink_to_dir1/dir2/dir3
```

Your guess was right. Though I'd rather call it good sleuthing, myself. ;)
