### ISSUE TITLE
Should perl-HTTP-Message include perl-IO-HTML as a dependency?

### ISSUE THREAD

**Issue by hakonhagland** [msys2/MSYS2-packages#2064]
I am debugging a failed test in [this](https://metacpan.org/pod/Alien::Base::ModuleBuild) module in MSYS2 on Windows 10. It turns out the problem is that it uses `HTTP::Message` to get a local file and then calls [decoded_content()](https://metacpan.org/release/HTTP-Message/source/lib/HTTP/Message.pm#L281) which calls [content_charset()](https://metacpan.org/release/HTTP-Message/source/lib/HTTP/Message.pm#L205) which requires `IO::HTML` at [line 247](https://metacpan.org/release/HTTP-Message/source/lib/HTTP/Message.pm#L247) which fails since `IO::HTML` is not installed. 

It looks to me as if  `perl-IO-HTML` should be a dependency of `perl-HTTP-Message` since the `Makefile.PL` also lists it as a dependency [at line 29](https://metacpan.org/source/ETHER/HTTP-Message-6.25/Makefile.PL#L29) ?

**Comment by lazka** [comment]
Sounds good. It's also a dependency in Arch.

**Comment by lazka** [comment]
Fixed in #2065, thanks @Biswa96 !
