### ISSUE TITLE
msys2-keyring: update to r21.b39fb11-1 in msys database

### ISSUE THREAD

**Issue by h-c-mueller** [msys2/MSYS2-packages#2068]
After following https://www.msys2.org/news/ for required key update I get the following message on command `LANG=C pacman -Suy`
`warning: msys2-keyring: local (r21.b39fb11-1) is newer than msys (r9.397a52e-1)`

So I assume you need to add r21.b39fb11-1 to msys database
Otherwise I assume `pacman -Suuy` will revert msys2-keyring to old r9.397a52e-1.

**Comment by lazka** [comment]
It is in the database: https://packages.msys2.org/base/msys2-keyring

weird..

**Comment by h-c-mueller** [comment]
We are getting closer. My `/etc/pacman.d/mirrorlist` refers to
`Server = http://repo.msys2.org/msys/$arch/`
My arch is  'i686', there is no such file. But in 'x86_64' I find:
`msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz`
So I assume this file needs to be copied also to 'i686'.

**Comment by lazka** [comment]
OK, see https://www.msys2.org/news/#2020-05-17-32-bit-msys2-no-longer-actively-supported

I'm closing this in favor of #2067
