### ISSUE TITLE
filesystem: include mingw32/64.ico

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2081]
I'd like to add extra profiles for msys/mingw32/mingw64 to Windows Terminal. It allows to specify an icon per profile but we currently only ship one.

![Capture](https://user-images.githubusercontent.com/991986/89126838-519e0380-d4e9-11ea-88ae-537a214f431d.PNG)

**Comment by angelog0** [comment]
I copied them from [msys2 launcher](https://github.com/msys2/msys2-launcher) repo... This is the result:


![WT_msys2](https://user-images.githubusercontent.com/35931460/89193743-bbc8ae00-d5a6-11ea-8714-223a252619f2.png)

```
[...]
"name": "MINGW64",
 "commandline": "C:/msys64/usr/bin/env.exe MSYS=winsymlinks:nativestrict MSYSTEM=MINGW64 /bin/bash --login",
 "startingDirectory": "C:/msys64/home/the_user",
"colorScheme": "MSYS2-Theme",
"icon": "C:/msys64/mingw64.ico"
[...]
```
