### ISSUE TITLE
About the SourceForge restructured page

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#2087]
I see you have removed the GitHub links to MSYS2/MINGW packages from this [page](https://sourceforge.net/projects/msys2/). This is a pity! Those links were very useful. I would suggest to restore them. They were a means to reach this page very fast!

BTW, the link to MSYS2 site is wrong: it has lost the `www` piece...

This really is not a bug just a request. How can I remove the `bug` label?

**Comment by lazka** [comment]
I'm afraid I don't know how the old page looked like as I've never used it. Can you explain what you are missing and why you can't just use bookmarks?

**Comment by angelog0** [comment]
There were 2 links to GiuHub pages. Now I found them elsewhere. Closing this...

**Comment by angelog0** [comment]
Anyway, the link to MSYS2 web site is wrong

### Follow MSYS2
**MSYS2 Web Site**  ==> https://msys2.org   which is wrong, or not?
