### ISSUE TITLE
[BUG] Pacman -Syu — mingw32, msys, mingw64: unknown key...

### ISSUE THREAD

**Issue by firesense** [msys2/MSYS2-packages#2097]
## Describe the bug

Description is provided by print screen file.

## Steps to Reproduce the Problem

1. pacman -Syu

See attached image.

## Additional Context: Operating System, Screenshots

![MSYS2-pacman_Syu-error](https://user-images.githubusercontent.com/36279223/89800163-0d3ce400-db37-11ea-979b-1214b9cceb96.png)

- OS: Windows 10 Pro version 1909 64bit

**Comment by Biswa96** [comment]
Try this https://www.msys2.org/news/#2020-06-29-new-packagers

**Comment by firesense** [comment]
> Try this https://www.msys2.org/news/#2020-06-29-new-packagers

Thanks a lot! Your solution solved the keys issue. ;)
