### ISSUE TITLE
A few packages are not upgraded

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#2098]
I have

```
$ cat /etc/pacman.d/mirrorlist.msys
##
## MSYS2 repository mirrorlist
##

## Primary
## msys2.org
Server = http://repo.msys2.org/msys/$arch/
Server = https://sourceforge.net/projects/msys2/files/REPOS/MSYS2/$arch/
Server = https://www2.futureware.at/~nickoe/msys2-mirror/msys/$arch/
...
```

From http://repo.msys2.org/msys/x86_64 I see there are new version for a few packages. For example, there is `filesystem-2020.02-6-x86_64.pkg.tar.xz ` and `mintty-1.3.3.0-1-x86_64.pkg.tar.xz` both released today August 10 but

```
$ pacman -Syu
:: Sincronizzazione dei database in corso...
 mingw32 è aggiornato
 mingw64 è aggiornato
 msys è aggiornato
:: Starting core system upgrade...
 non ci sono aggiornamenti disponibili
:: Aggiornamento del sistema in corso...
 non ci sono aggiornamenti disponibili
```

and

```
$ pacman -Ss filesystem
[...]
msys/filesystem 2020.02-5 [installato]
[...]

$ pacman -Ss mintty
msys/mintty 1~3.2.0-1 [installato]
    Terminal emulator with native Windows look and feel
```

What am I missing?

**Comment by mati865** [comment]
I don't understand Italian but maybe cache is wrong? Try `pacman -Syyu` to force refreshing it this time.
Otherwise please post result of `LANG=C pacman -Syu`.

**Comment by angelog0** [comment]
```
$ pacman -Syyu
:: Sincronizzazione dei database in corso...
 mingw32                                     506,2 KiB   470 KiB/s 00:01 [#######################################] 100%
 mingw32.sig                                 438,0   B  0,00   B/s 00:00 [#######################################] 100%
 mingw64                                     507,9 KiB   733 KiB/s 00:01 [#######################################] 100%
 mingw64.sig                                 438,0   B  0,00   B/s 00:00 [#######################################] 100%
 msys                                        203,8 KiB  1282 KiB/s 00:00 [#######################################] 100%
 msys.sig                                    438,0   B  0,00   B/s 00:00 [#######################################] 100%
:: Starting core system upgrade...
 non ci sono aggiornamenti disponibili
:: Aggiornamento del sistema in corso...
 non ci sono aggiornamenti disponibili
```

```
$ LANG=C pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by jeremyd2019** [comment]
Are you sure mintty and filesystem were updated?  They seem to still be in https://packages.msys2.org/queue and did not seem to be in the msys.db.  @elieux ?

**Comment by angelog0** [comment]
See this screenshot: 

![repo](https://user-images.githubusercontent.com/35931460/89833616-9f59e200-db61-11ea-8f28-69ceec02f0b8.png)

it shows that `filesystem-2020.02-6-x86_64.pkg.tar.xz` is in that repo. The same for the new version of `mintty`. This evening many package I see [here](https://sourceforge.net/p/msys2/activity) were upgraded but as many, not...

**Comment by angelog0** [comment]
Now, they are 2 hours that they were released....

**Comment by jeremyd2019** [comment]
So it appears the packages were uploaded, but not included in the db.

**Comment by angelog0** [comment]
Maybe we have only to wait but all this sounds strange because, usually, when on SourceForge I see packages just released (a few minutes..) I can upgrade them, all.

**Comment by Biswa96** [comment]
Two options:

1. Wait.
2. Download the .tar.zst and install it with `pacman -U`.

**Comment by lazka** [comment]
mintty is currently blocked by https://github.com/msys2/msys2-devtools/issues/15

Not sure why filesystem was uploaded but not included.

**Comment by Alexpux** [comment]
@lazka I think because command for adding to repo is wrong. As we currently have two package extensions - "tar.xz" and "tar.zst" but only zst packages added to repo

**Comment by lazka** [comment]
ah, good catch! @elieux ^

(in the case of mintty it was good, because that filename is broken currently, will fix later today..)

**Comment by angelog0** [comment]
...so you need a command to add also `tar.xz` packages... or to convert them in `tar.zst`.....

**Comment by lazka** [comment]
seems fixed now
