### ISSUE TITLE
Python os.envrion's PATH style is different ,according to different PATH directory's order.  

### ISSUE THREAD

**Issue by meziberry** [msys2/MSYS2-packages#2146]
- When shell PATH directory order is `/c/msys/mingw64/bin:/c/msys/usr/local/bin:/c/msys/usr/bin:`

the python `os.environ.items` PATH style is `C:\\msys\\mingw64\\bin;C:\\msys\\usr\\local\\bin;C:\\msys\\usr\\bin;`.

- When shell PATH directory order is `/c/msys/usr/bin:/c/msys/usr/local/bin:/c/msys/mingw64/bin:`

the python `os.environ.items` PATH style is `/c/msys/usr/bin:/c/msys/usr/local/bin:/c/msys/mingw64/bin:` .

It seems like python os package has called different exe file?. Why is it this?  
My .emacs use python to convert PATH to exec-path. When emacs starts under the frist style environment, can't set the vars exec-path correctly.

My os enviroment `win10 1909.   Python3.8.5 on msys2`

**Comment by mati865** [comment]
Python from `/mingw64/bin` is Windows native application and uses Windows paths while Python from `/usr/bin` is UNIX emulated application that uses UNIX paths.

**Comment by meziberry** [comment]
Thank you @mati865  for your reply.  I got it.   So, i close it.
