### ISSUE TITLE
iconv from msys missing windows code pages, which are present in mingw32

### ISSUE THREAD

**Issue by mefistotelis** [msys2/MSYS2-packages#2148]
I don't think there's even a need to comment that:

```
me@msys2 MINGW64 /d
# /usr/bin/iconv -l | grep 852

me@msys2 MINGW64 /d
# /mingw32/bin/iconv -l | grep 852
852 CP852 IBM852 CSPCP852
```

CP852 is one of the DOS era code pages used in localized Windows.

**Comment by lazka** [comment]
> When configured with the option --enable-extra-encodings, it also provides support for a few extra encodings:
CP{437,737,775,852,853,855,857,858,860,861,863,865,869,1125}

PR welcome

**Comment by mefistotelis** [comment]
Thanks for quick feedback; will do PR.

**Comment by 1480c1** [comment]
Can probably be closed since the pr was merged
