### ISSUE TITLE
[BUG] (poppler) conflicting files when installing dependencies 

### ISSUE THREAD

**Issue by micdev42** [msys2/MSYS2-packages#2154]
## Describe the bug

mingw-w64-x86_64-poppler: failed to commit transaction (conflicting files)

## Steps to Reproduce the Problem

I'm attempting to build inkscape x64 on Windows 10 x64 using MSYS2 x64 shell, following the instructions here https://wiki.inkscape.org/wiki/index.php?title=Compiling_Inkscape_on_Windows_with_MSYS2 

As part of that build I run this script `msys2installdeps.sh` (which runs `msys2installdeps.py`). The files are here: https://gitlab.com/inkscape/inkscape/-/tree/master/buildtools .

1. Run `./msys2installdeps.sh`
2. version conflict errors reported (see attached)

## Expected behavior
Dependencies installed without conflict

## Additional Context: Operating System, Screenshots

See attached log
[msys2installdeps.sh.log](https://github.com/msys2/MSYS2-packages/files/5249959/msys2installdeps.sh.log)

inkscape bug: https://gitlab.com/inkscape/inkscape/-/issues/1877 

- OS: Windows 10 Pro version 2004 x64
- OS Build 19041.508

**Comment by Biswa96** [comment]
Queries:

1. Why there is `C:/tools/git-sdk-64` in the log? Didn't you use MSYS2? If yes, try to remove that from `$PATH` or `%PATH%`.
2. Where did you find `mingw-w64-x86_64-xpdf-tools` package? There is no package with that name. See here https://packages.msys2.org/search?t=pkg&q=xpdf
3. If I do `pacman -Fyy; pacman -F /mingw64/bin/pdfdetach.exe` it is only owned by poppler.

A **destructive** workaround will be `pacman -S --overwrite=/mingw64/bin/* mingw-w64-x86_64-poppler`.

**Comment by mati865** [comment]
`mingw-w64-x86_64-xpdf-tools` comes from Git for Windows.
Looks like you are using [`git-sdk-64`](https://github.com/git-for-windows/git-sdk-64) where `mingw-w64-x86_64-xpdf-tools` comes pre-installed.

**Comment by micdev42** [comment]
Thanks. Yes I am. So that's bad? I'll do some reading...

**Comment by micdev42** [comment]
This may be finger trouble on my part. Once confirmed I'll update and close.

**Comment by mati865** [comment]
So this bug belongs to git-sdk, `xpdf-tools` should have field telling `pacman` it conflicts with poppler.

**Comment by micdev42** [comment]
OK finger trouble. Gawd knows why but in installed git for windows SDK and was trying to build with that rather than msys2 - as correctly surmised by @mati865 . This is a non-bug so I will close.
