### ISSUE TITLE
[BUG] Cannot update, repo.msys2.org times out

### ISSUE THREAD

**Issue by quanah** [msys2/MSYS2-packages#2171]
## Describe the bug

All attempts to use pacman to update fail because of timeouts to repo.msys2.org

Curl and other web tools also all fail to connect.  System is unreachable from multiple different networks spread across the US.

**Comment by Biswa96** [comment]
https://gitter.im/msys2/msys2?at=5f772485aa7388396e8d84e4

**Comment by mathacka** [comment]
Unable to download the current executable because repo.msys2.com times out as well.

**Comment by quanah** [comment]
Note: One workaround is to use a different mirror.  At this time the sourceforge mirror should be avoided since it's not up to date.

**Comment by jeremyd2019** [comment]
https://github.com/msys2/msys2-installer/releases/latest has the latest executables/installers

**Comment by KokoseiJ** [comment]
repo.msys2.org is down for a bit too long, Do any of you have idea of what's going on?

**Comment by lazka** [comment]
It's back up now. Sorry everyone.

(If anyone is willing to sponsor a better server please get in contact with us)
