### ISSUE TITLE
[BUG] Can't access msys2-keyring package

### ISSUE THREAD

**Issue by maxnelso** [msys2/MSYS2-packages#2175]
## Describe the bug

Hi,

I'm trying to download the msys2-keyring package (when installing a vcpkg package) from here: http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz, but it seems to be hanging...is there some issue? For reference, I think it's this package: https://packages.msys2.org/package/msys2-keyring?repo=msys&variant=x86_64. Thanks for any help!

## Steps to Reproduce the Problem

Try to download from: [http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz](http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz)

**Comment by 1480c1** [comment]
Probably related to https://github.com/msys2/MSYS2-packages/issues/2171

**Comment by maxnelso** [comment]
Oh i'm sorry, I didn't see that, I'll close.
