### ISSUE TITLE
Server downtime: Lessons learned

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2178]
Some things learned or things to do:

* We should try to not let the repo size grow indefinitely as that makes things hard to transfer/recover-> https://github.com/msys2/MSYS2-packages/issues/2174
* We should sign the installers, so they can safely be recovered from a third party mirror -> TODO
* We should make sure the sourceforge mirror is regularely/properly synced, or remove it
* We should document how to switch mirrors locally (using rankmirrors maybe)
* We should document the contact info for our existing mirrors

I've created a docker based server setup to quickly get a server running, though this isn't used right now because the server was already set up differently: https://github.com/msys2/msys2-repo-server Maybe it can be useful in the future.

Anything else?

**Comment by 1480c1** [comment]
Locally, I am just running

```bash
for list in mingw{32,64} msys; do
    cp /etc/pacman.d/mirrorlist.$list{,.orig}
    rankmirrors -r $list -v /etc/pacman.d/mirrorlist.$list.orig > /etc/pacman.d/mirrorlist.$list.ranked
    cp /etc/pacman.d/mirrorlist.$list{.ranked,}
done
```
for all of my msys2 installs so I get the best one either way

**Comment by jeremyd2019** [comment]
I was thinking something ranking mirrors post-install would be helpful, but then I thought that might cause more issues/annoyance when pacman-mirrors is updated.

**Comment by lazka** [comment]
@carrotIndustries are you the selfnet.de mirror contact? Seems rsync sync is broken, but I can't see why right now, maybe you can see some rsync logs or investigate this?

**Comment by lazka** [comment]
hm, I think the file permissions are wrong

**Comment by lygstate** [comment]
```
downloading mingw-w64-x86_64-python-setuptools-47.1.1-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-binutils-2.35.1-2-any.pkg.tar.zst...
downloading mingw-w64-x86_64-headers-git-8.0.0.6001.98dad1fe-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-crt-git-8.0.0.6001.98dad1fe-1-any.pkg.tar.zst...
downloading mingw-w64-x86_64-isl-0.22.1-1-any.pkg.tar.xz...
error: failed retrieving file 'mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded
downloading mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz...
downloading mingw-w64-x86_64-winpthreads-git-8.0.0.6001.98dad1fe-3-any.pkg.tar.zst...
downloading mingw-w64-x86_64-zstd-1.4.5-1-any.pkg.tar.zst...
```

more file lost in sf.net

**Comment by lygstate** [comment]
How about using github lfs as files storage?

**Comment by elieux** [comment]
> We should try to not let the repo size grow indefinitely as that makes things hard to transfer/recover-> #2174

I plan to regularly prune the old packages now.

> We should sign the installers, so they can safely be recovered from a third party mirror

Should I sign them retroactively, or shall we release a new installer and start with that one? By the way, we have a bunch of installer checksums in our homepage history.

> We should make sure the sourceforge mirror is regularely/properly synced, or remove it

Thanks to pruning, SF was able to be synced and it's now part of the repo update process.

> We should document how to switch mirrors locally (using rankmirrors maybe)

Good point.

> We should document the contact info for our existing mirrors

I once tried to go through the PKGBUILD history to find who added what, but that's a bit of a mess. Keeping contacts (and checking in every now and then) would be great.

> error: failed retrieving file 'mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded

I don't know what's wrong there. The file is there and both checksum and signature checks are green.

> How about using github lfs as files storage?

[Looks like it's very limited.](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/about-storage-and-bandwidth-usage)

**Comment by lygstate** [comment]
> > We should try to not let the repo size grow indefinitely as that makes things hard to transfer/recover-> #2174
> 
> I plan to regularly prune the old packages now.
> 
before prune， can we backup it first？
> > We should sign the installers, so they can safely be recovered from a third party mirror
> 
> Should I sign them retroactively, or shall we release a new installer and start with that one? By the way, we have a bunch of installer checksums in our homepage history.
> 
> > We should make sure the sourceforge mirror is regularely/properly synced, or remove it
> 
> Thanks to pruning, SF was able to be synced and it's now part of the repo update process.
> 
> > We should document how to switch mirrors locally (using rankmirrors maybe)
> 
> Good point.
> 
> > We should document the contact info for our existing mirrors
> 
> I once tried to go through the PKGBUILD history to find who added what, but that's a bit of a mess. Keeping contacts (and checking in every now and then) would be great.
> 
> > error: failed retrieving file 'mingw-w64-x86_64-windows-default-manifest-6.4-3-any.pkg.tar.xz' from sourceforge.net : Maximum file size exceeded
> 
> I don't know what's wrong there. The file is there and both checksum and signature checks are green.
> 
> > How about using github lfs as files storage?
> 
> [Looks like it's very limited.](https://docs.github.com/en/free-pro-team@latest/github/managing-large-files/about-storage-and-bandwidth-usage)

**Comment by jtanx** [comment]
Who's the contact for the primary repo? Would you mind if I shot an email to aarnet to see if they're willing to mirror it? (or happy for someone else to email them) https://support.aarnet.edu.au/hc/en-us/articles/220499087-How-do-I-get-an-archive-added-to-mirror-

**Comment by lazka** [comment]
> Some things learned or things to do:
> 
>     * We should try to not let the repo size grow indefinitely as that makes things hard to transfer/recover-> [[Discussion] Prune old packages from the repos #2174](https://github.com/msys2/MSYS2-packages/issues/2174)

There is now a prune script: https://github.com/msys2/msys2-devtools/blob/main/msys2-repo-prune

>     * We should sign the installers, so they can safely be recovered from a third party mirror -> TODO

This is now done, and there is a script to verify that all files are signed: https://github.com/msys2/msys2-devtools/blob/main/msys2-repo-verify

>     * We should make sure the sourceforge mirror is regularely/properly synced, or remove it

It got removed

>     * We should document how to switch mirrors locally (using rankmirrors maybe)

Ideally we will recover faster next time, so this isn't needed.

>     * We should document the contact info for our existing mirrors

This is now on the mirror page.

> I've created a docker based server setup to quickly get a server running, though this isn't used right now because the server was already set up differently: https://github.com/msys2/msys2-repo-server Maybe it can be useful in the future.

This is now the main server.
