### ISSUE TITLE
[BUG] Python seems to be misconfigured

### ISSUE THREAD

**Issue by mbasaglia** [msys2/MSYS2-packages#2185]
## Describe the bug

I'm trying to compile some software on Windows (64bit) which includes CPython headers.

The python header complain about sizeof(long) not being correct.

## Steps to Reproduce the Problem

```bash
pacman -S mingw-w64-x86_64-python
echo '#include <Python.h>' >foo.c
gcc foo.c -I/mingw64/include/python3.8
```

it will give an error about `LONG_BIT` being the wrong size.

```
/mingw64/include/python3.8/pyport.h:745:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
  745 | #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?).
```

The error is cause by the file `pyconfig.h` that defines `SIZEOF_LONG` to 4 instead of 8.

## Additional Context: Operating System, Screenshots

Windows 10 Pro 1909

I've compiled a small test program:

```c++
#include <iostream>
int main()
{
    std::cout << sizeof(long) << " " << sizeof(long*);
}
```

it prints `8 8` so everything is 64 bits

**Comment by jeremyd2019** [comment]
That's odd, sizeof(long) on Windows is supposed to be 4.

**Comment by mbasaglia** [comment]
maybe something happened when I installed the packages? after reinstalling the same packages it works fine

**Comment by lazka** [comment]
You were in a msys shell but need to be in a mingw64 shell.
