### ISSUE TITLE
Pacman failing to download the packages with 404

### ISSUE THREAD

**Issue by ganga1980** [msys2/MSYS2-packages#2212]
## Steps to Reproduce the Problem

1. Run '...'
We have below steps in docker file like to this to install ruby via rdk. This was working until last week and now we are seeing package download  failing with 404.  

RUN refreshenv \
&& ridk install 3 \
&& echo gem: --no-document >> C:\ProgramData\gemrc \
&& gem install cool.io -v 1.5.4 --platform ruby \
&& gem install oj -v 3.3.10 \
&& gem install json -v 2.2.0 \
&& gem install fluentd -v 1.10.2 \
&& gem install win32-service -v 1.0.1 \
&& gem install win32-ipc -v 0.7.0 \
&& gem install win32-event -v 0.6.3 \
&& gem install windows-pr -v 1.2.6 \
&& gem install tomlrb -v 1.3.0 \
&& gem install gyoku -v 1.3.1 \
&& gem sources --clear-all

2. Do something '....'
3. Catch the error

Step 7/35 : RUN refreshenv && ridk install 1 3
 ---> Running in 2b83aab65bc0
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
> sh -lc true
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autoconf2.13 autogen automake-wrapper automake1.10 automake1.11 automake1.12 automake1.13 automake1.14 automake1.15 automake1.6 automake1.7 automake1.8 automake1.9 diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git
warning: file-5.37-1 is up to date -- skipping
warning: gawk-5.0.0-1 is up to date -- skipping
warning: grep-3.0-2 is up to date -- skipping
warning: m4-1.4.18-2 is up to date -- skipping
warning: sed-4.7-1 is up to date -- skipping
warning: wget-1.20.3-1 is up to date -- skipping
resolving dependencies...
looking for conflicting packages...

Packages (51) automake1.16-1.16.1-1  db-5.3.28-2  gdbm-1.18.1-2  libatomic_ops-7.6.10-1  libgc-7.6.8-1  libgdbm-1.18.1-2  libguile-2.2.4-3  libltdl-2.4.6-6  mingw-w64-x86_64-expat-2.2.6-1  mingw-w64-x86_64-gettext-0.19.8.1-8  mingw-w64-x86_64-gmp-6.1.2-1  mingw-w64-x86_64-isl-0.21-1  mingw-w64-x86_64-libiconv-1.16-1  mingw-w64-x86_64-mpc-1.1.0-1  mingw-w64-x86_64-mpfr-4.0.2-2  mingw-w64-x86_64-windows-default-manifest-6.4-3  mingw-w64-x86_64-zlib-1.2.11-7  perl-5.28.2-1  tar-1.32-1  autoconf-2.69-5  autoconf2.13-2.13-2  autogen-5.18.16-1  automake-wrapper-11-1  automake1.10-1.10.3-3  automake1.11-1.11.6-3  automake1.12-1.12.6-3  automake1.13-1.13.4-4  automake1.14-1.14.1-3  automake1.15-1.15.1-1  automake1.6-1.6.3-2  automake1.7-1.7.9-2  automake1.8-1.8.5-3  automake1.9-1.9.6-2  diffutils-3.7-1  libtool-2.4.6-6  make-4.2.1-1  mingw-w64-x86_64-binutils-2.30-5  mingw-w64-x86_64-crt-git-7.0.0.5449.a0647123-1  mingw-w64-x86_64-gcc-8.3.0-2  mingw-w64-x86_64-gcc-libs-8.3.0-2  mingw-w64-x86_64-headers-git-7.0.0.5449.a0647123-1  mingw-w64-x86_64-libmangle-git-7.0.0.5230.69c8fad6-1  mingw-w64-x86_64-libwinpthread-git-7.0.0.5447.a2d94c81-1  mingw-w64-x86_64-make-4.2.1-2  mingw-w64-x86_64-pkg-config-0.29.2-1  mingw-w64-x86_64-tools-git-7.0.0.5394.0dfb3d3f-1  mingw-w64-x86_64-winpthreads-git-7.0.0.5447.a2d94c81-1  patch-2.7.6-1  pkg-config-0.29.2-1  texinfo-6.6-1  texinfo-tex-6.6-1

Total Download Size:    86.15 MiB
Total Installed Size:  524.71 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading mingw-w64-x86_64-libiconv-1.16-1-any.pkg.tar.xz...
downloading mingw-w64-x86_64-zlib-1.2.11-7-any.pkg.tar.xz...
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.30-5-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.30-5-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.30-5-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-binutils-2.30-5-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'mingw-w64-x86_64-headers-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-headers-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-headers-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-headers-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed retrieving file 'mingw-w64-x86_64-crt-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-crt-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-crt-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-x86_64-crt-git-7.0.0.5449.a0647123-1-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404

Expected behavior: A clear and concise description of what you expected to happen instead.

packages should be loaded successfully as it was before.

## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 Pro version 1909 64bit]
- '...'

**Comment by mati865** [comment]
Does rdk run `pacman -Syu` before installing packages?

**Comment by ganga1980** [comment]
> Does rdk run `pacman -Syu` before installing packages?

> Hi, @mati865, thanks for the response. yes, I have tried invoking packman commands but no luck.
since pacman installed with ridk so cant move pacman before installing of ridk. Until last week everything was working but since around Oct 21 also, downloading of packages failing. any insights would be greatly helpful?


Here is the snippet commands I have docker file

# Do not split this into multiple RUN!
# Docker creates a layer for every RUN-Statement
RUN powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
# Fluentd depends on cool.io whose fat gem is only available for Ruby < 2.5, so need to specify --platform ruby when install Ruby > 2.5 and install msys2 to get dev tools
RUN choco install -y ruby --version 2.6.5.1 --params "'/InstallDir:C:\ruby26'" \
&& choco install -y msys2 --version 20190524.0.0.20191030 --params "'/NoPath /NoUpdate /InstallDir:C:\ruby26\msys64'" \
&& choco install -y vim


RUN refreshenv \
&& ridk install 1 3

# RUN pacman -Syyu --noconfirm
RUN pacman -Syuv --debug --noconfirm
RUN pacman -S pacman-mirrors --noconfirm

RUN pacman -Syyu --noconfirm
RUN pacman-db-upgrade

RUN ridk install 3 \
&& echo gem: --no-document >> C:\ProgramData\gemrc \
&& gem install cool.io -v 1.5.4 --platform ruby \
&& gem install oj -v 3.3.10 \
&& gem install json -v 2.2.0 \
&& gem install fluentd -v 1.10.2 \
&& gem install win32-service -v 1.0.1 \
&& gem install win32-ipc -v 0.7.0 \
&& gem install win32-event -v 0.6.3 \
&& gem install windows-pr -v 1.2.6 \
&& gem install tomlrb -v 1.3.0 \
&& gem install gyoku -v 1.3.1 \
&& gem sources --clear-all

**Comment by mati865** [comment]
The problem is `RUN refreshenv && ridk install 1 3` being ran before updating MSYS2 (lines starting with `RUN pacman *`).
You should move it lower.

**Comment by ganga1980** [comment]
> The problem is `RUN refreshenv && ridk install 1 3` being ran before updating MSYS2 (lines starting with `RUN pacman *`).
> You should move it lower.

> Hi, @mati865, if  I move "RUN refreshenv && ridk install 1 3" after pacman commands and pacman didnt get recognized since pacman getting installed as part of ridk install 1 3 step and here is the error I am getting. do you have any insights how to get pacman getting installed with ridk install?


Refreshing environment variables from registry for cmd.exe. Please wait...Finished..
Removing intermediate container 6cd200d9fe5c
 ---> ffad5ff80d6e
Step 8/38 : RUN pacman -Syu --debug --noconfirm
 ---> Running in 75dcc19c9d31
**'pacman' is not recognized as an internal or external command,**
operable program or batch file.
The command 'cmd /S /C pacman -Syu --debug --noconfirm' returned a non-zero code: 1

**Comment by ganga1980** [comment]
Hi, @mati865 , here is the complete docker file which was working until last week https://raw.githubusercontent.com/microsoft/Docker-Provider/ci_dev/kubernetes/windows/Dockerfile
On top of this I tried adding pacman commands to sync the db and repos but no luck.

**Comment by mati865** [comment]
@ganga1980 then you should contact with authors of `ridk`.
MSYS2 has to be updated before installing packages.

**Comment by ganga1980** [comment]
> @ganga1980 then you should contact with authors of `ridk`.
> MSYS2 has to be updated before installing packages.

> Hi, @mati865 , changing  msys2 version from 20190524.0.0.20191030 to to 20200903.0.0 resolved the issue. thanks for the pointer.
