### ISSUE TITLE
Curl is being built in debug mode. 

### ISSUE THREAD

**Issue by kd-boss** [msys2/MSYS2-packages#2223]
## Describe the issue
Curl fails in corner cases where it shouldn't in release, however, it informs the user that it's failure is fatal due to it being a debug build. 

A clear and concise description of what the issue is.
error: failed retrieving file 'mingw-w64-x86_64-icu-debug-libs-67.1-1-any.pkg.tar.zst' from sourceforge.net : OpenSSL SSL_read: Connection closed abruptly, errno 0 (Fatal because this is a curl debug build)

## Steps to Reproduce the Problem

1. Run 'pacman'
2. Do something 'install a package with a slow or inconsistent internet connection (such as with a mobile device using WIFI hotspot features).'
3. Describe what happens? 
the package installation fails because curl can't recover from the error due to the build not being in release mode. 

4. What did you expect to happen instead?
The bin utilities that ship with MSYS to be compiled in release mode. 

## Additional Context: Operating System, Screenshots

![image](https://user-images.githubusercontent.com/6182638/97786379-2cb53d00-1b79-11eb-9e4e-87f86b34eb7f.png)

- OS: 
 Windows 10 Pro version 19041 64bit

**Comment by lazka** [comment]
Interesting, thanks

**Comment by kd-boss** [comment]
> Interesting, thanks

You're welcome. I hope this helps and that you have a good day.

**Comment by kd-boss** [comment]
That is awesome!

Thank you, Christopher!
