### ISSUE TITLE
Ruby was not configured properly

### ISSUE THREAD

**Issue by andrew-aladev** [msys2/MSYS2-packages#2232]
## Describe the issue

Hello, I am trying to add windows support for some ruby gems. It will be easy solution to use ruby from msys2 package. Unfortunately ruby was not configured properly.

## Steps to Reproduce the Problem

1. Run `pacman --sync --noconfirm --needed ruby`.
2. Open `/c/tools/msys64/usr/include/ruby-2.7.0/x86_64-msys/ruby/config.h`.
3. Config includes `HAVE_SYS_SELECT_H 1`, `HAVE_SYS_SOCKET_H 1`, etc. As I know mingw have no such sys headers, it looks like this config was created for `cygwin`, not for `mingw`.
4. Gem installation with extension fails `gem install json`: `sys/select.h not found`.

## Additional Context: Operating System, Screenshots

- OS: latest windows 10 virtual machine from [official microsoft website](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).

**Comment by 1480c1** [comment]
you need to use `mingw-w64-x86_64-ruby` package instead of `ruby` since `ruby` is, as you said, configured for cygwin, which is what msys2 is based on

**Comment by andrew-aladev** [comment]
Thank you, I will try this package.
