### ISSUE TITLE
Where is the text editor?????

### ISSUE THREAD

**Issue by cimerio7** [msys2/MSYS2-packages#2244]
## Describe the issue
I tried vi, gedit, everything. I can't believe that eve this tool don't have a default text editor. Where is?
A clear and concise description of what the issue is.

## Steps to Reproduce the Problem

1. Run '...'
2. Do something '....'
3. Describe what happens?
4. What did you expect to happen instead?

## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 Pro version 1909 64bit]
- '...'

**Comment by Biswa96** [comment]
To install,

1. gedit: `pacman -S --needed mingw-w64-x86_64-gedit`
2. vim: `pacman -S --needed vim`
3. nano: `pacman -S --needed nano`

**Comment by cimerio7** [comment]
Thank you,, Biswa.96. I searched for a answer like yours in official site, but I couldn't find. About these editors or even how to install (not update) a new package.

**Comment by Biswa96** [comment]
* If you are not familiar with Pacman package manager you can find command examples here https://wiki.archlinux.org/index.php/Pacman/Rosetta
* You can search packages by their name here https://packages.msys2.org/search

**Comment by lazka** [comment]
I've added 'nano' to the base install in #2262
