### ISSUE TITLE
Issue with pacman -Syu after fresh installation

### ISSUE THREAD

**Issue by metafalls** [msys2/MSYS2-packages#2246]
I fresh installed the latest MSYS2 available on msys2.org and after it is done, every single time I tried
`pacman -Syu`
this result is always as follows:
`error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`error: msys: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`:: Synchronizing package databases...`
`error: failed to update mingw32 (unable to lock database)`
`error: failed to update mingw64 (unable to lock database)`
`error: failed to update msys (unable to lock database)`
`error: failed to synchronize all databases`

Using 
`pacman -Su`
results as follows
`error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`error: msys: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust`
`error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))`
`error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))`
`error: database 'msys' is not valid (invalid or corrupted database (PGP signature))`

Trying to resolve the signature issue with 
`curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz`
`curl -O http://repo.msys2.org/msys/x86_64/msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig`
does not seem to do anything as it results as follows:
![image](https://user-images.githubusercontent.com/15654860/100812952-cde12d00-3470-11eb-9162-fde245933446.png)

**Comment by oscarfv** [comment]
Please see #2058 

Are you installing the 32bit version of MSYS2? It is no longer maintained (although the 32 bit MinGW packages are).

Is this resolves your problem, please close this issue. Thanks.

**Comment by metafalls** [comment]
Pretty sure its the 64 bit. I'll try and see later

**Comment by oscarfv** [comment]
Please show the file name of the installer you used.
