### ISSUE TITLE
AVAST virus reports IDP.ARES.Generic for latest msys64\usr\bin\bash.exe. Please whitelist.

### ISSUE THREAD

**Issue by rfinner** [msys2/MSYS2-packages#2279]
AVAST virus reports IDP.ARES.Generic for latest msys64\usr\bin\bash.exe. Please whitelist

This also occurs for sh.exe

see https://support.avast.com/en-us/article/Threat-Lab-file-whitelist/

**Comment by rfinner** [comment]
AVAST virus reports IDP.ARES.Generic for latest msys64\usr\bin\bash.exe. Please whitelist

see https://support.avast.com/en-us/article/Threat-Lab-file-whitelist/

**Comment by lazka** [comment]
I can't reproduce: https://www.virustotal.com/gui/file/9104d4ac01235e8461eefc7c8048d2d80f5bfc1cb0aa9d572346f446f442a396/detection

**Comment by rfinner** [comment]
I upgraded to paid Avast subscription, uninstalled existing msys2, and downloaded latest release. However, gpg did not seem to like the signature:

 gpg --verify msys2-x86_64-20201109.exe.sig msys2-x86_64-20201109.exe
gpg: Signature made 11/13/2020 10:07:59 AM Pacific Standard Time
gpg:                using RSA key E0AA0F031DBD80FFBA57B06D5A62D0CAB6264964
gpg: Can't check signature: No public key

I am running a fully updated version of Windows 10 Pro.

The original Avast report and quarantine happened when I attempted a pacman -Syuu which I have performed everyday for a year without any issues with bash.exe or sh.exe before.

**Comment by rfinner** [comment]
After re-installing and performing pacman -Syuu I am still having the same issue. Here are some screen shots:

![bash-5-1-update-using-pacman-1](https://user-images.githubusercontent.com/28765091/103159522-5b1d5600-477f-11eb-99a9-28cce2108cda.png)
![bash-5-1-update-using-pacman-2](https://user-images.githubusercontent.com/28765091/103159526-5eb0dd00-477f-11eb-8f3d-34972ba0c26e.png)
![bash-5-1-update-using-pacman-3](https://user-images.githubusercontent.com/28765091/103159529-62446400-477f-11eb-8e44-b55e984c627e.png)

**Comment by rfinner** [comment]
I love msys2. It makes life more bearable when using windows. I hope these issues can be resolved. I could just add exceptions to Avast but since I run pacman -Syuu almost everyday with an elevated command prompt, it is already very scary to trust the security of these updates and bad signatures and overridden Avast warnings concern me very much.

**Comment by lazka** [comment]
> gpg --verify msys2-x86_64-20201109.exe.sig msys2-x86_64-20201109.exe
> gpg: Signature made 11/13/2020 10:07:59 AM Pacific Standard Time
> gpg: using RSA key E0AA0F031DBD80FFBA57B06D5A62D0CAB6264964
> gpg: Can't check signature: No public key

You need to fetch the public key: `gpg --recv E0AA0F031DBD80FFBA57B06D5A62D0CAB6264964`

The avast white listing is only provided to companies, so we can't do anything about it. Feel free to report it to them, maybe you have some leverage as a paying customer.

**Comment by rfinner** [comment]
Great. I am very happy the signature thing was simply my mistake!

I will contact Avast about providing more support for open-source tools and projects.

Thanks!

Closing this issue.
