### ISSUE TITLE
MSYS2 environments + naming

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2289]
### MSYSTEM=MSYS

* filesystem: `/`
* package prefix: ``

### MSYSTEM=MINGW32

* filesystem: `/mingw32`
* package prefix: `mingw-w64-i686-`

### MSYSTEM=MINGW64

* filesystem: `/mingw64`
* package prefix: `mingw-w64-x86_64-`

Potential new ones:

### MSYSTEM=CLANG64

* filesystem: `/clang64`
* package prefix: `mingw-w64-clang-x86_64-`

Less clear potential new ones:

* mingw + x86_64+ gcc + ucrt?
* mingw + arm64 + gcc/clang? + ucrt?

Some patterns that emerge that might be nice to preserve:

* mingw packages start with "mingw-w64-", while msys one don't
* lowercase MSYSTEM matches the filesystem root

**Comment by Biswa96** [comment]
Can't this be in [discussions](https://github.com/msys2/MSYS2-packages/discussions)?
