### ISSUE TITLE
MSYS2 clang va

### ISSUE THREAD

**Issue by easyaspi314** [msys2/MSYS2-packages#2290]
## Describe the issue

A clear and concise description of what the issue is.

## Steps to Reproduce the Problem

1. Run '...'
2. Do something '....'
3. Describe what happens?
4. What did you expect to happen instead?

## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 Pro version 1909 64bit]
- '...'

**Comment by easyaspi314** [comment]
Whoops, pressed enter by mistake. See #2291 for the correct bug report.

**Comment by Biswa96** [comment]
You could just edit it here.

**Comment by easyaspi314** [comment]
I thought I hit esc fast enough for it to not post, so I didn't realize I double posted until after.
