### ISSUE TITLE
Errors trying to install MSYS2 in a Docker container

### ISSUE THREAD

**Issue by tprk77** [msys2/MSYS2-packages#2305]
## Describe the issue

I'm trying to use MSYS2 inside a Docker container. I'm getting some strange error messages followed by what seems to be hang. I have to admit that I'm new to Docker for Windows, so it's possible I've made a mistake somewhere. But I can say that this happens at least on my Windows 10 Pro laptop as well as a fresh Windows Server 2019 Datacenter on Azure.

In particular, these error messages:

```
warning: terminate other MSYS2 programs before proceeding
...
error: no operation specified (use -h for help)
...
error: could not fork a new process (Resource temporarily unavailable)
```

(Also see the full log below.)

If this is not actually a bug, I would really appreciate any help or hints of what might be going wrong.

## Steps to Reproduce the Problem

1. Create a Windows Server 2019 Datacenter on Azure
2. Install Docker
3. Copy my Dockerfile
4. `Get-Content .\Dockerfile | docker build -t test:test -`

## Additional Context: Operating System, Screenshots

Dockerfile, based on: https://www.msys2.org/docs/ci/

```docker
FROM mcr.microsoft.com/windows/servercore:ltsc2019

ARG MSYS2_INSTALLER_URL=https://github.com/msys2/msys2-installer/releases/download/2020-06-29/msys2-base-x86_64-20200629.sfx.exe

RUN curl -L -o C:\msys2.exe %MSYS2_INSTALLER_URL%
RUN C:\msys2.exe -y -o"C:\"

RUN C:\msys64\usr\bin\bash.exe -lc " "
RUN C:\msys64\usr\bin\bash.exe -lc "pacman -Syuu --noconfirm"
RUN C:\msys64\usr\bin\bash.exe -lc "pacman -Syuu --noconfirm"

ENV MSYSTEM=MINGW64

RUN C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-git"
# Install more stuff, etc

CMD ["C:\msys64\usr\bin\bash.exe", "-l"]
```

Log of the result:

```text
PS C:\Users\tim> Get-Content .\Dockerfile | docker build -t test:test -
Sending build context to Docker daemon   2.56kB
Step 1/12 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> c0773f9ce353
Step 2/12 : ARG MSYS2_INSTALLER_URL=https://github.com/msys2/msys2-installer/releases/download/2020-06-29/msys2-base-x86_64-20200629.sfx.exe
 ---> Using cache
 ---> ceb6d36de603
Step 3/12 : RUN curl -L -o C:\msys2.exe %MSYS2_INSTALLER_URL%
 ---> Using cache
 ---> 656c16c66cf1
Step 4/12 : RUN C:\msys2.exe -y -o"C:\"
 ---> Using cache
 ---> d88d9078b69d
Step 5/12 : RUN C:\msys64\usr\bin\bash.exe -lc " "
 ---> Using cache
 ---> e39e2c722cba
Step 6/12 : RUN C:\msys64\usr\bin\bash.exe -lc "pacman -Syuu --noconfirm"
 ---> Running in 310c7b0c8e08
:: Synchronizing package databases...
downloading mingw32.db...
downloading mingw32.db.sig...
downloading mingw64.db...
downloading mingw64.db.sig...
downloading msys.db...
downloading msys.db.sig...
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (6) bash-5.1.004-1  filesystem-2021.01-1  mintty-1~3.4.4-1  msys2-runtime-3.1.7-4  pacman-5.2.2-9  pacman-mirrors-20201208-1

Total Download Size:   11.05 MiB
Total Installed Size:  53.92 MiB
Net Upgrade Size:      -0.32 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
downloading bash-5.1.004-1-x86_64.pkg.tar.zst...
downloading filesystem-2021.01-1-x86_64.pkg.tar.zst...
downloading mintty-1~3.4.4-1-x86_64.pkg.tar.zst...
downloading msys2-runtime-3.1.7-4-x86_64.pkg.tar.xz...
downloading pacman-mirrors-20201208-1-any.pkg.tar.xz...
downloading pacman-5.2.2-9-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
checking for file conflicts...
checking available disk space...
:: Processing package changes...
upgrading bash...
upgrading filesystem...
upgrading mintty...
upgrading msys2-runtime...
upgrading pacman-mirrors...
upgrading pacman...
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
      0 [main] pacman (2776) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (3852) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (3912) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (6748) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (6844) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (2532) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (1412) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (7052) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (3316) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (6408) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (3880) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (2572) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (5468) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (4500) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (5876) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (1768) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (2328) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (6692) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (6788) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (544) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (5932) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (5328) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (5316) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (1836) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (7152) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (6424) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (4976) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (4324) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (2304) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      1 [main] pacman (124) shared_info::initialize: size of shared memory region changed from 49080 to 51128
      0 [main] pacman (2932) shared_info::initialize: size of shared memory region changed from 49080 to 51128
error: no operation specified (use -h for help)
      0 [main] pacman 553 dofork: child -1 - forked process 2776 died unexpectedly, retry 0, exit code 0x1, errno 11
error: could not fork a new process (Resource temporarily unavailable)
:: To complete this update all MSYS2 processes including this terminal will be closed. Confirm to proceed [Y/n]
```

Note that the last line is a prompt, but I think it's an actual hang and not just waiting on the prompt because of the use of `--noconfirm` above. I'm also very confused by the `warning: terminate other MSYS2 programs before proceeding` because nothing else should be running at that point.

**Comment by mingwandroid** [comment]
Is MSYS2 being used in a Windows Service perhaps? E.g. sshd?

**Comment by tprk77** [comment]
I don't think so. I am using RDP with the Azure instance, but I'm also getting the same problem when trying this on my physical Windows 10 Pro laptop, where these is no remote connection at all.

**Comment by tprk77** [comment]
Another detail to add: The problem only seems to occur with `docker build`. If I instead use `docker run -it` and execute the exact same commands in the console, they succeed as expected. I wonder if it has something to do with the lack of an interactive TTY? Or maybe there's a bad interaction between the MSYS2 update and Docker creating a new image layer during the build?

**Comment by 1480c1** [comment]
As a very small side note, I have gotten msys2 to be installed and work inside a windows servercore container on both an was windows instance and also my personal laptop, https://gitlab.com/AOMediaCodec/aom-testing/-/blob/master/docker-images/Dockerfile.core1809, however, I used 1809 due to kernel limitations on the self-hosted machine hooked up to gitlab and I added some additional stuff to the environment variables, you could try seeing if that, minus the MSVC related stuff works on your system

**Comment by tprk77** [comment]
Yeah, I'm beginning to think this is a Docker for Windows problem. I have found other people reporting a similar issue: apparently Docker gets hung in exporting layers because it can't remove directories like `C:\ProgramData\docker\tmp\hcs080992587`. I'm looking into a workaround, I'll post an update in a bit.

**Comment by tprk77** [comment]
Ok, so Docker for Windows apparently has some major issues, which is disappointing. Had I known this process would be so painful, I probably would have avoided it entirely. But I might also be a bit biased because I just wasted two days figuring this out.

See also:
- https://github.com/microsoft/hcsshim/issues/696
- https://github.com/docker/for-win/issues/5193

This is definitely not a MSYS2 problem. It's apparently a kind of race condition, seeming triggered by having a layer with many files. It might just happen to be that an MSYS2 update may trigger it more often than not. So anyway, I will document what I did for anyone searching for a similar issue. But be warned, it's a massive hack.

1. Modify your Dockerfile to put a sentinel at the end of each problematic command. For example, I used `&& echo DONE -- %DATE% %TIME%`, this is essential because you will need to know when the command is finished, and when Docker is hung.
2. Download `docker-ci-zap` from here: https://github.com/moby/docker-ci-zap
3. Open `C:\ProgramData\docker\tmp` in Explorer, so you can keep an eye on it.
4. Open a console and run `docker build` like you normally would.
5. Open another console, and get ready to run `docker-ci-zap`. You can't run this command too early, or the build will fail.
6. When the `RUN` has completed, but nothing is happening, look at `C:\ProgramData\docker\tmp`. On my machine, I would usually see two folders, e.g., `hcs080992587` and `hcs258708099`. One of these folder would usually disappear after a minute or two. I had the most success waiting for that to happen, then proceeding.
7. Run `docker-ci-zap` on the remaining folder, e.g.: 
```
.\docker-ci-zap -folder C:\ProgramData\docker\tmp\hcs258708099
```
8. Wait a minute or two, the build should resume.
9. Repeat for each layer as necessary. :sob:

I think it also helped to minimize the number of files. In particular, I deleted `C:\msys64\var\cache` after each invocation of `pacman` and that seemed to help. YMMV.

**Comment by Biswa96** [comment]
> I deleted C:\msys64\var\cache after each invocation of pacman and that seemed to help.

`yes | pacman -Scc` ([manual][1])

[1]: https://archlinux.org/pacman/pacman.8.html

**Comment by 1480c1** [comment]
> > I deleted C:\msys64\var\cache after each invocation of pacman and that seemed to help.
> 
> `yes | pacman -Scc` ([manual](https://archlinux.org/pacman/pacman.8.html))

I think `pacman -Scc --noconfirm` is enough, no need to pipe yes to it

**Comment by Biswa96** [comment]
> I think pacman -Scc --noconfirm is enough, no need to pipe yes to it

It works in msys2 but not in ArchLinux. Technically, `--noconfirm` does not mean "always yes". It "Bypass any and all “Are you sure?” messages." ([manual][1]). The pacman package in msys2 is patched to be "always yes", see this [patch][2] file.

[1]: https://archlinux.org/pacman/pacman.8.html
[2]: https://github.com/msys2/MSYS2-packages/blob/master/pacman/0008-answer-yes-by-default.patch

**Comment by mati865** [comment]
Windows containers are still in pretty bad shape, rustup (toolchain manager for Rust) doesn't work properly there even though it's normal Win32 binary built with MSVC toolchain...
