### ISSUE TITLE
Unable to install tools and/or packages

### ISSUE THREAD

**Issue by bastiro03** [msys2/MSYS2-packages#2341]
## Summary
When trying to install a package, the following error occurs.

## Steps to Reproduce
1. Run 'MSYS2 MSYS'
2. Install python (example) with "pacman -S make git python"

## Expected results:
The corresponding package will be installed.

## Actual results:
This error message is shown, and the install fails:
error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: msys: signature from "David Macek <david.macek.0@gmail.com>" is marginal trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))

**Comment by elieux** [comment]
These instruction should help you: https://www.msys2.org/news/#2020-06-29-new-packagers
