### ISSUE TITLE
`fish` creates a NUL file after any file I/O operation

### ISSUE THREAD

**Issue by BasixKOR** [msys2/MSYS2-packages#2347]
## Describe the issue
If any file has been touched by fish (such as rm), fish creates NUL file with empty content on the working directory.

## Steps to Reproduce the Problem

1. Run 'fish' (you may see a NUL file already in this step)
2. `touch` and `rm` a file.
3. Describe what happens?
  * fish creates a NUL file on the working directory.
4. What did you expect to happen instead?
  * Not creating a such file.

## Additional Context: Operating System, Screenshots

![image](https://user-images.githubusercontent.com/7413880/108610377-27e8f300-73cd-11eb-8fad-c294db6d15eb.png)

I discovered this behaviour using Process Monitor by Sysinternals.

- OS: Windows 10 Pro 20H2 (build 19042.631)

**Comment by elieux** [comment]
I cannot reproduce. Package version 3.1.2-1. Windows version 10.0.19042.804. I haven't ever used Fish before.

Is it possible it has something to do with your profile?

**Comment by BasixKOR** [comment]
Thank you for looking into this issue. As you said after disabling zoxide it doesn't happen. Closing this issue!
