### ISSUE TITLE
Converting mingw paths to windows paths

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [msys2/MSYS2-packages#2352]
## Describe the issue
Can we have a tool for converting mingw and msys paths to windows style paths (similar to wslpath)?
Benefits: can be used by build tools for converting a mingw path to windows path.

For example, convert /mingw64/bin to C:\msys64\mingw64\bin

**Comment by naveen521kk** [comment]
There is `cygpath`
use `cygpath --help` to see it's help.

**Comment by Biswa96** [comment]
Technically + Historically, the wslpath idea came from cygpath. When WSL was first born, there was no wslpath.

**Comment by jmoguillansky-gpsw** [comment]
thanks
