### ISSUE TITLE
Cannot upgrade old msys2 because all packages are in zstd format

### ISSUE THREAD

**Issue by gabrielschulhof** [msys2/MSYS2-packages#2353]
Hey, all!

I'm trying to

```
pacman -Syuu
```

to update everything, but I'm finding myself in a chicken-and-egg scenario where I cannot upgrade because all packages are in zst format, and so is the zstd package. Is there an old version of the zstd package that's stored in a format that old pacman can recognize?

**Comment by mingwandroid** [comment]
Can you try to follow the instructions at: https://www.msys2.org/wiki/MSYS2-reinstallation/

**Comment by intvsteve** [comment]
Unfortunately I started following instructions [here](https://www.msys2.org/news/). Now I get this:
>$ pacman

That's it. Zero. Nada. Nothing. No output whatsoever. The last entries in the log are from these steps:
> pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/libzstd-1.4.4-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/zstd-1.4.4-2-x86_64.pkg.tar.xz"
pacman --noconfirm -U "http://repo.msys2.org/msys/x86_64/pacman-5.2.1-6-x86_64.pkg.tar.xz"

I know that I'd done some of the later steps listed on the News page already in order to get the keys / trust issues resolved.

**Comment by mmottaghi** [comment]
Simply replace the existing msys2 installation with a new archive:

1. Lets assume your current msys2 installation folder is `c:\msys64`
2. Rename `c:\msys64` to `c:\msys64-old`
2. Download http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20210228.tar.xz and call it _newm.tar.xz_
3. Unzip _newm.tar.xz_ at `c:\msys64`
4. Run `c:\msys64\msys2_shell.cmd -defterm -no-start -use-full-path -c "echo make: `which make`"`

**Comment by intvsteve** [comment]
Thanks, @mmottaghi - but I must be missing something. Does this imply that I must rediscover (manually) and reinstall all the packages and rebuild my entire msys2 environment? My goal was to not start over from scratch if possible.

**Comment by mmottaghi** [comment]
You can automatically reinstall all your existing packages. 
1. Obtain a list of your current packages `pacman -Qqe | xargs echo > /c/packages.txt ; exit`
2. Reinstall msys2 (follow the 5 steps that I listed above).
3. Use the list in step 1 to automatically re-install all the packages you had before: `pacman -S --needed $(cat /c/packages.txt)`

**Comment by intvsteve** [comment]
Therein lies the problem. In the old install, `pacman -Que` produces _no output of any kind_. In the new install, it only shows `bash`.

**Comment by Biswa96** [comment]
All the problems have been fixed. Feel free to reopen the issue if needed.
