### ISSUE TITLE
[procps]

### ISSUE THREAD

**Issue by AlastairGrowcott** [msys2/MSYS2-packages#2376]
'pidof' has disappeared from this package.

My MSys install blew itself up completely this morning after I tried to update the keys. I installed from scratch and "pidof" is nowhere to be seen. Looking at my old installation, it used to be part of this package. When I invoked the binary from my new shell I get:

C:/msys64/usr/bin/pidof.exe: error while loading shared libraries: msys-procps-7.dll: cannot open shared object file: No such file or directory

**Comment by cbrt64** [comment]
Sorry to answer this so late.

The `procps` package is really old, and never included pidof; you must have had `procps-ng` installed previously, which does have pidof.exe as well as msys-procps-*.dll. Keep in mind, these two packages are mutually exclusive.

For future reference: `pacman -Fx /usr/bin/command` is a quick way to find which package owns `command`, whether it be .exe or script (`pacman -Fy` first to populate the package file list databases).

**Comment by AlastairGrowcott** [comment]
Thanks for the information. I wish there was a better way to search packages and then I could have saved you some time.

**Comment by Biswa96** [comment]
You can search for packages here https://packages.msys2.org/search

**Comment by AlastairGrowcott** [comment]
I did. Searching for "pidof" in both base packages and packages returns zero results.
