### ISSUE TITLE
binutils: `windres` no longer accepts `gcc -E ...` as `--preprocessor` argument

### ISSUE THREAD

**Issue by dscho** [msys2/MSYS2-packages#2379]
## Describe the issue

It seems that `windres` accepted `--preprocessor 'gcc -E -xc -DRC_INVOKED -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG'`, but it no longer does: https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=72588&view=logs&j=37cf11af-77b8-5c27-8799-06c003698f4e&t=1bd7294c-f7d3-59f4-5adf-18c9754f1b0e&l=171

## Steps to Reproduce the Problem

1. Run this:
   ```shell-session
   $ >example.rc

   $ windres --preprocessor 'gcc -E -xc -DRC_INVOKED -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG' example.rc example.o
   /bin/sh: gcc -E -xc -DRC_INVOKED -MMD -MP -DTARGET=x86_64-pc-msys -DNDEBUG: command not found
   windres: preprocessing failed.
   ```

## Additional Context: Operating System, Screenshots

This happened while I tried to build MinTTY v3.4.7, which used that `windres` invocation for ages, but it now fails. So it must have been caused by one of the recent updates to `binutils`.

**Comment by mintty** [comment]
What does that patch actually do? It's not included in the commit.

**Comment by lazka** [comment]
I had to backport some things for mingw: https://github.com/msys2/MINGW-packages/pull/7870 maybe the same issue?

**Comment by lazka** [comment]
> What does that patch actually do? It's not included in the commit.

here is the fixup commit: https://github.com/git-for-windows/MSYS2-packages/commit/4d84177e30dec51a5e637899bbb8564b5a035a61

**Comment by mintty** [comment]
I can reproduce the (unpachted) issue after updating MSYS2 but it still works in cygwin. Isn't MSYS2 cloning the package releases from cygwin? Any background information?

**Comment by lazka** [comment]
cygwin is still on binutils 2.35.

The only relevant patch seems to be https://github.com/bminor/binutils-gdb/commit/21c33bcbe36377abf01614fb1b9be439a3b6de20

**Comment by mintty** [comment]
Thanks; I sent a notice to the patch author that it breaks build processes.

**Comment by nickclifton** [comment]
Hi Guys,

  Is there any chance that you could file a bug report about this problem here:

https://sourceware.org/bugzilla/enter_bug.cgi?product=binutils

  The change came about because of another bug report which pointed out that the 
  --preprocessor option did not handle paths that contained spaces:

https://sourceware.org/bugzilla/show_bug.cgi?id=4356

  I am not sure how to solve this problem however.  Consider the following invocation:

     windres --preprocessor 'c:\Program Files\gcc -E -Ic:\Path With Spaces\include -Dfoo'

  When this command line is broken up into a program name and its arguments, the spaces
  in the paths need to be preserved, but the spaces between the arguments must be removed... 
  Any suggestions for how windres can determine which spaces to save and which to remove ?
     
  Note - as a workaround for the current behaviour you could use the --preprocessor-arg option, as in:
    --preprocessor gcc \
    --preprocessor-arg -E \
    --processor-arg -xc \
    -DRC_INVOKED \
    --processor-arg -MMD \
    --preprocess-arg -MP \
    -DTARGET=x86_64-pc-msys \
    -DNDEBUG

Cheers
  Nick Clifton

**Comment by mintty** [comment]
Submitted https://sourceware.org/bugzilla/show_bug.cgi?id=27594
with the following proposal:

My suggestion is to apply some obvious magic to option --preprocessor; 
everything following a space-separated dash, like " -" in "path to gcc -x -y", should be used as a set of arguments as before, so confining the new space-in-pathname support to the actual command.

**Comment by dscho** [comment]
@nickclifton The common way to address this is to require the path with spaces to be quoted. Something like this:

```
 windres --preprocessor '"c:\\Program Files\\gcc" -E "-Ic:\Path With Spaces\include" -Dfoo'
```

> My suggestion is to apply some obvious magic to option --preprocessor;

That's not really "magic", it's hacky, and prone to cause more problems by virtue of violating the law of least surprise.

**Comment by mintty** [comment]
I agree with this proposal, would you add it to the issue I submitted them?
Either way, it's a regression for those who don't use spaces in the program path, and those who need that should be the ones required to do something.

**Comment by dscho** [comment]
> would you add it to the issue I submitted them

[Done](https://sourceware.org/bugzilla/show_bug.cgi?id=27594#c1).

**Comment by lazka** [comment]
Revert here: #2384 but I haven't tested it

**Comment by mintty** [comment]
Q: Which MSYS2 package contains windres?

**Comment by mati865** [comment]
It's [binutils](https://packages.msys2.org/package/binutils?repo=msys&variant=x86_64).

**Comment by mintty** [comment]
@dscho, are you following the discussion in the binutils issue? Maybe you can help arguing against that guy who's keeping to ask for an incompatible change.

**Comment by mintty** [comment]
The mintty 3.5.1 Makefile now has a workaround, so the MSYS2 patch can be removed.

**Comment by lazka** [comment]
thanks for the upate

**Comment by 2nil-web** [comment]
As of 2025-01-04 this bug/misbehaviour reappear to me.
The workaround to it seems to add the option '--use-temp-file' in my windres command ...
