### ISSUE TITLE
autoconf to recent for some packages

### ISSUE THREAD

**Issue by revelator** [msys2/MSYS2-packages#2382]
2.71 breaks several packages that expect exactly version 2.69 is there a possibility to downgrade ? or create wrappers for older versions

**Comment by Biswa96** [comment]
Any example of those packages? Chaging the version number in configure.ac may fix the issue. For example, recently mingw-w64 did this https://sourceforge.net/p/mingw-w64/mingw-w64/ci/8d3d95f7e286a4e46c13f82643c28b85c48755c1/

**Comment by lazka** [comment]
Arch is also using 2.71, so I expect all those upstreams to be fixed sooner or later

**Comment by revelator** [comment]
we can hope but untill then it leaves a lot of broken packages that need patching.

**Comment by revelator** [comment]
downgraded from cache for the time being untill this gets sorted upstream

**Comment by revelator** [comment]
old mingw.org suite had an autotools wrapper which allowed choosing which version was needed, while the older versions may contain some nasty stuff at times it allows us the use of some packages which may no longer be maintained but which are still usefull. 

If there is interrest ill see if i can magic up a PKGBUILD for the autotools wrapper from mingw.org, the wrapper can use any version of autotools so it might be handy.

**Comment by Biswa96** [comment]
Which project does have that issue?

**Comment by revelator** [comment]
several off the bat adns is one and btw this package needs to have its url updated the old git link in this package has been moved here https://github.com/gpg/adns.git the specific commit the package is looking for is also still availiable at the new address.

If you are not to keen on having the autotool wrappers added to msys2 it can be installed as an optional package in /opt atleast thats the way it was in the old msys.

**Comment by Biswa96** [comment]
The development of gpg/adns project seems to be halted 5 years ago. So, it's upstream fault not to update/fix issues. Speaking of git link, ArchLinux uses the same upstream link for adns as in mingw-w64-adns package.

**Comment by Biswa96** [comment]
The development of gpg/adns project seems to be halted 5 years ago. So, it's upstream fault not to update/fix issues. Speaking of git link, ArchLinux uses the chiark.greenend.org.uk link for source tarball with autoconf.

**Comment by piotrvv** [comment]
![Zrzut ekranu 2021-03-18 184450](https://user-images.githubusercontent.com/38948025/111672316-21a63500-881a-11eb-8846-5c830f817d57.png)
![Zrzut ekranu 2021-03-18 184350](https://user-images.githubusercontent.com/38948025/111672321-24088f00-881a-11eb-8a41-f377b42dc8ef.png)
How about first this way?

**Comment by Biswa96** [comment]
Apology, I did not understand your question/request? What is "this way"? Packages are always updated before building in CI.

**Comment by piotrvv** [comment]
This was built by my server. I did not build any of the packages shown, but many of your packages are missing dependencies. Because they lack a certain idea of ​​how to detect and parse each other. tcl tk is my biggest problem because it has a lot of deficiencies.

**Comment by revelator** [comment]
looks like the package is no longer needed as a dependency, will be removed from repo.
