### ISSUE TITLE
Missing ucrt64 console title & icon setting

### ISSUE THREAD

**Issue by kmilos** [msys2/MSYS2-packages#2406]
Please add console title and icon setting for UCRT as well:

https://github.com/msys2/MSYS2-packages/blob/a18fd79e5f60e3f2a285604d9700f204e41a911a/filesystem/msys2_shell.cmd#L104

Also, ucrt64.ico (and clang64.ico) are missing, so either ship them w/ filesystem, or remove all *.ico and rely on embedded icons in *.exe shipped by msys2-launcher?

**Comment by lazka** [comment]
thanks, yes, this is all work in progress at the moment

**Comment by kmilos** [comment]
Sure, good to know. It seems there is some disconnect between filesystem, installer, and launcher when it comes these shortcuts...
