### ISSUE TITLE
Console does not launch after upgrade. Launcher error:  C. Reason T (0x2)

### ISSUE THREAD

**Issue by askondro** [msys2/MSYS2-packages#2407]
## Describe the issue

The last update of mintty and other components caused an issue.
After launching mingw64.exe I get the "Error message C. Reason T (0x2)" message and the console window does not open.

## Steps to Reproduce the Problem

1. After upgrade
2. Run mingw64.exe
3. Error message C. Reason T (0x2)
4. Error message T. Reason C (0x0)

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Pro 19042.870 x86_64

**Comment by fabiangreffrath** [comment]
Same here. Running `usr/bin/mintty.exe` works to some extend.

**Comment by askondro** [comment]
msys2_shell.cmd also works in a limited way. But is not usable for mingw64.

**Comment by Biswa96** [comment]
There is a pull request to fix this issue. Meanwhile MINGW64 can be launched from Command Prompt with this command `C:\msys64\msys2_shell.cmd -defterm -no-start -mingw64`.

**Comment by podsvirov** [comment]
Confirm. Windows 7 SP1 64bit.
![msys2-launcher-1 2-1-error-1](https://user-images.githubusercontent.com/8400779/112517291-3306b880-8da9-11eb-8e78-0c90b0deceba.png)
![msys2-launcher-1 2-1-error-2](https://user-images.githubusercontent.com/8400779/112517302-369a3f80-8da9-11eb-8849-36b83ce63ca0.png)
Quick fix - downgrade the msys2-launcer package. If a package was installed at an earlier stage, and the pacman cache was not cleaned, install an earlier version from /var/cache/pacman/pkg/. For example type in cmd:
C:\msys64\usr\bin\pacman.exe -U "C:\msys64\var\cache\pacman\pkg\msys2-launcher-1.0-1-x86_64.pkg.tar.zst"
Otherwrice, download http://repo.msys2.org/msys/x86_64/msys2-launcher-1.0-1-x86_64.pkg.tar.zst firs.

**Comment by lazka** [comment]
hm, I've downgraded for now

**Comment by lazka** [comment]
I pushed a new version. Does it work better?

**Comment by podsvirov** [comment]
The consoles from the `msys2-launcher-1.3-1` package are launched. Errors don't pop up.

**Comment by lazka** [comment]
Thanks.

For some reason it worked fine with ucrt which I happened to build with when testing.

Sorry for the breakage.
