### ISSUE TITLE
[bash]

### ISSUE THREAD

**Issue by crus-thenry** [msys2/MSYS2-packages#2409]
10# syntax does not appear to work.

--> 10#: invalid integer constant (error token is "10#")

**Comment by lazka** [comment]
hm?

**Comment by crus-thenry** [comment]
for sym in "${common[@]}"
    do
        # turn octal-y numbers like 000123 into decimal by stripping the leading 0's
        # for whatever reason, nm prints decimal numbers with leading zeros...
        sz0="$((10#${elf0_symsz[$sym]}))"
        sz1="$((10#${elf1_symsz[$sym]}))"
        echo "$sz0" "$sz1" $(( $sz0 - $sz1 )) "$sym"  >> scrap1.edl
    done

--> line 130: 10#: invalid integer constant (error token is "10#")

Works in bash-4.x, apparently does not work in 5.1

**Comment by 1480c1** [comment]
Question, what is the `#` supposed to do there? I'm not aware of any usage of it that is valid in posix shell arithmetic expansion, c operators, or any bashisms

I see that in both ubuntu and msys2, `$((10#10))` returns 10 and `$((2#10))` returns 2 so it seems to me that it returns the lower of the two arguments

**Comment by crus-thenry** [comment]
I am trying to convert octal to decimal before doing arithmetic.
For example, searching “bash convert octal to decimal”
https://serviceitdirect.com/hex-octal-and-binary-shell-conversions
https://stackoverflow.com/questions/48526711/convert-octal-to-decimal-in-bash
etc

I know that I can do this with bc.
But this syntax is working in bash-4.1.0 (on MacOSX fwiw)

**Comment by lazka** [comment]
ok, so a reproducer is `echo "$((10#))"`. But I get the same error with bash 5.1 on Arch linux, so I'd say not a MSYS2 issue.

**Comment by lazka** [comment]
so maybe bash is stricter now and requires a number after '#' and before it defaulted to '0'.

**Comment by crus-thenry** [comment]
sz0="$((10#0${elf0_symsz[$sym]}))"
added------^

seems to work.
so ... not a bug, just a bash change i didn't know about ...
my mistake
thanks for the help.
i think this can be closed.

**Comment by lazka** [comment]
ok :+1:
