### ISSUE TITLE
[binutils] unrecognized option '--hash-style=gnu'

### ISSUE THREAD

**Issue by mahaase** [msys2/MSYS2-packages#2411]
is there any reason, why this linker option isn't supported?

**Comment by Biswa96** [comment]
Please provide steps or minimal code sample to reproduce your issue.

**Comment by mahaase** [comment]
just providing the linkerflag by LDFLAGS, e.g.:

`export LDFLAGS="-Wl,-O1 -Wl,--hash-style=gnu"`

**Comment by mingwandroid** [comment]
https://stackoverflow.com/a/42069534

Because it's an elf thing and not a PECOFF thing?

**Comment by mahaase** [comment]
okay thanks, so this is not supported by msys toolchain at all?!

**Comment by mingwandroid** [comment]
It is totally meaningless to support different hash styles for a format without any support for hash tables!

**Comment by mingwandroid** [comment]
Why do you want this? It cannot do what you think it does (on Windows)

**Comment by mahaase** [comment]
okay, i understand! i am working in an environment, where this is set by default. so i have to force to fix this environment. thanks for help!!
