### ISSUE TITLE
CMake: A suggestion for minimizing the support patch

### ISSUE THREAD

**Issue by orgads** [msys2/MSYS2-packages#2419]
The CMake package contains a [very large patch file](https://github.com/msys2/MSYS2-packages/blob/master/cmake/0001-Support-MSYS.patch) for supporting MSYS runtime environment.

I have a suggestion for minimizing this patch. The approach is similar to what is done on gcc.

I started an attempt to [upstream this patch](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5933), but since it is so large, I was asked to split it. When I reviewed the patch content, I've noticed that most of it can be removed.

The current patch defines `MSYS` only. Then, on each `CYGWIN` condition you have to add `MSYS` as well.

On gcc, the compiler defines *both* `__CYGWIN__` and `__MSYS__` macros. This way, existing code with `__CYGWIN__` conditionals works out of the box, and MSYS-specific code can use `__MSYS__`.

I suggest to do the same for CMake - define *both* `CYGWIN` and `MSYS`, then leave almost all the existing conditions untouched.

Pros:
* Easy to maintain
* Should be fairly easy to upstream
* New conditions in CMake will just work, without the need to adjust them
* The only important difference I found between these platforms are in `MSYS.cmake` itself - library prefix (`cyg` vs `msys-`)

Cons:
* Need to carefully review each existing condition, and see if it requires special handling for MSYS.
* Might break existing packages in msys2, if for example they have something like:
```cmake
if(CYGWIN)
# ...
elseif(MSYS)
# ...
endif()
```

What do you think?

**Comment by lazka** [comment]
Sounds good to me

**Comment by 1480c1** [comment]
Personally, the only thing I can see that might really break is the usage of `/mnt/c` instead of `/c` and visa versa and maybe stuff like x11 where cygwin might provide it but we don't

**Comment by lazka** [comment]
I patched meson similarly in that if pretends to be cygwin for the buildscript but produces msys builds.

**Comment by orgads** [comment]
Does any of you know why response files are disabled on both MSYS and MinGW?

**Comment by jeremyd2019** [comment]
clang/llvm doesn't support them

**Comment by 1480c1** [comment]
depends on the command, I think gcc has support built-in from libiberty ( I think this is the one), if it's any other ones based on cygwin style stuff, I think they only support it if running from cmd.exe

**Comment by lazka** [comment]
hm, it's there from the start.. I could see response files breaking automatic path conversion for mingw builds, but not sure.

**Comment by orgads** [comment]
I've been using response files with qmake/mingw for a decade, and never had any problems with it.

**Comment by 1480c1** [comment]
I think that's usually because gcc handles the response files or qmake uses a non-bash terminal to run the commands

**Comment by mingwandroid** [comment]
Back in the early days I think we found it far harder to debug build failures when they were used and kind of got sick of them!

We should not do that though.

**Comment by orgads** [comment]
Ah, maybe path conversions won't work if the paths are in a response file. The conversion is done by the terminal/runtime when executing the command, right?

**Comment by orgads** [comment]
I mean the translation of `/c/foo/bar` -> `c:\foo\bar`.

**Comment by 1480c1** [comment]
Surprisingly, seems the answer is no
temp.txt
```none
-l
/mingw64
```
in powershell
```powershell
ls.exe '@temp.txt'
total 2064
-rwxr-xr-x 1 cddeg cddeg 1664313 Feb  3  2020 a.exe
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:48 bin
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:47 etc
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:48 include
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:48 lib
drwxr-xr-x 1 cddeg cddeg       0 Oct  9  2019 libexec
drwxr-xr-x 1 cddeg cddeg       0 Feb  8  2020 qt5-static
drwxr-xr-x 1 cddeg cddeg       0 Feb  2 20:30 sbin
-rw-r--r-- 1 cddeg cddeg     769 Jan  2 08:01 setup_vars_opencv4.cmd
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:47 share
drwxr-xr-x 1 cddeg cddeg       0 Mar 26 16:47 ssl
-rw-r--r-- 1 cddeg cddeg     288 Feb  3  2020 temp.c
-rw-r--r-- 1 cddeg cddeg    1179 Feb  3  2020 temp.o
drwxr-xr-x 1 cddeg cddeg       0 Jul  2  2019 var
drwxr-xr-x 1 cddeg cddeg       0 Jun 29  2019 x86_64-w64-mingw32
```

**Comment by lazka** [comment]
but ls.exe is cygwin

**Comment by 1480c1** [comment]
> but ls.exe is cygwin

This example was specifically for the `The conversion is done by the terminal/runtime when executing the command, right` showing that the conversion for some commands isn't handled by the terminal, unless he means runtime as in the binary itself

**Comment by orgads** [comment]
From my experiments, it looks like MinGW apps don't translate paths in response file, but MSYS executables do (at least g++):

```
C:\Temp>set PATH=%PATH%;C:\msys64\usr\bin

C:\Temp>g++.exe @test.rsp
C:\Temp>set PATH=C:\msys64\mingw64\bin;%PATH%

C:\Temp>g++.exe @test.rsp
g++.exe: error: /c/Temp/test.cpp: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
```

Then maybe we should disable it only for MinGW?

**Comment by 1480c1** [comment]
Yeah, that's probably appropriate as it's best to treat binaries inside /mingw64/bin as close to native windows binaries as possible, (meaning no cygwin/unix paths)

**Comment by orgads** [comment]
Ok, so #2422 is ready for review then.

**Comment by orgads** [comment]
MSYS clang accepts MSYS-style paths in the response file, while MinGW clang doesn't. It's the same as GCC.

**Comment by mingwandroid** [comment]
❤

**Comment by orgads** [comment]
Quick update: Support has landed upstream. The patch can be dropped on next major release of cmake. Many thanks to Brad King for his assistance and patience.

**Comment by lazka** [comment]
Thanks!

I've also started to clean up some of our patches based on it:

* https://github.com/msys2/MSYS2-packages/pull/2465
* https://github.com/msys2/MSYS2-packages/pull/2468
