### ISSUE TITLE
NCDU not working in common drives

### ISSUE THREAD

**Issue by rashil2000** [msys2/MSYS2-packages#2428]
## Describe the issue

NCDU does not work in directories like `/c`, `/d`, or even `$HOME` (which is `/c/Users/<username>`).

## Steps to Reproduce the Problem

1. `pacman -S ncdu`
2. `ncdu ~`
3. **Error obtaining full path: No such file or directory**
4. Expected: It should show the correct disk usage.

## Additional Context: Operating System, Screenshots

- OS: `uname -a` = _MSYS_NT-10.0-19042 Omen-15 3.1.7-340.x86_64 2021-03-26 22:17 UTC x86_64 Msys_
- ![image](https://user-images.githubusercontent.com/46838874/114128825-e4196100-991a-11eb-9a69-52bf6be212f4.png)

**Comment by Biswa96** [comment]
Is this issue solved? Pease share your solution.

**Comment by rashil2000** [comment]
I updated the packages 'bash' and 'filesystem', they were very outdated (you can see in the kernel info above)
