### ISSUE TITLE
[pacman] Remove SigLevel=DatabaseOptional

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2453]
We copied this (I guess) from Arch Linux which doesn't sign databases.

But we do sign them, so we shouldn't allow DBs without a signature.

In theory this (as it is now) would allow a mirror/server attacker to modify the DB to provide old packages without security fixes (the package signatures still have to work out..)

open question: Do we need to adjust the staging repo example docs if we change this?

**Comment by Biswa96** [comment]
Where are the file databases built?

**Comment by lazka** [comment]
here: https://github.com/msys2/msys2-devtools/blob/d24def76b8fe2a21c5b6c1a105408daed1adfb25/msys2-dbadd#L35 (executed on the server by the maintainers)

Or do you mean something different?

**Comment by lazka** [comment]
One small thing I noticed is that `pacman -F` will fail with this until you run `pacman -Fy` again.

```
pacman -F
error: mingw32: missing required signature
error: mingw64: missing required signature
error: ucrt64: missing required signature
error: msys: missing required signature
```

Minor, but kinda unexpected.

**Comment by Biswa96** [comment]
I still see those missing signature errors. Are those signature not added in pacman repo?

**Comment by lazka** [comment]
For which command? All signatures should be there.

**Comment by Biswa96** [comment]
If I do `pacman -Scc` then `pacman -Fyy` the error is shown.

**Comment by lazka** [comment]
ok, thanks, I'll try later.

**Comment by lazka** [comment]
For some reason `pacman -Scc` removes all `/var/lib/pacman/sync/*.files.sig` files

**Comment by lazka** [comment]
fixed upstream, needs a backport

**Comment by lazka** [comment]
-> #2470
