### ISSUE TITLE
sshpass: Failed to set controlling terminal in child (TIOCSCTTY): Invalid argument

### ISSUE THREAD

**Issue by shenlijun** [msys2/MSYS2-packages#2458]
This error occurred with latest update

**Comment by lazka** [comment]
When does this error happen?

**Comment by shenlijun** [comment]
> When does this error happen?

Normal use like:
sshpass -p 'password' ssh root@ip

But it works fine before

**Comment by sdbbs** [comment]
Same here - though I haven't used sshpass in a while (so not sure when it worked, if ever), this is what I got today (latest MSYS2 updates from today):

```
$ git svn clone svn+ssh://username@svn.code.sf.net/p/myproject/code/ myproject
...
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
(username@svn.code.sf.net) Password:
        A       files/file.py
...
r100 = f2ec84c31d82401fb594bbc359eeec86c233b0b8 (refs/remotes/git-svn)
(username@svn.code.sf.net) Password:
...

$ sshpass -e git svn clone svn+ssh://username@svn.code.sf.net/p/myproject/code/ myproject
sshpass: Failed to set controlling terminal in child (TIOCSCTTY): Invalid argument
```

**Comment by cmal** [comment]
same problem.

**Comment by brendan-simon-indt** [comment]
Yep.  Fails in all environments: msys, mingw64, ucrt64, and Command Prompt too.

**Comment by amolinas** [comment]
The same here. Windows 11 Pro (21H2, 22000.652), MSYS2 up to date (2022-05-04).

**Comment by pidgeon777** [comment]
Same problem. I wonder if a fix will be released?

**Comment by progheal** [comment]
Looks like a bug in sshpass.

**Comment by zudsniper** [comment]
still having this issue, WIN 10 MSYS2 MINGW64

`sshpass: Failed to set controlling terminal in child (TIOCSCTTY): Invalid argument`

**Comment by Biswa96** [comment]
Was that patch applied in the upstream repository in a commit?

**Comment by iakov** [comment]
ATM the `main` branch is the only branch in the repo, [and the patch is not applied](https://sourceforge.net/p/sshpass/code-git/ci/main/tree/main.c#l337)

**Comment by lazka** [comment]
Fixed by #3555 (not in the repo yet)

**Comment by lazka** [comment]
In the repo now

**Comment by AgentRev** [comment]
When I run `pacman -S sshpass`, it still installs v1.09, even after updating the package database with `pacman -Fy`

**Comment by lazka** [comment]
> even after updating the package database with `pacman -Fy`

this should be `pacman -Sy`
