### ISSUE TITLE
[subversion] SQLite error

### ISSUE THREAD

**Issue by trzy** [msys2/MSYS2-packages#2460]
The latest msys/subversion package is seemingly incompatible with MSYS2: 
svn: E200029: Couldn't perform atomic initialization
svn: E200030: SQLite compiled for 3.35.5, but running with 3.34.0

Any ideas on how to fix this? I'm not sure where svn is getting SQLite from but upgrading it with pacman doesn't help.

**Comment by lazka** [comment]
Did you run `pacman -Suy` to update all packages?

**Comment by trzy** [comment]
I solved the problem by installing libsqlite-devel and then reinstalling SVN. Your solution probably would have done that for me :)

**Comment by lazka** [comment]
I don't know to be honest. Let's close this then for now. If this happens again feel free to report it again.

**Comment by Biswa96** [comment]
> I solved the problem by installing libsqlite-devel and then reinstalling SVN

Just FYI, `libsqlite-devel` does not have any DLL file to be depend on, file list [here][1].

[1]: https://packages.msys2.org/package/libsqlite-devel?repo=msys&variant=x86_64

**Comment by lazka** [comment]
(I suspect the "reinstall" pulled in some updates maybe...)

**Comment by trzy** [comment]
Reinstalling SVN by itself didn’t do anything nor did installing sqlite explicitly with Pacman. Note also that this was happening on a clean MSYS2 install.
