### ISSUE TITLE
Unable to update (unable to lock database)

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MSYS2-packages#2469]
```
pacman -Syu
:: Synchronizing package databases...
error: failed to update mingw64 (unable to lock database)
error: failed to update ucrt64 (unable to lock database)
error: failed to update msys (unable to lock database)
error: failed to synchronize all databases
```

**Comment by naveen521kk** [comment]
It means Pacman didn't have permissions to write files on disk especially `/`. Check it has write permissions or start in Admin mode.

**Comment by MehdiChinoune** [comment]
> It means Pacman didn't have permissions to write files on disk especially `/`. Check it has write permissions or start in Admin mode.

The problem starts appearing with the latest update #2456

**Comment by cbrt64** [comment]
FWIW, in my experience this is usually a simple hiccup, see https://github.com/msys2/MSYS2-packages/issues/1996#issuecomment-639675486.
