### ISSUE TITLE
[Request] Add a Compiler / Linker / Windres / Whatever Flag to DISABLE forced linking against default-manifest.o

### ISSUE THREAD

**Issue by MeerMusik** [msys2/MSYS2-packages#2472]
I am in the middle of trying to compile wxWidgets (self-built). Everything works except that LD.exe ALWAYS FORCIBLY is linking against the 'default-manifest.o' - which already costed my a whole day trying to disable that behaviour. And also because I thought wxWidgets is broken. 

The Problem is:
* My Resource File gets completely ignored!
* The wxWidgets Resource File gets completely ignored!

Why is this an Issue:
* I need to define Windows Versions, HiDPI and Feature Flags

That you are forcibly push the 'default-manifest.o' down our throats is an absolute no go! Especially when there is no known Flag to disable it or overwrite it. As much as I love what you do otherwise, these things make me want to go back to VC++. Please finally fix this! It has been much too long already! Thank You!

**Comment by ZachBacon** [comment]
I think you want to move this to the https://github.com/msys2/MINGW-packages repo instead since you are referring to a mingw problem

**Comment by MeerMusik** [comment]
> 
> 
> I think you want to move this to the https://github.com/msys2/MINGW-packages repo instead since you are referring to a mingw problem

Oops too many Tabs open. Moved over.
