### ISSUE TITLE
git bisect is broken

### ISSUE THREAD

**Issue by 89z** [msys2/MSYS2-packages#2479]
If I run these commands:

~~~
git bisect start
git bisect new
git bisect old @~10
git bisect skip
~~~

With these Git:

~~~
git-2.31.1-2-x86_64.pkg.tar.zst
git-2.31.1-1-x86_64.pkg.tar.zst
~~~

Nothing happens. However if I use older version:

~~~
git-2.30.0-1-x86_64.pkg.tar.zst
~~~

I get correct result:

~~~
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[9af12f451c4b15a6a5fe108c509e20236fb4a1b1] Move code outside of a lock
~~~

**Comment by 1480c1** [comment]
Does the same occur with git-for-windows?

**Comment by 89z** [comment]
It fails with git-for-windows as well

**Comment by 1480c1** [comment]
Seems you might have found an actual git bug (as compared to being a msys2 specific bug)

**Comment by 89z** [comment]
I did some more testing, this is the last good version:

<http://repo.msys2.org/msys/x86_64/git-2.30.2-1-x86_64.pkg.tar.zst>

I will be using that until this is fixed.

**Comment by lazka** [comment]
Thanks for filing it upstream: https://github.com/git-for-windows/git/issues/3211

Once a new release is out we will update.

**Comment by dscho** [comment]
@89z as an alternative to waiting and leaning on others (which is the impression you leave with me, which does rub me the wrong way), you could easily integrate the patch into https://github.com/msys2/MSYS2-packages/tree/HEAD/git by providing a PR.

**Comment by lazka** [comment]
To clarify, by referring to git-for-windows as upstream I meant in the "knowledge-about-all-git-things-on-windows" sense. Our git is not based on it.

Backporting is fine with me to.

**Comment by 89z** [comment]
> @89z as an alternative to waiting and leaning on others (which is the impression you leave with me, which does rub me the wrong way), you could easily integrate the patch into https://github.com/msys2/MSYS2-packages/tree/HEAD/git by providing a PR.

@dscho yeah no, Im not doing that. I think a better use of my time, is just patching my own package installer, to allow older verion of packages [1]. I think its odd that just a large project leans so heavily on shell scripts [2][3] after 16 years.

1. https://github.com/89z/sienna/commit/c11b5381
2. https://github.com/git/git/blob/master/git-bisect.sh
3. https://github.com/git/git/blob/master/git-submodule.sh

**Comment by dscho** [comment]
Booh.
