### ISSUE TITLE
python: broken with child_info_fork::abort: address space needed

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2487]
* Rebuild Python as is
* Build glib2 (which uses meson and thus Python)

```
2021-05-08T21:44:59.3747015Z ==> Starting build()...
0 [main] python 22250 child_info_fork::abort: address space needed by '_ssl.cpython-38-x86_64-msys.dll' (0x190000) is already occupied
0 [main] python 22251 child_info_fork::abort: address space needed by '_ssl.cpython-38-x86_64-msys.dll' (0x190000) is already occupied
0 [main] python 22252 child_info_fork::abort: address space needed by '_ssl.cpython-38-x86_64-msys.dll' (0x190000) is already occupied
```

CI run: https://github.com/lazka/MSYS2-packages/runs/2536195524

**Comment by jeremyd2019** [comment]
This looks like the algorithm that Windows uses when the address space that an image wants to occupy is already occupied, it will start filling them in at fairly low addresses, but not in a way that necessarily loads them at the same place in each process.  So I would look for any DLLs that would overlap imagebase + length.

It's odd that the compile of .py modules at the end of python build didn't fail, that's where I had a lot of issues with i686.  That involves lots of forking from multiprocessing module, and loads all the extension dlls.

**Comment by jeremyd2019** [comment]
(I wish the "MSYS2 DLL dependencies"/ldd listing would include the image base of the module itself in addition to those of its dependencies... maybe even the lengths too)

**Comment by jeremyd2019** [comment]
Here's yer overlap:
```
  /c/_/python/pkg/python/usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-msys.dll                base 0x0005d76d0000 size 0x00029000 *
  /c/_/python/pkg/python/usr/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-msys.dll             base 0x0005d76e0000 size 0x0000f000 *
```

**Comment by lazka** [comment]
Previously:
```
/usr/lib/python3.8/lib-dynload/_ssl.cpython-38-x86_64-msys.dll base 0x0004210a0000 size 0x00029000
/usr/lib/python3.8/lib-dynload/_struct.cpython-38-x86_64-msys.dll base 0x0004cef70000 size 0x0000f000
```

**Comment by jeremyd2019** [comment]
I would guess the hash changed in binutils, and the new one is "unlucky" and resulted in a collision.  However, I looked at git blame and didn't see any changes.  🤷

**Comment by lazka** [comment]
I tried building with older binutils back then and got the same result, so that's not the cause

**Comment by lazka** [comment]
binutils seems to limit the hash output to 16bits, what if bump that?

**Comment by lazka** [comment]
Possible fix here: #2494

**Comment by jeremyd2019** [comment]
This seems to have reappeared ☹️

**Comment by lazka** [comment]
ah, likely autobuild failed to pull in binutils because it's not a real dep. I'll trigger a rebuild

**Comment by lazka** [comment]
fixed now, sorry for missing this.
