### ISSUE TITLE
clang: broken — libLLVM.dll is not found

### ISSUE THREAD

**Issue by miketimofeev** [msys2/MSYS2-packages#2500]
## Describe the issue
Get the following error when trying to execute `clang`
```
testadm2@VS19Msys2 MINGW64 ~
# clang
C:/msys64/mingw64/bin/clang.exe: error while loading shared libraries: libLLVM.dll: cannot open shared object file: No such file or directory
```

## Steps to Reproduce the Problem

1. Install clang using pacman `pacman.exe -S --noconfirm --needed --noprogressbar mingw-w64-x86_64-clang`
2. Run 'clang' from msys64 shell
3. Get the error

## Additional Context: Operating System, Screenshots

![image](https://user-images.githubusercontent.com/48208649/118250968-b0000580-b4af-11eb-980e-081783139a8e.png)
Happens on both windows server 2016 & 2019

**Comment by mati865** [comment]
Duplicate of https://github.com/msys2/MINGW-packages/issues/8658

**Comment by miketimofeev** [comment]
@mati865 thanks for the response! libxml2 installation fixes the issue.
