### ISSUE TITLE
ci-library.sh: `check_recipe_quality` require `saneman` from `pactoys`

### ISSUE THREAD

**Issue by podsvirov** [msys2/MSYS2-packages#2524]
## Describe the issue

The `check_recipe_quality` functions from `ci-library.sh` require `saneman` from `pactoys` but looks like it not installed.

## Steps to Reproduce the Problem

Make some `PR` and see `Actions` log.

**Comment by jeremyd2019** [comment]
odd, it worked before.  Related to #2519?

**Comment by podsvirov** [comment]
@jeremyd2019, thanks for quick response and fixing.

**Comment by jeremyd2019** [comment]
anyone noticed if this happens on MINGW-packages too?

**Comment by jeremyd2019** [comment]
It does

**Comment by cbrt64** [comment]
#1983's dropping `pactoys` from `base` might be connected. Although it _was_ a year ago.
