### ISSUE TITLE
Wrong double initialization

### ISSUE THREAD

**Issue by omichel** [msys2/MSYS2-packages#2528]
This simple program gives a wrong result on Windows/MSYS2. On Ubuntu 18.04, it works properly:
```c
#include <math.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
  double a = -1.5708;
  double c = cos(-1.5708);
  double d = cos(a);
  unsigned long long *lc = (unsigned long long *)&c;
  unsigned long long *ld = (unsigned long long *)&d;
  printf("c = %.17e %llu\n", c, *lc);
  printf("d = %.17e %llu\n", d, *ld);
  if (c == d)
    printf("correct result\n");
  else
    printf("wrong result\n");
  return 0;
}

```

Windows/MSYS2:
```console
$ gcc cos.c -o cos -lm ; ./cos
c = -3.67320510334657393e-06 13749155573439758092
d = -3.67320510334657563e-06 13749155573439758096
wrong result
```

Ubuntu 18.04:
```console
olivier@ubuntu:~$ gcc cos.c -o cos -lm ; ./cos
c = -3.67320510334657393e-06 13749155573439758092
d = -3.67320510334657393e-06 13749155573439758092
correct result
```

I am doing something wrong or is it a bug of gcc on MSYS2?

**Comment by Biswa96** [comment]
Which gcc are you using? In my case, mingw32 and msys2 shows correct and ucrt64 shows wrong.

**Comment by omichel** [comment]
> Which gcc are you using? In my case, mingw32 and msys2 shows correct and ucrt64 shows wrong.

I use the mingw64 gcc.

**Comment by omichel** [comment]
See this very good answer: https://stackoverflow.com/a/67817418/810268
The problem is basically that cos is not guaranteed to give the same results across platforms and cos(1.5708) is evaluated at compile time with MPFR while cos(a) is evaluated a run-time with libm, thus the difference.
