### ISSUE TITLE
Questions regarding compiler flags given in makepkg_mingw.conf

### ISSUE THREAD

**Issue by carlkl** [msys2/MSYS2-packages#2538]
I have two questions regarding compiler flags given in `makepkg_mingw.conf`

1.  is `-D__USE_MINGW_ANSI_STDIO=1` really needed for architectures targetting `UCRT`? AFAIK mingw-w64 needs this only only in case of targeting `msvcrt`. 
2. What should be the minimal CPU requirement for 64bit and 32bit? Today we can assume, that at least SSE3 is supported for all existing machines and `-march=nocona -mtune=generic -O2` is a better choice compared to `-march=x86-64 -mtune=generic -O2` or `-march=i686 -mtune=generic -O2`  (32bit).

**Comment by 1480c1** [comment]
> `-D__USE_MINGW_ANSI_STDIO=1`

I think until the rest of the world decides to run a windows update to install ucrt and project maintainers are comfortable enough to drop any previous windows specific hack for printf and co I don't think we should drop this just yet, especially when I don't think Microsoft has any official way to detect UCRT inside the code just yet, and I personally have committed some code that specifically checks for that macro to decide some stuff like using `%I` or `%zu` and have no option yet of detecting UCRT

https://github.com/AOMediaCodec/libavif/blob/5e8cb669701672bea1f2f683fb07ce6915a69972/apps/shared/avifutil.h#L16

**Comment by 1480c1** [comment]
> What should be the minimal CPU requirement for 64bit and 32bit

We could follow fedora's guideline and make sse2 the min https://fedoraproject.org/wiki/Changes/Update_i686_architectural_baseline_to_include_SSE2 or follow MS's docs on Windows 10 distribution and also make the minimum sse2 https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#31-processor or follow steam's hardware survey and set sse3 as the minimum https://store.steampowered.com/hwsurvey (under Other Settings)

**Comment by 1480c1** [comment]
As a small note, I found a way to detect ucrt in an awful way during configure time,
```c
#include <windows.h>
#include <stdio.h>
int main() {
    printf("%p\n", _aligned_malloc(10, 0));
}
```
if this code is compiled with msvcrt and you run it, you will probably see some random address given by malloc, but if you run it with ucrt, it will return NULL.

**Comment by Biswa96** [comment]
Ruby detects UCRT vs MSVCRT by checking the presence of msvcrt.dll in the output of `objdump` with a simple executable.

**Comment by jeremyd2019** [comment]
Old hardware aficionado here
> > What should be the minimal CPU requirement for 64bit and 32bit
> follow MS's docs on Windows 10 distribution and also make the minimum sse2 https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview#31-processor 

Ah yes, I remember when MS made sse2 default in their compiler, broke on Athlon XP.  Yes, we were running Win7 on Athlon XPs.  Those were the days...

**Comment by carlkl** [comment]
detect `_UCRT`:

`echo "#include <windows.h>"| gcc -E -dM -  | grep -i _UCRT`

gives `#define _UCRT` for `UCRT64` architecture only.

**Comment by 1480c1** [comment]
I'm not sure if that would be an okay way to do so since I can't find that in any of MS's docs, so that could mean it's always subject to change

**Comment by Biswa96** [comment]
Remember that will only work if you use mingw-w64 toolchain.

**Comment by carlkl** [comment]
CPU target:

Maybe there is a demand to support rare legacy systems with Windows XP and non SSE enabled CPUs. But I'm not sure if they really need support with a full set of software packages that itself may have higher demands on the CPU arch. Relying on SSE2 (32bit) and SSE3 (64 bit) as a minimum seems to be a reasonable choice.

**Comment by 1480c1** [comment]
> Remember that will only work if you use mingw-w64 toolchain.

Technically `vcruntime.h` does define it in `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\include\vcruntime.h` with
```c
//
// vcruntime.h
//
//      Copyright (c) Microsoft Corporation. All rights reserved.
//
// Declarations used throughout the VCRuntime library.
//
#pragma once
//
// Note on use of "deprecate":
//
// Various places in this header and other headers use
// __declspec(deprecate) or macros that have the term DEPRECATE in them.
// We use "deprecate" here ONLY to signal the compiler to emit a warning
// about these items. The use of "deprecate" should NOT be taken to imply
// that any standard committee has deprecated these functions from the
// relevant standards.  In fact, these functions are NOT deprecated from
// the standard.
//
// Full details can be found in our documentation by searching for
// "Security Enhancements in the CRT".
//
#ifndef _VCRUNTIME_H
#define _VCRUNTIME_H

#ifndef _VCRT_COMPILER_PREPROCESSOR
// Many VCRuntime headers avoid exposing their contents to non-compilers like
// the Windows resource compiler and Qt's meta-object compiler (moc).
#if defined(RC_INVOKED) || defined(Q_MOC_RUN)
#define _VCRT_COMPILER_PREPROCESSOR 0
#else
#define _VCRT_COMPILER_PREPROCESSOR 1
#endif
#endif // _VCRT_COMPILER_PREPROCESSOR

#ifndef _UCRT
    #define _UCRT
#endif
```
But I'm not sure if this is reason enough to consider it an official macro that developers can check

**Comment by Biswa96** [comment]
> But I'm not sure if this is reason enough to consider it an official macro that developers can check

At least, that's _not_ in the official [Predefined macros][1] documentation. But who can prevent 🤷 

[1]: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros

**Comment by carlkl** [comment]
`_UCRT` seemed to me more or less mingw-w64 specific. I'm suprised to find the `_UCRT` macro in `vcruntime.h` from MSVC. So maybe I was wrong with this assumption.

However: mingw-w64 itself doesn't define `__USE_MINGW_ANSI_STDIO` in case of targetting UCRT in `mingw-w64-headers/crt/_mingw.h.in`:

```C
/* We are activating __USE_MINGW_ANSI_STDIO for various define indicators.
 * printf ll modifier (unsupported by msvcrt.dll) is required by C99 and C++11 standards. */
#if (defined (_POSIX) || defined (_POSIX_SOURCE) || defined (_POSIX_C_SOURCE) \
     || defined (_ISOC99_SOURCE) \
     || (defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L && __MSVCRT_VERSION__ < 0xE00) \
     || (defined (__cplusplus) && __cplusplus >= 201103L && __MSVCRT_VERSION__ < 0xE00) \
     || defined (_XOPEN_SOURCE) || defined (_XOPEN_SOURCE_EXTENDED) \
     || defined (_GNU_SOURCE) \
     || defined (_SVID_SOURCE)) \
    && !defined(__USE_MINGW_ANSI_STDIO)
/* Enable __USE_MINGW_ANSI_STDIO if user did _not_ specify it explicitly... */
#  define __USE_MINGW_ANSI_STDIO			1
#endif
```
the measure is: `__MSVCRT_VERSION__ < 0xE00`, but `__MSVCRT_VERSION__` is also mingw-w64 specific.

My point was: is it necessary to define `__USE_MINGW_ANSI_STDIO` for UCRT architectures? Of course in case of using a recent mingw-w64 Version.

**Comment by mati865** [comment]
GCC always defines `__USE_MINGW_ANSI_STDIO` in libstdc++ headers so without defining it you could run into incompatibilities.

Also without `__USE_MINGW_ANSI_STDIO` long doubles won't work because GCC uses 80-bit while MSVC uses 64-bit type.

**Comment by carlkl** [comment]
BTW, there is a fresh set of mingw-w64 patches from Martin Storsjö concerning strtold and wcstold and its mingw-w64 variants:

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/73806c0709b7e6c0f6587f11a955743670e85470/
```
crt: Use the __mingw_strtold implementation for strtold, too

The second implementation, which was under the 'strtold' name, was
lacking (it didn't support e.g. strings like "0x125p-1"), while the
'__mingw_strtold' one seemed correct and complete.
```

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/f9e944d378042b35443dc3c92df16961a8af4e2a/
```
crt: Make __mingw_wcstold an alias to wcstold

There's no need to keep two vaguely differing versions of the same
functions; out of the two, wcstold seems to be more correct.
```

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/19db623deed8df4e122e4fe1d5e27bb523fc485a/
```
crt: Don't provide strtold/wcstold in the UCRT import libraries

The long double type in the UCRT doesn't match the one in mingw
on x86, thus make sure we don't accidentally link to them (if
the user e.g. specifies the CRT import library before libmingwex.a).
```

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/333a219d5a95c0be3b0a01eb8ec659a72997dcd4/
```
crt: Set errno where needed in __mingw_wcstod

This is similar to faa833310419c49cfaeeecb53f9d7366cdc1f120 but for
the __mingw_wcstod function which is implemented around __mingw_wcstold.
```

https://sourceforge.net/p/mingw-w64/mingw-w64/ci/faa833310419c49cfaeeecb53f9d7366cdc1f120/
```
crt: Fix setting errno in the strtod based strtof implementation

In this case, strtod will have set errno for cases that were out of
range for doubles. For doubles that were in range, but that are out
of ranges for float, set errno before returning.
```

If I understand all this correctly there is no need to unconditionally define `__USE_MINGW_ANSI_STDIO=1` all over the place. But maybe it does not harm anyway as there are some places where it is now defined as `__USE_MINGW_ANSI_STDIO=0` in case of problems.

**Comment by carlkl** [comment]
Since my questionary is more of a suggestion than a bug description I'm closing this issue.
