### ISSUE TITLE
Missing wish when running gitk

### ISSUE THREAD

**Issue by Samega7Cattac** [msys2/MSYS2-packages#2541]
## Describe the issue

Seems there's a missing exec when trying to run gitk.
The environment is updated

## Steps to Reproduce the Problem

1. Install git package
2. clone a repo
3. try to run gitk

## Additional Context: Operating System, Screenshots

```
$ gitk
/usr/bin/gitk: line 3: exec: wish: not found
```

- OS: Windows 10 Enterprise LTSC version 1809 64bit
- git package: 2.32.0-1

**Comment by ZachBacon** [comment]
Run _pacman -S tcl tk_ and then try running gitk

**Comment by lazka** [comment]
> Run _pacman -S tcl tk_ and then try running gitk

there is no "tk"

**Comment by Samega7Cattac** [comment]
from a older issue it says tc needs xorg, but it was working previously, I'm having this issue with recent updates (maybe weeks).

**Comment by Samega7Cattac** [comment]
Running Msys 64bit solves the issue

**Comment by kumoyuki** [comment]
this problem appears to be present with package git-2.41.0-1

$ cat /proc/version
MSYS_NT-10.0-17763 version 3.4.6.x86_64 (runneradmin@fv-az250-451) (gcc version 11.3.0 (GCC) ) 2023-05-30 17:53 UTC

running the mingw64.exxe shell doesn;t solve the problem either. Is this a reopen? Or a new Bug?

**Comment by lazka** [comment]
gitk works fine here in anything but the msys shell.
