### ISSUE TITLE
mingw32-make changes PREFIX variable

### ISSUE THREAD

**Issue by igagis** [msys2/MSYS2-packages#2544]
## Describe the issue

I'm calling the `mingw32-make` as follows:
```console
mingw32-make PREFIX=/usr
```
and in the `makefile` the `PREFIX` variable becomes `C:/msys64/usr`.

I'm wondering where can I get that `C:/msys64` from (i.e. install path of the `Msys2`) to remove that prefix from the variable?
How does `mingw32-make` know where `Msys2` is installed on the host system?

I need this in context of `install:` target in my `makefile`, I need to prepend the `DESTDIR` variable to the `PREFIX` variable. And in this case `$(DESTDIR)$(PREFIX)` gives `my_destdirC:/msys64/usr` which is obviously not what I need. So I want to check if `PREFIX` starts with `C:/msys64` and then strip it out.

## Steps to Reproduce the Problem

1. Prepare `makefile` with line `$(info PREFIX = $PREFIX)`
2. Run `mingw32-make PREFIX=/usr`

Result:
`PREFIX = C:/msys64/usr` is printed

**Comment by jeremyd2019** [comment]
1. you may not really want mingw32-make.  Its use is generally discouraged here in favor of msys `make`.
2. If you really do, you need to set `MSYS2_ARG_CONV_EXCL` to prevent paths on the command line getting translated when launching a native process.

See https://www.msys2.org/wiki/Porting/

**Comment by igagis** [comment]
Well, I have to use `mingw32-make` right because of that reason, that it constructs windows-like absolute paths which work OK with `mingw-gcc`. If I knew the `msys2` install path, i.e. that `C:/msys64` I think I could go with msys `make`.

The `MSYS2_ARG_CONV_EXCL` approach works for me as a workaround, but not as a solution I'd want to have.

I'm developing a `GNU make`-based [build system](https://github.com/cppfw/prorab) and `MSYS2_ARG_CONV_EXCL` approach would require user to bother about setting it when using the thing. But, knowing the `C:/msys64` in the `makefile` would allow hiding this thing from the user.

**Comment by jeremyd2019** [comment]
> But, knowing the `C:/msys64` in the `makefile` would allow hiding this thing from the user.

If you really want that, `$(shell cygpath -m /)`

**Comment by jeremyd2019** [comment]
> Well, I have to use `mingw32-make` right because of that reason, that it constructs windows-like absolute paths which work OK with `mingw-gcc`. 

Note that this same automatic command line conversion of paths applies to msys make running mingw gcc, so in general it Just Works.

**Comment by igagis** [comment]
Thanks, that worked!
