### ISSUE TITLE
clang32 isn't known by pacman

### ISSUE THREAD

**Issue by carlkl** [msys2/MSYS2-packages#2554]
clang32 is not included in `pacman.conf`. Is this intended?

**Comment by lazka** [comment]
somewhat, since we werent sure if we want to support it with 32bit going away.

**Comment by carlkl** [comment]
I don't believe 32bit is going away anytime soon. A 32bit UCRT compiler infrastructure with the most prominent libraries would be great (my personal preference is gcc with gfortran). I see the maintainance problem, so I agree that some combinations has to be declared deprecated at some point.

**Comment by Biswa96** [comment]
According to a [Microsoft docs][1]:

> Beginning with Windows 10, version 2004, all new Windows 10 systems will be required to use 64-bit builds and Microsoft will no longer release 32-bit builds for OEM distribution.

So, something will happen with 32 bit system.

[1]: https://docs.microsoft.com/en-us/windows-hardware/design/minimum/minimum-hardware-requirements-overview

**Comment by carlkl** [comment]
I don't think so. The WOW64-Subsystem (running 32bit software on 64bit Windows) is still there.  A lot of MS software is usually available as 32bit, i.e. MS Office. Legacy software is typically using 32bit as well. There are a lot of cases where you are stick on 32bit software packages. Newly developed software packages should of course use 64bit exclusively.

**Comment by mati865** [comment]
The problem with clang32 is that many packages fail to build because of address space constrains.
Even if we enable it there will be many missing packages and its future is uncertain as it might stop building on LLVM upgrade.

**Comment by jeremyd2019** [comment]
> A 32bit UCRT compiler infrastructure with the most prominent libraries would be great (my personal preference is gcc with gfortran)

> The problem with clang32 is that many packages fail to build because of address space constrains.
> Even if we enable it there will be many missing packages and its future is uncertain as it might stop building on LLVM upgrade.

msys2/CLANG-packages#34 - perhaps in light of this 32-bit gcc+ucrt would be/have been a better choice for a "supported" toolchain.  But, at least the clang32 toolchain has found some nice bugs in llvm.

**Comment by carlkl** [comment]
Of course it's up to the maintainers. A 32-bit gcc+ucrt would get a :+1: from me. Is there anything I could help?

**Comment by carlkl** [comment]
Since everything has been said, I'm closing this issue. Just one remark: maybe a hint about the non-availability of CLANG32 or UCRT32 could be helpful, i.e. on this place: https://www.msys2.org/docs/environments/
