### ISSUE TITLE
pacman -Syu -> failed retrieving file

### ISSUE THREAD

**Issue by SloBloLabs** [msys2/MSYS2-packages#2575]
## Describe the issue

updating my repo today and running into the following issue (See full log below):
error: failed retrieving file 'mingw-w64-x86_64-python-astroid-2.4.2-1-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

## Steps to Reproduce the Problem
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64                                                                                                                               1468.7 KiB  1834 KiB/s 00:01 [####################################################################################################] 100%
 clang64                                                                                                                              1095.6 KiB  1246 KiB/s 00:01 [####################################################################################################] 100%
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: mingw-w64-x86_64-libwebp will be installed before its mingw-w64-x86_64-libtiff dependency
warning: dependency cycle detected:
warning: mingw-w64-x86_64-harfbuzz will be installed before its mingw-w64-x86_64-freetype dependency

Packages (202) asciidoc-9.1.0-2  autoconf-2.71-1  automake1.16-1.16.3-1  binutils-2.36.1-4  bison-3.7.6-1  brotli-1.0.9-2  bsdcpio-3.5.1-1  bsdtar-3.5.1-1  ca-certificates-20210119-1  cmake-3.20.4-1  curl-7.76.1-1  dash-0.5.11.4-1  diffstat-1.64-1  dtc-1.6.0-4
               expat-2.3.0-1  file-5.40-2  findutils-4.8.0-1  gdb-10.2-3  gdbm-1.19-1  git-2.32.0-1  glib2-2.68.1-1  gnupg-2.2.28-3  help2man-1.48.3-1  icu-68.2-1  lemon-3.36.0-1  less-581-1  libarchive-3.5.1-1  libassuan-2.5.5-1  libcrypt-2.1-3  libcurl-7.76.1-1
               libedit-20210522_3.1-1  libexpat-2.3.0-1  libgcrypt-1.9.2-1  libgdbm-1.19-1  libgnutls-3.7.2-1  libgpg-error-1.42-1  libgpgme-1.16.0-1  libhogweed-3.7.3-1  libidn2-2.3.1-2  libksba-1.6.0-1  libltdl-2.4.6-11  libnettle-3.7.3-1  libnghttp2-1.43.0-1
               libopenssl-1.1.1.k-1  libp11-kit-0.23.22-2  libpcre-8.45-1  libpcre16-8.45-1  libpcre2_16-10.37-1  libpcre2_32-10.37-1  libpcre2_8-10.37-1  libpcre2posix-10.37-1  libpcre32-8.45-1  libpcrecpp-8.45-1  libpcreposix-8.45-1  librhash-1.4.1-2
               libsqlite-3.36.0-1  libtasn1-4.17.0-2  libtool-2.4.6-11  libunrar-6.0.7-1  libunrar-devel-6.0.7-1  libuv-1.41.0-1  libxml2-2.9.10-9  libxslt-1.1.34-4  libxxhash-0.8.0-1  libzstd-1.5.0-1  m4-1.4.19-1  man-db-2.9.4-1
               mingw-w64-cross-crt-git-9.0.0.6158.1c773877-1  mingw-w64-cross-headers-git-9.0.0.6158.1c773877-1  mingw-w64-cross-winpthreads-git-9.0.0.6158.1c773877-1  mingw-w64-x86_64-SDL2-2.0.14-2  mingw-w64-x86_64-aom-3.1.1-4  mingw-w64-x86_64-c-ares-1.17.1-1
               mingw-w64-x86_64-ca-certificates-20200601-3  mingw-w64-x86_64-capstone-4.0.2-1  mingw-w64-x86_64-curl-7.77.0-2  mingw-w64-x86_64-dav1d-0.9.0-1  mingw-w64-x86_64-djvulibre-3.5.28-2  mingw-w64-x86_64-exiv2-0.27.4-1  mingw-w64-x86_64-expat-2.4.1-1
               mingw-w64-x86_64-fftw-3.3.9-2  mingw-w64-x86_64-fontconfig-2.13.93-3  mingw-w64-x86_64-freeglut-3.2.1-2  mingw-w64-x86_64-freetype-2.10.4-4  mingw-w64-x86_64-gcc-libgfortran-10.3.0-2  mingw-w64-x86_64-gcc-libs-10.3.0-2
               mingw-w64-x86_64-gdk-pixbuf2-2.42.4-1  mingw-w64-x86_64-giflib-5.2.1-3  mingw-w64-x86_64-glib2-2.68.3-1  mingw-w64-x86_64-gmp-6.2.1-2  mingw-w64-x86_64-harfbuzz-2.8.1-1  mingw-w64-x86_64-hidapi-0.10.1-2  mingw-w64-x86_64-imagemagick-7.0.10.11-4
               mingw-w64-x86_64-jasper-2.0.32-1  mingw-w64-x86_64-jemalloc-5.2.1-2  mingw-w64-x86_64-lcms2-2.12-1  mingw-w64-x86_64-libdeflate-1.7-3  mingw-w64-x86_64-libffi-3.3-4  mingw-w64-x86_64-libheif-1.12.0-2  mingw-w64-x86_64-libidn2-2.3.1-1
               mingw-w64-x86_64-libimagequant-2.13.1-1  mingw-w64-x86_64-libjpeg-turbo-2.0.6-1  mingw-w64-x86_64-libpng-1.6.37-4  mingw-w64-x86_64-libpsl-0.21.1-3  mingw-w64-x86_64-libraqm-0.7.1-1  mingw-w64-x86_64-libraw-0.20.2-2  mingw-w64-x86_64-libssh2-1.9.0-3
               mingw-w64-x86_64-libtasn1-4.17.0-1  mingw-w64-x86_64-libtiff-4.3.0-3  mingw-w64-x86_64-libtool-2.4.6-20  mingw-w64-x86_64-libunistring-0.9.10-4  mingw-w64-x86_64-libusb-1.0.24-3  mingw-w64-x86_64-libusb-compat-git-r76.b5db9d0-2
               mingw-w64-x86_64-libwebp-1.2.0-2  mingw-w64-x86_64-libwinpthread-git-9.0.0.6246.ae63cde27-1  mingw-w64-x86_64-libwmf-0.2.12-3  mingw-w64-x86_64-libxml2-2.9.12-1  mingw-w64-x86_64-mpdecimal-2.5.0-2  mingw-w64-x86_64-ncurses-6.2-3
               mingw-w64-x86_64-nghttp2-1.43.0-1  mingw-w64-x86_64-openblas-0.3.13-2  mingw-w64-x86_64-openocd-0.11.0-1  mingw-w64-x86_64-openssl-1.1.1.k-2  mingw-w64-x86_64-p11-kit-0.23.22-1  mingw-w64-x86_64-pcre-8.44-3  mingw-w64-x86_64-python-3.8.9-2
               mingw-w64-x86_64-python-appdirs-1.4.4-1  mingw-w64-x86_64-python-astroid-2.4.2-1  mingw-w64-x86_64-python-attrs-21.2.0-1  mingw-w64-x86_64-python-cachecontrol-0.12.6-2  mingw-w64-x86_64-python-certifi-2021.5.30-1  mingw-w64-x86_64-python-chardet-4.0.0-1
               mingw-w64-x86_64-python-colorama-0.4.4-1  mingw-w64-x86_64-python-contextlib2-0.6.0.post1-1  mingw-w64-x86_64-python-distlib-0.3.2-1  mingw-w64-x86_64-python-idna-3.2-1  mingw-w64-x86_64-python-isort-5.8.0-1
               mingw-w64-x86_64-python-lazy-object-proxy-1.6.0-1  mingw-w64-x86_64-python-lockfile-0.12.2-2  mingw-w64-x86_64-python-matplotlib-3.3.4-2  mingw-w64-x86_64-python-msgpack-1.0.2-1  mingw-w64-x86_64-python-numpy-1.21.0-1
               mingw-w64-x86_64-python-packaging-20.9-1  mingw-w64-x86_64-python-pandas-1.0.5-2  mingw-w64-x86_64-python-pep517-0.10.0-1  mingw-w64-x86_64-python-pillow-8.3.0-1  mingw-w64-x86_64-python-pip-21.1.3-1  mingw-w64-x86_64-python-pylint-2.6.0-1
               mingw-w64-x86_64-python-pytz-2021.1-1  mingw-w64-x86_64-python-requests-2.25.1-2  mingw-w64-x86_64-python-scipy-1.6.3-1  mingw-w64-x86_64-python-setuptools-57.0.0-1  mingw-w64-x86_64-python-six-1.16.0-1  mingw-w64-x86_64-python-toml-0.10.2-1
               mingw-w64-x86_64-python-typed_ast-1.4.2-1  mingw-w64-x86_64-python-urllib3-1.26.6-1  mingw-w64-x86_64-qhull-2020.2-2  mingw-w64-x86_64-rav1e-0.4.1-1  mingw-w64-x86_64-readline-8.0.004-2  mingw-w64-x86_64-sqlite3-3.35.5-1  mingw-w64-x86_64-tcl-8.6.11-3
               mingw-w64-x86_64-tk-8.6.11.1-2  mingw-w64-x86_64-vulkan-headers-1.2.179-1  mingw-w64-x86_64-vulkan-loader-1.2.179-2  mingw-w64-x86_64-x265-3.4-2  mingw-w64-x86_64-zlib-1.2.11-9  mingw-w64-x86_64-zstd-1.5.0-1  mpc-1.2.1-1  msys2-keyring-1~20210213-2
               msys2-launcher-1.3-2  msys2-w32api-headers-9.0.0.6158.1c773877-1  msys2-w32api-runtime-9.0.0.6158.1c773877-1  nettle-3.7.3-1  openssh-8.5p1-1  openssl-1.1.1.k-1  p11-kit-0.23.22-2  pactoys-git-r2.07ca37f-2  pcre-8.45-1  pcre2-10.37-1  perl-5.32.1-1
               perl-HTML-Parser-3.76-1  perl-HTTP-Cookies-6.10-1  perl-HTTP-Message-6.32-1  perl-IO-Socket-SSL-2.071-1  perl-Net-HTTP-6.21-1  perl-Net-SSLeay-1.90-1  perl-URI-5.09-1  perl-YAML-Syck-1.34-1  perl-libwww-6.55-1  pinentry-1.1.1-1  pkgconf-1.7.4-1
               python-3.9.5-1  rebase-4.5.0-1  scons-3.1.2-6  tar-1.34-1  tzcode-2021a-1  unrar-6.0.7-1  vim-8.2.2859-2  wget-1.21.1-2  whois-5.5.9-1  xxhash-0.8.0-1  zstd-1.5.0-1

Total Download Size:     47.49 MiB
Total Installed Size:  1763.29 MiB
Net Upgrade Size:        78.92 MiB

:: Proceed with installation? [Y/n] Y
:: Retrieving packages...
 mingw-w64-x86_64-python-astroid-2.4.2-1-any is up to date
 mingw-w64-x86_64-python-colorama-0.4.4-1-any                                                                                           25.4 KiB  8.44 KiB/s 00:03 [####################################################################################################] 100%
 mingw-w64-x86_64-python-contextlib2-0.6.0.post1-1-any                                                                                  16.1 KiB  3.21 KiB/s 00:05 [####################################################################################################] 100%
 mingw-w64-x86_64-python-distlib-0.3.2-1-any                                                                                           278.6 KiB  39.7 KiB/s 00:07 [####################################################################################################] 100%
 mingw-w64-x86_64-python-isort-5.8.0-1-any                                                                                             183.4 KiB  20.3 KiB/s 00:09 [####################################################################################################] 100%
 Total ( 5/34)                                                                                                                          47.5 MiB  2.52 MiB/s 00:19 [####################################################################################################] 100%
error: failed retrieving file 'mingw-w64-x86_64-python-astroid-2.4.2-1-any.pkg.tar.zst?viasf=1.sig' from master.dl.sourceforge.net : Maximum file size exceeded
warning: failed to retrieve some files
error: failed to commit transaction (download library error)
Errors occurred, no packages were upgraded.

Windows 10.0.18363

**Comment by jeremyd2019** [comment]
hmm, msys2/msys2-pacman#1 ?

**Comment by Biswa96** [comment]
I think this is just SourceForge's issue. @SloBloLabs make sure you have all the mirrors link in /etc/pacman.d/mirrorlist files. The mirrors can be found in this repo in pacman-mirrors folder.

**Comment by SloBloLabs** [comment]
There are two files in that pacman-mirrors folder which I copied both to my local /etc/pacman.d folder. The identical issue above occurs when loading python-astroid package.
I recognized my set of mirrorlist files is bigger than in the repo:
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       07.01.2021     19:15                gnupg
-a----       04.07.2021     09:27           1475 mirrorlist.clang32
-a----       04.07.2021     09:27           1475 mirrorlist.clang64
-a----       07.07.2021     20:36           1492 mirrorlist.mingw
-a----       04.07.2021     09:27           1429 mirrorlist.mingw.bak
-a----       08.12.2020     09:37           1214 mirrorlist.mingw32
-a----       04.07.2021     09:27           1406 mirrorlist.mingw32.pacnew
-a----       08.12.2020     09:37           1252 mirrorlist.mingw64
-a----       04.07.2021     09:27           1452 mirrorlist.mingw64.pacnew
-a----       07.07.2021     20:37           1468 mirrorlist.msys
-a----       08.12.2020     09:37           1204 mirrorlist.msys.bak
-a----       04.07.2021     09:27           1407 mirrorlist.msys.pacnew
-a----       04.07.2021     09:27           1452 mirrorlist.ucrt64

Shell I remove the others?

**Comment by Biswa96** [comment]
Noooo... 😨 those are important. Just make sure those file have mirror.msys2.org and repo.msys2.org links at first (like [these][1]).

[1]: https://github.com/msys2/MSYS2-packages/blob/master/pacman-mirrors/mirrorlist.mingw

**Comment by jeremyd2019** [comment]
> I think this is just SourceForge's issue. @SloBloLabs make sure you have all the mirrors link in /etc/pacman.d/mirrorlist files. The mirrors can be found in this repo in pacman-mirrors folder.

I was thinking SourceForge's redirector (maybe the one @lazka just switched back to that supports symlinks) appends a query string to the URL, then making it sort of like the github issue

**Comment by SloBloLabs** [comment]
Ok, that's fine 😅 Thank you for the swift reaction. Alright, now I ran pacman -Syu again, same result.
For some reason it wants to pull the xxx.sig url from master.dl.sourceforge.net. I performed a recursive search of master.dl.sourceforge.net in my msys environment, but that string would appear in no file.
What do you say: Do I need to rebuild everything from scratch to get back to working state quickly or are there other preferred options (e.g. clearing some caches)?

**Comment by lazka** [comment]
oh, yeah, looks like like the github issue

**Comment by jeremyd2019** [comment]
> For some reason it wants to pull the xxx.sig url from master.dl.sourceforge.net. I performed a recursive search of master.dl.sourceforge.net in my msys environment, but that string would appear in no file.

That's probably the target of a redirect.  I would suggest editing your pacman.conf and/or mirrorlists to make sure sourceforge is *below* mirror.msys2.org or repo.msys2.org (or not present at all)

**Comment by SloBloLabs** [comment]
Thanks to everyone. By commenting out all occurances of sourceforge in the mirrorlist files I do now come ahead with the system upgrade. Issue is closed then.
