### ISSUE TITLE
fish have delay when drawing prompt

### ISSUE THREAD

**Issue by soredake** [msys2/MSYS2-packages#2587]
## Describe the issue

Fish in msys2/mingw64 have delay in prompt draw.

## Steps to Reproduce the Problem

1. Install msys2
2. Select MINGW64 as backend
3. Install fish
4. Di `fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher pure-fish/pure'`
5. Run `fish` and cd to any directory (git repo for example)

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Pro 21H1

Video showing delay:
https://user-images.githubusercontent.com/5204968/127196715-b15cc512-21f3-43b5-85ef-dc195997c38c.mp4

**Comment by NotKyros** [comment]
I am currently experiencing the same issue. There is this pause between the output of commands and the drawing of the prompt.

**Comment by NotKyros** [comment]
I play around with this some more this evening. It's 100% the default fish_prompt causing this issue. If you set it to something static it goes back to being fast again.

**Comment by soredake** [comment]
@NotKyros can you also test my other problems https://github.com/msys2/MSYS2-packages/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+author%3Asoredake? I want to know if they are specific to me or not, thanks anyway.

**Comment by NotKyros** [comment]
@soredake I'm also having several of those issues. In fact, it seems like the whole io system is extremely slow compared to previous versions. I was trying to get some work done today and it was rather painful. There is a very noticeable delay when I launch any program that does file io. This is all on a nvme drive also.

**Comment by soredake** [comment]
Maybe related https://github.com/msys2/MSYS2-packages/issues/138

**Comment by NotKyros** [comment]
I followed the suggestions in that thread to generate passwd and group then disabled db in /etc/nsswitch.conf. Everything seems back to normal now. Thank you very much.

**Comment by soredake** [comment]
Unfortunately this does not helps with any of mine problems, meh.
