### ISSUE TITLE
makepkg takes a long time to parse a big PKGBUILD file

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/MSYS2-packages#2593]
## Describe the issue

makepkg takes a long time to parse a big PKGBUILD file

## Steps to Reproduce the Problem

1. checkout https://github.com/msys2/MINGW-packages/pull/9249
2. makepkg -g
3. It takes a long time.

**Comment by lazka** [comment]
not much we can do I think.. lots of forks..

**Comment by Biswa96** [comment]
Make smaller pkgbuild files like qt6.

**Comment by MehdiChinoune** [comment]
> Make smaller pkgbuild files like qt6.

I tried, but It is not easy to deal with qmake buildsystem.

**Comment by Biswa96** [comment]
I've also tried to split qt5 packages but got a dead end with some path issues. The media-autobuild-suite guys did something with qt5 static build /cc @1480c1

**Comment by 1480c1** [comment]
For qt5 building, we first built `https://github.com/qt/qtbase.git`, then `https://github.com/qt/qtdeclarative.git`, then `https://github.com/qt/qtsvg.git`, and so on, in rough terms, the order was

```bash
export QMAKE_CXX=$CXX QMAKE_CC=$CC
export MSYS2_ARG_CONV_EXCL="--foreign-types="
_check=(bin/qmake.exe Qt5Core.pc Qt5Gui.pc Qt5Widgets.pc)
https://github.com/qt/qtbase.git

_deps=(Qt5Core.pc)
_check=(Qt5Quick.pc Qt5Qml.pc)
https://github.com/qt/qtdeclarative.git

_deps=(Qt5Core.pc)
_check=(Qt5Svg.pc)
https://github.com/qt/qtsvg.git

_deps=(Qt5Core.pc Qt5Quick.pc Qt5Qml.pc)
_check=("$LOCALDESTDIR/qml/QtGraphicalEffects/libqtgraphicaleffectsplugin.a")
https://github.com/qt/qtgraphicaleffects.git

_deps=(Qt5Core.pc Qt5Quick.pc Qt5Qml.pc)
_check=(Qt5QuickControls2.pc)
https://github.com/qt/qtquickcontrols2.git
```

where the `_check` refers to a file that was installed in the install stage and the `_deps` array refers to what files the package depends on. This isn't all of qt's stuff afaik, but just the stuff needed for vlc

**Comment by jeremyd2019** [comment]
> not much we can do I think.. lots of forks..

Yep.  Fork overhead is even worse on ARM64 with emulation overhead added on 😬
