### ISSUE TITLE
`texi2dvi` not working

### ISSUE THREAD

**Issue by mmuetzel** [msys2/MSYS2-packages#2596]
I'm not able to create .dvi files from .texi files using `texi2dvi`.

With the attached file, I see the following:
```
$ texi2dvi test.texi
/usr/bin/texi2dvi: texinfo.tex appears to be broken.
This may be due to the environment variable TEX set to something
other than (plain) tex, a corrupt texinfo.tex file, or
to tex itself simply not working.
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021/Built by MSYS2 project) (preloaded format=etex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `txiversion.tex'.
<*> txiversion.tex

(Press Enter to retry, or Control-Z to exit)
Please type another input file name:
! Emergency stop.
<*> txiversion.tex

No pages of output.
Transcript written on texput.log.
/usr/bin/texi2dvi: quitting.
```

The same command with that file successfully creates a .dvi file on Ubuntu 21.04.

Fwiw, the error is the same for `texi2pdf test.texi`

[test.zip](https://github.com/msys2/MSYS2-packages/files/6932259/test.zip)

**Comment by Biswa96** [comment]
I am not familiar with that program. In my case the output of `texi2dvi test.txi` command is like this 

```
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.  If you want to use
this script, you'll need to install TeX (if you don't have it) or change
your PATH or TEX environment variable (if you do).  See the --help
output for more details.

For information about obtaining TeX, please see http://tug.org/texlive,
or do a web search for TeX and your operating system or distro.
```

tex.exe binary can be found in `$MINGW_PACKAGE_PREFIX-texlive-bin` package.

**Comment by mmuetzel** [comment]
Sorry. Forgot to mention:
I also tried installing `mingw-w64-x86_64-texlive-full` that is probably a lot more than would be needed. But I wanted to make sure that I'm not missing something.
IIUC, it should be working with `mingw-w64-x86_64-texlive-core` or less. (But I could be wrong since it isn't working for me...)

**Comment by mmuetzel** [comment]
I'm not sure if this is a bug in texi2dvi or in texlive.
Should I open another issue at https://github.com/msys2/msys2-texlive/issues?

**Comment by mmuetzel** [comment]
This was caused by a local configuration error.
Closing issue.
