### ISSUE TITLE
NaN string to double GCC

### ISSUE THREAD

**Issue by Satoshi-Yoda** [msys2/MSYS2-packages#2597]
Good day! :)

Noticed strange behavior is some rare cases in my program, and after some digging found this essence:
```
std::string str { "nan" };
std::cout << str << " " << atof(str.c_str()) << " " << stod(str) << std::endl;
```

For me it returns
`nan 0 nan`

But expected result is
`nan nan nan`

I am using
`gcc (Rev6, Built by MSYS2 project) 10.2.0 on Windows 10.`
I tried some online GCC compilers, and saw the correct result everywhere. So it is not common for GCC in general.

I am not sure, that I picked right repository to report this... It just looks more suitable =)

**Comment by jeremyd2019** [comment]
```
$ cat teststod.cpp
#include <iostream>
#include <stdlib.h>
#include <string>

int main()
{
        std::string str { "nan" };
        std::cout << str << " " << atof(str.c_str()) << " " << stod(str) << std::endl;
        return 0;
}

$ echo $MSYSTEM
MSYS

$ g++ -o teststod teststod.cpp

$ ./teststod.exe
nan nan nan

```
