### ISSUE TITLE
Is there a EULA or Terms and Conditions for accessing the repository at repo.msys2.org ?

### ISSUE THREAD

**Issue by tpanza** [msys2/MSYS2-packages#2599]
## Describe the issue

Is there any sort of EULA, terms of service, or terms and conditions associated with accessing the repository at https://repo.msys2.org. I am asking about the repository itself, not the license of a particular package. I have not been able to find any documentation about this one or way or the other anywhere on the msys2.org site.

Is there any restriction regarding commercial use or access of this repository?

**Comment by ZachBacon** [comment]
The licensing of each package can be found in each package, so you'll have to adhere to what's found there, msys2 just provides the packages in binary and development headers and libraries for use, but in the end it's up to the end user to adhere to the individual packages licensing.

**Comment by 1480c1** [comment]
Regarding accessing repo.msys2.org, I don't think there are any restrictions other than no ddossing and the normal rules since nothing has really been stated in that regard from what I remember.

/cc @elieux

**Comment by lazka** [comment]
There are no restrictions, but also no guarantees and support.
