### ISSUE TITLE
cmake does nothing under both msys2 and mgw64

### ISSUE THREAD

**Issue by blmckinley** [msys2/MSYS2-packages#2606]
## Describe the issue

I cannot get cmake to function under msys2 or mgw64. I followed the discussion in https://github.com/msys2/MSYS2-packages/issues/397 and none of that helped.

## Steps to Reproduce the Problem

1. Run cmake with any set of parameters. For example:
    $ cmake --version
returns nothing.

## Additional Context: Operating System, Screenshots

- OS: Microsoft Windows [Version 10.0.19041.1165]
- Other msys2 functions seem to work perfectly well (make, gcc, g++, etc)

$ pacman -S cmake
succeeds

$ sha1sum cmake.exe
7348ce02edfc2c410c36f09a556527ce59cf6523 *cmake.exe

$ which cmake
/usr/bin/cmake

**Comment by Biswa96** [comment]
Try to use latest installer. Update packages. For msys2 programs, use /usr/bin/cmake.exe, install it with `pacman -S cmake` command. For mingw programs, use `${MINGW_PREFIX}/bin/cmake.exe`, install it with `pacman -S ${MINGW_PACKAGE_PREFIX}-cmake` command.

**Comment by blmckinley** [comment]
Wow. I already attempted both of those, to no effect. But now I have done so again and it seems to be working. 
Thanks!
