### ISSUE TITLE
Python 3.9 - absolute path assumed erroneously 

### ISSUE THREAD

**Issue by adisuciu** [msys2/MSYS2-packages#2628]
Open mingw64 shell - works the same in msys2 shell
Create test script - 
```
echo "print('testing Python')" > test.py
```
Run script with mingw-w64-x86_64-python3 (installed via pacman -S mingw-w64_x86_64-python3 - Success 
```
$	C:/msys64/mingw64/bin/python3 C:/msys64/home/Adi/test.py
testing Python
```
Run script with msys2 python(installed via pacman -S python3) - Fail
```
$  C:/msys64/usr/bin/python3 C:/msys64/home/Adi/test.py
C:/msys64/usr/bin/python3: can't open file '/home/Adi/C:/msys64/home/Adi/test.py': [Errno 2] No such file or directory
```
This however works 
```
$ C:/msys64/usr/bin/python3 /C/msys64/home/Adi/test.py - works
testing Python
```

Looks like msys2 python doesn't detect that C:/ is an absolute path and prepends the the pwd.
The mingw version works fine.

Screenshot:
![image](https://user-images.githubusercontent.com/8676912/131897872-fa3fae8d-ad85-4f8c-a5aa-022150053cb1.png)

**Comment by adisuciu** [comment]
Anyone else notice this ? This messes up builds in CI as the mingw version has some other issues.

**Comment by lazka** [comment]
msys tools don't know anything about Windows style paths, so it gets interpreted as a relative path since it doesn't start with /

**Comment by adisuciu** [comment]
I get that, but the previous version of msys python worked, so there must be some regression in there.

**Comment by adisuciu** [comment]
This works:
https://repo.msys2.org/msys/x86_64/python-3.8.2-1-x86_64.pkg.tar.xz (this is the one I tested, but I think it works all the way up to 3.8.7)
This doesn't:
https://repo.msys2.org/msys/x86_64/python-3.9.6-1-x86_64.pkg.tar.zst

**Comment by lazka** [comment]
Then 3.8 didn't try to convert that path to an absolute one and you were just lucky :)

**Comment by adisuciu** [comment]
Guess we were lucky for 4 years straight ..

**Comment by lazka** [comment]
Also see https://www.msys2.org/docs/filesystem-paths/#windows-unix-path-conversion

**Comment by adisuciu** [comment]
Thanks, this makes it a little bit clearer. Some cmake scripts generate those kind of mixed Unix/Windows paths on our build. The cmake i'm using is also mingw-w64 but I don't know for sure if the subsequent tools that are used are mingw-w64 versions. I'll port the script to use only mingw-w64 tools and it should (hopefully) work.
