### ISSUE TITLE
ci-get-build-order.py from MINGW-packages confused by MSYS2 curl

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MSYS2-packages#2634]
@jtanx 
I was trying to merge the CI scripts between MINGW-packages and MSYS2-packages, and my quick test on MSYS2-packages failed:
https://github.com/jeremyd2019/MSYS2-packages/actions/runs/1203672370

```
warning: dependency cycle detected on libcurl-devel
warning: dependency cycle detected on curl
warning: dependency cycle detected on libcurl-devel

[MSYS2 CI] Processing changes

	[2a66a481] CI: merge with MINGW-packages
	[ee16fe35] test CI by building a few packages

[MSYS2 CI] Building packages

	libcurl
	cmake
	python-pyalpm

[MSYS2 CI] Approving recipe quality

error: missing directory ‘libcurl’
```

It seems that recursing on `pkg.deps` is problematic, because the deps may be split packages, not the "base" package, and in any event may not be the same as the directory name.

**Comment by jeremyd2019** [comment]
Idea: add another property to `PackageInfo` class, with the `package` from `get_pkginfo`, and add that instead of `package` from `get_build_order`.

**Comment by jtanx** [comment]
Nice, thanks for fixing that!
