### ISSUE TITLE
GTK stack as part of MSYS2-packages?

### ISSUE THREAD

**Issue by rubyFeedback** [msys2/MSYS2-packages#2649]
Heya msys2-packages maintainers,

I had a look at the repository here:

https://github.com/msys2/MSYS2-packages

I searched for "gtk" but I only found gtk-doc which I assume refers to the 
source archive here: https://download.gnome.org/sources/gtk-doc/1.33/gtk-doc-1.33.2.tar.xz (or any other similar version).

So I assume that the GTK stack (atk, pango, glib, cairo, gtk, etc..) is not part of the msys2 packages  
right now. Or perhaps hosted elsewhere, but anyway.

Would it be possible to add the gtk stack there?

There are instructions how to compile gtk on windows available here:

https://www.gtk.org/docs/installations/windows#using-gtk-from-msys2-packages

I can compile simple C and C++ programs via msys2 just fine; the resulting
.exe files work. I tried the above method but it failed for me at some linking 
step, but I also assume that something is wrong with my base system. I 
think I installed msys2 before but may not have cleaned it up correctly
when I installed a new msys2, but I am not certain. I will probably re-install
windows completely because I don't understand it (I am using linux most of
the time so windows runs only on my laptop which I do not use on a daily
basis).

I will then try the method listed at the GTK homepage again, but it would be
encouraging if someone else got this all figured out for the msys2-packages.

I think one may be able to download gtk already via msys2 pacman but I
also don't use pacman and would ideally love to avoid it  - I usually compile
from source on linux, which is, ironically, simpler for me (I can use LFS and
BLFS instructions and these work really well on my linux system; all my 
ruby-gtk code works fine. On windows right now I use libui though, but I'd
love to use gtk too, due to the CSS support in gtk3).

So, TL,DR:

- Please consider adding the MSYS2 packages for the GTK stack to this
repository as well and make sure that these work. (I am fine running
them via "pacman -S --needed base-devel msys2-devel; cd ${package-name};
makepkg" by the way. The thing is more that when this does not work then
I have no idea what to do, and I don't want to learn pacman when I really
don't need it; I am not an archie so ... right now msys2 is totally centric to
pacman, for better or worse. Better for those who like pacman, not so
good for those who don't, yet don't know the windows platform. I know
linux fairly well but on windows I am a real noob. I am just glad I can 
compile simple C programs! This part works fine. Not sure why linking
larger stuff does not work, but even the pkg-config output on windows
totally confuses me. I don't even know where anything is right now .... )

**Comment by Biswa96** [comment]
Those are in MINGW-packages. Search the package name here https://packages.msys2.org/search
