### ISSUE TITLE
openssh-8.8p1-1 upgrade somehow broke git ssh public key authentication.

### ISSUE THREAD

**Issue by bbholty1** [msys2/MSYS2-packages#2660]
git pulls and pushes worked fine before the update, and after the update all the repositories I use had key authentication failures:

E.g.
`--> git pull+++++++
git@bitbucket.wdc.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

After downgrading openssh to 8.7p1-1, git public key authentication started working again.
`--> pacman -U downloads/openssh-8.7p1-1-x86_64.pkg.tar.zst+
loading packages...
warning: downgrading package openssh (8.8p1-1 => 8.7p1-1)

Thanks!

**Comment by lazka** [comment]
Maybe this? https://gitter.im/msys2/msys2?at=6166ee62a41fd20699df5d80
