### ISSUE TITLE
pacman does not find libmetalink

### ISSUE THREAD

**Issue by sphoto** [msys2/MSYS2-packages#2688]
`pacman -Ss metalink` does not find the package although available (e.g. mingw-w64-x86_64-libmetalink-0.1.3-4-any.pkg.tar.zst)

**Comment by lazka** [comment]
The package got removed because it has no users anymore and the project is unmaintained for many years and has unfixed security issues.

**Comment by sphoto** [comment]
Need it to build wget with metalink support.

It would be very helpful if pacman shows a message  that the package was removed instead of no output.

**Comment by lazka** [comment]
I don't think pacman can do that.

you can install the last version via `pacman -U "https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-libmetalink-0.1.3-4-any.pkg.tar.zst"`

**Comment by lazka** [comment]
If you have a good reason to re-instate the support feel free to share your thoughts on that.

curl dropping support for it because of security reasons seemed like a good reason to get rid of it altogether back then.
