### ISSUE TITLE
Error when starting Python GUI script

### ISSUE THREAD

**Issue by cbrnr** [msys2/MSYS2-packages#2694]
I get an error when starting a Python GUI script from git-bash (which I believe uses msys2):

<img width="163" alt="Screenshot 2021-11-13 171000" src="https://user-images.githubusercontent.com/4377312/141650829-b5767f5a-2942-4806-86d0-1405c4a3c258.png">

This error does not occur when I start the same script from cmd or powershell.

## Steps to Reproduce the Problem

1. Install Python 3.9.8 for Windows (https://www.python.org/ftp/python/3.9.8/python-3.9.8-amd64.exe)
2. Install PySide2 with `pip install PySide2`
3. Download and unzip the files required for a minimal example: https://github.com/cbrnr/stderr-duplication/archive/refs/heads/main.zip
4. In a terminal, change into that directory and type `pip install .`
5. Type `mypackage` to run the script and get the error message

**Comment by Biswa96** [comment]
@dscho may provide some info.

**Comment by dscho** [comment]
I have _no_ idea where that is coming from.

**Comment by jeremyd2019** [comment]
https://github.com/pypa/pip/issues/10444 but that got closed for no response

**Comment by jeremyd2019** [comment]
I do vaguely remember caveats with GetStdHandle in GUI apps.  Seems odd that they would only have an issue with stderr though.

**Comment by cbrnr** [comment]
Thanks @jeremyd2019 for the find! That seems to be the same issue. It is definitely not related to some special install method because I have a package on PyPI that has the same behavior on Bash for Windows. I have also [asked on SO](https://stackoverflow.com/questions/66137439/python-gui-entry-point-not-working-on-bash-for-windows) but have not received any comments leading to a solution.

**Comment by jeremyd2019** [comment]
Some observations that may be interesting:
* all 3 handles (stdin, stdout, stderr) are 0 when GUI app is run from cmd.
* stdin and stdout are 0 but stderr is non-zero when GUI app is run from MSYS2 from Windows console, and DuplicateHandle fails on this non-zero handle with `ERROR_NOT_SUPPORTED`.
* all 3 handles are valid when GUI app is run from MSYS2 mintty.
* all 3 handles are 0 when GUI app is run via winpty (regardless of Windows console or mintty)
* `enable_pcon` option makes no difference.

**Comment by cbrnr** [comment]
I think this can be closed in favor of https://github.com/pypa/pip/issues/10444; let's continue the discussion over there.
