### ISSUE TITLE
Will msys2 work in Windows 11?

### ISSUE THREAD

**Issue by StandingPadAnimations** [msys2/MSYS2-packages#2698]
I'm thinking of upgrading to Windows 11 sometime this year or next year, but I want to make sure that things won't break in Windows 11.

Does msys2 break in Windows 11?

**Comment by mati865** [comment]
Had no issues with MSYS2, using Windows 11 since its premiere.

**Comment by naveen521kk** [comment]
Had no issues, using Windows 11 since last month.

**Comment by jayweaver1946** [comment]
Im having serious problems with msys2 on win11.
the installer for msys2 is not copying all the files into mingw64 directories.
all of the directories are empty after installation.
all directories seem to be there but nothing is in them!.

**Comment by Biswa96** [comment]
@jayweaver1946 Please follow the installation procedure from here https://www.msys2.org/
