### ISSUE TITLE
Looking for Python 3.7 Package for MSYS2

### ISSUE THREAD

**Issue by msarwar20** [msys2/MSYS2-packages#2711]
Hello everyone,

I need Python 3.7 package for MSYS2. The official package repository has only Python 3.8 and Python 3.9 packages.
I need to downgrade to Python 3.7 as one of my sources would compile only with Python 3.7.

Thanks.

**Comment by lazka** [comment]
We only have one active Python version, sorry.

**Comment by msarwar20** [comment]
> We only have one active Python version, sorry.

Hey,
Thanks for your reply. I found a workaround.

**Comment by mikiboii** [comment]
hey can u tell me what was the work around for installing python 3.7 in msys2

**Comment by Biswa96** [comment]
> hey can u tell me what was the work around for installing python 3.7 in msys2

python 3.7 is EOLed https://devguide.python.org/versions/
