### ISSUE TITLE
binutils: auto image base range overlaps cygwin heap

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MSYS2-packages#2723]
#2721 / #2722
python _random module ended up with a base of 0x80e100000 when rebuilt with gcc 11
> winsup/cygwin/heap.cc:  uintptr_t start_address = 0x800000000L;

cygwin heap seems to be 0x800000000-0x820000000
that's a side-effect of the increased entropy patch https://github.com/msys2/MSYS2-packages/blob/ce227e481dc52c185f44f9cd6cf94a0ccf451cc6/binutils/3000-more-base-entropy.patch#L7-L8
stock binutils wouldn't have came up with an auto image base above 0x5ffff0000 
the safest thing would be to reduce mask to 0x3ffff0000, would then stop at 0x7ffff0000, but I think that wasn't enough entropy last time

**Comment by lazka** [comment]
The last change in that area in cygwin gives a lot of background on what is supposed to be where: https://github.com/msys2/msys2-runtime/commit/e1254add73b1fb834933

**Comment by lazka** [comment]
> would then stop at 0x7ffff0000, but I think that wasn't enough entropy last time

yeah -> https://github.com/msys2/MSYS2-packages/pull/2494#issuecomment-837357367

**Comment by jeremyd2019** [comment]
Well, I don't know what can be done to fix it then.  The address space >= 0x8:00000000 is apparently already spoken for, and we just got lucky before.

**Comment by lazka** [comment]
rebuilding gettext triggers this for msys-intl-8.dll (don't try, it breaks everything): https://github.com/msys2/MSYS2-packages/pull/2747

**Comment by jeremyd2019** [comment]
Maybe the best thing would be to revert/remove that patch extending the auto image base range, and I guess try to come up with some other solution for conflicts?

**Comment by lazka** [comment]
yeah

**Comment by jeremyd2019** [comment]
Maybe #2721 / #2747 would work now?  I don't know about sed, I never looked at what was happening with that but seems fishy based on the timing...
