### ISSUE TITLE
Primary mirrors are slow

### ISSUE THREAD

**Issue by 89z** [msys2/MSYS2-packages#2726]
This seems to be a recent issue, as previously the speed was decent:

~~~
PS C:\> curl -L -O mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-1.1.1.l-1-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 36 4843k   36 1775k    0     0  64970      0  0:01:16  0:00:27  0:00:49 69172
~~~

Other primary slow too:

~~~
PS C:\> curl -L -O repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-1.1.1.l-1-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4843k  100 4843k    0     0   477k      0  0:00:10  0:00:10 --:--:--  747k
~~~

https://github.com/msys2/MSYS2-packages/blob/3e14b95280f5d98c32efbdf7ea6c1ce3f72ed050/pacman-mirrors/mirrorlist.mingw#L3-L5

**Comment by Biswa96** [comment]
repo.msys2.org works fine here. Primary mirrors may be geologically farther from your location than the mirror are being used at first.

**Comment by 89z** [comment]
@Biswa96 I agree, it seems upon second test that `repo.msys2.org`  has decent speed. I think the mirror should be changed on the website:

https://packages.msys2.org/package/mingw-w64-x86_64-openssl

**Comment by lazka** [comment]
@89z

* https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-1.1.1.l-1-any.pkg.tar.zst?mirrorlist&fromip=1.1.1.1
* Replace the IP at the end with your IP
* It should show you which mirrors are active for your region
* Which mirrors are those?

**Comment by 89z** [comment]
looks like just these two:

mirror.clarkson.edu
ftp.osuosl.org

**Comment by lazka** [comment]
ok, I've disabled mirror.clarkson.edu for now since it seems overwhelmed. Feedback welcome.

**Comment by 89z** [comment]
Still about half the speed of the other one:

~~~
PS C:\> curl -L -O mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-1.1.1.l-1-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4843k  100 4843k    0     0  1162k      0  0:00:04  0:00:04 --:--:-- 1619k

PS C:\> curl -L -O repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-1.1.1.l-1-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4843k  100 4843k    0     0  2718k      0  0:00:01  0:00:01 --:--:-- 2718k
~~~

but its definitely an improvement, thanks

**Comment by lazka** [comment]
US mirrors are hard to come by.. for some reason. thanks for testing.

**Comment by 89z** [comment]
Maybe contact some of the Cygwin US mirrors?

https://cygwin.com/mirrors.html

**Comment by lazka** [comment]
We have a new mirror now: https://mirror.umd.edu/msys2/

**Comment by lazka** [comment]
@89z how do these work now for you?

* https://mirror.umd.edu/msys2/mingw/mingw64/mingw-w64-x86_64-petsc-3.15.2-2-any.pkg.tar.zst (100MB)
* https://ftp.osuosl.org/pub/msys2/mingw/mingw64/mingw-w64-x86_64-petsc-3.15.2-2-any.pkg.tar.zst (100MB)

**Comment by 89z** [comment]
UMD is really good:

~~~
PS C:\> curl -O mirror.umd.edu/msys2/mingw/mingw64/mingw-w64-x86_64-petsc-3.15.2-2-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.7M  100 99.7M    0     0  8302k      0  0:00:12  0:00:12 --:--:-- 8657k
~~~

Other one is worse, but still good enough:

~~~
PS C:\> curl -O ftp.osuosl.org/pub/msys2/mingw/mingw64/mingw-w64-x86_64-petsc-3.15.2-2-any.pkg.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 99.7M  100 99.7M    0     0  1288k      0  0:01:19  0:01:19 --:--:-- 1197k
~~~

**Comment by lazka** [comment]
Yeah, I'm wondering if we should demote ftp.osuosl.org too.. in theory it's three servers with good connection.. but not sure..

**Comment by 89z** [comment]
I think its on the slow side, but good enough for my needs. My tool caches the downloads, so its not a huge deal, but the sub 1M speed I was originally getting was too slow.

**Comment by lazka** [comment]
Let's close this then. If there are any changes feel free to open a new issue.

**Comment by lazka** [comment]
We've re-enabled mirror.clarkson.edu now because they got a connection upgrade now, see https://github.com/msys2/msys2.github.io/issues/185

If there are any problems let us know.
