### ISSUE TITLE
prepending bash in address bar??

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#2744]
## Describe the issue

Feature request/discussion: 
prefixing `bash `  in the address bar of windows explorer should be able to open bash there, 
just like prefixing `cmd `  does.

## Steps to Reproduce the Problem

0. Open explorer
1. Go to address bar (press F4)
2. Move cursor to beginning of the line (home)
3. Type `cmd ` with space
4. Go to step 0, and repeat upto step 3, but with `bash ` in step 3.
5. Describe what happens?
Doing with `cmd ` opens cmd in that folder, while not in bash
4. What did you expect to happen instead?
If it makes sense, then bash should open in that directory too

## Environment
- OS: Windows 10 20H2 64bit]

**Comment by 1480c1** [comment]
There's a phony `/usr/bin/cmd` file that interferes with `cmd`, I personally just delete it, it has no real use afaik

**Comment by 1480c1** [comment]
Next, there's an environment variable called `CHERE_INVOKING`, you might want to export that to 1 or something that's not an empty string, that's from cygwin afaik https://conemu.github.io/en/CygwinStartDir.html

**Comment by 1480c1** [comment]
Oh wait, I never realized you could do the thing in Windows explorer with cmd, that's interesting

By default, with `bash` (so not specific to msys2), the first non-flag argument is going to be the shell script it will try to run. Normally speaking, when you run a script like `./test.sh`, it actually runs `/usr/bin/bash test.sh` (or `/usr/bin/sh test.sh` if the first line is `#!/usr/bin/sh` instead of `#!/usr/bin/bash`). There is no way afaik to do what you are wanting to do

**Comment by yashpalgoyal1304** [comment]
> the first non-flag argument

i also suspected that, and to test that, i did `cmd SOME-DIR` and it didnt work. which means, cmd doesnt accept that either it seems, which means that it uses some other way to do what it does.

and i filed this issue based on that.

**Comment by yashpalgoyal1304** [comment]
umh, but that address bar way is verrrrry verry hacky. and i dont think it will be worth it....

* i just thought to share the idea 'cz i want to be able to "open bash here" but the default explorer didnt provide a way for that...

* i tried using other explorers, and they had their own blocker/show stopper issue due to which i couldnt use those either....

**Comment by yashpalgoyal1304** [comment]
* alternate maybe to provide "(Open) Bash here" in the windows context menu 
* similar to options of "Git Bash here" or "Open PowerShell window here"

![image](https://user-images.githubusercontent.com/19423063/146528358-0e1d4c56-e5d5-4a2d-a526-13de43d4031b.png)

**Comment by cbrt64** [comment]
Thanks for learning me this awesome tip, it's faster than a context menu. They should call it the awesome bar! Oh wait that's Firefox. 🤦‍♂️

The right way to do this appears to be, _don't_ keep the folder name in the address bar. Explorer runs whatever command line you type, with the currently navigated folder as the new process's current working directory. Just plain `Alt+D / bash / Enter` will do what you want (which bash you get depends on your system's PATH of course).

More examples: `explorer ..` and `notepad foo.bat`. [See also](https://www.howtogeek.com/139900/stupid-geek-tricks-run-commands-in-the-windows-explorer-address-bar/).

**Comment by yashpalgoyal1304** [comment]
> Just plain `Alt+D / bash / Enter` will do

hi, yeah, i have tried that as well i think. anyways, retried it today, and no, it opened in .....

ohwww, wait. i was doing it in the home screen of My Computer/This PC... ahwkayh, and that's prolly why it opened in `/c/WINDOWS/system32`

i entered in a drive today, and it worked. thanks 👍

**Comment by cbrt64** [comment]
YW! Obligatory [ONT](https://devblogs.microsoft.com/oldnewthing/20170314-00/?p=95727); it works in web browsers too, see [What does Alt+D do?](https://www.computerhope.com/jargon/a/alt-d.htm)

**Comment by yashpalgoyal1304** [comment]
one more point to remember: 
use `mintty` in the editors (VSCodium, or other such) when you want to use bash in the external mintty terminal
(typing `bash` there just opens bash's instance in that inbuilt terminal itself)
