### ISSUE TITLE
sed: crashes after rebuild

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2748]
* rebuild `sed`

```
$ sed
Segmentation fault (core dumped)
```

```
Thread 1 "sed" received signal SIGSEGV, Segmentation fault.
0x0000000100000000 in ?? ()
(gdb) bt
#0  0x0000000100000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

No idea what to do next here.

**Comment by 1480c1** [comment]
time to build it in debug i guess

**Comment by lazka** [comment]
This is with debug

**Comment by 1480c1** [comment]
Oh, then that's going to be a pain

**Comment by lazka** [comment]
It crashes here: https://github.com/coreutils/gnulib/blob/a2c2b549a759952349baaffcaa37caa647d59e71/lib/localeinfo.c#L101 on the first loop iteration.

**Comment by lazka** [comment]
It's actually caused by this somehow: https://github.com/coreutils/gnulib/blob/3c99da63be95a3bc6cc881e1ca6c849a921569e1/lib/setlocale_null.c#L209

**Comment by lazka** [comment]
It's due to HAVE_WEAK_SYMBOLS being defined while it shouldn't.

**Comment by lazka** [comment]
https://git.savannah.gnu.org/cgit/gnulib.git/commit/m4?id=7818455627c5e54813ac89924b8b67d0bc869146
