### ISSUE TITLE
Unable to access network drive:  Too many levels of symbolic links

### ISSUE THREAD

**Issue by bll123** [msys2/MSYS2-packages#2753]
I uninstalled msys2 completely and made a new installation (since the signing keys were all mucked up).

Now I can no longer access the network drive (virtualbox drive).
I have tried mapping the networked drive to other drive letters, but that does not help.
Accessing  existing Windows drives works.

```
bll@bll-win81-64 MINGW64 ~
$ ls /z
ls: cannot access '/z': Too many levels of symbolic links

bll@bll-win81-64 MINGW64 ~
$ ls /f
'$RECYCLE.BIN'  'System Volume Information'
```

Edit: Windows 8.1

**Comment by jeremyd2019** [comment]
Yep, msys2/msys-runtime#58.  There's supposed to be a fix for that upstream, that I've cherry-picked but haven't gotten a chance to test yet.  Could you download the artifact from https://github.com/msys2/msys2-runtime/pull/73/checks, replace /usr/bin/msys-2.0.dll with the version in that (with no msys2 processes running, and keeping a backup copy!), and seeing if the fixes work for you?

**Comment by bll123** [comment]
Yes.  That artifact works.   Thanks.
