### ISSUE TITLE
32bit and windows 7 support

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [msys2/MSYS2-packages#2758]
it does not make sense to drop support for those on windows side... specially since its not hard to keep suporting those
and cygwin and wsl would already be running on win10 anyway

so removing support for 32bit and win7 is probabily removing support for those who most value your project :(

i always have put up good words for you guys... but its disappointing to see that you have plans to sink into the scum along cygwin... so please dont do that...

**Comment by brendanw36** [comment]
if it's so easy, why don't you just fork it and do it yourself?

**Comment by Kogarou-san** [comment]
The time is now. Dropping support for 32-bit OSes is likely to be a blessing for the lost souls working and maintaining this project.
64-bit programs are not the boogeyman you want to make everyone be afraid of, and if anything, they allow actual users to make use of more than 2/3/4GB of virtual address space, which has virtually no drawbacks _even in computers with <4GB of system RAM_; And the few there are are are massively outweighed by the benefits of running 64-bit programs on AMD64 CPUs with 64-bit OSes, brand-new innovations available to the average Joe **16 years** ago.
I wouldn't be surprised if >10% of the current users running MSYS2 in 32-bit OSes are this project's maintainers just for the sake of testing.
As for dropping support for Win7, something something new Win32 API functions in newer Win10 versions being useful to some people.
Your continuous attitude towards various unpaid volunteers giving their precious time for FOSS software can only be seen as whiny, narcissistic and clueless, at least for the outside observer. I feel sorry for them.
