### ISSUE TITLE
Add mirror:  mirrors.bfsu.edu.cn

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2775]
https://mirrors.bfsu.edu.cn/msys2

See https://github.com/msys2/MSYS2-packages/pull/2770

No rsync support.

We should also ask them to switch to rsync for syncing: https://mirrors.bfsu.edu.cn/status/

I noticed that our main server gets hammered from time to time with HEAD requests for all files from China.. maybe that is them. rsync would be more efficient.

**Comment by ZenithalHourlyRate** [comment]
> https://mirrors.bfsu.edu.cn/msys2
> 
> See #2770
> 
> No rsync support.
> 

rsync is supported
```
$ rsync rsync://mirrors.bfsu.edu.cn/msys2
drwxr-xr-x              7 2021/12/30 15:44:29 .
-rw-r--r--             11 2021/12/30 15:40:00 lastsync
-rw-r--r--             11 2021/12/30 15:36:50 lastupdate
drwxr-xr-x             15 2021/12/01 03:34:30 distrib
drwxr-xr-x             11 2021/07/02 14:52:30 mingw
drwxr-xr-x              5 2015/07/23 01:03:30 msys

```

> We should also ask them to switch to rsync for syncing: https://mirrors.bfsu.edu.cn/status/
> 

Will do.

> I noticed that our main server gets hammered from time to time with HEAD requests for all files from China.. maybe that is them. rsync would be more efficient.

**Comment by lazka** [comment]
oh, nice, thanks ❤️

**Comment by lazka** [comment]
> FYI, You may refer to https://mirrorz.org/list/msys2 to find more mirrors from China. We have notified some of them on switching from http to rsync

Thanks, I found one more, added in #2777

mirrors.bfsu.edu.cn has been added to the mirrorlist file, the mirrorbits server and the website.

**Comment by lazka** [comment]
@ZenithalHourlyRate

just a heads up that there are various new rsync vulnerabilities disclosed today, which also affect read-only public rsyncd mirror setups like yours:
https://www.openwall.com/lists/oss-security/2025/01/14/3

In case of Debian, which also updated the protocol version to v31 to v32 as part of the backports, the following should show 32.0 with the fixes in place (replace the domain with your rsync mirror domain):

```
$  timeout 1 telnet repo.msys2.org 873 | grep @RSYNCD
@RSYNCD: 32.0 sha512 sha256 sha1 md5 md4
```

**Comment by lazka** [comment]
mirrors.bfsu.edu.cn rsync and http are out of sync, and http gives outdated data.

<img width="718" height="139" alt="Image" src="https://github.com/user-attachments/assets/f7fa3999-4a1c-400b-a139-9c1250f5453a" />

```
$ rsync --no-motd rsync://mirrors.bfsu.edu.cn/msys2/msys/x86_64/msys.db
lrwxrwxrwx             15 2026/08/20 09:05:10 msys.db
```

I'll have disable it for now, as that leads to package downgrades.
