### ISSUE TITLE
RFC: Better license strings in packages

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#2776]
Status quo:

* Arch is limited to these standardized licenses: https://archlinux.org/pacman/PKGBUILD.5.html https://archlinux.org/packages/core/any/licenses/ with many variants missing
* Everything else needs to be marked as "custom:xxx", with no defined naming, or use the default, slightly wrong licenses. For example what is GPLv2-only?
* It's not clear if multiple licenses mean they both apply together or either one of them applies.
* There was a short discussion on the Arch mailing list, but I think nothing came of it: https://lists.archlinux.org/pipermail/arch-dev-public/2019-October/029695.html

My suggestion:

* We use SPDX specifiers: https://spdx.org/licenses/
* We prefix them with "spdx:GPL-2.0-only" to avoid namespacing issues and make it clear what they mean
* For multiple licenses we follow what composer does: https://getcomposer.org/doc/04-schema.md#license

**Comment by umarcor** [comment]
I like the proposal to use SPDX specifiers and prepend them with `spdx:`.

There is a use case which I'd like to bring attention to: using a license for the tool and a different license for the docs, or for some specific module/library. According to the composer solution, that'd be `X and Y`, however, I wonder if we can do better with a dictionary:

```json
{
    "license": {
       "main": "spdx:Apache-2.0",
       "doc": "spdx:CC-BY-4.0",
       "thirdparty/lib": "spdx:MIT"
    }
}
```

**Comment by lazka** [comment]
The license field in PKGBUILD is limited to an array, so not sure. Debian has more complicated system with https://dep-team.pages.debian.net/deps/dep5/ but from my experience this makes things too complicated so it's more often than not wrong or outdated.

The license field can be set on each package separately though, so on split packages you could have different licenses (say libfoo and libfoo-doc).

**Comment by umarcor** [comment]
@lazka, fair enough!

**Comment by lazka** [comment]
@umarcor re multiple licenses in the same package: I found a similar example in the Python docs with vendored deps with different licenses using spdx: https://www.python.org/dev/peps/pep-0639/#advanced-example

**Comment by lazka** [comment]
I've summarized things here: https://www.msys2.org/wiki/package_licensing (I might move the page to a better place later)
