### ISSUE TITLE
Package update delays due to the number of automake versions involved

### ISSUE THREAD

**Issue by ferdnyc** [msys2/MSYS2-packages#2788]
I'm glad to see the effort being undertaken (in #2745) to pare down the `base_devel` group, and have packages more explicitly depend on what they need.

But for `automake`, typically `automake-wrapper` gets pulled in by some legacy build tool, bringing with it **eleven** different versions of `automake` as separate, tiny packages. Including `automake-wrapper` itself, that makes for an even dozen packages found on the typical MSYS2 build system.

I think we're all aware that `pacman` can be somewhat slow, on Windows.In particular, update/install transactions incur a rather significant _per-package_ speed penalty in many instances.

### Real-world impacts

Which is why, every time @eine, @Ecco, and friends' excellent msys2/setup-msys2 action spins up an MSYS2 environment for my CI builds, and that environment does a package update, I'm treated to the sight of automake version after automake version being ticked off, slowly one at a time like the second hand of a wristwatch, seeming impossibly slow given that automake1.6 is < 300K packaged (~800K installed) and automake1.16 only raises that to ~500K (~1.5M).

Is 13 seconds a lot of time? No, in the grand scheme of things it isn't.

But 13 seconds _per run_ (actually, _per job_, per run, per repo, per PR) does start to add up pretty quickly, and those package-transaction times are all factors in why our project's Windows CI jobs take nearly 11 minutes just to complete the **setup phase** of each run — meaning, they still haven't even _started_ compiling before the Linux jobs _complete_ their entire 8-minute run. (The full Windows runs clock in at over 25 minutes.)

Now, I want to stress that I'm **not** trying to turn this into a Windows-vs-Linux speed trial, and I fully understand the many realities of why builds on Windows will, and should, always take more time. My only motivation here is to examine a particular transaction that adds significant time to MSYS2's update process, to see if there might be opportunities for optimization.

### Some context

(I'm  not exaggerating the impact, either. In fact, I'm understating it. Here's an excerpt from one of my [actual CI jobs](https://github.com/ferdnyc/libopenshot/runs/4686669745?check_suite_focus=true) earlier today: A hair shy of 20 seconds, total, just to update 11 separate automake versions. Not even counting download time.)
```console
Mon, 03 Jan 2022 00:09:31 GMT upgrading automake1.6...
Mon, 03 Jan 2022 00:09:32 GMT upgrading automake1.7...
Mon, 03 Jan 2022 00:09:34 GMT upgrading automake1.8...
Mon, 03 Jan 2022 00:09:36 GMT upgrading automake1.9...
Mon, 03 Jan 2022 00:09:38 GMT upgrading automake1.10...
Mon, 03 Jan 2022 00:09:39 GMT upgrading automake1.11...
Mon, 03 Jan 2022 00:09:41 GMT upgrading automake1.12...
Mon, 03 Jan 2022 00:09:44 GMT upgrading automake1.13...
Mon, 03 Jan 2022 00:09:45 GMT upgrading automake1.14...
Mon, 03 Jan 2022 00:09:47 GMT upgrading automake1.15...
Mon, 03 Jan 2022 00:09:48 GMT upgrading automake1.16...
Mon, 03 Jan 2022 00:09:50 GMT upgrading automake-wrapper...
```
(Each of the `automake` packages fires off its own separate `install-info` in its post_install, which I thought might've explained the slowness... but that command is virtually instantaneous on my local system, so it doesn't seem to be an issue.)

### For your consideration

So, the issues I'd be grateful to hear your thoughts on are:

1. **Does MSYS2 _really_ need ELEVEN different `automake` versions?**

    Even Debian/Ubuntu trimmed it down to only two. (Debian bullseye and Ubuntu 20.04 offer their default `automake` (aka `automake-1.15`), plus an additional `automake1.11` legacy/compatibility package. But that's it, just the two.) I'm well aware of the issues with newer releases, and of the need to keep earlier versions available for older packages to continue building. But this feels excessive.

2. **Even more importantly, does _every_ individual automake version need to be a _completely separate_ package?**

    Since `automake-wrapper` pulls them all in en masse, and is probably the main reason most systems have all of those packages installed, couldn't `automake1.6` through `automake1.15` (or some subset) be combined into a single `automake-compat` package, for `automake-wrapper` to depend on? Or they could even be rolled directly _into_ the `automake-wrapper` package itself. A single combined package should take a fraction of the time it takes to install 11 separate ones.

3. (More generally, beyond this immediate particular concern...) **Are there other transaction activities that impact `pacman` task runtimes, and are there potential changes that could be implemented to reduce transaction delays?**

    Other than a surprising number of packages that run `install-info` post-transaction (which like I said doesn't seem  to be a problem), I can see that MSYS2/MinGW packages are mostly devoid of unnecessary busywork, so I don't have any suggestions to offer regarding streamlining.

Obviously this is hardly something you're all unaware of, or that you haven't been paying any attention to all along — that's not at all what I'm trying to imply. If eleven automake packages are an outlier, and the rest of the package collection has had every last drop of speed squeezed out of it already, then there's nothing more that can be done.  `¯\_(ツ)_/¯`

(I'd still like to get my 20 seconds back, though. Die, automakes 1.6 through 1.14, die!)

**Comment by lazka** [comment]
I'm still trying to figure out how all autotools stuff is connected... so did things one step at a time.

thanks for the writeup.

**Comment by lazka** [comment]
ah, you are using the existing msys2 install on the GHA image. I guess that should improve when they update it (not sure how often that happens). Why don't you use a fresh install?

**Comment by lazka** [comment]
OK, I think I understand our current setup a bit better now.

We can definitely drop <1.11 and remove the install scripts, but the whole automake-wrapper part (borrowed from gentoo) seems quite nice given the autotools version mess, so I'd rather keep it. They even have a autoconf wrapper too which we could borrow.

As for your specific situation:
* You can switch to the windows-2022 CI image (`runs-on: windows-2022`) which has a leaner MSYS2 by default -> fewer updates
* You can tell the GH action to use a fresh install via `release: true`
* You can disable updates in the GHA via `update: false`

**Comment by lazka** [comment]
> We can definitely drop <1.11 and remove the install scripts

this is now done

**Comment by lazka** [comment]
> They even have a autoconf wrapper too which we could borrow.

I started this in https://github.com/msys2/MSYS2-packages/pull/2810

**Comment by lazka** [comment]
Either way, see https://github.com/msys2/MSYS2-packages/issues/2788#issuecomment-1005468906 for suggestions on how to improve your situation.

If there is anything slower as expected still, let us know.

**Comment by ferdnyc** [comment]
@lazka 
- You can switch to the windows-2022 CI image (runs-on: windows-2022) which has a leaner MSYS2 by default -> fewer updates
- You can tell the GH action to use a fresh install via release: true -> fewer updates

Thanks, I'll look into both of those. Turning off updates wasn't working out for us because we install a lot of additional packages. We ended up having problems due to version mismatches, unless the preinstalled set was up to date first. So for our builds, you may be right that starting fresh would be the better option.

Thanks for the changes you've already made in response, though, I think they'll improve the situation for everyone. (Which was part of my larger goal here, our _particular_ situation was merely used as an example.)

**Comment by lazka** [comment]
Thanks.

One more thing, the delta of updated packages that need to updated from a base install is very large atm because of the recent dependency cleanup. Once a new installer is out things should be faster again.

**Comment by ferdnyc** [comment]
Yeah, I noticed there's an ebb and flow to this, as packages are updated past the set that was rolled into the most recent preinstall image. Which makes sense, it's just kind of the nature of rolling-release anything.

**Comment by ferdnyc** [comment]
@lazka et al.

I need to confirm these numbers with some additional CI runs, since GitHub Actions execution times can vary a great deal based on overall system load, time of day, day of the week, etc.)... but, here are some very preliminary results:

* Switching to the `windows-2022` image seems to buy us next to nothing. (`9m 4s` setup time as opposed to `9m 13s`, effectively equal as `9s` is well within the margin of error)
* However, setting `release: true` and installing everything from scratch looks like it may potentially shave almost three full minutes off that time, down to `6m 12s`. 
* And that's _without_ a package cache — so, even including download times. When `setup-msys2` is able to restore a recent saved cache, that drops down further to `4m 52s`.

Somewhat surprisingly (well, it surprised me), even though _this_ is our additional package set:
```yaml
          install: >-
              mingw-w64-x86_64-gcc
              mingw-w64-x86_64-lld
              mingw-w64-x86_64-make
              mingw-w64-x86_64-cmake
              mingw-w64-x86_64-pkgconf
              mingw-w64-x86_64-qt5
              mingw-w64-x86_64-libvpx
              mingw-w64-x86_64-ffmpeg
              mingw-w64-x86_64-zeromq
              mingw-w64-x86_64-opencv
              mingw-w64-x86_64-protobuf
              mingw-w64-x86_64-babl
              mingw-w64-x86_64-catch
              mingw-w64-x86_64-python3
              mingw-w64-x86_64-swig
```
...which expands to 204 packages after dependency resolution, it appears that it's still faster to just install all 204 from scratch on a blank slate, than it is to first update a preinstalled set and _then_ install additional packages on top of that. So, if nothing else that's good information to have! :+1: 

Like I said, the final numbers may shift a bit one way or the other. The times above are just the results of a single run of each type. (Meaning one each of: `windows-2022`, `windows-2022 + release`, `windows-2022 + release + hot cache`.) In order to make a fair comparison and eliminate external effects as much as possible, I need to do a few more runs of each type and compare their best-run times.

But I can't imagine the `release: true` path ending up _slower_ than the update-and-install path... it's just a question of _how much_ faster it really is to go that route.

**Comment by umarcor** [comment]
@ferdnyc although not critical, you might want to reduce the verbosity through:

```yml
          pacboy: >-
              gcc:p
              lld:p
              make:p
              cmake:p
              pkgconf:p
              qt5:p
              libvpx:p
              ffmpeg:p
              zeromq:p
              opencv:p
              protobuf:p
              babl:p
              catch:p
              python3:p
              swig:p
```

See https://github.com/msys2/setup-msys2#pacboy.

**Comment by lazka** [comment]
> I need to confirm these numbers with some additional CI runs, since GitHub Actions execution times can vary a great deal based on overall system load, time of day, day of the week, etc.)... but, here are some very preliminary results:

They also have 5 different types of machines, some are 50% faster than others.

> Switching to the windows-2022 image seems to buy us next to nothing. (9m 4s setup time as opposed to 9m 13s, effectively equal as 9s is well within the margin of error)

That's a bit surprising, do you have a job link?

> Somewhat surprisingly (well, it surprised me), even though this is our additional package set:

Note that last year we split up the "qt5" package into the separate qt5 components. qt5 is now a meta package depending on all of them for backwards compat. If you depend on the specific components instead it could speed up your install: https://packages.msys2.org/package/mingw-w64-x86_64-qt5

**Comment by ferdnyc** [comment]
@lazka 
> > Switching to the windows-2022 image seems to buy us next to nothing. (9m 4s setup time as opposed to 9m 13s, effectively equal as 9s is well within the margin of error)
> 
> That's a bit surprising, do you have a job link?

Surprising because it wasn't true. Additional runs showed that the `9m 4s` time was an exceptionally slow outlier. Using `windows-2022` helps _some_ (it shaves maybe a minute off, on average), though still not even remotely as much as things like `release: true`, or...

> Note that last year we split up the "qt5" package into the separate qt5 components. qt5 is now a meta package depending on all of them for backwards compat. If you depend on the specific components instead it could speed up your install: https://packages.msys2.org/package/mingw-w64-x86_64-qt5

I had not spotted that, and it does indeed make all the difference in the world. Our builds actually only need a tiny subset of the Qt modules, in fact, and none of the big, hairy ones. I was able to prune the set we install down to just these:
```
mingw-w64-x86_64-qt5-base
mingw-w64-x86_64-qt5-svg
mingw-w64-x86_64-qt5-winextras
mingw-w64-x86_64-qt5-tools
```
(I think I also need to put `mingw-w64-x86_64-qt5-imageformats` back in, but currently it's not listed.)

Tossing out the rest of the Qt modules, along with any unique dependencies they were pulling in, dropped the count of packages in the resolved set down from 204 to 168. My most recent build, assisted by the setup action's automatic package caching, got through `setup-msys2` in `3m 43s` total. The entire Windows job took `19m 36s` which isn't the quickest time I've seen lately, even... but considering it's down from a normal range of `28m` - `32m` a week ago, it's still pretty amazing. Thanks again for all of the assistance.

(In fact, this leaves our Windows builds completing significantly faster than the macOS jobs, so I guess now I get to go harass the Homebrew devs instead. :wink: )

Considering what a difference it made dropping the unnecessary Qt dependencies, if anyone's looking for additional packages to target for a break up/out, my picks would be:

* **ffmpeg's `libavdevice`**
    Debian splits out _all_ of the libraries into individual packages, but they're so interdependent that the benefits there are debatable. However, many distros that package all the rest together still break out `libavdevice`. It's only required to do things that involve hardware I/O; like reading from capture devices, cameras, or physical media — and notably, **not** required for GPU de/encoding — so it's unnecessary for most video-processing applications. Plus it has a lot of unique dependencies: libbluray, libcdio, openal... dropping it lets you drop all of _those_ as well.

* **OpenCV, to whatever extent possible**
    The monolithic OpenCV package not only pulls in a _lot_ of dependencies, but many of them are esoteric and (for our purposes) completely useless ones, things that are only required by a very narrow audience. For example, if I'm using OpenCV's neural-net object recognition and tracking to process video streams, I can absolutely guarantee `tesseract-ocr` will not be needed — but it's a required dependency, so in it goes.

  I don't really know how feasible breaking up OpenCV's packaging would be, but it'd be great if it can be done. Splitting the core package from -contrib I would think is probably doable, since they're even distributed separately. (They're currently being combined to create `mingw-w64-*-opencv`.) That alone wouldn't help us, as we're using modules from -contrib, but it might be useful to others. The -contrib modules are where a lot of the weird, niche dependencies get pulled in, so breaking -contrib up into _multiple_ packages would be the real win.
