### ISSUE TITLE
Installing "info" into new root: "cygpath: error converting "C:\Windows" - No such file or directory", lots of output

### ISSUE THREAD

**Issue by mitchhentges** [msys2/MSYS2-packages#2793]
## Describe the issue

I believe this is caused by [the changes updating `info`'s hooks](https://github.com/msys2/MSYS2-packages/commit/1184d42ee9a3d4fed5362a6a3894f770af9bcadb#diff-b27228a5b21ade8e59a94810365df5e6046637603f9a9c43a33436392f1edf8b), maybe (edit: `pacman -U --root . <info-6.8-1>` succeeds, so I'm pretty confident that this issue is specific to the `info-6.8-2` release).
When I install `info` into a freshly-bootstrapped environment, I see the following error, and a lot of `$path -> /home/Mitch/$path` lines.

```
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
cygpath: error converting "C:\Windows" - No such file or directory
ln: failed to create symbolic link '/dev/stdin': No such file or directory
ln: failed to create symbolic link '/dev/stdout': No such file or directory
ln: failed to create symbolic link '/dev/stderr': No such file or directory
ln: failed to create symbolic link '/dev/fd': No such file or directory
ln: failed to create symbolic link '/etc/mtab': No such file or directory
Copying skeleton files.
These files are for the users to personalise their msys2 experience.

They will never be overwritten nor automatically updated.

'./clang32.ico' -> '/home/Mitch/clang32.ico'
'./clang64.ico' -> '/home/Mitch/clang64.ico'
'./clangarm64.ico' -> '/home/Mitch/clangarm64.ico'
/usr/bin/install: creating directory '/home/Mitch/etc'
'./etc/bash.bashrc' -> '/home/Mitch/etc/bash.bashrc'
'./etc/bash.bash_logout' -> '/home/Mitch/etc/bash.bash_logout'
<snip>
```

Note that this also happens from within the MSYS2 environment (`pacman` doesn't have to be called from a win32 context to repro)

## Steps to Reproduce the Problem

1. `mkdir new-env && cd new-env && mkdir -p tmp var/lib/pacman var/log
2. `pacman -Sy --noconfirm --root . msys2-runtime bash coreutils filesystem findutils info`
3. Post-install hooks throw unexpected errors

## Additional Context: Operating System, Screenshots

```
Edition	Windows 10 Home
Version	21H2
Installed on	‎2021-‎09-‎05
OS build	19044.1415
Experience	Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by jeremyd2019** [comment]
looks like using a login shell in the hook had unanticipated side effects (like running the on-first-login scripts for a new root)

**Comment by jeremyd2019** [comment]
I'm guessing this also did bad things to the nightly installer - it got a heck of a lot larger than it was.

**Comment by jeremyd2019** [comment]
I'm guessing this also did bad things to the nightly installer - it got a heck of a lot larger than it was.

**Comment by lazka** [comment]
uh, oh :( I'll revert this

**Comment by lazka** [comment]
revert is in the repo
