### ISSUE TITLE
Installing base-devel does not install all packages listed at https://packages.msys2.org/group/base-devel

### ISSUE THREAD

**Issue by martinwhitaker** [msys2/MSYS2-packages#2794]
This is probably due to your ongoing base-devel package cleanup. That's causing me grief, as it keeps breaking the CI for the project I help maintain.

**Comment by jeremyd2019** [comment]
For the reason, there is now a package called `base-devel`, and packages take precedence over groups with the same name.  What is 'included' are the dependencies of the base-devel package: https://packages.msys2.org/package/base-devel?repo=msys&variant=x86_64

**Comment by lazka** [comment]
I'll try to add this to the NEWS entry.

Sorry for the inconvenience @martinwhitaker

**Comment by lazka** [comment]
d59571bf8efb5072
