### ISSUE TITLE
MSYSTEM_CHOST is incorrect in mingw64 env

### ISSUE THREAD

**Issue by alphonsetai** [msys2/MSYS2-packages#2796]
current msystem:

> MINGW64)
        MSYSTEM_PREFIX='/mingw64'
        MSYSTEM_CARCH='x86_64'
        MSYSTEM_CHOST='x86_64-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
        ;;

when build ffplay with sdl2, configure will link mingw32.lib.

when i fix MSYSTEM_CHOST :
MSYSTEM_CHOST='x86_64-w64-mingw64'

link is correct.

**Comment by Biswa96** [comment]
Was the issue solved?

**Comment by alphonsetai** [comment]
> Was the issue solved?

no, maybe mingw-w64-x86_64-SDL2 package have some error .
i try found out problem again

because "sdl2-config --libs" result:
-LC:/msys64/mingw64/lib -lmingw32 -lSDL2main -lSDL2 -mwindows

i can't search mingw32.lib or mingw64.lib

**Comment by Biswa96** [comment]
It is provided by mingw-w64-crt package. You need to install mingw-w64-x86_64-toolchain group package. Also that file name is libmingw.a. For example, here is the details in ucrt64 environment. 

```
$ pacman -F /ucrt64/x86_64-w64-mingw32/lib/libmingw32.a
ucrt64/x86_64-w64-mingw32/lib/libmingw32.a is owned by ucrt64/mingw-w64-ucrt-x86_64-crt-git 9.0.0.6373.5be8fcd83-1
```

**Comment by alphonsetai** [comment]
> 

i was install mingw-w64-x86_64-toolchain, but i can't found libmingw32.a or other same lib

**Comment by alphonsetai** [comment]
> It is provided by mingw-w64-crt package. You need to install mingw-w64-x86_64-toolchain group package. Also that file name is libmingw.a. For example, here is the details in ucrt64 environment.
> 
> ```
> $ pacman -F /ucrt64/x86_64-w64-mingw32/lib/libmingw32.a
> ucrt64/x86_64-w64-mingw32/lib/libmingw32.a is owned by ucrt64/mingw-w64-ucrt-x86_64-crt-git 9.0.0.6373.5be8fcd83-1
> ```

thx, i found it.
ffmpeg configure error , it's look likes i need some config for msys2 + vs2017_env_cli(--toolchain=msvc)
