### ISSUE TITLE
[mingw-w64-cross-binutils] locks up while building

### ISSUE THREAD

**Issue by stahta01** [msys2/MSYS2-packages#2807]
I am trying to build mingw-w64-cross-binutils under Window 7 64 bit and it locks up during
ld/genscripts.sh in x86_64-pc-mingw32 target.

I edited just the pkgrel and tried to see if server can build it. It has been running 4.5 hours when does it give up?

Tim

**Comment by stahta01** [comment]
It failed at 6 hours running on the github CI server

**Comment by jeremyd2019** [comment]
GHA hosted runners time out jobs at 6 hours.

I wonder if this is related to msys2/msys2-runtime#77?

**Comment by stahta01** [comment]
Could be related; but, I am not sure. I am trying to build the package locally using an upgraded version of binutils and if that works; I would say it is not the same problem. Be likely a few hours before build locks up or fails. Tim S.

**Comment by stahta01** [comment]
The build worked using version 2.37; so, it is not the same problem.

Tim S.
