### ISSUE TITLE
git-http-push.exe not found in git-2.34.1-1-x86_64.pkg.tar.zst

### ISSUE THREAD

**Issue by piotrvv** [msys2/MSYS2-packages#2818]
![printscreen](https://user-images.githubusercontent.com/38948025/150641106-c01388f6-75d3-4ce4-91ae-411ee83107f0.jpg)

**Comment by lazka** [comment]
Looking at the build logs I don't see anything suspicious: https://github.com/msys2/msys2-autobuild/commit/310a1fa4e41deffece9d0b8ded83cd0c81a127c1/checks/4318563454/logs

**Comment by piotrvv** [comment]
I have rebuilt the git package. The effect was that it was bigger, which interested me. I noticed that this file is missing.[usr/lib/git-core/git-http-push](https://archlinux.org/packages/extra/x86_64/git/files/)

**Comment by lazka** [comment]
see https://github.com/msys2/MSYS2-packages/pull/2819

translations are missing though now, I'll need to look

**Comment by piotrvv** [comment]
This may help to solve other problems with the git package as well.

**Comment by lazka** [comment]
Will be fixed in the next upload, thanks for the report.

**Comment by lazka** [comment]
done

**Comment by piotrvv** [comment]
Thanks

**Comment by piotrvv** [comment]
It would be worth checking other packages after the latest fixes in msys-runtime. I believe some files in packages were built but not added to the package in the end.

**Comment by lazka** [comment]
Which fix do you mean? Why would some files be missing?

**Comment by piotrvv** [comment]
msys2-runtime: a directory with .lnk suffix is not a .lnk file #2817

**Comment by lazka** [comment]
Which file?

**Comment by piotrvv** [comment]
git-http-push.exe

**Comment by lazka** [comment]
git-http-push.exe was missing because of the missing libexpat dependency.

**Comment by piotrvv** [comment]
My server found it not only without these dependencies.

**Comment by lazka** [comment]
That can't be, git doesn't build git-http-push without libexpat: https://github.com/git/git/blob/297ca895a27a6bbdb7906371d533f72a12ad25b2/configure.ac#L584

**Comment by piotrvv** [comment]
My server builds your packets for me on demand. Therefore, I found this file without adding dependencies in the PKGBUILD file.

**Comment by piotrvv** [comment]
The tests show that the file is building but does not work properly.

**Comment by jeremyd2019** [comment]
This is more likely a result of the changing of what packages are installed with `base-devel` than of the change to msys2-runtime.  If your server just updates, rather than doing a clean install of msys2, it may still have the packages installed that were members of base-devel at the time you set it up.  (Now that base-devel is a package rather than a group, if things are removed from it moving forward they will show up in `pacman -Qtd` as unrequired dependencies).

**Comment by piotrvv** [comment]
I prepare many packages for programmers, I make sure that they have the most up-to-date tools. If I don't leave package files installed before build this is not possible. I have many different tools and when something is built it is always done from scratch.
