### ISSUE TITLE
Resizing the terminal window using zsh freezes the prompt

### ISSUE THREAD

**Issue by Lycolia** [msys2/MSYS2-packages#2820]
## Describe the issue

Resizing the terminal window while using zsh freezes the prompt

### Case 1

in Windows Terminal

1. `C:/env/msys64/msys2_shell.cmd -mingw64 -defterm -here -use-full-path -no-start -shell zsh`
2. Launch Windows Terminal
3. Resize window
4. Press Return Key
5. New prompt not shown

### Case 2

in VSCode

1. Launch VSCode
2. Resize terminal
3. Press Return Key
4. New prompt not shown

#### settings.json

```json
"terminal.integrated.defaultProfile.windows": "MSYS2",
"terminal.integrated.profiles.windows": {
    "MSYS2": {
        "overrideName": true,
        "path": ["C:\\env\\msys64\\msys2_shell.cmd"],
        "args": [
            "-defterm",
            "-here",
            "-use-full-path",
            "-no-start",
            "-mingw64",
            "-shell",
            "zsh"
        ]
    },
}
```

## Additional Context: Operating System, Screenshots

This issue did not occur in Ubuntu 20.04.3 LTS terminal with zsh

### Operation System

-   Windows 11 22000.434
-   Windows 10 19043.1466

### Terminal

-   Windows Terminal 1.11.3471.0
-   VSCode 1.63.2

### .zshrc

```sh
current_git_branch() {
  (git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/')
}

parse_git_dirty() {
  local DIRTY=$(command git status -s | tail -1)
  if [[ -n $DIRTY ]]; then
    echo "%{$fg_bold[magenta]%})%{$fg_bold[red]%}✗"
  else
    echo "%{$fg_bold[magenta]%})%{$fg_bold[blue]%}✓"
  fi
}

print_git_prompt() {
  local FIND_BRANCH=$(command git branch 2> /dev/null | tail -1)
  if [[ -n $FIND_BRANCH ]]; then
    echo "%{$fg_bold[magenta]%}(%{$reset_color%}%{$fg_bold[yellow]%}"$(current_git_branch)$(parse_git_dirty)" %{$reset_color%} "
  else
    echo ""
  fi
}

if [ "$USERNAME" = "root" ]; then
  CARETCOLOR="red";
else
  CARETCOLOR="magenta";
fi

PROMPT="
%{$fg_bold[cyan]%}%n%{$reset_color%}%{$fg_bold[blue]%}@%m%{$reset_color%}:%{${fg_bold[green]}%}%~%{$reset_color%}
%(?:%{$fg_bold[green]%}➜:%{$fg_bold[red]%}➜)  %{${reset_color}%}"'$(print_git_prompt)'
# The following changes will prevent it from freezing
# But it doesn't work properly
# '$(print_git_prompt)' -> $(print_git_prompt)

RPS1="%(?..%{$fg_bold[red]%} [ %? ]%{$reset_color%}) %D - %*"
```

**Comment by hdk5** [comment]
Can confirm. The issue is also reproducible on plain old conhost.exe.

I use [starship](https://github.com/starship/starship), and the freeze could be triggered with the default minimal starship configuration.
The freeze does not happen on bash in MSYS2 or zsh in WSL, or with empty .zshrc on zsh in MSYS2.

**Comment by Lycolia** [comment]
I looked up the smallest case to reproduce
This has been confirmed on Windows Terminal and Ubuntu 20.04.3 LTS terminal(not WSL, native Linux)

## git command pattern

| Windows Terminal     | Ubuntu Terminal                                             |
| -------------------- | ----------------------------------------------------------- |
| Freezes when resized | Prompt for each resize<br />And doesn't freeze when resized |

```sh
setopt PROMPT_SUBST
PROMPT='$(git branch)'
```

## date command pattern

| Windows Terminal            | Ubuntu Terminal             |
| --------------------------- | --------------------------- |
| Doesn't freeze when resized | Doesn't freeze when resized |

```sh
setopt PROMPT_SUBST
PROMPT='$(date)'
```

## Invalid command pattern

| Windows Terminal                                            | Ubuntu Terminal                                             |
| ----------------------------------------------------------- | ----------------------------------------------------------- |
| Prompt for each resize<br />And doesn't freeze when resized | Prompt for each resize<br />And doesn't freeze when resized |

```sh
setopt PROMPT_SUBST
PROMPT='$(aaa)'
```

**Comment by hdk5** [comment]
@Lycolia 

Oh, is your `git`, by a chance, is a `git for windows`, and not `git` from `msys` repository?
Because, with the minimal case you provided, it does not reproduce with `msys/git`, but is reproducible with `git-for-windows/mingw-w64-x86_64-git`

**Comment by Lycolia** [comment]
@hdk5 
Has been solved!
Thank you, this was unexpected!
This problem occurred in `git-for-window` but did not reproduce in `msys/git`

**Comment by hdk5** [comment]
@Lycolia Glad this worked for you.

However, it feels more like a workaround for me, and I still would like to have a way to run `mingw-w64-x86_64-git` from my zsh prompt (e.g. for a performance and compatibility reasons).

I'll keep looking for a proper solution.

**Comment by Lycolia** [comment]
Finded a issue that `msys2/git` cannot keep the auth of GitHub
It's terribly annoying to type every time

**Comment by Lycolia** [comment]
oops...
- #500

**Comment by Lycolia** [comment]
In `msys2/git` the following command fails
`mkdocs gh-deploy`

```
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git log --date=short --format=%at -n 1 D:\path\to\file.md
  stderr: 'fatal: invalid object name '"D'.'
```
