### ISSUE TITLE
pacman: unknown option -- a

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MSYS2-packages#2828]
## Describe the issue
In msys2-x86_64-20220128.exe, I could not install ffmpeg by using pacman command

![QQ截图20220129092009](https://user-images.githubusercontent.com/48978473/151641702-ceb9faf0-081b-47ad-96e5-4aae23879170.png)

**Comment by Biswa96** [comment]
From the screenshot, it looks to you are using MSYS2 environment where the MINGW_PACKAGE_PREFIX environment variable is not set. Run mingw* or clang* launcher to install packages for that environment.

Alternatively you can use pacboy tool. It's a thin wrapper around pacman. Run `pacman -S pacboy` to install pacboy. Then, for example, open mingw64 launcher and run `pacboy -S ffmpeg:p` to install mingw-w64-x86_64-ffmpeg package.

**Comment by zhangjp0405** [comment]
![微信截图_20220129143552](https://user-images.githubusercontent.com/48978473/151650563-28c283ce-1bf1-4c78-a58f-ccf54d2c6859.png)

**Comment by Biswa96** [comment]
Opps! My apology, the package name is pactoys. The command is `pacman -S pactoys`.

**Comment by zhangjp0405** [comment]
![微信截图_20220129144433](https://user-images.githubusercontent.com/48978473/151650783-aa8f5347-b214-4e87-a27a-4db13285de0d.png)
I Still Fail

**Comment by Biswa96** [comment]
It's TOYS, not BOYS.

**Comment by zhangjp0405** [comment]
"pactoys -S ffmpeg:p" Could not install ffmpeg but "pacman -S mingw-w64-x86_64-ffmpeg" Success!
![微信截图_20220129145109](https://user-images.githubusercontent.com/48978473/151651015-c9d3989b-5815-41b9-8e72-30d578b1159e.png)

**Comment by zhangjp0405** [comment]
![微信截图_20220129152230](https://user-images.githubusercontent.com/48978473/151651822-4aa795f5-4814-4530-8abf-abe9c69bc5ec.
![微信截图_20220129152250](https://user-images.githubusercontent.com/48978473/151651826-5dbed1aa-495b-4c62-8788-b9d625866e37.png)
png)
I have installed libxm2 in"E:\msys64\mingw64\include", why msys2 could not auto recognize the path

**Comment by zhangjp0405** [comment]
![微信截图_20220129152230](https://user-images.githubusercontent.com/48978473/151651864-f292f938-76cd-4904-a697-a1e7315eab08.png)
