### ISSUE TITLE
msys2 could not auto recognize the include path

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MSYS2-packages#2830]
![微信截图_20220129152230](https://user-images.githubusercontent.com/48978473/151652259-c90fb67e-c20d-4838-b4c7-518dd71f8915.png)
![微信截图_20220129152250](https://user-images.githubusercontent.com/48978473/151652267-dbcfa810-e7e5-4fb6-aa4c-54fc0d4127f4.png)
![微信截图_20220129153848](https://user-images.githubusercontent.com/48978473/151652320-c23f9588-76e5-4388-94a3-83bfa7d8a901.png)
I have installed libxm2 in"E:\msys64\mingw64\include", why msys2 could not auto recognize the path

**Comment by Biswa96** [comment]
Please provide the steps to reproduce your issue.

**Comment by zhangjp0405** [comment]
1、Download mplayer source ，i download is "mplayer-export-snapshot.tar.bz2"
2、cd mplayer-export-snapshot.tar.bz2
3、./configure
4、make

**Comment by mati865** [comment]
What does `gcc --version` show?

**Comment by zhangjp0405** [comment]
I try again by myself
