### ISSUE TITLE
meson command fail

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MSYS2-packages#2842]
## Describe the issue
I Installed python3 and meson . But when i use meson command, it fail
![微信截图_20220203100620](https://user-images.githubusercontent.com/48978473/152269602-41e5b911-2189-4bf2-919b-51f449867cb9.png)

**Comment by 1480c1** [comment]
Have you tried reopening the window, and can you make sure `command -v meson` and `command -v python3` both have `/mingw32/bin` in the beginning?

**Comment by zhangjp0405** [comment]
meson have in "/usr/bin/meson"
python3 have in "/mingw32/bin/python3"
![微信截图_20220203101651](https://user-images.githubusercontent.com/48978473/152270575-e45f174f-a61c-4c7e-9470-bcfd58709bc6.png)

**Comment by 1480c1** [comment]
Seems you were using the wrong/incompatible meson, you would need `mingw-w64-i686-meson` if you want to use the MINGW32 environment, make sure to try to use the mingw-w64-i686- prefixed packages before the msys/ ones if available when using the MINGW32 environment

**Comment by zhangjp0405** [comment]
I have resolved it, Thank you very much!
