### ISSUE TITLE
pip install pycairo Fail

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MSYS2-packages#2843]
## Describe the issue
I use "pip install pycairo" command in mys2 Fail!
![微信截图_20220203214638](https://user-images.githubusercontent.com/48978473/152354968-3e821181-6176-4b55-bd06-c8ea91d76f46.png)

**Comment by lazka** [comment]
https://www.msys2.org/news/#2021-12-21-potential-incompatibilities-with-newer-python-setuptools

**Comment by zhangjp0405** [comment]
I use “export SETUPTOOLS_USE_DISTUTILS=stdlib” command, resolved it。Thank you!
![微信截图_20220205091344](https://user-images.githubusercontent.com/48978473/152623643-6d4c7fbc-b753-4b1a-9017-c18d5a54c734.png)
