### ISSUE TITLE
I use "pip install pygobject" command in mys2 Fail!

### ISSUE THREAD

**Issue by zhangjp0405** [msys2/MSYS2-packages#2845]
## Describe the issue
I use "pip install pygobject" command in mys2 Fail!
![微信截图_20220205164957](https://user-images.githubusercontent.com/48978473/152635230-5b351080-c1aa-421c-967b-6fc282dae2aa.png)
![微信截图_20220205165034](https://user-images.githubusercontent.com/48978473/152635234-e5c3d66c-129f-4876-828d-8722a5a0117c.png)

**Comment by MehdiChinoune** [comment]
- You should report this o msys2/MINGW-packages.
- Install gobject-introspection package before building your python module.
- There is already a package python-pygobject, no need to build it yourself.

**Comment by zhangjp0405** [comment]
I try again
