### ISSUE TITLE
"no such file or directory" with npm in msys2 bash

### ISSUE THREAD

**Issue by KevenChesn** [msys2/MSYS2-packages#2855]
Here my screenshot. It happens on my brand new PC with clean installation of msys2 and nodejs.

![image](https://user-images.githubusercontent.com/20589824/153205462-3f4aa294-28e7-48a6-bc81-be8b973953d8.png)

**Comment by Biswa96** [comment]
As far as I know, msys2 does not provide NodeJS or NPM packages. If that is external program then make sure the program path is in $PATH environment variable.

**Comment by KevenChesn** [comment]
Sure its in my $PATH env, and both nodejs, npm file in the same folder ```/c/Program Files/nodejs/```. The strange thing is that when I try to exec this two command. Node is correct but npm shows not found error.

![image](https://user-images.githubusercontent.com/20589824/153329914-a272a1cf-4f8e-46a0-a65a-c129e7b3233e.png)

**Comment by KevenChesn** [comment]
Sure its in my $PATH env. And the strange thing is, both node and npm file in same folder ```/c/Program Files/nodejs```. But when I try to exec this two commands, node is correct but npm shows not found error.

![1644462942(1)](https://user-images.githubusercontent.com/20589824/153330957-1f838057-aa01-4693-b6b4-3901d57c05cc.jpg)

**Comment by Biswa96** [comment]
The npm.cmd looks like a batch script. So, just "npm" will not run. Try something like `cmd.exe /c npm.cmd`.

**Comment by KevenChesn** [comment]
That's not the way npm works. Because the entry file name is just ```npm``` as the ```whereis``` command says. And I have ```yarn``` program have the same file struct (means its have both ```yarn``` and ```yarn.cmd```) but it works fine.

![image](https://user-images.githubusercontent.com/20589824/153335113-a1c5682e-08ce-4dd4-ab44-22591ed7c6ac.png)

![image](https://user-images.githubusercontent.com/20589824/153335174-c1d8292b-d12a-47be-97bc-fe9c2dcf1385.png)

![image](https://user-images.githubusercontent.com/20589824/153335218-c154f89d-a90b-4995-9e30-ea32f36ef9b6.png)

**Comment by Biswa96** [comment]
Normal npm command works in my system.

![image](https://user-images.githubusercontent.com/31443074/153336441-68c4090f-81ad-428c-a78f-e196ca8234c3.png)

**Comment by KevenChesn** [comment]
That's not working on my computer. I've tring reinstall node at another place ```/c/nodejs```, but still have the same problem.

Finally, I'm try to add a bash alias like ```alias npm_proxy="/bin/bash /c/nodejs/npm"``` and it's worked 🎉🎉🎉. Though I have no idea why this problem happens. I'll close this issue and still try to find the reason.

**Comment by lonelam** [comment]
I encountered this problem too, and on my computer C:/Program Files/nodejs is just a shortcut for `C:\ProgramData\nvm\v16.20.2`, which makes nvm for windows work for command line, maybe msys2 should work with directory shortcut to be compatible with **nvm for windows**
