### ISSUE TITLE
[git] - git-http-push.exe not found when git installed by pacman -S git on MSYS2

### ISSUE THREAD

**Issue by D3vil0per** [msys2/MSYS2-packages#2856]
Hello,

I installed MSYS2 (`MINGW64_NT-10.0-22000 MSI 3.3.4-341.x86_64 2022-02-01 09:34 UTC x86_64 Msys` version) on Windows 11, and when I install git package by `pacman -S git`, the repository installs on my environment not the current version shown in https://packages.msys2.org/package/git (currently `2.35.1-1`) but `2.34.1`.

Furthermore, after the installation, if I try to use `git push` or `git -c http.sslVerify=false push` I receive an error like: `git: 'http-push' is not a git-command. See 'git --help'.`

I discovered that on `/usr/lib/git-core/`, `git-http-push` file is not there. and I think also that the related libraries of this executable are not present.

I tried to uninstall and install the package several times but I receive the same issue.

**Comment by lazka** [comment]
`pacman -Suy` to update everything, which should also bring back git-http-push which was missing in some older releases.

**Comment by D3vil0per** [comment]
@lazka it seems to solve my issue.

Thank you!
