### ISSUE TITLE
Should wipe be added to msys2?

### ISSUE THREAD

**Issue by wszqkzqk** [msys2/MSYS2-packages#2860]
Should [wipe](http://wipe.sourceforge.net/) be added to msys2 to support safe deletion?

**Comment by Biswa96** [comment]
The main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum. There are already many tools to delete file securely. This article may help https://www.howtogeek.com/72130/learn-how-to-securely-delete-files-in-windows/
