### ISSUE TITLE
GCC mingw-w64-x86_64-toolchain Exit Code 1

### ISSUE THREAD

**Issue by nsmryan** [msys2/MSYS2-packages#2869]
## GCC mingw-w64-x86_64-toolchain Error

The GCC that comes with "pacman -S mingw-w64-x86_64-toolchain" always returns exit code 1 with no error message even on trivial programs.

## Steps to Reproduce the Problem

1. Fresh install MSYS2 using msys2-x86_64-20220128.exe
2. pacman -Syyuu
3. "pacman -Syyuu" again seems to update a few more packages.
4. pacman -S mingw-w64-x86_64-toolchain
5. Run "/mingw64/bin/x86_64-w64-mingw32-gcc test.c -o test" on the trivial C program below.
```c
#include <stdio.h>

int main(int argc, char * argv[]) {
	printf("hello, msys\n");
}
```
I expect an executable called 'test' that prints "hello, msys".

What happens is that no file is output, gcc exits with code 1:
```
$ echo $?
1
```
and there is no output to stdout or stderr explaining what the problem might be.

I'm at a complete loss on how to track this down. The error seems opaque to me- I don't know of a log or anything that provides more details, and adding "-v" does not provide any error information:
```
$ /mingw64/bin/x86_64-w64-mingw32-gcc test.c -o test -v
Using built-in specs.
COLLECT_GCC=C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe
COLLECT_LTO_WRAPPER=C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-11.2.0/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/include --libexecdir=/mingw64/lib --enable-bootstrap --enable-checking=release --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++,jit --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts --enable-libstdcxx-time --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-lto --enable-libgomp --disable-multilib --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-pkgversion='Rev9, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --with-boot-ldflags='-pipe -Wl,--disable-dynamicbase -static-libstdc++ -static-libgcc' LDFLAGS_FOR_TARGET=-pipe --enable-linker-plugin-flags='LDFLAGS=-static-libstdc++\ -static-libgcc\ -pipe\ -Wl,--stack,12582912'
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.2.0 (Rev9, Built by MSYS2 project)
COLLECT_GCC_OPTIONS='-o' 'test.exe' '-v' '-mtune=generic' '-march=x86-64'
 C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/cc1.exe -quiet -v -iprefix C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/ -D_REENTRANT test.c -quiet -dumpbase test.c -dumpbase-ext .c -mtune=generic -march=x86-64 -version -o C:\msys64\tmp\ccz0sjPQ.s
```

**Comment by nsmryan** [comment]
I tried:
```bash
strace /mingw64/bin/x86_64-w64-mingw32-gcc test.c -o test
```
I get a series of message boxes titled "cc1.exe  - System Error".

These messages boxes indicate that the libraries libwinpthread-1.dll, libgmp-10.dll, libzstd.dll, zlib.1.dll are all missing.

I tried installing packages to pick up these dependencies:
```bash
pacman -S mingw-w64-x86_64-gmp
pacman -S mingw-w64-x86_64-libzip
pacman -S mingw-w64-x86_64-zstd
```
in case this helped, but I get the exact same set of messages.

![image](https://user-images.githubusercontent.com/1892046/155420927-e20c1f25-c0ee-40cd-bcd5-cc02bf10bcad.png)

**Comment by Biswa96** [comment]
Make sure you are using MINGW64 environment (the blue icon). The prompt text will have MINGW64 string.

**Comment by nsmryan** [comment]
You are correct. I had no idea!
It sounds like the different executables set up different environments, and the MSYS2 MinGW x64 one works.

**Comment by jeremyd2019** [comment]
Yes, specifically the `PATH` in this case.  Windows finds DLLs as well as executables using `PATH` (rather than something like `LD_LIBRARY_PATH` on Linux).  Windows also by default looks in the same directory as the executable for DLLs, but in the case of GCC some of its executables like cc1.exe live in a different directory, and if `/mingw64/bin` is not on the `PATH` they cannot find the DLLs they need to run.

**Comment by Nadzieja83** [comment]
runs-on: windows-latest
steps
- uses: eine/setup-msys2@v1
  with:
    msystem: MINGW64
    update: true
    install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git patch
- name: build for windows x64
  run: msys2 make release-static-win64 -j2

**Comment by Nadzieja83** [comment]
Pkg install runs-on: windows-latest
steps
- uses: eine/setup-msys2@v1
  with:
    msystem: MINGW64
    update: true
    install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-x86_64-openssl mingw-w64-x86_64-zeromq mingw-w64-x86_64-libsodium mingw-w64-x86_64-hidapi mingw-w64-x86_64-protobuf-c mingw-w64-x86_64-libusb git patch
- name: build for windows x64
  run: msys2 make release-static-win64 -j2
