### ISSUE TITLE
pkg-config and pkgconf are in conflict

### ISSUE THREAD

**Issue by alicera** [msys2/MSYS2-packages#2872]
## Describe the issue
I can't  install pkg-config.

https://github.com/msys2/msys2-installer/releases/download/2022-01-28/msys2-x86_64-20220128.exe
[msys2-x86_64-20220128.exe](https://github.com/msys2/msys2-installer/releases/download/2022-01-28/msys2-x86_64-20220128.exe)

```
$ pacman -S pkg-config
resolving dependencies...
looking for conflicting packages...
:: pkg-config and pkgconf are in conflict. Remove pkgconf? [Y/n] Y
error: failed to prepare transaction (could not satisfy dependencies)
:: removing pkgconf breaks dependency 'pkgconf' required by base-devel
```

- OS: [. Windows 10 Pro version 1909 64bit]

**Comment by 1480c1** [comment]
As far as I understand, `pkgconf` is supposed to conflict with `pkg-config` as they both provide a `pkg-config` binary, and that part is the same regardless of distro as even having pkgconf on ubuntu and trying to install pkg-config will remove pkgconf

For the 
```
error: failed to prepare transaction (could not satisfy dependencies)
:: removing pkgconf breaks dependency 'pkgconf' required by base-devel
```

part, I'm not sure

**Comment by lazka** [comment]
hm, yeah, if one package provides and another has the exact name, the later wins. pkg-config also providing pkgconf might help in this case.

**Comment by alicera** [comment]
I find the different.

First, 
```
pacman -Syu
pacman -Su
```
Then 
```
pacman -S pkg-config 
```
It will happen the conflict status.

But
First,
```
pacman -S pkg-config 
```
It will successfully install pkg-config .
