### ISSUE TITLE
pacman -S --needed base-devel mingw-w64 x86_64-toolchain

### ISSUE THREAD

**Issue by biru97** [msys2/MSYS2-packages#2874]
While running the command I am getting below errors - 

error: target not found: mingw-w64
error: target not found: x86_64-toolchain

I am running it through MSYS2 MSYS. let me know how I can resolve it.

**Comment by Biswa96** [comment]
It's typo. It is `mingw-w64-x86_64-toolchain`.

**Comment by biru97** [comment]
Oh that is correct, thank you.
