### ISSUE TITLE
GCC C standard library & GTK3

### ISSUE THREAD

**Issue by Azurpourpre** [msys2/MSYS2-packages#2877]
Hello, I've had a cpp program, that uses GTK3, and it compiled great 2 weeks ago.
Now, when compiling it throws error (a lot), like 'intptr_t does not name a type' in standard C library (malloc.h, stdlib.h ....)
And can't figure out what's really wrong behind but i'm thinking that it could be some  header or library file missing

I've tried to compile some gtk3 hello world (https://riptutorial.com/gtk3/example/18820/-c---hello-world--in-gtkplus) and it does the same

I'm on win10 64 bit

**Comment by Biswa96** [comment]
Can you provide a minimal sample code ans the commands to reproduce the issue exactly?

**Comment by Azurpourpre** [comment]
You can install gtk like this : https://www.gtk.org/docs/installations/windows
Then the sample code is here : https://riptutorial.com/gtk3/example/18820/-c---hello-world--in-gtkplus

And you compile with : gcc gtktest.c -o gtktest `pkg-config --cflags --libs 'gtk+-3.0`

**Comment by Biswa96** [comment]
The example code and the command works fine in my system. Make sure you are using MINGW64 environment, the blue icon. List of environments are here https://www.msys2.org/docs/environments/. Also the `gcc -v` command should show `Target: x86_64-w64-mingw32`.

**Comment by Compyx** [comment]
You have a single quote (') in front of "gtk+-3.0", so if that's the actual command used to compile the file then yeah, you'll get a ton of errors.

**Comment by Azurpourpre** [comment]
Ok thanks for testing. Will investigate on my side. Closing
