### ISSUE TITLE
Strange issue with msys-2.0.dll

### ISSUE THREAD

**Issue by pananton** [msys2/MSYS2-packages#2893]
Hello! Sorry, but this will be a pretty long message because I hardly can understand what's happening exactly. I belive you are familiar with conan package manager which has recipes for msys2 to build some packages on windows. I also use gitlab CI/CD in my work and encountered the following problem.

I have a gitlab CI job which builds libiconv library from conan recipe `libiconv/1.16` on windows gitlab CI runner. This conan recipe uses msys2/cci.latest conan recipe which currently downloads from https://github.com/msys2/msys2-installer/releases/download/2022-01-18/msys2-base-x86_64-20220118.tar.xz). The libiconv build process stucks during configuration phase (i.e. when `configure` script is running). This script determines compiler features available on the platform (windows in my case). It does this work by generating simple C program in *conftest.c* file and passing it to compiler. In my case the problem appers when `configure` tries to determine absolute path to some standard C headers (for example, `<stdio.h>`). Diving through `configure` script internals I've figured out that the process stucks forever in the last command of this sequence (I've replaced some bash variables from the original `configure` script to actual values to be more specific):

```
gl_dirsep_regex='[/\\]'
gl_make_literal_regex_sed='s,[]$^\\.*/[],\\&,g'
gl_header_literal_regex=`echo 'stdio.h' | sed -e "$gl_make_literal_regex_sed"`
gl_absolute_header_sed="/${gl_dirsep_regex}${gl_header_literal_regex}/"'{
      s/.*"\(.*'"${gl_dirsep_regex}${gl_header_literal_regex}"'\)".*/\1/
      s|^/[^/]|//&|
      p
      q
    }'
gl_cv_absolute_stdio_h=`(eval "cl -E conftest.c") 2>config.log | sed -n "$gl_absolute_header_sed"` <--- stucks here
```

The content of *conftest.c* at this moment is:

```
/* confdefs.h */
#define PACKAGE_NAME "libiconv"
#define PACKAGE_TARNAME "libiconv"
#define PACKAGE_VERSION "1.16"
#define PACKAGE_STRING "libiconv 1.16"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL ""
#define PACKAGE "libiconv"
#define VERSION "1.16"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define __EXTENSIONS__ 1
#define _ALL_SOURCE 1
#define _DARWIN_C_SOURCE 1
#define _GNU_SOURCE 1
#define _NETBSD_SOURCE 1
#define _OPENBSD_SOURCE 1
#define _POSIX_PTHREAD_SEMANTICS 1
#define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#define __STDC_WANT_LIB_EXT2__ 1
#define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#define _TANDEM_SOURCE 1
#define _HPUX_ALT_XOPEN_SOCKET_API 1
#define _DARWIN_USE_64_BIT_INODE 1
#define LT_OBJDIR ".libs/"
#define INSTALLPREFIX "C:/Users/gitlab/conan-recipe/.conan/data/libiconv/1.16/_/_/package/3fb49604f9c2f729b85ba3115852006824e72cab"
#define HAVE_VISIBILITY 0
#define ICONV_CONST 
#define HAVE_MBSTATE_T 1
#define HAVE_WCHAR_T 1
#define HAVE_MBRTOWC 1
#define HAVE_WCRTOMB 1
#define HAVE_SETLOCALE 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_WCHAR_H 1
#define HAVE_STDINT_H 1
#define HAVE_GETCWD 1
#define HAVE__SET_INVALID_PARAMETER_HANDLER 1
#define HAVE_WORKING_O_NOATIME 0
#define HAVE_WORKING_O_NOFOLLOW 0
#define HAVE_WCHAR_H 1
#define WORDS_LITTLEENDIAN 1
#define HAVE_ALLOCA 1
#define DOUBLE_SLASH_IS_DISTINCT_ROOT 1
#define HAVE_ENVIRON_DECL 1
#define HAVE_DECL_STRERROR_R 0
#define pid_t int
#define mode_t int
#define HAVE_STDLIB_H 1
#define MALLOC_0_IS_NONNULL 1
#define HAVE_UNSIGNED_LONG_LONG_INT 1
#define HAVE_LONG_LONG_INT 1
#define HAVE_MSVC_INVALID_PARAMETER_HANDLER 1
#define HAVE_DECL_SETENV 0
#define ssize_t int
#define uid_t int
#define gid_t int
#define USER_LABEL_PREFIX 
#define nlink_t int
#define HAVE__BOOL 1
#define HAVE_WINT_T 1
#define restrict /**/
#define _USE_STD_STAT 1
#define HAVE_DECL_CLEARERR_UNLOCKED 0
#define HAVE_DECL_FEOF_UNLOCKED 0
#define HAVE_DECL_FERROR_UNLOCKED 0
#define HAVE_DECL_FFLUSH_UNLOCKED 0
#define HAVE_DECL_FGETS_UNLOCKED 0
#define HAVE_DECL_FPUTC_UNLOCKED 0
#define HAVE_DECL_FPUTS_UNLOCKED 0
#define HAVE_DECL_FREAD_UNLOCKED 0
#define HAVE_DECL_FWRITE_UNLOCKED 0
#define HAVE_DECL_GETC_UNLOCKED 0
#define HAVE_DECL_GETCHAR_UNLOCKED 0
#define HAVE_DECL_PUTC_UNLOCKED 0
#define HAVE_DECL_PUTCHAR_UNLOCKED 0
#define GNULIB_CANONICALIZE_LGPL 1
#define GNULIB_TEST_CANONICALIZE_FILE_NAME 1
#define GNULIB_TEST_REALPATH 1
#define DOUBLE_SLASH_IS_DISTINCT_ROOT 1
#define GNULIB_TEST_ENVIRON 1
#define HAVE_DECL_PROGRAM_INVOCATION_NAME 0
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 0
#define HAVE_DECL___ARGV 1
#define GNULIB_TEST_LSTAT 1
#define GNULIB_TEST_MALLOC_POSIX 1
#define HAVE_MBSTATE_T 1
#define GNULIB_MSVC_NOTHROW 1
#define HAVE_DECL_PROGRAM_INVOCATION_NAME 0
#define HAVE_DECL_PROGRAM_INVOCATION_SHORT_NAME 0
#define HAVE_RAISE 1
#define GNULIB_TEST_RAISE 1
#define GNULIB_TEST_READ 1
#define GNULIB_TEST_READLINK 1
#define HAVE_SEARCH_H 1
#define GNULIB_SIGPIPE 1
#define GNULIB_TEST_SIGPROCMASK 1
#define ssize_t int
#define GNULIB_TEST_STAT 1
#define __USE_MINGW_ANSI_STDIO 1
/* end confdefs.h.  */
#include <stdio.h>
```

As you can see, `configure` tries to invoke windows C compiler as preprocessor and extract path to `<stdio.h>` from it's output. And it stucks here... If I login directly to windows machine which is used as CI runner, I can see cl.exe in the task manager. If it is killed, then building continues normally.

I also should mention, that described problem only apprears when library is built by CI job, which is executed by CI runner, which in turn is installed as **windows service**. If I perform the same command when I directly login to runner's machine using **the same** user as for windows service everything works just fine. I've also tried to completely disable UAC and it did not work.

After some hard times trying to find the problem I've decided to try to build libiconv/1.16 using older msys2 version from conan recipe msys2/20210105 (downloads from http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20210105.tar.xz) and everything works. Trying to figure out what file in new version of msys2 causes the problem I've started to copy portions of older files from */usr/bin* of msys2/20210105 to msys2/cci.latest until I've found that if I replace only a single msys-2.0.dll to older version then everything works. I assume that there is some bug in msys-2.0.dll with processing input/output of commands which relates to windows services, but I can't be more specific. Can you please take a look what can be a problem?

**Comment by jeremyd2019** [comment]
Sounds like msys2/MSYS2-runtime#77.  Please test the msys-2.0.dll from the artifact in #88

**Comment by pananton** [comment]
Unfortunately simply replacing msys-2.0.dll taken from here https://github.com/msys2/msys2-runtime/suites/5773285081/artifacts/192238073 did not help.. But I belive this problems are related..

**Comment by jeremyd2019** [comment]
For keeping discussion together I'll close this issue and continue discussion on the msys2-runtime issue.
