### ISSUE TITLE
MSYS2 not installing corectly (wine on linux)

### ISSUE THREAD

**Issue by pazza2234** [msys2/MSYS2-packages#2898]
## Describe the issue

A clear and concise description of what the issue is.
one wine (i am trying to install super Mario 64 on Linux) it hangs at 66%. i have herd that it is windows defender but wine dose not have win defender
## Steps to Reproduce the Problem
- make a Linux VM or tern on a Linux computer 
- install wine and wine tricks
- i have some other programs like net framework and stuff, may be that has something to do with it
- download the msys2 installer
- go through the install processes and it will hang at 66%
1. Run '...'
2. Do something '....'
3. Describe what happens?
4. What did you expect to happen instead?

## Additional Context: Operating System, Screenshots
also on my old computer it worked fine
- OS: pop os 21.10 last updated march 30th at 6:56PM

**Comment by lazka** [comment]
If you don't care where sm64 runs in the end I'd recommend just building it natively on Linux.

Either way, wine wont work atm.
