### ISSUE TITLE
texi2dvi script cannot find tex (broken detection of path separator)

### ISSUE THREAD

**Issue by kalibera** [msys2/MSYS2-packages#2901]
The `texi2dvi` script doesn't find a working tex installation, even though it is on PATH:

```
$ which tex
/c/Users/tomas/AppData/Local/Programs/MiKTeX/miktex/bin/x64/tex
$ texi2dvi nonexistent.texi
You don't have a working TeX binary (tex) installed anywhere in
your PATH, and texi2dvi cannot proceed without one.
...
```
The problem is caused by that `find_prog` fails to find `tex`, which in turn is because `path_sep` is detected to be `;` while in fact it is `:`. The problem is located here:

```
# Systems which define $COMSPEC or $ComSpec use semicolons to separate
# directories in TEXINPUTS -- except for Cygwin and Msys, where COMSPEC
# might be inherited, but : is used.

# In the case of Msys, uname returns a value derived from MSYSTEM, as
# MSYSTEM is user configurable, it is not so safe to use it to detect
# Msys. It is safer to use OSTYPE, this is why we set MSYSTEM to
# $OSTYPE before calling uname
if test -n "$COMSPEC$ComSpec" \
   && MSYSTEM=$OSTYPE uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
  path_sep=";"
else
  path_sep=":"
fi
```
This code ends up calling `MSYSTEM=msys uname`, but, `uname` does not recognize "msys" (it does recognize "MSYS"), so the check above fails to detect Msys2.

```
$ MSYSTEM=MSYS uname
MSYS_NT-10.0-19044

$ MSYSTEM=msys uname
MINGW64_NT-10.0-19044

$ MSYSTEM=randomthing uname
MINGW64_NT-10.0-19044

$ echo $MSYSTEM
MSYS

$echo $OSTYPE
msys
```
There are work-around possible, including

```
$ OSTYPE=MSYS ./texi2dvi nonexistent.texi
$ COMSPEC= ./texi2dvi nonexistent.texi
./texi2dvi: cannot read ./nonexistent.texi, skipping.
```
But it would be very nice if it could be fixed.

**Comment by mmuetzel** [comment]
Does the following change in that script fix it for you?
``` diff
-   && MSYSTEM=$OSTYPE uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
+   && MSYSTEM=${OSTYPE^^} uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
```

**Comment by kalibera** [comment]
Yes, it does.

**Comment by kalibera** [comment]
For reference, for a fix to be acceptable upstream it should preserve the behavior with the original MSYS (https://lists.gnu.org/archive/html/bug-texinfo/2022-04/msg00003.html).

**Comment by mmuetzel** [comment]
I don't have the original MSYS or cygwin installed. Can you check if that change breaks for those?
In case it does break, maybe try and use the following change instead:
``` diff
-   && MSYSTEM=$OSTYPE uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
+   && MSYSTEM=$OSTYPE uname | $EGREP -iv 'cygwin|msys' >/dev/null
+   && MSYSTEM=${OSTYPE^^} uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
```

**Comment by kalibera** [comment]
I've tested on cygwin and MSYSTEM. This second fix you suggested works on both (as well as on Msys2) for me. The first fix doesn't work on MSYSTEM.

In more details, I tested on these 3 systems:

Msys2: MSYS_NT-10.0-19044 DESKTOP-G858KME 3.3.4-341.x86_64 2022-02-15 17:24 UTC x86_64 Msys
MSYSTEM: MINGW32_NT-6.2 DESKTOP-G858KME 1.0.19(0.48/3/2) 2016-07-13 17:45 i686 Msys
cygwin: CYGWIN_NT-10.0 DESKTOP-G858KME 3.3.4(0.341/5/3) 2022-01-31 19:35 x86_64 Cygwin

On cygwin, both fixes work and it is because:

```
$ echo $OSTYPE
cygwin

$ MSYSTEM=$OSTYPE uname
CYGWIN_NT-10.0

$ MSYSTEM=CYGWIN uname
CYGWIN_NT-10.0
```
On MSYSTEM, the behavior of these is also for the test:

```
$ MSYSTEM=$OSTYPE uname
msys_NT-6.2

$ MSYSTEM=msys uname
msys_NT-6.2

$ MSYSTEM=MSYS uname
MSYS_NT-6.2

$ echo $OSTYPE
msys
```
But bash is too old (it is 3.1.23)., so
```
texi2dvi: line 88: ${OSTYPE^^}: bad substitution
```

**Comment by mmuetzel** [comment]
Thanks for testing.
So to summarize: Because of the short-circuit `&&` in those tests, the later tests are only ever run if the previous ones succeeded, i.e., they are only run on Windows.
If that test is run on Windows with an older shell (that doesn't support `${xxx^^}`) and it is not the original MSYS or cygwin, the new part of the test would cause an error.

Is the following more portable?
``` diff
-   && MSYSTEM=$OSTYPE uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
+   && MSYSTEM=$(echo $OSTYPE | tr [a-z] [A-Z]) uname | $EGREP -iv 'cygwin|msys' >/dev/null; then
```

**Comment by kalibera** [comment]
Works for me on those three systems (and the cygwin and MSYSTEM installation is the default and hence contains tr).

**Comment by mmuetzel** [comment]
According to this overview, it should be possible to use `tr` pretty portably:
https://www.codetinkerer.com/is-shell-portable/

Would you like to prepare a PR for that change in msys2, and maybe also suggest that change upstream?

**Comment by kalibera** [comment]
So it was quick, fixed upstream by Gavin Smith, slightly differently, simplifying the existing test
https://git.savannah.gnu.org/cgit/texinfo.git/commit/?id=df780e22a5898df4a0f52ceb0ae3579ea7c78646

Could this be back-ported to Msys2?

**Comment by kalibera** [comment]
Thanks for the quick back-port.
