### ISSUE TITLE
mutt: no authenticators available

### ISSUE THREAD

**Issue by Konfekt** [msys2/MSYS2-packages#2902]
## Describe the issue

Sending with mutt returns error "no authenticators available"

## Steps to Reproduce the Problem

1. Running 'mutt -s "test" email@address.com < file.txt'
2. Gives output

No authenticators available
Could not send the message.

Instead, the message should have been successfully sent.

This happens for different SMTP servers on different machines with different settings of the variables

```
set smtp_url      = "smtp(s)://$imap_user@mailserver.org:port/"
set smtp_authenticators = "login"
set ssl_starttls  = no
set ssl_force_tls = yes
```

and with `cyrus-sasl` installed. 

(Secure)IMAP works flawlessly.

## Additional Context: Operating System, Screenshots

- mutt:

Mutt 2.1.4 (2021-12-11)

System: MSYS_NT-10.0-19044 3.3.4-341.x86_64 (x86_64)
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libiconv: 1.16
libidn2: 2.3.2 (compiled with 2.3.2)
hcache backend: GDBM version 1.22. 19/10/2021 (built Feb 12 2022 14:23:35)

- OS: 

Windows 10 Pro
Version	21H2
Build 19044.1586
Windows Feature Experience Pack 120.2212.4170.0

**Comment by Biswa96** [comment]
Fixed in #4514
