### ISSUE TITLE
Keepass SSH agent not working with Windows msys2/openssh-8.9x. Had to revert to msys2/openssh-8.8x

### ISSUE THREAD

**Issue by Wihlelm** [msys2/MSYS2-packages#2914]
ssh connexion with msys2/openssh does not take keys from Keepass starting from version msys2/openssh-8.9x
Reverting to previous version msys2/openssh-3.8x solves the problem.

**Comment by Biswa96** [comment]
Can you provide any error message or logs? Also provide any details about how to reproduce the issue.

**Comment by Wihlelm** [comment]
Well I don't know how to generate an informative error log...

Here are the good.log et bad.log files resulting from 
ssh -vvv machine &> good.log for msys2/openssh-3.8x
and 
ssh -vvv machine &> bad.log for msys2/openssh-3.9x

[bad.log](https://github.com/msys2/MSYS2-packages/files/8429027/bad.log)
[good.log](https://github.com/msys2/MSYS2-packages/files/8429028/good.log)

and their diff :

```
1c1
< OpenSSH_8.9p1, OpenSSL 1.1.1n  15 Mar 2022
---
> OpenSSH_8.8p1, OpenSSL 1.1.1n  15 Mar 2022
7a8
> debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
13a15,16
> debug1: identity file /home/wihle/.ssh/id_dsa type -1
> debug1: identity file /home/wihle/.ssh/id_dsa-cert type -1
24,26c27
< debug1: identity file /home/wihle/.ssh/id_dsa type -1
< debug1: identity file /home/wihle/.ssh/id_dsa-cert type -1
< debug1: Local version string SSH-2.0-OpenSSH_8.9
---
> debug1: Local version string SSH-2.0-OpenSSH_8.8
44c45
< debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,sntrup761x25519-sha512@openssh.com,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
---
> debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
88c89
< debug2: ssh_set_newkeys: mode 1
---
> debug2: set_newkeys: mode 1
94c95
< debug2: ssh_set_newkeys: mode 0
---
> debug2: set_newkeys: mode 0
96c97
< debug1: get_agent_identities: ssh_get_authentication_socket: No such file or directory
---
> debug1: pubkey_prepare: ssh_get_authentication_socket: No such file or directory
97a99
> debug1: Will attempt key: /home/wihle/.ssh/id_dsa
103d104
< debug1: Will attempt key: /home/wihle/.ssh/id_dsa
122a124,125
> debug1: Trying private key: /home/wihle/.ssh/id_dsa
> debug3: no such identity: /home/wihle/.ssh/id_dsa: No such file or directory
133,134d135
< debug1: Trying private key: /home/wihle/.ssh/id_dsa
< debug3: no such identity: /home/wihle/.ssh/id_dsa: No such file or directory

```

If you think I can do any other test, please tell me.

**Comment by jeremyd2019** [comment]
This seems to be going around... It sounds like openssh changed the agent protocol in 8.9.
https://bugs.archlinux.org/task/74143

**Comment by Wihlelm** [comment]
Ok, probably the outdated ssh-agent extension for keepass not including the last agent protocol. It is 1.5 year old.
[KeeAgent v0.12.1 Released](https://lechnology.com/2020/08/keeagent-v0-12-1-released/) August 31, 2020
Thanks

**Comment by jeremyd2019** [comment]
My opinion is that OpenSSH should have come up with a way to keep the addition of a protocol extension from breaking communications with 3rd party agents.  But maybe that wasn't possible.

**Comment by jeremyd2019** [comment]
https://dev.gnupg.org/T5931, it looks like gpg-agent stubbed in the extension to just silently return success to get it working with openssh 8.9 for gnupg 2.3.6.  So it seems there is an extension mechanism in the protocol, and a way to return that the agent doesn't support a requested extension... Hmm, wonder what openssh was thinking here
