### ISSUE TITLE
[base-devel] Package dependencies and group member packages differ.

### ISSUE THREAD

**Issue by aphanic** [msys2/MSYS2-packages#2932]
## Issue description

At the moment the `base-devel` group and package don't match, the `base-devel` package doesn't depend on all of the packages in the group so syncing it won't pull them all. For example, `gettext-devel`, `intltool` and `xmlto` are all members of the group but not dependencies of the packge.

## Steps to Reproduce the Problem

1. Check package members any way you prefer, for example by running `pacman -Sg base-devel`.
2. Because there's a matching package name, syncing the group installs the package and its dependences, running `pacman -S --needed base-devel` displays all of the packages it depends on that are not yet installed.
3. Lists don't match at the moment, there are packages in the group that aren't dependencies of the package and at least one that isn't part of the group, `m4`. Ideally they'd both be in sync.

## Additional Context

Environment: 64-bit Windows 10 21H2, fresh MSYS2 install after a `pacman -Syu` was issued.
<details><summary>Commands and their output... (drop down)</summary>

```
Alex@Luna MSYS ~
$ pacman -Sg base-devel
base-devel asciidoc
base-devel binutils
base-devel bison
base-devel diffstat
base-devel diffutils
base-devel dos2unix
base-devel file
base-devel flex
base-devel gawk
base-devel gdb
base-devel gettext
base-devel gettext-devel
base-devel gperf
base-devel grep
base-devel groff
base-devel help2man
base-devel intltool
base-devel make
base-devel man-db
base-devel pacman
base-devel patch
base-devel patchutils
base-devel perl
base-devel pkgconf
base-devel sed
base-devel tar
base-devel texinfo
base-devel texinfo-tex
base-devel unrar
base-devel wget
base-devel xmlto

Alex@Luna MSYS ~
$ pacman -S --needed base-devel
resolving dependencies...
looking for conflicting packages...

Packages (16) binutils-2.37-5  bison-3.8.2-3  diffstat-1.64-1  diffutils-3.8-3  dos2unix-7.4.2-1  flex-2.6.4-2  gperf-3.1-4  groff-1.22.4-3  m4-1.4.19-2  make-4.3-3  patch-2.7.6-1  pkgconf-1.8.0-1  tar-1.34-2  texinfo-6.8-4  texinfo-tex-6.8-4  base-devel-2022.01-1

Total Download Size:   11.63 MiB
Total Installed Size:  72.31 MiB

:: Proceed with installation? [Y/n]
```
After installing the `base-devel` package and its dependences these remain to be installed:
```
Alex@Luna MSYS ~
$ pacman -Ss base-devel | awk '!/installed/ && /msys/'
msys/asciidoc 9.1.1-1 (base-devel)
msys/gdb 11.1-1 (base-devel)
msys/gettext-devel 0.21-1 (development base-devel)
msys/help2man 1.48.5-1 (base-devel)
msys/intltool 0.51.0-2 (base-devel)
msys/man-db 2.10.2-2 (base-devel)
msys/patchutils 0.4.2-2 (base-devel)
msys/unrar 6.1.4-1 (base-devel)
msys/xmlto 0.0.28-3 (base-devel)
```

**Comment by lazka** [comment]
The group is no longer used. Is it causing any problems?

**Comment by aphanic** [comment]
Nope, not at all, I was in the process of building an application that depended on `intltool` and I only realized about the discrepancy because it wasn't installed.

Just in case it was something that was meant to be in sync I decided to report it, but it's no trouble at all to just add X or Y packages to `makedepends`.

**Comment by lazka** [comment]
OK, see https://www.msys2.org/news/#2021-12-22-ongoing-cleanup-of-the-base-devel-package-group

The group should slowly go away once all packages are rebuilt.
