### ISSUE TITLE
MSYS2 pacman -Sys Unable to lock database

### ISSUE THREAD

**Issue by ViratSrivastava** [msys2/MSYS2-packages#2933]
To start Code and Compile C++, I must install a compiler. For my case, it is MSYS2 through which MinGW is available. According to the installation guild mentioned on the [website](https://www.msys2.org/), I installed the software without any errors. Now I was supposed to update the package database and base packages by entering `Pacman -Sys` but it has shown an error
 `error: failed to synchronize all databases (unable to lock database)`

After searching online for a solution I found that deleting/removing the `db.lck` will work, for that, I used this command 
`rm /var/lib/pacman/db.lck` but it showed another error. Right now there is no solution to this on the internet. I've also pasted the terminal output of MSYS2 MSYS for reference. Also, the Directory image is shared for reference.

**Note:**

1. No anti-virus installed. Just regular old Windows Defender.
2. Re-installed it 3 times in different locations but no change in result.
3. All installations were made as admin.

![Screenshot (30)](https://user-images.githubusercontent.com/98209563/163698613-27150b62-0e57-4db2-94dc-c431de17fa05.png)

```
$ pacman -Sys
:: Synchronizing package databases...
error: failed to synchronize all databases (unable to lock database)

VIRAT@DESKTOP-97BS0AB MSYS ~
$ rm /var/lib/pacman/db.lck
rm: cannot remove '/var/lib/pacman/db.lck': No such file or directory

VIRAT@DESKTOP-97BS0AB MSYS ~
$ pacman -S --needed base-devel mingw-w64-x86_64-toolchain
error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied

VIRAT@DESKTOP-97BS0AB MSYS ~
$ pacman -Su
error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied

VIRAT@DESKTOP-97BS0AB MSYS ~
$
```

**Comment by Biswa96** [comment]
> No anti-virus installed. Just regular old Windows Defender.

Windows Defender is also on the list of showing false positive with msys2/mingw programs. Please test with excluding the whole msys2 install directory. Does the `/var/lib/pacman/db.lck` file actually exist?

**Comment by ViratSrivastava** [comment]
> Does the `/var/lib/pacman/db.lck` file actually exist?

no the `/var/lib/pacman/db.lck` doesn't exist

**Comment by ViratSrivastava** [comment]
> Windows Defender is also on the list of showing false positive with msys2/mingw programs. Please test with excluding the whole msys2 install directory. 

No Changes in the output result
```
VIRAT@DESKTOP-97BS0AB MSYS ~
$ pacman -Sys
:: Synchronizing package databases...
error: failed to synchronize all databases (unable to lock database)

VIRAT@DESKTOP-97BS0AB MSYS ~
$ rm /var/lib/pacman/db.lck
rm: cannot remove '/var/lib/pacman/db.lck': No such file or directory

VIRAT@DESKTOP-97BS0AB MSYS ~
$

```

**Comment by stevenclarke9** [comment]
start a command shell using "cmd.exe" as Administrator, then you can delete the db.lck file.
```
del C:\msys64\var\lib\pacman\db.lck
```

**Comment by ViratSrivastava** [comment]
> start a command shell using "cmd.exe" as Administrator, then you can delete the db.lck file.
> 
> ```
> del C:\msys64\var\lib\pacman\db.lck
> ```

The system cannot find the path specified.

**Comment by koyouin1s** [comment]
run as administrator

**Comment by ViratSrivastava** [comment]
> run as administrator




> 3. All installations were made as admin.

Already done

**Comment by neriyac** [comment]
Find a solution?
I got the same errors the hell...
![image](https://user-images.githubusercontent.com/69886097/165240712-882dddb9-28f2-46d6-9857-099a8e1c42b0.png)

**Comment by stevenclarke9** [comment]
I would delete the whole msys64 folder.
Open a command shell as an Administrator.
Create a C:\msys64 directory.
Open Windows Security and add the C:\msys64 directory to the exceptions list. This will stop Windows Defender from scanning the directory and blocking the programs.
run the installer as an Administrator.
You can then update as per the documentation on the website.

**Comment by neriyac** [comment]
Try this one, I think that solved my issue.

**Comment by ViratSrivastava** [comment]
> Try this one, I think that solved my issue. https://sourceforge.net/projects/mingw/

This is an outdated source of MinGW.
For updated versions, MSYS2 is used.

**Comment by ViratSrivastava** [comment]
> I would delete the whole msys64 folder. Open a command shell as an Administrator. Create a C:\msys64 directory. Open Windows Security and add the C:\msys64 directory to the exceptions list. This will stop Windows Defender from scanning the directory and blocking the programs. run the installer as an Administrator. You can then update as per the documentation on the website.

I tried a bit different method and it seems to work. It looks like this software doesn't install well in drives except for the C drive.
I uninstalled and deleted any residue folders of MSYS2. And re-installed it in C drive. It worked without any errors.

**Comment by Biswa96** [comment]
> It looks like this software doesn't install well in drives except for the C drive.

I am using msys2 from both D: and F: drives. Testing purposes 😎

**Comment by ViratSrivastava** [comment]
> Find a solution? I got the same errors the hell... ![image](https://user-images.githubusercontent.com/69886097/165240712-882dddb9-28f2-46d6-9857-099a8e1c42b0.png)


Solution⬇️

> I would delete the whole msys64 folder. Open a command shell as an Administrator. Create a C:\msys64 directory. Open Windows Security and add the C:\msys64 directory to the exceptions list. This will stop Windows Defender from scanning the directory and blocking the programs. run the installer as an Administrator. You can then update as per the documentation on the website.

**Comment by ViratSrivastava** [comment]
> > It looks like this software doesn't install well in drives except for the C drive.
> 
> I am using msys2 from both D: and F: drives. Testing purposes 😎

Used any Specific Settings to accomplish that???

**Comment by readhere** [comment]
I met the same problem, finally I found msys64 folder must be created at the root of the disk, such as c:\msys64 or d:\msys64.

**Comment by Biswa96** [comment]
> I found msys64 folder must be created at the root of the disk, such as c:\msys64 or d:\msys64.

It is not required. There maybe some other issues as well.

**Comment by readhere** [comment]
Yes, in the detail install guide: https://www.msys2.org/wiki/MSYS2-installation/
   They can be installed or extracted to any place on your computer, but you MUST use folder names that consist of only ascii characters and no spaces (also it makes good sense to put it in a path that doesn't use many characters due to PATH_MAX being 260; C:\msys32 or C:\msys64 is ideal)
   my fault is the space in the folder name.

**Comment by Ali5Ismail** [comment]
I have the same problem but I solve this problem by running the MSYS as an administrator

**Comment by Biswa96** [comment]
msys2 programs do not need to run as administrator. Removing the `/var/lib/pacman/db.lck` is the only solution.

**Comment by stumpedatwork** [comment]
Solved this issue by giving my user the `Full Control` permission over the directory.

**Comment by Amirbhn** [comment]
> Yes, in the detail install guide: https://www.msys2.org/wiki/MSYS2-installation/ They can be installed or extracted to any place on your computer, but you MUST use folder names that consist of only ascii characters and no spaces (also it makes good sense to put it in a path that doesn't use many characters due to PATH_MAX being 260; C:\msys32 or C:\msys64 is ideal) my fault is the space in the folder name.

Thanks it worked for me.

**Comment by seowooku2ka2** [comment]
I completely solved this problem by running msys as administrator.

**Comment by Owais-Creates** [comment]
> I have the same problem but I solve this problem by running the MSYS as an administrator

Thanks brother it helped me after searching for a solution for hours can vouch worked for me too.

**Comment by Cvjark** [comment]
same issue, uninstall and run the installer as Administrator help for me.

**Comment by thang080920** [comment]
No need to uninstall, just re-run msys2 terminal again and re-run command using Administrator permission is enough, I put mine under Program Files and it works like a champ.

**Comment by cibo005** [comment]
> I met the same problem, finally I found msys64 folder must be created at the root of the disk, such as c:\msys64 or d:\msys64.

TRUE indeed, why the hack it is mandatory to be installed at the root level ?
