### ISSUE TITLE
Mintty hangs out after some time of idle SSH session

### ISSUE THREAD

**Issue by cdoublev** [msys2/MSYS2-packages#2945]
## Describe the issue

I connect to a virtual machine (Vagrant box, Virtual Box provider) with `vagrant ssh -- -L 9222:localhost:9222`. The port forwarding is for debugging a JavaScript program in the Chrome DevTools. Since the last update of Mintty to 3.6.0, but I'm not sure it was from 3.5.x, Mintty hangs after some period without interacting with the VM, while running a program in "watch" mode (Jest test runner). Keyboard inputs have no effect including CTRL + D but except CTRL + C, which triggers a log out, but inputs still have no effect, including CTRL + D, except another CTRL + C, then CTRL + D closes Mintty.

Before reporting this issue, I opened a session with port forwarding and another one without. I will update this issue accordingly if this makes a difference. I believe the issue occurs even when not running a program in watch mode, but I will also check this point.

## Steps to Reproduce the Problem

1. Run a virtual machine with Vagrant and Virtual Box
2. Connect via SSH (eventually with a port forwarding)
3. Do not interact with the VM for about 20 minutes

## Additional Context: Operating System, Screenshots

- OS: Windows 10 Family 64 bits 21H2
- Mintty: 3.6.0 x86_64-pc-msys
- Vagrant: 2.2.19
- Virtual Box: 6.1.32 r 149290

**Comment by mintty** [comment]
This is hardly related to the terminal, especially as you describe yourself that it still works normally, taking and forwarding ^C. You can check further with output into the terminal, to its tty from another session.

**Comment by cdoublev** [comment]
Yes, it is related to `jest`. This [blog post](https://lifesaver.codes/answer/ctrl-+-c-doesn-t-kill-gracefully-node-v6-11-3-git-bash) describe it perfectly, I think. I will investigate a bit more. Thanks.
