### ISSUE TITLE
Problems with yandex.ru mirror

### ISSUE THREAD

**Issue by zdm** [msys2/MSYS2-packages#2952]
I have permanent problems with thw yandex.ru mirror. 
Is it possible to locally edit list of mirrors and remove yandex?

Run `pacman -S --noconfirm --needed --refresh --sysupgrade`.

Result:
```
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang64 is up to date
 msys is up to date
error: failed retrieving file 'mingw64.db' from mirror.msys2.org : Failed to connect to mirror.yandex.ru port 443 after 5224 ms: Connection timed out
error: failed retrieving file 'msys.db' from mirror.msys2.org : Failed to connect to mirror.yandex.ru port 443 after 5222 ms: Connection timed out
```

**Comment by Biswa96** [comment]
Can you do `ping mirror.yandex.ru` ? It works fine in my system.

**Comment by Biswa96** [comment]
Maybe something is blocking the connection. I assume the reason is out of our scope you-know-why. As a workaround, a specific mirror can be selected in `/etc/pacman.d/mirrorlist.*` files. But remember to change it in all mirrorlist files. Current online mirrors can be seen here https://packages.msys2.org/mirrors

**Comment by zdm** [comment]
I remove "mirror.yandex.ru" from all plain text files, where I found it.
But it still trying to use if.
I found, that substring yandex.ru also hardcoded in some exe files.
How is is possible to remove this mirror completely from msys2 locally?

**Comment by zdm** [comment]
Here isthe list of files, where `yandex` substring found:
```
d:\devel\msys2\usr\bin\msys-psl-5.dll
d:\devel\msys2\usr\bin\pacman.exe
d:\devel\msys2\usr\bin\pacman-conf.exe
d:\devel\msys2\usr\bin\pactree.exe
d:\devel\msys2\usr\bin\testpkg.exe
d:\devel\msys2\usr\bin\whois.exe
```

**Comment by zdm** [comment]
Works now, thank you.
