### ISSUE TITLE
invoking Windows commands from MSYS2

### ISSUE THREAD

**Issue by ousia** [msys2/MSYS2-packages#2953]
Excuse whether my question is stupid.

 I have been searching for this and I couldn’t find any information for this.

From the command prompt in Windows, I can run a Python script with a batch file containing the following command:

```
start "" "C:\msys64\mingw64.exe" /usr/bin/bash -lc 'python ~/my-script.py "%~1"'
```

How could do it the other way around?

I mean, how could I invoke or run a pure Windows command (no MSYS2) from something similar to `os.system()` in the script mentioned above?

Now I realize that the simplest solution would be the to add a second line to the batch file above.

But I wonder whether there would be a way to do that from the Python script itself.

The file argument could be empty and the Python script could have the file selected inside the script.

Many thanks for your help.

**Comment by Biswa96** [comment]
Does not just executing the Windows program work from msys2 e.g. cmd.exe, notepad.exe etc.? What command would you want to run?
