### ISSUE TITLE
Is the package succesfully installed?where is it?

### ISSUE THREAD

**Issue by masta99wrfvsHsa** [msys2/MSYS2-packages#2966]
## Describe the issue

The liinking just seems to fail.not sure why.Even though the package is installed.

## Steps to Reproduce the Problem

1. pacman -S --needed base-devel mingw-w64-x86_64-toolchain as official documentation suggested.
Then,, install the relevant packages.aka( pacman -S libiconv)
Then, make project( i am trying to compile this github project.https://github.com/cedricfrancoys/tagger)
oops error

4. What did you expect to happen instead?
No error succesfully compile

## Additional Context: Win10.64bit.run msys2 of thumbdrive*

The useful log____________
 pacman -S libiconv
warning: libiconv-1.16-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) libiconv-1.16-2

Total Installed Size:  1.25 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] n

$ ls /usr/lib
automode.o          itcl4.2.0         libiberty.a       libtclstub8.6.a    tcl8.6
awk                 libacl.a          libiconv.a        libtextmode.a      tclConfig.sh
bfd-plugins         libalpm.a         libiconv.dll.a    libtextreadmode.a  tclooConfig.sh
binmode.o           libautomode.a     libm.a            libtz.a            tdbc1.1.1
coreutils           libbfd.a          libmagic.dll.a    libutil.a          tdbcmysql1.1.1
cpp.exe             libbinmode.a      libmsys-2.0.a     liby.a             tdbcodbc1.1.1
crt0.o              libc.a            libopcodes.a      openssl            tdbcpostgres1.1.1
default-manifest.o  libcharset.a      libpkgconf.dll.a  p11-kit            terminfo
gawk                libcharset.dll.a  libpthread.a      perl5              texinfo
gcc                 libctf-nobfd.a    libresolv.a       pkcs11             textmode.o
gcrt0.o             libctf.a          librt.a           pkgconfig          textreadmode.o
gettext             libdl.a           libssp.a          python3.9          thread2.8.5
gio                 libfl.a           libtcl.dll.a      systemd            w32api
gnupg               libg.a            libtcl8.6.dll.a   tar
groff               libgmon.a         libtclstub.a      tcl8

$ ls /usr/local/lib
libcharset.a  libcharset.la  libiconv.a  libiconv.la

$ make
Linking binary:
gcc -o tagger.exe -L/usr/lib -L/usr/local/lib -lm obj/charset.o obj/elem.o obj/env.o obj/error.o obj/eval.o obj/hash.o obj/list.o obj/md5.o obj/tagger.o obj/xalloc.o
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x3c2): undefined reference to `libiconv_open'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x41e): undefined reference to `libiconv'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x449): undefined reference to `libiconv_close'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x50e): undefined reference to `libiconv_open'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x562): undefined reference to `libiconv'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x58d): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
make: *** [makefile:32: tagger.exe] Error 1

the relevant makefile>
CC       = c99
# compiling flags here
CFLAGS   = -I/usr/include -I/usr/local/include -D_DEFAULT_SOURCE

LINKER   = gcc -o
# linking flags here
LFLAGS   = -L/usr/lib -L/usr/local/lib -lm

**Comment by mmuetzel** [comment]
Missing `-liconv` in the linker flags?

OT: Did you intend to set `LFLAGS`? That is usually used for setting flags for `lex` (or `flex` or whatever version you are using). Linker flags are most commonly set in `LDFLAGS`.

**Comment by masta99wrfvsHsa** [comment]
hmm i tried those path..and it still seems to fail.so i will just close this.maybe its the make file or msys2 itself or gcc have some bug

>
$ make
Linking binary:
gcc -o tagger.exe -L/usr/lib -L/usr/local/lib -L/usr/bin/ -lm obj/charset.o obj/elem.o obj/env.o obj/error.o obj/eval.o obj/hash.o obj/list.o obj/md5.o obj/tagger.o obj/xalloc.o
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x3c2): undefined reference to `libiconv_open'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x41e): undefined reference to `libiconv'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x449): undefined reference to `libiconv_close'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x50e): undefined reference to `libiconv_open'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x562): undefined reference to `libiconv'
/usr/lib/gcc/x86_64-pc-msys/11.2.0/../../../../x86_64-pc-msys/bin/ld: obj/charset.o:charset.c:(.text+0x58d): undefined reference to `libiconv_close'
collect2: error: ld returned 1 exit status
make: *** [makefile:32: tagger.exe] Error 1

**Comment by mmuetzel** [comment]
I still can't find `-liconv` in your linking command. Without it, those symbols *will* be undefined.

**Comment by masta99wrfvsHsa** [comment]
pacman -Fx libiconv
....
msys/libiconv-devel 1.16-2 (development) [installed]
    usr/lib/libiconv.a
    usr/lib/libiconv.dll.a

**Comment by lazka** [comment]
`-lm -liconv` need to come last

**Comment by masta99wrfvsHsa** [comment]
thx it worked.
BTW,somehow my mingw64 compiling the same project somehow have some error
>collect2.exe: error: ld returned 1 exit status

do you happen to have any similar experience?or any hints on reinstalling gcc parts?

**Comment by Smuel24** [comment]
Hello, i have a problem installing MSYS2 to c++, if someone knw how to resolve this, please help.

warning: database file for 'mingw32' does not exist (use '-Fy' to download)
warning: database file for 'mingw64' does not exist (use '-Fy' to download)
warning: database file for 'ucrt64' does not exist (use '-Fy' to download)
warning: database file for 'clang32' does not exist (use '-Fy' to download)
warning: database file for 'clang64' does not exist (use '-Fy' to download)
warning: database file for 'msys' does not exist (use '-Fy' to download)

**Comment by mmuetzel** [comment]
Did you try downloading the databases (with `pacman -Fy`) like suggested in these messages? Does that make a difference?

**Comment by Smuel24** [comment]
Yes, i use the -fy, but now i resolve with other command, thank you
