### ISSUE TITLE
[bug] ln cannot create symbolic link

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MSYS2-packages#2992]
`ln` can create correct hard link, but cannot create symbolic link, it only copy the target file. Only test in NTFS.

```bash
❯ uname -a
MINGW64_NT-10.0-19044 windows10 3.3.3-341.x86_64 2021-12-30 06:18 UTC x86_64 Msys
❯ pacman -Qi coreutils|rg -N Version|cut -d: -f2
 8.32-2
❯ touch a
❯ ln -s a b
❯ cmd /c 'mklink c a'
You do not have sufficient privilege to perform this operation.
# need win-sudo
❯ sudo cmd /c 'mklink c a'
为 c <<===>> a 创建的符号链接
❯ ls -l a b c
-rw-r--r-- 1 wzy None 0 May 13 21:39 a
-rw-r--r-- 1 wzy None 0 May 13 21:39 b
lrwxrwxrwx 1 wzy None 1 May 13 21:43 c -> a
```

**Comment by Biswa96** [comment]
The symlink creation is cotrolled by `winsymlinks` environment variable. See this docs https://www.cygwin.com/cygwin-ug-net/using-cygwinenv.html

**Comment by Freed-Wu** [comment]
I Refer `https://stackoverflow.com/questions/18654162/enable-native-ntfs-symbolic-links-for-cygwin`, however, `CYGWIN=winsymlinks:nativestrict ln -s a b` still copy the file not create true symbolic link. Whatever `CYGWIN`, `ln -s` always copy the file, even `CYGWIN=winsymlinks:lnk ln -s a b`

**Comment by Freed-Wu** [comment]
You are right! `:)`

**Comment by Freed-Wu** [comment]
It seems git don't respect `$MSYS`, that is if a repo contains a symlink, git will not according to `$MSYS` to decide the symlink will be changed to which file. the symlink always be changed to a text file which context is the target path. Why not let git change the symlink to a true symlink?

**Comment by lazka** [comment]
git will decide this on repo creation time. you can try `git config core.symlinks true` followed by `git reset --hard` (be aware that this resets all changes)
