### ISSUE TITLE
[question] Does this repo accept some shell script?

### ISSUE THREAD

**Issue by Freed-Wu** [msys2/MSYS2-packages#2998]
Like <https://github.com/pipeseroni/pipes.sh>, <https://github.com/LuRsT/hr>, etc?

**Comment by Biswa96** [comment]
Nope. See https://www.msys2.org/

> ...the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum.

**Comment by 1480c1** [comment]
I would say the requirement is if it's useful for developers who might use it for developing native windows software, for neofetch specifically, it can help convey system information in a single screen
