### ISSUE TITLE
error: failed retrieving file 'clang64.db' from mirror.msys2.org : SSL connection timeout

### ISSUE THREAD

**Issue by DS-Liu** [msys2/MSYS2-packages#3016]
When running `pacman -Syu` to update the package database and base packages, an error occured: 
`error: failed retrieving file 'clang64.db' from mirror.msys2.org : SSL connection timeout. `
How can I solve it?

```
 $pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
error: failed retrieving file 'clang64.db' from mirror.msys2.org : SSL connection timeout
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

**Comment by DS-Liu** [comment]
I tried several times and fortunately the error disappeared.

**Comment by Lishinuo** [comment]
Help me,please.What method you used?

**Comment by yotsuba44** [comment]
I had almost the same error but there were a lot of them
![error3](https://github.com/user-attachments/assets/491089d5-3a38-42f7-8f53-ea1671e2216f)
So basically I was restarting and restarting the whole process until there is no error. For instance I had problems from the very beginning so I wrote `pacman -Syu` several times until no error occured.
