### ISSUE TITLE
Cannot downgrade from GCC 12 to 11.3

### ISSUE THREAD

**Issue by MartinEesmaa** [msys2/MSYS2-packages#3017]
## Describe the issue

I can't downgrade GCC versions, because I already accidentallity updated to GCC 12, which makes me unstable. I tried remove packages and reinstall of GCC packages, but it got error, so I tried use code `pacman -Syu` and `pacman -Su`, then I retried again, but nothing worked, I tried everything.

## Steps to Reproduce the Problem

1: locating and cding
2: Trying to downgrade of gcc version
3: I typed `n` to no skip above packages and got an error.
See the log below

## Additional Context: Operating System, Screenshots

- OS: Windows 11 Pro

```
pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libgccjit
warning: mingw-w64-x86_64-gcc-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-ada-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-fortran-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-libgfortran-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-objc-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-libgccjit-12.1.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (6) mingw-w64-x86_64-gcc-12.1.0-1  mingw-w64-x86_64-gcc-ada-12.1.0-1  mingw-w64-x86_64-gcc-fortran-12.1.0-1
             mingw-w64-x86_64-gcc-libgfortran-12.1.0-1  mingw-w64-x86_64-gcc-objc-12.1.0-1  mingw-w64-x86_64-libgccjit-12.1.0-1

Total Installed Size:  448.11 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
(6/6) checking keys in keyring                                                          [##################################################] 100%
(6/6) checking package integrity                                                        [##################################################] 100%
(6/6) loading package files                                                             [##################################################] 100%
(6/6) checking for file conflicts                                                       [##################################################] 100%
(6/6) checking available disk space                                                     [##################################################] 100%
:: Processing package changes...
(1/6) reinstalling mingw-w64-x86_64-gcc                                                 [##################################################] 100%
(2/6) reinstalling mingw-w64-x86_64-gcc-ada                                             [##################################################] 100%
(3/6) reinstalling mingw-w64-x86_64-gcc-libgfortran                                     [##################################################] 100%
(4/6) reinstalling mingw-w64-x86_64-gcc-fortran                                         [##################################################] 100%
(5/6) reinstalling mingw-w64-x86_64-gcc-objc                                            [##################################################] 100%
(6/6) reinstalling mingw-w64-x86_64-libgccjit                                           [##################################################] 100%

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ gpg
gpg: keybox '/home/marti/.gnupg/pubring.kbx' created
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: Go ahead and type your message ...

gpg: signal Interrupt caught ... exiting


marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ gpg --import *.sig
gpg: Total number processed: 0

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ ls
mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst              mingw-w64-x86_64-gcc-libgfortran-11.3.0-2-any.pkg.tar.zst.sig
mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst.sig          mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
mingw-w64-x86_64-gcc-ada-11.3.0-2-any.pkg.tar.zst          mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst.sig
mingw-w64-x86_64-gcc-ada-11.3.0-2-any.pkg.tar.zst.sig      mingw-w64-x86_64-gcc-objc-11.3.0-2-any.pkg.tar.zst
mingw-w64-x86_64-gcc-fortran-11.3.0-2-any.pkg.tar.zst      mingw-w64-x86_64-gcc-objc-11.3.0-2-any.pkg.tar.zst.sig
mingw-w64-x86_64-gcc-fortran-11.3.0-2-any.pkg.tar.zst.sig  mingw-w64-x86_64-libgccjit-11.3.0-2-any.pkg.tar.zst
mingw-w64-x86_64-gcc-libgfortran-11.3.0-2-any.pkg.tar.zst  mingw-w64-x86_64-libgccjit-11.3.0-2-any.pkg.tar.zst.sig

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ gpg --import mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst.sig
gpg: Total number processed: 0

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst                                                                                    loading packages...
warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc-libgfortran

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst.sig
loading packages...
error: could not open file mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst.sig: Unrecognized archive format
error: 'mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst.sig': cannot open package file

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc-libgfortran

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -Syu
:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 ucrt64 is up to date
 clang32 is up to date
 clang64 is up to date
 msys is up to date
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-ada mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc-libgfortran mingw-w64-x86_64-gcc-objc mingw-w64-x86_64-libgccjit
warning: mingw-w64-x86_64-gcc-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-ada-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-fortran-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-libgfortran-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-gcc-objc-12.1.0-1 is up to date -- reinstalling
warning: mingw-w64-x86_64-libgccjit-12.1.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (6) mingw-w64-x86_64-gcc-12.1.0-1  mingw-w64-x86_64-gcc-ada-12.1.0-1  mingw-w64-x86_64-gcc-fortran-12.1.0-1
             mingw-w64-x86_64-gcc-libgfortran-12.1.0-1  mingw-w64-x86_64-gcc-objc-12.1.0-1  mingw-w64-x86_64-libgccjit-12.1.0-1

Total Installed Size:  448.11 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] n

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc-libgfortran

marti@LAPTOP-HM70RGB0 MINGW64 /c/users/marti/downloads/back22
$ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
resolving dependencies...
warning: cannot resolve "mingw-w64-x86_64-gcc-libs=11.3.0-2", a dependency of "mingw-w64-x86_64-gcc"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-gcc

:: Do you want to skip the above package for this upgrade? [Y/n] n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'mingw-w64-x86_64-gcc-libs=11.3.0-2' required by mingw-w64-x86_64-gcc
```

**Comment by MehdiChinoune** [comment]
> ## Describe the issue
> I can't downgrade GCC versions, because I already accidentallity updated to GCC 12, which makes me unstable.

What type of issues do you face with gcc-12

**Comment by MartinEesmaa** [comment]
> > ## Describe the issue
> > I can't downgrade GCC versions, because I already accidentallity updated to GCC 12, which makes me unstable.
> 
> What type of issues do you face with gcc-12

The issue is that it example build compiled by warnings and errors, but in GCC 11, it compiles normally well without warnings and errors.

**Comment by MehdiChinoune** [comment]
> The issue is that the example build compiled by warnings and errors, but in GCC 11, it compiles normally well without warnings and errors.

Could you show that example!

There are some possibilities:
1- Your code use an old standard, then you could pass `-std=` to gcc/g++
1- GCC is right, then you should fix your code
2- bug from GCC, then you should report that to GCC.

MSYS2 is a rolling-based platform, there is no official way to roll back to an old version.
You could download old version from https://repo.msys2.org/mingw/mingw64/ and install it locally by `pacman -U <package-files>`.

**Comment by MartinEesmaa** [comment]
@MehdiChinoune, I already tried download old versions and used code: `pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst`, but I got an error:
```
$ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
resolving dependencies...
warning: cannot resolve "mingw-w64-x86_64-gcc-libs=11.3.0-2", a dependency of "mingw-w64-x86_64-gcc"
:: The following package cannot be upgraded due to unresolvable dependencies:
      mingw-w64-x86_64-gcc

:: Do you want to skip the above package for this upgrade? [Y/n] n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'mingw-w64-x86_64-gcc-libs=11.3.0-2' required by mingw-w64-x86_64-gcc

```

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune, I already tried download old versions and used code: `pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst`, but I got an error:
> 
> ```
> $ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
> loading packages...
> warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
> resolving dependencies...
> warning: cannot resolve "mingw-w64-x86_64-gcc-libs=11.3.0-2", a dependency of "mingw-w64-x86_64-gcc"
> :: The following package cannot be upgraded due to unresolvable dependencies:
>       mingw-w64-x86_64-gcc
> 
> :: Do you want to skip the above package for this upgrade? [Y/n] n
> error: failed to prepare transaction (could not satisfy dependencies)
> :: unable to satisfy dependency 'mingw-w64-x86_64-gcc-libs=11.3.0-2' required by mingw-w64-x86_64-gcc
> ```

You should download gcc-libs 11.3.0 as it is part of gcc-11

**Comment by MartinEesmaa** [comment]
> > @MehdiChinoune, I already tried download old versions and used code: `pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst`, but I got an error:
> > ```
> > $ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
> > loading packages...
> > warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
> > resolving dependencies...
> > warning: cannot resolve "mingw-w64-x86_64-gcc-libs=11.3.0-2", a dependency of "mingw-w64-x86_64-gcc"
> > :: The following package cannot be upgraded due to unresolvable dependencies:
> >       mingw-w64-x86_64-gcc
> > 
> > :: Do you want to skip the above package for this upgrade? [Y/n] n
> > error: failed to prepare transaction (could not satisfy dependencies)
> > :: unable to satisfy dependency 'mingw-w64-x86_64-gcc-libs=11.3.0-2' required by mingw-w64-x86_64-gcc
> > ```
> 
> You should download gcc-libs 11.3.0 as it is part of gcc-11

I tried:
```
$ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc
:: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc-libgfortran
```

**Comment by kmilos** [comment]
> What type of issues do you face with gcc-12

We're also seeing an [issue w/ darktable CI since GCC 12](https://github.com/darktable-org/darktable/issues/11889) was introduced.

**Comment by MehdiChinoune** [comment]
> > > @MehdiChinoune, I already tried download old versions and used code: `pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst`, but I got an error:
> > > ```
> > > $ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst
> > > loading packages...
> > > warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
> > > resolving dependencies...
> > > warning: cannot resolve "mingw-w64-x86_64-gcc-libs=11.3.0-2", a dependency of "mingw-w64-x86_64-gcc"
> > > :: The following package cannot be upgraded due to unresolvable dependencies:
> > >       mingw-w64-x86_64-gcc
> > > 
> > > :: Do you want to skip the above package for this upgrade? [Y/n] n
> > > error: failed to prepare transaction (could not satisfy dependencies)
> > > :: unable to satisfy dependency 'mingw-w64-x86_64-gcc-libs=11.3.0-2' required by mingw-w64-x86_64-gcc
> > > ```
> > 
> > 
> > You should download gcc-libs 11.3.0 as it is part of gcc-11
> 
> I tried:
> 
> ```
> $ pacman -U mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst
> loading packages...
> warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
> resolving dependencies...
> looking for conflicting packages...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc
> :: installing mingw-w64-x86_64-gcc-libs (11.3.0-2) breaks dependency 'mingw-w64-x86_64-gcc-libs=12.1.0-1' required by mingw-w64-x86_64-gcc-libgfortran
> ```

You should downgrade all of gcc components of them at the same time `pacman -U gcc-package-file gcc-libs-package-file gcc-libgfortran-package-file`

**Comment by MartinEesmaa** [comment]
@MehdiChinoune, thanks you're the best! I thought I have to insert only one time package, but now I know that I have to put all packages to downgrade. I'm closing this issue.
```
$ pacman -U mingw-w64-x86_64-gcc-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-gcc-libs-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-gcc-libgfortran-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-gcc-ada-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-gcc-fortran-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-gcc-objc-11.3.0-2-any.pkg.tar.zst mingw-w64-x86_64-libgccjit-11.3.0-2-any.pkg.tar.zst
loading packages...
warning: downgrading package mingw-w64-x86_64-gcc (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-gcc-libs (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-gcc-libgfortran (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-gcc-ada (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-gcc-fortran (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-gcc-objc (12.1.0-1 => 11.3.0-2)
warning: downgrading package mingw-w64-x86_64-libgccjit (12.1.0-1 => 11.3.0-2)
resolving dependencies...
looking for conflicting packages...

Packages (7) mingw-w64-x86_64-gcc-11.3.0-2  mingw-w64-x86_64-gcc-ada-11.3.0-2  mingw-w64-x86_64-gcc-fortran-11.3.0-2
             mingw-w64-x86_64-gcc-libgfortran-11.3.0-2  mingw-w64-x86_64-gcc-libs-11.3.0-2  mingw-w64-x86_64-gcc-objc-11.3.0-2
             mingw-w64-x86_64-libgccjit-11.3.0-2

Total Installed Size:  412.36 MiB
Net Upgrade Size:      -38.53 MiB

:: Proceed with installation? [Y/n] y
(7/7) checking keys in keyring                                                          [##################################################] 100%
(7/7) checking package integrity                                                        [##################################################] 100%
(7/7) loading package files                                                             [##################################################] 100%
(7/7) checking for file conflicts                                                       [##################################################] 100%
(7/7) checking available disk space                                                     [##################################################] 100%
:: Processing package changes...
(1/7) downgrading mingw-w64-x86_64-gcc-libs                                             [##################################################] 100%
(2/7) downgrading mingw-w64-x86_64-gcc                                                  [##################################################] 100%
(3/7) downgrading mingw-w64-x86_64-gcc-libgfortran                                      [##################################################] 100%
(4/7) downgrading mingw-w64-x86_64-gcc-ada                                              [##################################################] 100%
(5/7) downgrading mingw-w64-x86_64-gcc-fortran                                          [##################################################] 100%
(6/7) downgrading mingw-w64-x86_64-gcc-objc                                             [##################################################] 100%
(7/7) downgrading mingw-w64-x86_64-libgccjit                                            [##################################################] 100%
```

**Comment by MehdiChinoune** [comment]
> > What type of issues do you face with gcc-12
> 
> We're also seeing an [issue w/ darktable CI since GCC 12](https://github.com/darktable-org/darktable/issues/11889) was introduced, seems to be OpenMP related...

Let me show you what to do:
1- Build darktable with debug symbols by passing `-DCMAKE_BUILD_TYPE=Debug`.
2- Install gdb `pacman -S mingw-w64-x86_64-gdb`
3- run darktable with gdb `gdb --args darktable-cli.exe --width 20[4](https://github.com/darktable-org/darktable/runs/6583723366?check_suite_focus=true#step:7:4)8 --height 2048 --hq true --apply-custom-presets false $(cygpath ${SRC_DIR})/src/tests/integration/images/mire1.cr2 $(cygpath ${SRC_DIR})/src/tests/integration/0000-nop/nop.xmp output.png --core --disable-opencl --conf host_memory_limit=[8](https://github.com/darktable-org/darktable/runs/6583723366?check_suite_focus=true#step:7:8)1[9](https://github.com/darktable-org/darktable/runs/6583723366?check_suite_focus=true#step:7:9)2 --conf worker_threads=4 -t 4 --conf plugins/lighttable/export/force_lcms2=FALSE --conf plugins/lighttable/export/iccintent=0`
4- After it crashes/segfaults type `bt`, It will show you where the crash occurs in darktable code.
5- Take a look at that part code and see if there is something wrong you should fix
6- If not try to create a minimal reproducer and report the bug to GCC.

**Comment by kmilos** [comment]
@MehdiChinoune The trace is already in the linked issue and has been narrowed down to changes in OpenMP behaviour.

**Comment by MehdiChinoune** [comment]
> @MehdiChinoune The trace is already in the linked issue and has been narrowed down to changes in OpenMP behaviour. So yes, we need a simpler, isolated reproducer...

Then do step 6 mentioned above.

**Comment by etrinh** [comment]
Got the same openmp issue with this sample:

```
#include <stdio.h>
int main() {
 #pragma omp parallel for if (false)
 for (int idx = 0; idx < 10; ++idx) { }
 printf("success\n");
 return 0;
}
```

compiled with: `g++ -fopenmp -o myTest.exe myTest.cpp`

If I remove the `if (false)` from openmp statement, then it works.

**Comment by kmilos** [comment]
> If I remove the `if (false)` from openmp statement, then it works.

Great, thanks for this minimal reproducer! Any chance you can confirm this worked w/ GCC 11.3?

**Comment by kmilos** [comment]
So, who is brave enough to report this upstream? 😉

**Comment by MehdiChinoune** [comment]
> So, who is brave enough to report this upstream? 😉

Did you check if the issue is only on MINGW or everywhere?

**Comment by etrinh** [comment]
No issue with the gcc docker image (gcc 12.1.0)

**Comment by kmilos** [comment]
We have another dark table user confirming this is ok on Linux:

> With 3.9.0+1605~gf7d792d41 on Arch Linux with GCC 12.1.0, Release build type, the command in the original post runs successfully.
