### ISSUE TITLE
More complete support for `mingw-w64-cross-ucrt-toolchain`

### ISSUE THREAD

**Issue by metab0t** [msys2/MSYS2-packages#3040]
[mingw-w64-cross-ucrt-toolchain](https://packages.msys2.org/group/mingw-w64-cross-ucrt-toolchain) conflicts with [mingw-w64-cross-toolchain](https://packages.msys2.org/group/mingw-w64-cross-toolchain).

If I install `mingw-w64-cross-ucrt-crt` then I cannot install `mingw-w64-cross-gcc` because it conflicts with `mingw-w64-cross-crt-git`.

There should be `mingw-w64-cross-ucrt-gcc` and relevant packages in `mingw-w64-cross-ucrt-toolchain`.

**Comment by mati865** [comment]
Why would install it?
They are meant only for bootstrapping mingw and ucrt subsystems.

**Comment by metab0t** [comment]
I want to compile Julia by using the cross toolchain.
The official method is using cross compiler in Cygwin, so I think maybe Msys2 can do it too.

**Comment by mati865** [comment]
We have (out of date) [Julia package](https://packages.msys2.org/package/mingw-w64-x86_64-julia?repo=mingw64) so I'd recommend using native subsystems.

> The official method is using cross compiler in Cygwin, so I think maybe Msys2 can do it too.

It is the difference between Cygwin and MSYS2. They use cross compilers to build native executables while we use native compilers for this thing. So once more I recommend using native subsystems instead as the packages you have mentioned aren't really meant to be used by the users.

**Comment by metab0t** [comment]
Thanks for the reply!
I know there is a Julia package for MinGW subsystem.
However, the compiling system of Julia is designed around cross compilation, so I just want to try the cross compiling process in Msys2 instead of Cygwin. (Because install locally built package in Cygwin is too cumbersome and I want to use UCRT-enabled MinGW toolchain)
If cross compilation is not encouraged in Msys2, feel free to close it.
