### ISSUE TITLE
nodejs istTTY is true on `git-bash` but undefined on `msys2`

### ISSUE THREAD

**Issue by wszgrcy** [msys2/MSYS2-packages#3051]
## Describe the issue
when run ` node -p -e "process.stdout.isTTY"` on git-bash(git for window,mingw64,mintty 3.6.1) return true.
on msys2(or mingw64 mingw32....),return undefined
![image](https://user-images.githubusercontent.com/9607121/175076659-6a2a90ad-1f73-43c1-9abc-c02a2a2f9992.png)
![image](https://user-images.githubusercontent.com/9607121/175077177-9a792e23-a0dd-4e96-8a8e-a589c447308a.png)
- same node version (node 16.14.2),same mintty version(3.6.1),but msys2 display does not meet expectations...
- on vscode terminal use msys2 `bash` also return `true`
- I try to copy msys2.exe in git folder and run, same return `true`
- I find mintty [https://github.com/mintty/mintty/issues/56](https://github.com/mintty/mintty/issues/56) has resolve on 3.1.0,is the same problem?

## Steps to Reproduce the Problem

1. open E:\msys2\msys2.exe
2. run `node -p -e "process.stdout.isTTY"`
> node is download on `https://nodejs.org/`
4. return undefind
5. What did you expect to happen instead?
> retrun true
## Additional Context: Operating System, Screenshots

- OS: [e.g. Windows 10 19044.1165 ]
- '...'

**Comment by Biswa96** [comment]
The ConPTY feature in not enabled by default in msys2 environments. It has to be manually enabled using `MSYS=enable_pcon` environment variable **before** initiating any msys2 instance.

**Comment by lazka** [comment]
It's probably time we start thinking about enabling it by default..

**Comment by Biswa96** [comment]
I have seen some msys2/cygwin tools have weird behavior with conpty e.g. autotools, tmux etc.

**Comment by wszgrcy** [comment]
@Biswa96  thanks
