### ISSUE TITLE
git add interactive regression

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#3066]
works with <2.37, broken with 2.37

* touch myfile
* git add myfile
* git commit -m "bla"
* rm myfile
* git add -i
* 2
* 1
* enter

Actual:

`fatal: unable to stat 'myfile': No such file or directory`

Expected:

File removal gets staged

**Comment by lazka** [comment]
Also reproduced on Arch Linux.

**Comment by dscho** [comment]
Can you "work around" it by setting `add.interactive.useBuiltin=false`?

**Comment by dscho** [comment]
> Can you "work around" it by setting `add.interactive.useBuiltin=false`?

@lazka this work-around works here... I will work on a proper fix, though.

**Comment by lazka** [comment]
yes, that fixes things.

(note: I only mentioned you directly because I saw you were involved in the rewrite)
