### ISSUE TITLE
`time` doesnt detect arguments supplied to it

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3069]
## Describe the issue

* `time` is not detecting any `[option...]` and rather treating them as `COMMAND`
* Ref: `info time` --> "1.6 Running the 'time' Command"

```info
The format of the 'time' command is:

     time [option...] COMMAND [ARG...]

'--help'
     Print a summary of the command line options to 'time' and exit.

'-V'
'--version'
     Print the version number of 'time' and exit.
```

## Steps to Reproduce the Problem

```bash
$ time --help
bash: --help: command not found

$ time --version
bash: --version: command not found
```

<img src="https://user-images.githubusercontent.com/19423063/176493624-11c3b929-7ce6-4673-afa5-9aa3eba35b13.png" height="200px">

### Additional Info:
* https://github.com/msys2/MSYS2-packages/blob/master/time/PKGBUILD

### Versions:

- OS: Windows 10 version 20H2 64bit
- `time` : **1.9-1** (via `pacman -Q time` )

**Comment by 1480c1** [comment]
You are calling your shell's builtin time, you need to either call it by path or use `\time`

**Comment by yashpalgoyal1304** [comment]
i updated `time` and still the same.

ohh, @ 1480c1 ohkay, will try that. then i am hiding this comment of mine meanwhile.

<details>

```bash
$ pacman -S time
...
Packages (1) time-1.9-3
...
:: Proceed with installation? [Y/n] Y
...

$ time --help
<-- still the same -->
```

Ref: https://wiki.archlinux.org/title/Pacman#Querying_package_databases

</details>

**Comment by yashpalgoyal1304** [comment]
> use `\time`

Thanks @1480c1 it worked. but can u please explain this? i dont understand what it – "shell's builtin time" – means and how does backslash fix that?

**Comment by yashpalgoyal1304** [comment]
ohh, github changed it's Ctrl + Enter keys behaviour now?

**Comment by yashpalgoyal1304** [comment]
just discovered this a few days ago:

https://github.com/msys2/MSYS2-packages/blob/e3e8e77a2ba7040e072afdb4e2c36cd98be42d4d/filesystem/dot.bashrc#L79-L83

<details>
<summary>Quoting in text</summary>

```bash
# .... . For example, alias rm='rm -i' will mask the rm
# application.  To override the alias instruction use a \ before, ie
# \rm will call the real rm not the alias.
```

</details>
