### ISSUE TITLE
Automatic update notifications and security advisories

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#3088]
A bit of a meta issue.

Stories:
a) a new upstream release is out which we could package and we want to be notified (with some upper version limit, in case we have separate packages for different major versions)
b) we want to link packages to cygwin/arch to share patches, see potential problems (we have https://packages.msys2.org/outofdate right now)
c) we want to know all open security advisories for the version currently in the repo and a way to ignore them on a per issue/package basis.

For (a) and (c) we need to know the real package names and real versions of each package. So for example the real pypi name, or a git repo + commit hash if we build from git, or a git tag. In various cases we have to adjust the version format for pacman, or rename the package to avoid naming conflicts or have consistent package names in our repo. If it's a git hash it would also be nice to know what the last/base version is so we can see if there is something newer.

Random list of things that might be helpful here:

* https://github.com/package-url/purl-spec - A URL format for linking to a package source
* https://repology.org/projects/?inrepo=msys2_msys2&vulnerable=1 - parses our repo right now and also lists CVEs
* https://github.com/advisories - githubs collection of security advisories for certain package repos
* https://github.blog/2022-06-17-creating-comprehensive-dependency-graph-build-time-detection/ - github API to push rust/go/python dependency information to github, so it can notify us of security issues
* https://github.com/flathub/flatpak-external-data-checker - a json format and tool to check for new upstream versions (used to automatically update flatpaks)
* https://release-monitoring.org/ - fedora release monitoring repi/api

**Comment by lazka** [comment]
There is now an extra metadata file in each repo which can be used to store things related to a package: https://github.com/msys2/MSYS2-packages/blob/master/PKGMETA.yml

We only use it for https://packages.msys2.org atm

**Comment by yashpalgoyal1304** [comment]
I do think that how f-droid manages their repo can be took some ideas from. 

They have a bot, which scans for updates on repos, if update found, those are added to new build pipeline.

Do u want me to tag an fdroid person?

**Comment by yashpalgoyal1304** [comment]
I also wanted the information about "out-of-date" packages in the repo to be included in repo index (the repo file which pacman fetches), which is then shown by pacman while running some commands like `-S`, `-Ss` or `-Qu`.

Does that come under this issue?

**Comment by goyalyashpal** [comment]
in case no service exist, then can web scraping the repology to extract the info help?

**Comment by lazka** [comment]
scraping is (a) slow (b) not nice the the project being scraped and (c) prone to break quickly

**Comment by dscho** [comment]
I was recently made aware of [this blog post](https://devblogs.microsoft.com/engineering-at-microsoft/generating-software-bills-of-materials-sboms-with-spdx-at-microsoft/) describing how so-called "Bills of Materials" ("BOMs") are generated at scale at Microsoft. These BOMs are stored in `.spdx.json` files conforming to the [SPDX standard](https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements) and can be used by a GitHub Action called `spdx-to-dependency-graph` (https://github.com/jhutchings1/spdx-to-dependency-graph-action) to "quickly receive Dependabot alerts for package manifests which GitHub doesn't directly support".

It should be (relatively) straight-forward to generate such `.spdx.json` files from the information present in the `PKGBUILD` files (or from the `.PKGINFO` files contained in the `.tar.pkg.zst` files). Not the least involved project, I know. But an option.

**Comment by lazka** [comment]
Thanks. From what I understand this still only supports the ecosystems listed here https://github.com/advisories, so packages from pip, ruby, and go would be relevant, but that's only a fraction of our packages.

**Comment by dscho** [comment]
@lazka you're correct. I thought that packages using "other" package management systems could be used here, too, but it seems that there is no standardized way to label the CVEs accordingly ☹️

**Comment by lazka** [comment]
https://dependencytrack.org/ might be worth a look

**Comment by lazka** [comment]
As a first step, we now automatically create a SBOM file for the git repo content: https://github.com/msys2/MINGW-packages/releases/tag/srcinfo-cache

It only contains some pypi packages + curl atm.

![image](https://github.com/msys2/MSYS2-packages/assets/991986/fc8aa9b2-216d-41fd-8835-dfe0a88e805b)

**Comment by lazka** [comment]
https://github.com/anchore/grype also seems to work outside of the language ecosystems

**Comment by lazka** [comment]
This is now implemented, see https://www.msys2.org/news/#2024-04-02-automated-vulnerability-reporting-system
