### ISSUE TITLE
Saving file with nano in MinTTY causes entire terminal to freeze

### ISSUE THREAD

**Issue by DavidEGrayson** [msys2/MSYS2-packages#3100]
I've been using MSYS2 and its nano package for years and it has been great.  I just updated my MSYS2 packages the other day and now I am noticing a strange bug.  When I type Ctrl+O and then Enter to save a file I am editing in nano, it works fine the first time, but then the second time it freezes the entire terminal.  The "File Name to Write:" prompt stays visible and nothing I do seems to have any effect on nano, including pressing Ctrl+C.  Sometimes I can't even see my mouse cursor when I put it over the MinTTY window; it just disappears.  However I know MinTTY is still responding to clicks because I can click on the icon in the upper left and use the menu.

## Steps

1. Run mingw64.exe .
2. Launch nano by running `nano test.txt` .
3. Type Ctrl+O and then press Enter to save the file.  This should work fine and you should get the message "Wrote 0 lines" at the bottom.
4. Type Ctrl+O and then press Enter to save the file again.  I would expect things to work exactly same as they did in Step 3, but instead the "File Name to Write:" prompt is still shown, none of my keystrokes seem to do anything, and the mouse cursor might be invisible.

## Additional Context

My OS is Windows 10 64-bit version 21H2 (OS build 19044.1826).

This is a new, recent bug.  MSYS2+nano worked great for me on this same computer for over a year.

![image](https://user-images.githubusercontent.com/466764/179667334-480eb42d-3637-4544-a6b3-ce7a0ef7c11a.png)

```text
$ nano --version
 GNU nano, version 6.3
 (C) 1999-2011, 2013-2022 Free Software Foundation, Inc.
 (C) 2014-2022 the contributors to nano
 Compiled options: --enable-utf8
$ pacman -Q nano
nano 6.3-1
```

I see there are older versions of the `nano` package here: https://repo.msys2.org/msys/x86_64/
I tried all the versions from 5.8-1 to 6.3-1 and they all seem to have this problem, so I suspect the problem is not with nano itself but some library or MSYS2 system component.

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system.

**Comment by DavidEGrayson** [comment]
Oh, after I reboot I can't reproduce the problem any more either.  So I'll close this as it was probably just some weird glitch in Windows.

**Comment by Biswa96** [comment]
BTW, now-a-days this link is popular https://cygwin.com/faq/faq.html#faq.using.bloda

**Comment by DavidEGrayson** [comment]
Hmm, I don't understand the link you sent or the "question" label.

**Comment by Biswa96** [comment]
Sometimes antivirus or antimalware software catches cygwin related programs or operations as malware. And that leads to unexpected behavior. The article explains it.
