### ISSUE TITLE
MSYS2 not launching

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3102]
## Describe the issue

MSYS2 MSYS or any other launchers (i.e. those 4 shortcuts to `C:\msys64\msys2_shell.cmd` with different arguments) thereof doesnt launch.

## Steps to Reproduce the Problem

0. Press <kbd>win</kbd> & type MSYS
1. Click on any of "MSYS2 MSYS" or "MSYS2 MINGW"

**Now:** (from some months) Some window seems to flash and disappear, nothing visible and persistent seems to happen. 
**Earlier:** It used to launch the terminal window.

## Additional Context: Screenshots

* ~~my msys2 has pro'lly never been fully upgraded since 2021-December, so, it is pending upgrades of 162 packages (241 MiB download size)~~
* but I thought to file this before updating in case some useful info can be dug up via this
* ~~is there any particular package which requires updating for this to be fixed?~~

Duplicate search: [msys not launching](https://github.com/msys2/MSYS2-packages/issues?q=is%3Aissue+msys+not+launching)

https://user-images.githubusercontent.com/19423063/180391060-e92846de-439f-447e-b825-8528835e2f56.mp4

## Environment

- OS: Windows 10 Home Single Language version 20H2 64bit
- '...'

**Comment by yashpalgoyal1304** [comment]
is this issue even worth persuing?

**Comment by yashpalgoyal1304** [comment]
This problem persists even after doing core and full system upgrade of msys2

**Comment by yashpalgoyal1304** [comment]
hi, 
i think this issue belongs to this repo: https://github.com/msys2/msys2-launcher 

so, to avoid creating duplicates, can anyone please move this issue to that repo ??

https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by yashpalgoyal1304** [comment]
ping

**Comment by sskras** [comment]
It would be nice, there are only 3 open issues here at the moment:

![image](https://user-images.githubusercontent.com/7887758/197995714-8b31ed1c-1a71-4e62-811c-37e77557e322.png)

**Comment by yashpalgoyal1304** [comment]
my last attempt at gaining some attention for this issue... i did not want to mention anyone, but sorry, i can't think of any other way...

@Alexpux @lazka @Biswa96 @jeremyd2019

**Comment by Biswa96** [comment]
Try a clean install with latest installer. Need more info to understand the issue. Make sure things are not deleted or modified by antivirus software. Check if the launchers are working e.g. mingw64.exe etc.

**Comment by yashpalgoyal1304** [comment]
> [C:\msys64\]mingw64.exe

yes, it's working:

![image](https://user-images.githubusercontent.com/19423063/210137470-81b4440c-6dfa-44cc-8117-907285161d23.png)

**Comment by Biswa96** [comment]
What command did you run with that msys2_shell.cmd and in which shell?

**Comment by yashpalgoyal1304** [comment]
> What command did you run with that msys2_shell.cmd and in which shell?

i manually launched this launcher exe-s from `C:/msys64`

**Comment by Biswa96** [comment]
I mean in actual issue, in the original post, _What command did you run with that msys2_shell.cmd and in which shell?_

**Comment by yashpalgoyal1304** [comment]
Found a maybe related pull: https://github.com/msys2/msys2-installer/pull/50

**Comment by yashpalgoyal1304** [comment]
> What command did you run with that msys2_shell.cmd and in which shell?

umh, i run that directly, and from start menu... so, i guess it opens by default in the `conhost` terminal and since the extension is `.cmd` I guess it would have used cmd shell?

i mean, i did not, and still don't understand what this question means 😅

**Comment by yashpalgoyal1304** [comment]
so, i tried running the script from an already running `cmd` shell, and surprisingly, it ran successfully as well 😵

```console
$ cd /c/msys64
$ cmd
C:\msys64>
```

And all of the following commands worked i.e. launched the `mintty` with `$MSYSTEM` defined
([environments#overview] - the prefix column in table; I should know that these both are not same)

[environments#overview]: https://www.msys2.org/docs/environments#overview

<details><summary>msys2_shell.cmd script with various arguments</summary>

```cmd
msys2_shell.cmd
msys2_shell.cmd -msys
msys2_shell.cmd -ucrt64
msys2_shell.cmd -clang64
msys2_shell.cmd -clangarm64
msys2_shell.cmd -clang32
msys2_shell.cmd -mingw64
msys2_shell.cmd -ming32
```
</details>

So, the error seems to be in running the shortcuts i guess?

**Comment by yashpalgoyal1304** [comment]
> What command did you run with that msys2_shell.cmd and in which shell?

now it seems to make sense 😅 

i am guessing that 
- those script files when opened from explorer 
(in any way: right click context menu, or double click, or shortcut - which includes shortcut from start menu as well)
- it is not opening with required stuff, i.e. it is not getting `cmd` there
- but i don't see how I can change which program it opens with, like i don't see any "open with" menu item on right clicking on it, i don't see any such thing in the properties panel either....

<img src="https://user-images.githubusercontent.com/19423063/214369287-57c429cc-8bf2-4e55-8714-8514d540a6b4.png" width="250px"/>

**Comment by yashpalgoyal1304** [comment]
> i don't see how I can change which program it opens with

yeah.... i found it. So, 

* it turns out that the running shell used for `.cmd` scripts too depend on the `CompSpec` system variable, 
* which i had redefined with value `bash.exe` for my windows user account
* from there, rest is pretty self explanatory: the script runs with bash, which returns an error, the terminal disappears.

```
CompSpec=C:\msys64\usr\bin\bash.exe
```

so, this was caused by same reason as: https://github.com/wez/wezterm/discussions/2909

**Comment by yashpalgoyal1304** [comment]
> Found a maybe related pull: [msys2/msys2-installer#50](https://github.com/msys2/msys2-installer/pull/50)
\- https://github.com/msys2/MSYS2-packages/issues/3102#issuecomment-1399317103

oh and yeah, this above related pull from ['22-09-04] release tag of msys2-installer, was _really_ related to this issue. brilliant.

having .exe installers elevates from this dependence on the `CompSpec` environment variable, so that the user can freely use the `bash` at system level if per so wishes to. 

nice.

['22-09-04]: https://github.com/msys2/msys2-installer/releases/tag/2022-09-04
