### ISSUE TITLE
Pacman very slow

### ISSUE THREAD

**Issue by Luca00711** [msys2/MSYS2-packages#3130]
## Describe the issue

The execution of pacman is very slow

```
# time pacman
real    0m7,400s
user    0m0,232s
sys     0m0,369s
```` 

## Additional Context: Operating System, Screenshots

- OS: [Windows 11 Pro version 21H2 64bit]

**Comment by lazka** [comment]
exclude it from defender

**Comment by Luca00711** [comment]
@lazka 
> try to exclude it from windows defender

Thank you. This was the problem. 
👍🏻
