### ISSUE TITLE
Feature request: Package xauth in MSYS2 to support 'ssh -X' and 'runx'

### ISSUE THREAD

**Issue by mviereck** [msys2/MSYS2-packages#3146]
I provide a script called [`runx`](https://github.com/mviereck/runx) that allows to run X server [`VcXsrv`](https://sourceforge.net/projects/vcxsrv/) in MSYS2 (and in Cygwin and WSL, too).

By default `runx` creates an X authentication cookie for access restriction.
The default linux tool for X authentication cookie setup is `xauth`.
`runx` itself can create a cookie on its own without the help of `xauth`, but uses `xauth` nonetheless if available.

But if one wants to use `ssh -X` or `ssh -Y`, the connection fails because `ssh` depends on `/usr/bin/xauth`. (Found in https://github.com/mviereck/runx/issues/7).

My feature request: Please provide package `xauth` in MSYS2 to support `runx` and in turn `ssh -X`.

----------
Additional notes:

 - Package `xauth` in Cygwin: https://cygwin.com/packages/summary/xauth.html
 - `VcXsrv` provides an `xauth.exe` on its own, but it is somehow broken and I could not get valid cookies from it. I would prefer an `xauth` package in MSYS2.
 - I've seen that @eine is involved in MSYS2, too. He is a user of `runx` and might support my request.

**Comment by Biswa96** [comment]
Unfortunately, we can not. See https://www.msys2.org/

> the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum.

**Comment by mviereck** [comment]
Ok, I understand that you want to keep the focus.
Thank you for looking at this!

**Comment by 1480c1** [comment]
The ideal would probably be a mix of cygwin and msys2's focus, so that those wishing to be able to use their linux native code can use that, but also benefit from the packages and windows specializations that msys2 provides through pacman and patches and compilers. But that would probably not be very easy, unless somehow it's possible to use pacman directly from msys2 and use the packages within cygwin without issues

**Comment by mviereck** [comment]
I want to note that with the great help of @esaulenka I was able to use `xauth.exe` from VcXsrv.
So I don't need `xauth` in MSYS2 anymore and revoke my package request.

Now it is possible with [runx](https://github.com/mviereck/runx) to run `ssh -X` in MSYS2 with X server VcXsrv and cookie authentication.
