### ISSUE TITLE
XZ-compressed zstd package pruned from repository?

### ISSUE THREAD

**Issue by nabijaczleweli** [msys2/MSYS2-packages#3215]
idk if this is the right place to post this, but: https://repo.msys2.org/msys/x86_64/ no longer contains XZ-compressed zstd packages, so it's impossible to do updates from AppVeyor, for example.

The strategy used to be to download and install, in order: `msys2-keyring` (XZ), `zstd` (XZ), `pacman` (XZ), `msys2-keyring` (zstd), then update, then it Just Works, but I can't do that anymore, since `zstd` (XZ) appears to have been pruned (and, for that matter, so has `pacman` (XZ)).

This is a corollary to #2353, I guess?

**Comment by Biswa96** [comment]
That's many months ago. Try to use latest build image in Appveyor or manually install latest msys2 installer in CI or use GitHub Actions.

**Comment by nabijaczleweli** [comment]
No it wasn't. The [latest correct build](https://github.com/nabijaczleweli/cargo-update/commit/25c9f42397e465c5726c7e4f0fa980eb505a5cd9) is 6 days old.

**Comment by Biswa96** [comment]
You have mentioned the older zstd package explicitly. That workaround may not be required anymore. Let me play with it.

**Comment by Biswa96** [comment]
Build succeeded without those old workarounds. Would you like to accept pull request to fix the Appveyor build?

**Comment by nabijaczleweli** [comment]
Can't reproduce this myself, so sure

**Comment by nabijaczleweli** [comment]
Great, thanks – https://github.com/nabijaczleweli/cargo-update/pull/202.

That fixes it for me, so closing.
