### ISSUE TITLE
[RFC] Default to -fstack-protector-strong

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#3237]
This means either passing `-fstack-protector-strong` by default, or building GCC with `--enable-default-ssp` (does clang have an equivalent?)

https://fedoraproject.org/wiki/Security_Features_Matrix has a nice overview with summaries of all the hardening features.

**Comment by lazka** [comment]
There were no objections, so let's give it a try.

**Comment by lazka** [comment]
Arch uses this patch to enable stack protector by default in clang: https://github.com/archlinux/svntogit-packages/blob/packages/clang/trunk/enable-fstack-protector-strong-by-default.patch

**Comment by mati865** [comment]
>  or building GCC with --enable-default-ssp (does clang have an equivalent?)

LLVM doesn't have its own libssp.

**Comment by lazka** [comment]
> --enable-default-ssp     Turn on -fstack-protector-strong by default.

I meant enabling it by default. The option is just badly named I think.

**Comment by lazka** [comment]
It's included in CFLAGS by default now. Let's worry about changing the toolchain default later.

**Comment by lazka** [comment]
I've added a NEWS entry: https://www.msys2.org/news/#2022-10-23-mingw-packages-now-built-with-d_fortify_source2-and-fstack-protector-strong

(I'm not sure if we should expand on it there..)
