### ISSUE TITLE
makepkg: default to -Wl,--large-address-aware for 32bit envs

### ISSUE THREAD

**Issue by lazka** [msys2/MSYS2-packages#3283]
https://learn.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-170

We already have it enabled for some things like clang/python/gcc/binutils to get more memory there, but it would be nice to avoid any potential issues the limited memory causes, especially with upstreams doing less testing with 32bit nowadays.

With all our packages supporting 64bit and ASLR enabled by default for a while I hope that this will not lead to regressions.

**Comment by jeremyd2019** [comment]
The most likely issues I could think of are if something tries to put a pointer into a signed integer type and then gets confused that it's negative, or what I remember Microsoft mentioning about code that assumes the most significant bit being set means it's a kernel-mode address.  Neither seems very likely for portable code.
