### ISSUE TITLE
[parallel] Hangs / simply not working

### ISSUE THREAD

**Issue by W4RH4WK** [msys2/MSYS2-packages#3289]
### Description

Just installed GNU parallel and the first command I tried does not work as expected. Ignoring the obnoxious cite message, it simply hangs.

```
$ parallel echo ::: foo bar
```

Version:

```
$ parallel --version
GNU parallel 20200322
Copyright (C) 2007-2020 Ole Tange, http://ole.tange.dk and Free Software
Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
GNU parallel comes with no warranty.

Web site: http://www.gnu.org/software/parallel

When using programs that use GNU Parallel to process data for publication
please cite as described in 'parallel --citation'.
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows [Version 10.0.19044.2251]

### Expected behavior

Parallel does not hang; expected output:

```
foo
bar
```

### Actual behavior

Parallel hangs, i.e. does not terminate.

### Repro steps

Run:

```
parallel echo ::: foo bar
```

### Are you willing to submit a PR?

No

**Comment by cbrt64** [comment]
This turns out to be a duplicate of #2947. I'll write up my findings there, and submit a PR.

**Comment by lazka** [comment]
Thanks! Let's close this then and continue in #2947

> Note (just FYI) that there is a completely different `parallel.exe` available in the moreutils package.

I see that Arch has renamed that to `parallel-moreutils`, maybe we should too.

**Comment by mesvam** [comment]
I don't think this is a duplicate, the command isn't just slow, it actually hangs forever on my machine. I've left it running for more than a day and there's no sign that it's doing anything. In procmon, there are no processes being started or terminated by this process after a minute

**Comment by cbrt64** [comment]
Is your MSYS2 installation excluded from MS Defender (or whatever malware defense you may use)? On linux, I recently saw the main parallel process hang when a subprocess was killed due to Ctrl-C. If Defender kills a subprocess, the same thing might have happened to you. Just a quick thought FWIW.

**Comment by mesvam** [comment]
Disabling Defender or adding exclusions doesn't seem to have an effect unfortunately
