### ISSUE TITLE
Possible bad GCC package build issue because of Perl version 5.36.0

### ISSUE THREAD

**Issue by stahta01** [msys2/MSYS2-packages#3310]
I am trying to build old versions of MinGW GCC and about 2 weeks ago they stopped working.
I believe the cause was the upgrading of perl to 5.36.0.

The symptom is an MinGW GCC built with perl 5.36.0 does not work when trying to use it to build GCC or binutils.
I confirmed the problem exists for GCC 12.2 on my machine; but, it could be only my machine that has the problem.
The GCC built using perl 5.36.0 acts like it has issues finding its headers and libraries.

Edit2: All my testing was done under MINGW32 and Windows 10 64 bit.

Tim S.

**Comment by jeremyd2019** [comment]
There was recently a regression in msys2-runtime that broke gcc building (MINGW-packages#14173), perhaps that was involved?

**Comment by stahta01** [comment]
> There was recently a regression in msys2-runtime that broke gcc building (MINGW-packages#14173), perhaps that was involved?

Thanks, I will try building with the newest perl version and see if the problem is gone.

Tim S.

**Comment by stahta01** [comment]
The problem seems to be gone and runtime was the likely cause as per jeremyd.
