### ISSUE TITLE
[texinfo] Feature request: add makeinfo.bat to allow other program outside MSYS2 use makeinfo

### ISSUE THREAD

**Issue by ghost** [msys2/MSYS2-packages#3333]
Currently makeinfo is a perl script and thus not a executable for windows, when trying to use makeinfo outside MSYS2, i.e. not inside MSYS2's terminals it won't work. 

This can be fixed by add a simple makeinfo.bat at the same folder of makeinfo, within the makeinfo.bat file:
```bat
@echo off
perl "%~dpn0" %*
```

**Comment by lazka** [comment]
Isn't that true for all perl/python/ruby scripts we ship?

**Comment by pRot0ta1p** [comment]
Sorry, I think I asked the wrong question, texinfo source already have the .bat files, and you are right add a bat file to MSYS package dose not quite make sense. Maybe I should ask for a MinGW64 port of texinfo?

**Comment by yashpalgoyal1304** [comment]
i think this issue can be closed as the OP has deleted per's account, there's nothing more left to be done 😅
