### ISSUE TITLE
Error in installing cgal with vcpkg command

### ISSUE THREAD

**Issue by Sajad86** [msys2/MSYS2-packages#3377]
### Description

I wanted to install cgal library in my windows 10 with the following command:
".\vcpkg install cgal:x64-windows"
But I got en error which I athached the error log file.

[CGALErrorLog.txt](https://github.com/msys2/MSYS2-packages/files/10176623/CGALErrorLog.txt)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Pro

### Expected behavior

-

### Actual behavior

-

### Repro steps

-

**Comment by Biswa96** [comment]
Can you check if excluding the msys2 install directory in antivirus program solves the issue?

**Comment by revelator** [comment]
not allways possible to exclude directories, for instance when it comes to files located in $TMP it would be very bad practice.
luckily i not had many examples where msys2 executables have been flagged lately (atleast not with windows defender).

**Comment by Biswa96** [comment]
The given log contains "cygheap base mismatch detected" error message. It happens if there is two cygwin like installation in PATH or antivirus programs disrupts the process execution. Not related to msys2.
