### ISSUE TITLE
sh.exe change the Windows System Power Plan to High Performance Mode.

### ISSUE THREAD

**Issue by jakitliang** [msys2/MSYS2-packages#3437]
### Description / Steps to reproduce the issue

Start sh.exe will cause the computer's fan spins crazy.

1. `C:/msys64/msys2_shell.cmd -defterm -here -no-start -ucrt64 -shell zsh`
2. `sh.exe`
3. Listen to the fan noise and see that Power Plan changed.

### Expected behavior

Don't change the power plan

### Actual behavior

Power Plan change to HIGH PERFORMANCE

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19042

**Comment by jakitliang** [comment]
> 

YES, I've adding it to my antivirus white list

**Comment by MehdiChinoune** [comment]
It doesn't change POWER PLAN at all. It's just the antivirus.
You could confirm by checking the power plan while shell is open.

**Comment by jakitliang** [comment]
> It doesn't change POWER PLAN at all. It's just the antivirus. You could confirm by checking the power plan while shell is open.

I confirm that.

I use Balance Plan, but starting `sh.exe` the power plan change to the High Performance and I can not select the Balance Plan back.

**Comment by jakitliang** [comment]
And when I CTRL + D exit the sh.exe, the power plan return to Balance Plan.

**Comment by MehdiChinoune** [comment]
Something weird abour your power settings.
Is your CPU an Adler Lake one (Intel 12th Gen)

**Comment by MehdiChinoune** [comment]
Seems like your PC was configured to switch to high performance mode on demand.
I suggest to search online for a solution to your issue specifying your PC model and CPU. Because this is mostly not related to MSYS shell.

**Comment by jakitliang** [comment]
> Is your CPU an Adler Lake one (Intel 12th Gen)

My CPU is Intel i7 10th gen.

> Seems like your PC was configured to switch to high performance mode on demand.

I guess so if it can't reproduce on your computer. And I can not find it out searching almost the answers of the Microsoft websites.

---

I shutdown my computer and reboot find this problem disappeared. 😓
