### ISSUE TITLE
pacman-mirrors got submitted to the AUR

### ISSUE THREAD

**Issue by philmmanjaro** [msys2/MSYS2-packages#3452]
### Description / Steps to reproduce the issue

It seems **pacman-mirrors** got submitted to the [AUR](https://aur.archlinux.org/packages/pacman-mirrors). That [created some issue](https://www.reddit.com/r/ManjaroLinux/comments/zsv4mb/what_is_pacmanmirrors_doing_in_the_aur/) with our similar named package at **Manjaro Linux**.

### Expected behavior

Not to be submitted to the AUR to begin with

### Actual behavior

Due to the versioning of 20221016-1, which is higher than our version 4.23.2-2, some users got an update offered when the AUR was enabled. We will look into it from our end, why AUR packages are preferred over packages in our repositories instead.

A [deletion request](https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/OLL4ENKRRYQL3F2ROG2POMC5G7FC4M63/) was already submitted.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

NONE

**Comment by Biswa96** [comment]
@Freed-Wu Did you submitted that AUR package?

**Comment by Biswa96** [comment]
That AUR package was not provided by msys2 project or by it's members and without any prior discussion.

**Comment by philmmanjaro** [comment]
I assumed that also. Anyway it also had its  good side as it might have pointed us to another issue which should not have happened to begin with in our package manager. So this is more a notification rather a bug report.

**Comment by Freed-Wu** [comment]
Sorry, I just want to test if archlinux can install msys's package so I package it. Because archlinux uses `pacman-mirrorlist` so this package doesn't conflict with any Archlinux package but I don't know manjoro use the same names. Now I'll let the administrator rename this package to msys2-pacman-mirrors to avoid any potential conflict.

**Comment by Freed-Wu** [comment]
Now that this issue is not related to msys2, can we close it? Any other discussion can be continued in the forum. Thanks.
