### ISSUE TITLE
Ease the base package installs

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3457]
### Summary
Installation of packages with multiple binaries available with different package prefixes should be simpler. Different package prefixes i.e. build against different environments.
_ref: "Package Naming" via #3095 thanks god i had opened that issue 😇_

### Summary in examples:

Should look like:
```console
$ pacman -S helix
... optional Questions about choice ...
... on with install ...
```

Looks like:
```console
$ pacman -S helix
error: target not found: helix

$ pacman -Ss helix
mingw32/mingw-w64-i686-helix 22.12-1
    A post-modern modal text editor (mingw-w64)
mingw64/mingw-w64-x86_64-helix 22.12-1
    A post-modern modal text editor (mingw-w64)
ucrt64/mingw-w64-ucrt-x86_64-helix 22.12-1
    A post-modern modal text editor (mingw-w64)

# Some moments of confusion and research
# Then COPY PASTE

$ pacman mingw-w64-***-helix
... on with install ...
```

### Details about problem and current situation
* In case a "base" package is available as build against multiple environments, the package names are prefixed with that environment info.
* While good for disambiguation, this causes the install instructions to become huge and often inconvenient.
* It is self evident when took in contrast with install instruction via other package managers
Refer: [helix/install] (click here for [permalink][helix/install.md])

[<img src="https://user-images.githubusercontent.com/19423063/209869655-e0fc50e5-35c6-4bed-9afa-4e1602a8f81c.png" width=500px/>][helix/install] 

This would not have been a problem if msys2 were only limited for fetching toolchains, or unix packages. However,
* As msys2 is now also being used as a reliable package manager for fetching native packages
* that is, this inconvenience caused by long names will pervade to normal users too

### P.S.

* helix is just one example, nothing special to it, replace it with any other appropriate package name.
* what is syntax for comment in the code block for "console" ? I had to use "bash" to use comments.

----

[msys2/helix]: https://packages.msys2.org/base/mingw-w64-helix
[msys2/gnuplot]: https://packages.msys2.org/base/mingw-w64-gnuplot

[choose-pkg]: https://github.com/msys2/MSYS2-packages/issues/3095

[helix/windows]: https://user-images.githubusercontent.com/19423063/209869655-e0fc50e5-35c6-4bed-9afa-4e1602a8f81c.png

[helix/install]: https://docs.helix-editor.com/install.html
[helix/install.md]: https://github.com/helix-editor/helix/blob/7ac72a39cbcaeda31c717418bde068f9bfc32d0e/book/src/install.md?plain=1#L53-L87

**Comment by yashpalgoyal1304** [comment]
### Thoughts about possible solutions
* I know, that the solution is not very straightforward and this problem is inherent with choice of building environements, 
* but as these packages are listed under the same page on packages.msys2.org
Refer: [msys2/helix], and [msys2/gnuplot]
* so, there's some record or way to club the packages together

#### 1.1
So, some thought out **combination** of the following points can yield some solution i think
* assigning priority to environments (as in f-droid repo priority)
* auto detection: say to: deprioritise i686 ones on x86_64 architectures
* global preference (as in `git --config global`)
* if some ambiguity still remains, then asking for the specification of the package while installing, rather than before...

Ofcourse, this last step also cause some UX issue:
* the whole pipeline will pause waiting for user input, 
* which can be jumpy for veteran CLI users
* but i think if the combination is battle tested enough, then maybe such case(s) of remaining ambiguity will be very very less.

#### 1.2
One further solution can be to add a different option for such base packages. So, using these base package names with normal existing flags will issue error as currently does, and job will run as always. But using these names with that new flag will use this above suggested workflow

#### Example run: 
The comments are just to communicate to you, not necessarily showing that they will be echoed.

```shell
$ pacman -S [--base] helix
$ pacman -S helix
# No exact match found
# Match found for "base package"
# Fetching binaries for different environments
# Narrowing down environments based on those points
# Ambiguity still remaining

Choose environment from below:
#say
clang-x86_64
x86_64
#user inputs accordingly, say
x86_64 chosen
... on with install ...
```



#### Or...
* maybe some solution already exists out there, maybe even in pacman and just i don't know about it 😅 
* The `--groups` option comes quite close to it maybe?
* maybe `MSYSTEM` active environment already automatically chooses it? I ran via wezterm, and my msys-launcher ain't working since months, so, i don't know.
Ref: #3102

**Comment by yashpalgoyal1304** [comment]
#### Or...
* maybe some solution already exists out there, maybe even in pacman and just i don't know about it 😅 
* The `--groups` option comes quite close to it maybe?
* maybe `MSYSTEM` active environment already automatically chooses it? I ran via wezterm, and my msys-launcher ain't working since months, so, i don't know.
Ref: #3102

**Comment by 1480c1** [comment]
I personally would recommend just getting pacboy and running `pacboy -S helix:p`, with the appropriate value for `MINGW_PACKAGE_PREFIX` set within the environment. Only downside afaik is you don't have a way to call that from outside a shell, so not from powershell or cmd, at least not without doing something like `bash -lc 'pacboy -S helix:p'`

**Comment by yashpalgoyal1304** [comment]
> running `pacboy -S helix:p`, 
> with the appropriate value for `MINGW_PACKAGE_PREFIX` set within the environment

wow, glad to see that it uses very similar solution to the one i proposed (with `:p` and the environment variable value)

----
i tried finding its manual online, but didn't find anything on:
* [mankier.com]
* official? site: https://xyne.dev/projects/pacboy/
* official? github repo: [pactoys/source/pacboy]
* `pacman -Ss pacboy`

[mankier.com]: https://www.mankier.com/?q=pacboy
[pactoys/source/pacboy]: https://github.com/renatosilva/pactoys/blob/master/source/pacboy/README.md

**Comment by yashpalgoyal1304** [comment]
other than that, i'd still say that this solution should be embedded within msys2's `pacman`

**Comment by yashpalgoyal1304** [comment]
while searching for git ( `pacman -Ss git` ), i noticed there is package called `pactoys`. i noted this above as well.

so, doing: 

```console
$ pacman -Ss pactoys
msys/pactoys r55.8860e1f-1
    A set of pacman packaging utilities
```

this was what you meant right?

**Comment by Biswa96** [comment]
> this should be merged in the msys2's pacman i guess? 

No, pacman and pactoys are separate project. It should be modified only when it is not possible in any other ways. Here "easing the prefix part" is already done by pactoys/pacboy. So, pacman can do its thing as usual.

**Comment by yashpalgoyal1304** [comment]
* i see your point, it fits very well with unix philosophy. and i personally don't have any problem with it, 
* my worry point is that, how to like... make this method to reach the normal end user reading the installation instructions from other sites (like that helix example....)

**Comment by Biswa96** [comment]
> make this method to reach the normal end user reading the installation instructions from other sites

The helix documentation need some clarification.

Other than the documentation, this does not look like any issue, right?

**Comment by yashpalgoyal1304** [comment]
> Other than the documentation, this does not look like any issue, right?

it kinda is - when you are managing packages, or searching for multiple packages at once then for each package, there are multiple items due to these package *pre*fixes. and being *pre*fixes sorted alphabatically, results get super mingled.

i always brush past it as compromise and actively ignore it as it's not something i am very passionate about at the moment. but it would be good the situation could be improved.

**Comment by Biswa96** [comment]
> there are multiple items due to these package prefixes...results get super mingled.

Yeah, it is somewhat confusing at first. It happened to me also. But when you understand why the prefix was named that way it would get more clear. Hope this page may help https://www.msys2.org/docs/environments/

I shall inform you about the helix docs change.

**Comment by yashpalgoyal1304** [comment]
also note that the `pacboy` did _NOT_ work for me as already reported in above comment: https://github.com/msys2/MSYS2-packages/issues/3457#issuecomment-1368359611

**Comment by Biswa96** [comment]
It depends on which environment you are running pacboy. The `:p` option varies with `MINGW_PACKAGE_PREFIX` environment variable.

**Comment by yashpalgoyal1304** [comment]
> * one possible way can be to increase its reach it to have `pacboy`/`pactoy` installed by default and include it in the msys2 manuals too - that is, giving it an "official treatment", will that make sense??

oh! it's already been added there: 
https://www.msys2.org/docs/package-naming/#avoiding-writing-long-package-names

via https://github.com/msys2/msys2.github.io/pull/208 
<-- found via [blame on package-naming.md](https://github.com/msys2/msys2.github.io/blame/source/web/docs/package-naming.md)

**Comment by yashpalgoyal1304** [comment]
(i also lowkey wonder why did you ask @ podsvirov for review 🤔 - obviously it's not at all important, but aaaah, my mind just gets drawn to it sorry 😅)

**Comment by Biswa96** [comment]
> i also lowkey wonder why did you ask @ podsvirov for review 

See the git history of that file in helix repository.

**Comment by yashpalgoyal1304** [comment]
> See the git history of that file in helix repository.

- aaahw, ohkayh, _of that file_ . nice. 
- i only watched git history of the repo in general.
- but yeah, fair point, will keep this in mind. 

thanks.
