### ISSUE TITLE
Missing msvcr80.dll when running g++ from cmd.exe

### ISSUE THREAD

**Issue by ChromatinRemodeling** [msys2/MSYS2-packages#3489]
### Description / Steps to reproduce the issue

Description:

I was following this article (https://code.visualstudio.com/docs/cpp/config-mingw) to learn how to use msys2 on Windows. I ran "g++ --version" and "g++ --help" on cmd.exe and the output is normal, but when I ran  "g++ --help=optimizers", It reported something like "cc1.exe - error: MSVCR80.dll not found". (This error message was translated from Chinese, so the actual phrasing may be different.) When I tried to use g++ to compile cpp files, the same error message occured.

What I've tried:

(1) Download and run different versions of vcredist.exe

(2) Reinstall msys2 and restart the computer

(3) Search for msvcr80.dll on my own laptop and copy to C:\Windows\System32. There are at least 4 versions of msvcr80.dll, the sizes of which are 612, 617, 778 and 783KB, respectively. I copied them to C:\Windows\System32 separately, and the error message changed for every time but did not disappear.

(4) Run sfc /scannow and some DISM commands. sfc found some problems and fixed. But g++ still not working properly.

My system is Windows 11 Home Chinese Edition, and my processor is AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz. I'm not sure whether this is a bug or something.

### Expected behavior

Successfully execute "g++ --help=optimizers" and "g++ aaa.cpp -o aaa" on cmd.exe

### Actual behavior

Showing a error message box saying something like "cc1.exe - error: MSVCR80.dll not found"

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

**Comment by Biswa96** [comment]
What is the full path of g++ executable?

**Comment by Biswa96** [comment]
What is the full path of g++ executable?

**Comment by ChromatinRemodeling** [comment]
>

C:\msys64\mingw64\bin\g++.exe

**Comment by ChromatinRemodeling** [comment]
May be some environment variable order issue. I typed PATH=C:\Windows\system32;C:\msys64\mingw64\bin;%PATH%, then "g++ --help=optimizers" yields desired results. Thank you for pointing out that binaries under /mingw64 depends on msvcrt.dll. It is very helpful.
