### ISSUE TITLE
MSYS2 Installation Error

### ISSUE THREAD

**Issue by FurqanAthar28** [msys2/MSYS2-packages#3490]
Hi I'm having trouble installing msys2 on windows 11. The installation generated error at 50% download.

![error](https://user-images.githubusercontent.com/117937864/212098738-3ddc4d1e-8b9b-43f3-9c2f-b04f7685519a.png)

**Comment by Biswa96** [comment]
Try to exclude the `C:\msys64` directory in Windows Defender or any antivirus software.

**Comment by Biswa96** [comment]
Issue can not be reproduce in normal condition. Only antivirus program can interfere with the installation procedure.
