### ISSUE TITLE
support the command `__git_ps1` for git branch prompt?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3529]
### Discussed in https://github.com/msys2/MSYS2-packages/discussions/3512

<div type='discussions-op-text'>

<sup>Modified from abridged post by **yashpalgoyal1304** January 25, 2023</sup>

- the gfw prompt `PS1` has this function `__git_ps1` for showing branch name
- I have almost found a minimal way to make it work in msys2 `bash` too

Question:
- Should I make a PR for that here? 
- I am thinking of including it in commented form - the way other tips in these config files are present.

-----
gitforwindows and msys2's default prompts:

<details><summary>this is NOT the solution, is here just for quick reference</summary>

```console
# gfw (git-for-windows)
$ echo $PS1
\[\033]0;$TITLEPREFIX:$PWD\007\]\n\[\033[32m\]\u@\h \[\033[35m\]$MSYSTEM \[\033[33m\]\w\[\033[36m\]`__git_ps1`\[\033[0m\]\n$

$ echo `__git_ps1`
(master)

# msys2 bash
$ echo $PS1
\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n\$
```
</details>

### Additional
* Duplicate searches: [git] | [prompt] | [__git_ps1]

[git]: https://github.com/msys2/MSYS2-packages/issues?q=git
[prompt]: https://github.com/msys2/MSYS2-packages/issues?q=prompt
[__git_ps1]: https://github.com/msys2/MSYS2-packages/issues?q=__git_ps1
</div>

**Comment by Biswa96** [comment]
Packages should not contain user customization parameters. Users are free to add their own prompt text and include shell scripts in shell rc files.

**Comment by yashpalgoyal1304** [comment]
i totally agree that packages shouldn't contain additional stuff... but my reasoning is as follows:

- git is an extremely common thing for developers
- I wasn't able to find any ready made solution to it
- the solution will be non-pervasive - commented out by default ...
- ... exactly simillar to the existing user customisations in these rc files

**Comment by Biswa96** [comment]
> I wasn't able to find any ready made solution to it

Embrace the power of googlefu 🥷 It is already explained here https://github.com/git-for-windows/build-extra/blob/main/git-extra/git-prompt.sh.

In msys2, you can add `source /usr/share/git/completion/git-prompt.sh` in shell rc file and change the PS1 variable according to your need.

**Comment by Biswa96** [comment]
Did you figure things out?

**Comment by yashpalgoyal1304** [comment]
no, i took break from low level stuff... will come back to this sometime later.

**Comment by yashpalgoyal1304** [comment]
just sharing for the records: this issue with git completion (even despite being copying or doing that stuff with git-completion etc)

* [MSYS2#17] PS1 command substitution 

[MSYS2#17]: https://sourceforge.net/p/msys2/tickets/17/#9e50/2168

**Comment by Biswa96** [comment]
You are looking old comments. Things are working as usual. Closing this issue because the command `__git_ps1` for git branch prompt is provided in shell completion scripts as mentioned above. And user has to just enable it in shell rc file.
