### ISSUE TITLE
Inform about "out-of-date" packages?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3536]
hi!

* should pacman warn or inform users about "[out-of-date]" packages ?
* while doing `-S` (installing) `-Ss` (searching) `-Si` (information) or `-Qu` (query updateable)
* i think yes! but would like to discuss on this.

[out-of-date]: https://packages.msys2.org/outofdate

something like: 
(MORE means the currently existing output)
(i dont remember the output format of -S commands, will update the example suggestions later)

```console
$ pacman -S samplepkg
warning: samplepkg out-of-date, contribute with updated PKGBUILD
... MORE ...

$ pacman -Qu samplepkg1 sample2
samplepkg1 0.1 -> 0.2 (out-of-date on repo)
sample2 0.1 (out-of-date on repo)
```

<!--
$ pacman -Ss samplepkg
msys/samplepkg 
```
-->

**Comment by Biswa96** [comment]
`pacman -Syu` command already shows which package need to be updated. Or are you asking for other commands?

**Comment by yashpalgoyal1304** [comment]
i think u havent checked the link 😅 

anyways, i am saying for the softwares which are outdated on the repo itself... not on the system.

**Comment by Biswa96** [comment]
> packages which are outdated on the repo itself

pacman, a package manager, is not for that job. The https://packages.msys2.org/outofdate page get the outdated packages by comparing versions with archlinux, AUR and cygwin.

**Comment by yashpalgoyal1304** [comment]
i was not saying that pacman should get and calculate that info

my idea was if the data from that page is put in repo data itself, and pacman just shows that....

**Comment by Biswa96** [comment]
> my idea was if the data from that page is put in repo data itself somehow

Your idea seems to be similar with this https://github.com/msys2/MSYS2-packages/issues/3088

**Comment by yashpalgoyal1304** [comment]
hi! thanks, yes it seems so... but it might be different as well...

umh, i will ask it there to see if that one covers this or is it better as a separate issue...

**Comment by lazka** [comment]
As said above, pacman is a user tool, not a package maintainer tool. Users shouldn't need to care which packages are outdated, ideally.

**Comment by yashpalgoyal1304** [comment]
> pacman is a user tool, not a package maintainer tool

it has nthng to do with being a pac maintainer. 

it's purpose is to let user know if the package they are going to install is outdated or not so that they can check for themselves if there is any breaking change in latest stable version.

that is, if they install and use an outdated package the latest of which has breaking changes - then they are already shooting themselves in foot.

e.g.: any programs that have some form of interface, or custom format etc. like content creation programms, programs with commands, programming languages

the current example is blender v2.93.14 on msys2 vs v3.4.1 - there are lots of breaking changes in v3.4 from v2.93
