### ISSUE TITLE
[cvs] does cvs in msys2 has miros patches?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [msys2/MSYS2-packages#3565]
i guess i picked a wrong template, i will update later

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19042

**Comment by Biswa96** [comment]
The cvs patches can be found here https://github.com/msys2/MSYS2-packages/tree/master/cvs

**Comment by yashpalgoyal1304** [comment]
The output of `cvs --version` doesn't contain "MirDebian" - so, i think that the MirOS patches are not included

```console
$ cvs --version

Concurrent Versions System (CVS) 1.11.23 (client/server)

Copyright (C) 2006 Free Software Foundation, Inc.

Senior active maintainers include Larry Jones, Derek R. Price,
and Mark D. Baushke.  Please see the AUTHORS and README files from the CVS
distribution kit for a complete list of contributors and copyrights.

CVS may be copied only under the terms of the GNU General Public License,
a copy of which can be found with the CVS distribution kit.

Specify the --help option for further information about CVS
```

**Comment by Biswa96** [comment]
> i think that the MirOS patches are not included

Do you have any issue with msys2 provided cvs package? why do we want to add those patches?

**Comment by yashpalgoyal1304** [comment]
> why do we want to add those patches?

to help users of cvs for migrating repos from cvs to git

**Comment by yashpalgoyal1304** [comment]
it was mentioned as a requirement in reposurgeon - and the author of that Eric - seems to be knowing what he is saying. 

So, i just echoed that here...
