### ISSUE TITLE
Question about `ENABLE_PCON` in mintty

### ISSUE THREAD

**Issue by rashil2000** [msys2/MSYS2-packages#3582]
Hi! 

I come here from this discussion: https://github.com/mintty/wsltty/issues/271#issuecomment-1429789254 

Basically, to use some (native) Windows programs from the Mintty terminal, I was advised to set the environment variable `MSYS=enable_pcon` for proper functioning. 

However, after reading https://www.msys2.org/news/#2022-09-24-conpty-support-enabled-by-default, I feel it shouldn't be required explicitly. But I still need to set it, otherwise the above programs don't work correctly. I have fully updated my MSYS2 distro. 

Interestingly, this problem does not occur on a fresh install of MSYS2. 

What seems to be the issue here? Do I need some specific versions of some packages?

**Comment by Biswa96** [comment]
> Interestingly, this problem does not occur on a fresh install of MSYS2.

As you've found that the issue doesn't happen in fresh install, wouldn't it be easier and quicker to use the newly installed msys2 setup?

**Comment by rashil2000** [comment]
Migrating to a new setup wouldn't be that easy - I have a lot programs installed - some through pacman, some through building from source, and a lot of customizations in /etc folders etc. 

Since this setting affects the core MSYS emulation engine, shouldn't just upgrading to the latest version of `msys2-runtime`, `filesystem`, `bash` be enough?

**Comment by Biswa96** [comment]
> shouldn't just upgrading to the latest version of msys2-runtime, filesystem, bash be enough?

Yes, it should be, but that's the ideal case 😄 

Could you try some basic stuff like -
* updating packages once more with `pacman -Syyu` command
* make sure to use updated mirror (list here https://packages.msys2.org/mirrors)
* reinstalling `msys2-runtime` package
* make sure that there is no MSYS variable defined in system
* make sure there is no option in minttyrc which can disable conpty
etc.

**Comment by rashil2000** [comment]
Okay, I found the cause. The version of `msys2-runtime` was on 3.3.6, while the latest is 3.4.5. 

3.3.6 was showing up as latest because I was following this guide: https://github.com/git-for-windows/git/wiki/Install-inside-MSYS2-proper, which puts Git's pacman repos above MSys2's repos.
