### ISSUE TITLE
Warning emitted by ac-wrapper

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#3588]
### Description / Steps to reproduce the issue

Recently building Emacs emits this warning

```
./autogen.sh
Checking whether you have the necessary tools...
(Read INSTALL.REPO for more details on building Emacs)
Checking for autoconf (need at least version 2.65) ... ok
Your system has the required tools.
Building aclocal.m4 ...
Running 'autoreconf -fi -I m4' ...
ac-wrapper: autoreconf: warning: auto-detected versions not found ( ); falling back to latest available
[...]
```

It seems that this happens since the last `autoconf-wrapper` update

### Expected behavior

.

### Actual behavior

.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
Agree. I can reproduce the warning in my setup. Though the warning does not look serious. It can be workaround with command like this `WANT_AUTOCONF=latest ./autogen.sh`

**Comment by angelog0** [comment]
Yes, it is just a warning, a `noise`...

**Comment by Biswa96** [comment]
This seems like a chicken-egg problem.

1. The autogen.sh file in emacs does not create the aclocal.m4 file using aclocal command. Instead, autogen.sh includes every m4 files in aclocal.m4. This way aclocal.m4 does not have the commented metadata at top.

2. In other side, ac-wrapper.sh finds those commented metadata in aclocal.m4 to extract version number. It does not find the version number and shows that warning. Here is the commit from autotools-wrapper which adds that version check https://gitweb.gentoo.org/proj/autotools-wrappers.git/commit/?h=main&id=26310da15dd46776faf1c8e892896f443aa9c419

**Comment by Biswa96** [comment]
Also emacs do not want to use aclocal as mentioned in autogen.sh file.

```
  # Build aclocal.m4 here so that autoreconf need not use aclocal.
  # aclocal is part of Automake and might not be installed, and
  # autoreconf skips aclocal if aclocal.m4 is already supplied.
```

So, the warning from ac-wrapper is expected.
