### ISSUE TITLE
openssh: OpenSSL version mismatch. Built against 30000070, you have 30100000

### ISSUE THREAD

**Issue by GalaxySnail** [msys2/MSYS2-packages#3660]
### Description / Steps to reproduce the issue

``` shell
$ pacman -Syu
$ ssh --version
OpenSSL version mismatch. Built against 30000070, you have 30100000
$ echo $?
255
```

OpenSSH needs to be rebuilt because of OpenSSL 3.1.0.

### Expected behavior

OpenSSH should work correctly.

### Actual behavior

OpenSSH doesn't work.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19044

**Comment by lazka** [comment]
thanks, fixed now

**Comment by lazka** [comment]
Ah, this is a bug in openssh, it doesn't support openssl 3.0: https://github.com/openssh/openssh-portable/blob/2dc328023f60212cd29504fc05d849133ae47355/openbsd-compat/openssl-compat.c#L43

**Comment by lazka** [comment]
Upstream bug: https://bugzilla.mindrot.org/show_bug.cgi?id=3548

**Comment by rgsl888prabhu** [comment]
@lazka Is this fixed or needs to be fixed ?

**Comment by Biswa96** [comment]
The package is fixed.

```
$ /usr/bin/ssh -V
OpenSSH_9.2p1, OpenSSL 3.1.0 14 Mar 2023
```

**Comment by d3vv3** [comment]
Since it is not available on Debian stable yet: ` sudo apt install libssl3=3.0.8-1 libssl-dev=3.0.8-1 openssl=3.0.8-1`. A full rollback makes it work till new version available.
