### ISSUE TITLE
add helix editor

### ISSUE THREAD

**Issue by soloturn** [msys2/MSYS2-packages#3677]
### Description / Steps to reproduce the issue

wold be cool to have an additional edit option with helix editor: https://github.com/helix-editor/helix, additional to, or instead of vim.

### Expected behavior

n/a

### Actual behavior

n/a

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

master

### Are you willing to submit a PR?

yes, if i can find how to :)

**Comment by Biswa96** [comment]
Already present https://packages.msys2.org/base/mingw-w64-helix
