### ISSUE TITLE
[vim] broken syntax highlighting 

### ISSUE THREAD

**Issue by sthalik** [msys2/MSYS2-packages#3680]
### Description / Steps to reproduce the issue

0. `$ vim`
1. `:se ft=c`
2. `:syntax on`

Last working version is vim 8.2.3582-1.

### Expected behavior

Syntax highlighting loaded.

### Actual behavior

```console
E484: Can't open file /usr/share/vim/vim82/syntax/syntax.vim
```

Note: making a symlink to `/usr/share/vim/vim90` makes it explode with a screenful worth of an error.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
Do you have any vimrc like file which have that old vim82 path? vim syntax is working fine in my system.

**Comment by sthalik** [comment]
This was a PEBKAC error (`vi.exe` hard linked rather than soft linked). Sorry for the noise.
