### ISSUE TITLE
I cannot install MSys2 without user interaction

### ISSUE THREAD

**Issue by vporton** [msys2/MSYS2-packages#3713]
### Description / Steps to reproduce the issue

I want to install MSys2 without user interaction and run:
```
.\msys2.exe --accept-licenses --accept-messages --confirm-command -t c:\msys2
```

### Expected behavior

Run without user interaction.

### Actual behavior

Displays a dialog box.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

**Comment by lazka** [comment]
You need to pass a command:

```
.\msys2.exe --accept-licenses --accept-messages --confirm-command -t c:\msys2 install
```
