### ISSUE TITLE
Do you have any plans to disable zlib support for openssl?

### ISSUE THREAD

**Issue by yumetodo** [msys2/MSYS2-packages#3731]
https://github.com/msys2/MSYS2-packages/blob/af2d9260bfaa35bf5e167d97f53a5535cacd3f05/openssl/PKGBUILD#L61

Currently, openssl is built with zlib support.

However, there are CRIME attack risk to be enabled zlib support.

Arch Linux's PKGBUILD dropped at https://github.com/archlinux/svntogit-packages/commit/9b3777f123bd298851a3ce1c2c6f2c4c3214b138.

**Comment by lazka** [comment]
thanks, sounds good
