### ISSUE TITLE
Mintty: StatusLine option causes msys2 to fail

### ISSUE THREAD

**Issue by TheBigEye** [msys2/MSYS2-packages#3746]
### Description / Steps to reproduce the issue

- There is an option in the Mintty configuration that is causing a problem (The status line), it turns out that when you activate it nothing bad happens at first glance, but when you close the terminal and then want to open it again, it crashes internally

1. Open any MSYS2 terminal
2. Access the terminal options with right click on the title bar
3. Go to `terminal` category
4. Activate the option `Status Line`
5. Apply, save the changes and close the terminal
6. Try open again the terminal :)

- When you want to open the terminal again, nothing will open, a `mintty.exe.stackdump` file will be generated
- To undo the problem it is necessary to modify the line `StatusLine=yes` to `StatusLine=no` in the `.minttyrc `file, thus deactivating the option and the terminal reopens without problems

### Expected behavior

It is expected that the terminal that has the activated configuration explained above can be opened without crashing ._.

### Actual behavior

- The following stack dump is generated:
```
Exception: STATUS_ACCESS_VIOLATION at rip=00010041B052
rax=0000000000000000 rbx=FFFFFFFFFFFFFFF8 rcx=00000000FFFFFFFF
rdx=0000000000000000 rsi=0000000000000000 rdi=00000000FFFFFFFF
r8 =FFFFFFF800003BB0 r9 =0000000000000001 r10=0000000000000000
r11=000000010041CD3F r12=0000000000000001 r13=00000001004E65A0
r14=00000007FFFFC6A0 r15=00000001004FBD80
rbp=00000007FFFFC610 rsp=00000007FFFFC4E0
program=C:\msys64\usr\bin\mintty.exe, pid 1621, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame         Function      Args
0007FFFFC610  00010041B052 (055600000000, 000000000300, 055600000000, 0001000002D8) mintty.exe+0x1B052
0007FFFFC610  00010041CD71 (000A00001BB0, 0001802386D4, 000100449F50, 000080000000) mintty.exe+0x1CD71
0007FFFFC610  000100466D1B (000180271D98, 0007FFFFCD30, 000A000015D9, 0007FFFFCC30) mintty.exe+0x66D1B
0007FFFFCD30  000180048140 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x8140
0007FFFFFFF0  000180045C86 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5C86
0007FFFFFFF0  000180045D34 (000000000000, 000000000000, 000000000000, 000000000000) msys-2.0.dll+0x5D34
End of stack trace
Loaded modules:
000100400000 mintty.exe
7FFD5ACF0000 ntdll.dll
7FFD5AAF0000 KERNEL32.DLL
7FFD584C0000 KERNELBASE.dll
7FFD59CB0000 ADVAPI32.dll
7FFD59750000 msvcrt.dll
7FFD59C10000 sechost.dll
7FFD5A4C0000 RPCRT4.dll
7FFD599B0000 comdlg32.dll
7FFD5A6C0000 combase.dll
7FFD58880000 ucrtbase.dll
7FFD596A0000 shcore.dll
7FFD594A0000 USER32.dll
7FFD58490000 win32u.dll
7FFD5ABD0000 GDI32.dll
7FFD58C30000 gdi32full.dll
7FFD58B90000 msvcp_win.dll
7FFD59640000 SHLWAPI.dll
7FFD59D60000 SHELL32.dll
7FFD5AC20000 IMM32.dll
7FFD59880000 ole32.dll
000180040000 msys-2.0.dll
7FFD47D30000 COMCTL32.dll
7FFD33380000 gdiplus.dll
7FFD4C600000 MPR.dll
7FFD50FA0000 WINMM.dll
7FFD402B0000 USP10.dll
7FFD3F9B0000 WINSPOOL.DRV
7FFD57CC0000 CRYPTBASE.DLL
7FFD583D0000 bcryptPrimitives.dll
7FFD561A0000 dwmapi.dll
7FFD55DE0000 uxtheme.dll
7FFD59AF0000 MSCTF.dll
7FFD5A5F0000 OLEAUT32.dll
7FFD41BE0000 TextShaping.dll
```

- I'm not sure what that setting does to cause this error

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

I'm sorry, I don't know how to fix this :(

**Comment by Biswa96** [comment]
Thanks you for reporting this issue. After enabling `StatusLine=yes`, I can reproduce it in my setup with msys2's mintty and from mintty source code. I have compiled mintty with `make DEBUG=1` and got the following message:

![image](https://user-images.githubusercontent.com/31443074/235043402-973b36fa-42f7-4f07-8005-46bb425ae9eb.png)

@mintty would you like look into this issue please?

**Comment by mintty** [comment]
I could reproduce this on one system but not on another (where I had tested it). Maybe some mysterious system dependency...

**Comment by mintty** [comment]
It happened with monitor DPI == 96. Fixed in repository.

**Comment by mintty** [comment]
Thanks for monitoring this and sorry for the release delay.
