### ISSUE TITLE
glib-compile-schemas failed on directory name with non Latin symbols

### ISSUE THREAD

**Issue by dantld** [msys2/MSYS2-packages#3764]
**Observed**:
`glib-compile-schemas` failed on MS Windows platform under the MINGW64 environment when source directory, passed through the command line, contains the non Latin symbols.

Example below show the problem: calling `glib-compile-schemas` with non-Latin symbols in source directory.
```sh
$ glib-compile-schemas.exe /c/Shared/vista-client-service/Юзер

(glib-compile-schemas.exe:7476): GLib-CRITICAL **: 19:05:16.746: g_dir_open_with_errno: assertion 'wpath != NULL' failed
Error opening directory в??(NULL)в??: No error
```

**Comment by Biswa96** [comment]
Please explain the issue. Also shouldn't you use the mingw glib2 package?

**Comment by dantld** [comment]
> 



> Did you report the issue in upstream and suggest your changes there?

Yes I'm raise the issue and suggest the fixing.

**Comment by Biswa96** [comment]
In that upstream repository, the fix should be provided as a merge request (same as pull request here).

**Comment by dantld** [comment]
I've made mistake: this issue must be opened in the MINGW-packages.
