### ISSUE TITLE
gcovr coverage report installation

### ISSUE THREAD

**Issue by pwr230047** [msys2/MSYS2-packages#3769]
### Description / Steps to reproduce the issue

Command:
`pacman -Q`
Version MSYS2:
msys2-keyring 1~20221024-1
msys2-launcher 1.5-1
msys2-runtime 3.3.6-3

1. `pacman -S mingw-w64-ucrt-x86_64-python-pip`
2. `pip install gcovr`

How to solve the problem??

### Expected behavior

I don't know.

### Actual behavior

`pip install gcovr`
Collecting gcovr
  Using cached gcovr-6.0-py2.py3-none-any.whl (94 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: pygments in c:/msys64/ucrt64/lib/python3.10/site-packages (from gcovr) (2.15.1)
Collecting lxml
  Using cached lxml-4.9.2.tar.gz (3.7 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: MarkupSafe>=2.0 in c:/msys64/ucrt64/lib/python3.10/site-packages (from jinja2->gcovr) (2.1.2)
Installing collected packages: lxml, jinja2, gcovr
  DEPRECATION: lxml is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the
'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' o
ption. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for lxml ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lxml did not run successfully.
  │ exit code: 1
  ╰─> [128 lines of output]
      Building lxml version 4.9.2.
      Building without Cython.
      Building against pre-built libxml2 andl libxslt libraries
      running install
      C:/msys64/ucrt64/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is
 deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.mingw_x86_64_ucrt-3.10
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/builder.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/cssselect.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/doctestcompare.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/ElementInclude.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/pyclasslookup.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/sax.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/usedoctest.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/_elementpath.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/__init__.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/__init__.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/builder.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/clean.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/defs.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/diff.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/ElementSoup.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/formfill.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/html5parser.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/soupparser.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/usedoctest.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/_diffcommand.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/_html5builder.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/_setmixin.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      copying src/lxml/html/__init__.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/html
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron
      copying src/lxml/isoschematron/__init__.py -> build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron
      copying src/lxml/etree.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/etree_api.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/lxml.etree.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/lxml.etree_api.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/etree.pyx -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/objectify.pyx -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/apihelpers.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/classlookup.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/cleanup.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/debug.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/docloader.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/dtd.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/extensions.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/iterparse.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/nsclasses.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/objectpath.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/parser.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/parsertarget.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/proxy.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/public-api.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/readonlytree.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/relaxng.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/saxparser.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/schematron.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/serializer.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xinclude.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xmlerror.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xmlid.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xmlschema.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xpath.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xslt.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/xsltext.pxi -> build/lib.mingw_x86_64_ucrt-3.10/lxml
      copying src/lxml/includes/c14n.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/config.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/dtdvalid.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/etreepublic.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/htmlparser.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/relaxng.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/schematron.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/tree.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/uri.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xinclude.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xmlerror.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xmlparser.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xmlschema.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xpath.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/xslt.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/__init__.pxd -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/etree_defs.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      copying src/lxml/includes/lxml-version.h -> build/lib.mingw_x86_64_ucrt-3.10/lxml/includes
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/rng
      copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/
rng
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/xsl
      copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/xsl
      creating build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.mingw_x86_64_ucrt-3.10/lxm
l/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.mingw_x86_64_ucrt-3.10/lxml/i
soschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.mingw_x86_64_ucrt-3.10/
lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.mingw_x86_64
_ucrt-3.10/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.mingw_x86_64_ucrt-3.10/lxml
/isoschematron/resources/xsl/iso-schematron-xslt1
      copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.mingw_x86_64_ucrt-3.10/lxml/isoschematr
on/resources/xsl/iso-schematron-xslt1
      running build_ext
      building 'lxml.etree' extension
      creating build/temp.mingw_x86_64_ucrt-3.10
      creating build/temp.mingw_x86_64_ucrt-3.10/src
      creating build/temp.mingw_x86_64_ucrt-3.10/src/lxml
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O2 -pipe -O3 -march=x86-64 -mtu
ne=generic -O2 -pipe -O3 -DCYTHON_CLINE_IN_TRACEBACK=0 -Isrc -Isrc/lxml/includes -IC:/msys64/ucrt64/include/python3.10 -c src/lxml/etre
e.c -o build/temp.mingw_x86_64_ucrt-3.10/src/lxml/etree.o -w
      In file included from src/lxml/etree.c:858:
      src/lxml/includes/etree_defs.h:14:10: fatal error: libxml/xmlversion.h: No such file or directory
         14 | #include "libxml/xmlversion.h"
            |          ^~~~~~~~~~~~~~~~~~~~~
      compilation terminated.
      Compile failed: command 'C:\\msys64\\ucrt64\\bin/gcc.exe' failed with exit code 1
      creating Users
      creating Users/P0FE4~1.PRZ
      creating Users/P0FE4~1.PRZ/AppData
      creating Users/P0FE4~1.PRZ/AppData/Local
      creating Users/P0FE4~1.PRZ/AppData/Local/Temp
      creating Users/P0FE4~1.PRZ/AppData/Local/Temp/1
      gcc -mdll -O2 -Wall -I/usr/include/libxml2 -c C:/Users/P0FE4~1.PRZ/AppData/Local/Temp/1/xmlXPathInitxxky5jcw.c -o Users/P0FE4~1.P
RZ/AppData/Local/Temp/1/xmlXPathInitxxky5jcw.o
      C:/Users/P0FE4~1.PRZ/AppData/Local/Temp/1/xmlXPathInitxxky5jcw.c:1:10: fatal error: libxml/xpath.h: No such file or directory
          1 | #include "libxml/xpath.h"
            |          ^~~~~~~~~~~~~~~~
      compilation terminated.
      error: command 'C:\\msys64\\ucrt64\\bin/gcc.exe' failed with exit code 1
      *********************************************************************************
      Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
      *********************************************************************************
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lxml

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

WIN 10

**Comment by Biswa96** [comment]
There are some incompatibility with mingw python, see https://www.msys2.org/docs/python/. If a python module contains C file those may not build.

* Easier way: Install `mingw-w64-ucrt-x86_64-python-lxml` package before the pip command. Make sure there is no similar python package installed with pacman. Otherwise, there may be conflicts with similar files.
* Harder way: Create mingw gcovr package.

**Comment by pwr230047** [comment]
Thanks for the quick and simple answer. I chose the easier way to solve it, because I didn't understand the more difficult help.
After installing the "pip" packages in MSYS2, I decided to enter your command: _packam - S mingw-w64-ucrt-x86_64-python-lxml_.
Then: _pip install gcovr_

**I got this result successfully :**
Collecting gcovr
   Using cached gcovr-6.0-py2.py3-none-any.whl (94 kB)
Collecting jinja2 (from gcovr)
   Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Requirement already satisfied: lxml in c:/msys64/ucrt64/lib/python3.10/site-packages (from gcovr) (4.9.1)
Requirement already satisfied: pygments in c:/msys64/ucrt64/lib/python3.10/site-packages (from gcovr) (2.15.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:/msys64/ucrt64/lib/python3.10/site-packages (from jinja2->gcovr) (
2.1.2)
Installing collected packages: jinja2, gcovr
Successfully installed gcovr-6.0 jinja2-3.1.2

Unfortunately, after installing the _pip_ and _lxml_ packages, as well as adding _project.yml_ to the unit test project configuration file:
:plugins:
   :load_paths:
     - "#{Ceedling.load_path}"
   :enabled:
     - stdout_pretty_tests_report
     - module_generator
     - gcov
   :gcov:
     :utilities:
       - gcovr # Use gcovr to create the specified reports (default).
       - ReportGenerator # Use ReportGenerator to create the specified reports.

I typed commands:
- _$ ceedling gcov:all utils:gcov_
- _$ ceedling gcov:all_

**It produces an ERROR.**
rake aborted!
Don't know how to build task 'gcov:all' (See the list of available tasks with `rake --tasks`)
/home/p.przemysl/.gem/ruby/2.7.0/gems/ceedling-0.31.1/bin/ceedling:345:in `block in <top (required)>'
/home/p.przemyśl/.gem/ruby/2.7.0/gems/ceedling-0.31.1/bin/ceedling:332:in `<top (required)>'
/home/p.przemyski/.gem/ruby/2.7.0/bin/ceedling:23:in `load'
/home/p.przemyśl/.gem/ruby/2.7.0/bin/ceedling:23:in `<main>'
(See full trace by running task with --trace)
ERROR: Ceedling Failed

**Comment by Biswa96** [comment]
Please provide the steps to reproduce the issue.

**Comment by Biswa96** [comment]
My apology I did not understand anything from step 4. Please wait for others to comment about this issue.

**Comment by pwr230047** [comment]
Step 4 is used for the configuration file for the Ceedling package.
Do help chapter under link: [Code coverage](https://embetronicx.com/tutorials/unit_testing/unit-testing-in-c-testing-with-unity/)

**Comment by pwr230047** [comment]
### Solution
Install the python pip package by typing the command in the MSYS2 UCRT64 console:
`pacman -S mingw-w64-ucrt-x86_64-python-pip`
Install the lxml package for Python by entering the following command in the MSYS2 UCRT64 console:
`pacman -S mingw-w64-ucrt-x86_64-python-lxml`
Install _dotnet-sdk-7.0.302-win-x64.exe_.
Install ReportGenerator. Run Launch Windows Commands and type the command:
`dotnet tool install -g dotnet-reportgenerator-globaltool`

![image](https://github.com/msys2/MSYS2-packages/assets/32525496/e763eca5-ec67-4801-b6b0-37a798150e85)

![image](https://github.com/msys2/MSYS2-packages/assets/32525496/69aa6380-56a7-466e-9635-2426bcddb866)
