### ISSUE TITLE
Ansible package - function 'wcwidth' not found

### ISSUE THREAD

**Issue by chibicitiberiu** [msys2/MSYS2-packages#3773]
### Description / Steps to reproduce the issue

I installed and updated a fresh copy of msys2, and then installed ansible. Running any ansible command has the following output: `ERROR: function 'wcwidth' not found`.

E.g:
1. install ansible `pacman -S ansible`
2. run an ansible command `ansible whatever`
3. error

### Expected behavior

The ansible command should work.

### Actual behavior

ERROR: function 'wcwidth' not found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

**Comment by chibicitiberiu** [comment]
The issue could be fixed with a patch that adds a dependency to the [wcwidth](https://pypi.org/project/wcwidth/) library, and replaces the calls to libc with calls to this library in `utils/display.py`.

**Comment by eddieparker** [comment]
I am having the same issue.  I did a 'pacman -Suy' and had nothing to update and I still get the same error about wcwidth not found.

Running the print command you had gave me 'None' as a response.

Do I need to install another package to make this work?

**Comment by arisudesu** [comment]
I encountered this error when tried to run ansible in MSYS environment. Output is `none`. In MINGW64 environment seems OK, output is `msvcrt.dll`.

**Comment by alexjorgef** [comment]
I apologize for returning to this subject so late, I finally have the machine ready to test a fresh installation. @chibicitiberiu @eddieparker @arisudesu @apg036, can you share the output of these two commands? Thanks

```shell
pacman -Q
```

```shell
uname -a
```

**Comment by alexjorgef** [comment]
@apg036 Thanks, apart from being MSYS2 MinGW64 (_MINGW64_NT_), my MSYS2 (_MSYS_NT_) environment looks exactly the same as yours, and Ansible runs without a problem. I'm re-installing Windows and MSYS2, and see if with a fresh installation I can reproduce the error.

**Comment by alexjorgef** [comment]
Should be fixed with #3821

**Comment by marko0486** [comment]
I have the same issue.
Thanks for the update
