### ISSUE TITLE
After an Update, the Shell Does Not Start and Closes

### ISSUE THREAD

**Issue by P0W3** [msys2/MSYS2-packages#3777]
### Description / Steps to reproduce the issue

In MSYS2, I used the command, "pacman -Syu". Then, the update error occured. Then, I exited MSYS2. Then, I launched "msys2.exe", and these errors appeared.

![image](https://github.com/msys2/MSYS2-packages/assets/18279115/6ba77637-4bba-4efc-8ae5-92bb094fcfc6)
![image](https://github.com/msys2/MSYS2-packages/assets/18279115/0214d664-d535-4e3d-83ea-ce8d27dd05a1)
![image](https://github.com/msys2/MSYS2-packages/assets/18279115/f04d4090-37a8-46f9-920a-2b37a602bdcd)

Note that it was never the fault from the staff of devkitPro.

### Expected behavior

MSYS2 should be run properly.

### Actual behavior

MSYS2 is not being run properly.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW32_NT-6.2

**Comment by P0W3** [comment]
[pacman.log](https://github.com/msys2/MSYS2-packages/files/11512800/pacman.log)

**Comment by Biswa96** [comment]
Did you exclude the msys2 installation directory in the antivirus software (for example Windows Defender) ?

> error: could not create database entry mintty-1~3.6.4-1
> error: could not create database entry msys2-runtime-3.4.6-2

From those lines in log file, it seems that something blocked the creation of database entry. Antivirus programs are generally the first suspect.

**Comment by P0W3** [comment]
I disabled Windows Defender, and I launched "msys2.exe". But, the same error occurred.

![image](https://github.com/msys2/MSYS2-packages/assets/18279115/2a3ef900-55c0-454a-8941-4bda29bbf8dc)
![image](https://github.com/msys2/MSYS2-packages/assets/18279115/9468b4b5-9c0c-4cbe-854b-fd92811b8d7c)
![image](https://github.com/msys2/MSYS2-packages/assets/18279115/89ec3361-d788-402c-b57c-bb9b197425a1)

[pacman.log](https://github.com/msys2/MSYS2-packages/files/11515947/pacman.log)

**Comment by MehdiChinoune** [comment]
Could you take a look at `D:\devkitPro\msys2\usr\bin` and see if mintty.exe exist, Maybe AV has deleted it.

**Comment by P0W3** [comment]
I looked into the directory, "`D:\devkitPro\msys2\usr\bin`". Also, "mintty.exe" is missing.

**Comment by sskras** [comment]
It would be nice if installer was to disable / add the exception to the AV automatically.

**Comment by Biswa96** [comment]
> Also, "mintty.exe" is missing.

It seems that Microsoft Defender has already modified or removed some files. Clean reinstalling may be the only hassle free solution now. Next time, remember to exclude the msys2 installation directory in Microsoft Defender.

> It would be nice if installer was to disable / add the exception to the AV automatically.

Even if it is possible, it would be a malicious behaviour. Any malware could take that kind of advantage.

**Comment by sskras** [comment]
@Biswa96, agreed to a degree. Then if the operation asks user to confirm adding of specific item (eg. using UAC prompt) with the provided details, it's not malicious.

BTW, it's possible to do with Power Shell and its' command `-Command Add-MpPreference -ExclusionPath`:
[Windows Defender - Add exclusion folder programmatically](https://stackoverflow.com/questions/40233123/windows-defender-add-exclusion-folder-programmatically/45339380#45339380)

**Comment by P0W3** [comment]
After managing MSYS2, I launched "msys2.exe", and I encountered this error.

![image](https://github.com/msys2/MSYS2-packages/assets/18279115/98174cab-c69d-43f1-a075-99a754f3e309)

"mintty.exe" is there, but "bash.exe" is not there.

**Comment by P0W3** [comment]
[pacman.log](https://github.com/msys2/MSYS2-packages/files/11521035/pacman.log)

**Comment by Biswa96** [comment]
> "mintty.exe" is there, but "bash.exe" is not there.

Excluding the msys64 path in Windows Defender is the only way here. We can not do anything in this situation.
