### ISSUE TITLE
I Used "update-ca-certificates", Then "-bash: update-ca-certificates: command not found" - What Happened?

### ISSUE THREAD

**Issue by P0W3** [msys2/MSYS2-packages#3813]
```
$ update-ca-certificates
-bash: update-ca-certificates: command not found
```

What happened?

**Comment by Biswa96** [comment]
Where did you find that command name `update-ca-certificates`? Are you looking for `update-ca-trust`?

**Comment by P0W3** [comment]
> Where did you find that command name `update-ca-certificates`? Are you looking for `update-ca-trust`?

Are you saying that `update-ca-certificates` is deprecated? Because as much as I remember, `update-ca-certificates` is still available. Also, you mentioned `update-ca-trust`.

This too happened.

```
$ update-ca-trust
-bash: /usr/bin/update-ca-trust: cannot execute: required file not found
```

**Comment by Biswa96** [comment]
It seems that `update-ca-certificates` is not provided in msys2 packages. Let us look into the issue.

**Comment by P0W3** [comment]
`ca-certificates-20230311-1` is already up-to-date.

**Comment by lazka** [comment]
update-ca-certificates is a Debian command, I don't think we every had it.
