### ISSUE TITLE
coreutils: Writing image by `dd` does not write the first partition correctly

### ISSUE THREAD

**Issue by KSR-Yasuda** [msys2/MSYS2-packages#3837]
### Description / Steps to reproduce the issue

Writing image by `dd` command works wrongly:
it does not write the first partition correctly.

```bash
% fdisk -l test.img
Disk test.seg: 16 KiB, 16384 bytes, 32 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x4bfafcd5

Device     Boot Start   End Sectors  Size Id Type
test.img1        2048 34815   32768   16M  e W95 FAT16 (LBA)
test.img2       34816 62719   27904 13.6M  e W95 FAT16 (LBA)

# SD card is `/dev/sdd`.

# [NG] Writing whole image at once into `/dev/sdd` fails
# to make the first partition (i.e. `/dev/sdd1`) broken:
# file name, file data, etc. are corrupted.
# 
# However, the latter partition (i.e. `/dev/sdd2`) is written correctly.
% dd if=test.img of=/dev/sdd

# [OK] Rewriting the first partition with writing image into `/dev/sdd1` succeeds.
% dd if=test.img of=/dev/sdd1 skip=2048 count=32768

# [NG] Rewriting via `/dev/sdd` fails, though.
% dd if=test.img of=/dev/sdd  skip=2048 count=32768 seek=2048

# [OK?] Reading the whole image via `/dev/sdd` looks working successfully.
% dd of=test2.img if=/dev/sdd
```

```bash
% pacman -F dd.exe
git-for-windows/mingw-w64-x86_64-busybox 1.34.0.19688.985b51cf7-1
    mingw64/libexec/busybox/dd.exe
git-for-windows-mingw32/mingw-w64-i686-busybox 1.34.0.19688.985b51cf7-1
    mingw32/libexec/busybox/dd.exe
msys/coreutils 8.32-5 [installed]
    usr/bin/dd.exe
```

Is there any constraints?

### Expected behavior

Writing image via `/dev/sd?` (e.g. `dd if=test.img of=/dev/sdd`) works correctly.

### Actual behavior

Writing image via `/dev/sd?` (e.g. `dd if=test.img of=/dev/sdd`) creates broken first partition.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045 ******** 3.3.6-bec3d608-341.x86_64 2023-05-08 18:33 UTC x86_64 Msys

**Comment by sskras** [comment]
1. Do similar tools fail to write the 1st partition to `/dev/sdd` too?
I mean:

- BusyBox-based implementation that you mentioned
- http://www.chrysocome.net/dd
- [rawcopy](http://www.ltr-data.se/opencode.html/#:~:text=Reads%20and%20writes%20files%20and%20devices)
- [HDD Raw Copy Tool](https://hddguru.com/software/HDD-Raw-Copy-Tool/)

2. Had the device partitions cleaned before writing the `test.img` ?

**Comment by KSR-Yasuda** [comment]
At the first post, it was Git-for-Windows SDK's MSYS env.

Now I tested the same in pure MSYS env,
it does completely rejected `/dev/sdX` device access.

```
% dd if=/dev/sdd of=test.img
dd: failed to open '/dev/sdd': Permission denied

% LANG=C sudo dd if=/dev/sdd of=test.img
dd: failed to open '/Device/Harddisk3/Partition0': No such file or directory
```

So, I'll withdraw the issue.

**Comment by KSR-Yasuda** [comment]
@sskras The letter is `dd` executed via [`gsudo`](https://github.com/gerardog/gsudo).
So I thought Git-for-Win env was special.

**Comment by sskras** [comment]
Ah, so MSYS2 was already elevated?
OK, seems like I will retest that scenario myself.

Regarding Git-for-Win:  if it behaves differently, then there is something really special.

Maybe some special steps were made by the setup Wizard. Eg. `SeCreateSymbolicLinkPrivilege` being added to the rights of my Windows user.

![image](https://github.com/msys2/MSYS2-packages/assets/7887758/f035239b-1d91-44d0-b634-8ec248316cd6)

Not sure, will have to test.
