### ISSUE TITLE
openssh: OpenSSL version mismatch. Built against 30000070, you have 30100010

### ISSUE THREAD

**Issue by guraltsev** [msys2/MSYS2-packages#3839]
### Description / Steps to reproduce the issue

Currently, ```ssh``` is broken with the updated ssl library

1. Update current MSYS2 installation
2. Here are the current package versions:
```
msys/openssh 9.3p1-1
msys/libssh2 1.11.0-1
msys/openssl 3.1.1-1
msys/libopenssl 3
```
3. Run any ```ssh``` command:
```
$ ssh --version
OpenSSL version mismatch. Built against 30000070, you have 30100010
```

### Expected behavior

SSH should work with currently available openssl package.

### Actual behavior

SSH errors out with currently available openssl package.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
It's working find in my setup.

```
$ ssh -V
OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
```

Are you using git-for-windows and msys2 both? What is the output of this command ` which ssh` ?

**Comment by guraltsev** [comment]
I have git for windows installed but separately from msys2. Strange, somehow it is no longer a problem for me if I try to reproduce it. It seems that downgrading and then upgrading again solved it. 

Here is the paths:
```
$ which ssh
/usr/bin/ssh
```

```
$  ssh -V
OpenSSH_9.3p1, OpenSSL 3.1.1 30 May 2023
```

```
$ pacboy info openssh
Name            : openssh
Version         : 9.3p1-1
```
