### ISSUE TITLE
Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by Yolkkkk** [msys2/MSYS2-packages#3863]
### Description / Steps to reproduce the issue

windows 

after install steps, I opened msys2.exe and use `pacman -Syu` and get output as followed

### Expected behavior

How can i `pacman -Syu` without error

### Actual behavior

```
error: failed retrieving file 'mingw32.db' from mirror.msys2.org : Recv failure: Connection reset by peer
error: failed retrieving file 'mingw64.db' from mirror.msys2.org : Recv failure: Connection reset by peer
```
![微信图片_20230628162302](https://github.com/msys2/MSYS2-packages/assets/55338216/0b199405-04be-4c0f-9268-9f40cb6fcc6b)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22621

**Comment by Biswa96** [comment]
There may be some issue with the network. Try to change mirrors in /etc/pacman.d or retry after some time.

**Comment by Biswa96** [comment]
The `pacman -Syu` command is working fine in my system.

![image](https://github.com/msys2/MSYS2-packages/assets/31443074/123a760f-0a82-4801-9567-fd6440ef551d)

**Comment by Biswa96** [comment]
The issue can not be reproduced.

**Comment by sskras** [comment]
Even if I support the "not planned" decision, it would be nice to know a way of troubleshooting this kind of HTTP-connectivity / network / middleboxe issue.

I wonder if people have implemented such tool in the ever accelerating world of HTTP transport.
