### ISSUE TITLE
cmd `set MSYSTEM=MINGW64 && "C:\msys64\usr\bin\bash.exe" -l ` set `path` var incorrect

### ISSUE THREAD

**Issue by WittonBell** [msys2/MSYS2-packages#3864]
### Description / Steps to reproduce the issue

env: WIN10 22H2
msys2 install at C:\msys64

1. use C:\msys64\mingw64.exe start mingw64, use cmd `echo $PATH` show:
```
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:...
```
It's correct.

2. use cmd `set MSYSTEM=MINGW64` first, then use `"C:\msys64\usr\bin\bash.exe" -l ` , the `PATH` is:
```
/mingw64/bin:/usr/local/bin:/usr/bin:/bin:...
```
It's correct.

3. use cmd `set MSYSTEM=MINGW64 && "C:\msys64\usr\bin\bash.exe" -l ` in windows terminal `Command Prompt`, show the var `PATH` is:
```
/bin:/usr/local/bin:/usr/bin:/bin:...
```
It's incorrect.

It also causes an error `PATH` of MinGW64 terminal in VSCode with confgiure:
```
"MinGW64": {
      "path": "C:\\msys64\\usr\\bin\\bash.exe",
      "args": ["-l"],
      "env": {
        "MSYSTEM": "MINGW64",
        "CHERE_INVOKING": "1",
        "MSYS2_PATH_TYPE": "inherit"
      }
    }
```

### Expected behavior

cmd `set MSYSTEM=MINGW64 && "C:\msys64\usr\bin\bash.exe" -l ` could set `PATH` correct.

### Actual behavior

cmd `set MSYSTEM=MINGW64 && "C:\msys64\usr\bin\bash.exe" -l ` not set `/mingw64/bin` in `PATH` var first.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

**Comment by WittonBell** [comment]
I found that it was caused by a case statement matching failure in the `etc/msystem` script. It should be a bug in the case statement. Replace it with an if statement to determine if it will work properly.

```
if [ ${MSYSTEM} == MINGW32 ]; then
        MSYSTEM_PREFIX='/mingw32'
        MSYSTEM_CARCH='i686'
        MSYSTEM_CHOST='i686-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
elif [ ${MSYSTEM} == MINGW64 ]; then
        MSYSTEM_PREFIX='/mingw64'
        MSYSTEM_CARCH='x86_64'
        MSYSTEM_CHOST='x86_64-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
elif [ ${MSYSTEM} == CLANG32 ]; then
        MSYSTEM_PREFIX='/clang32'
        MSYSTEM_CARCH='i686'
        MSYSTEM_CHOST='i686-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-clang-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
elif [ ${MSYSTEM} == CLANG64 ]; then
        MSYSTEM_PREFIX='/clang64'
        MSYSTEM_CARCH='x86_64'
        MSYSTEM_CHOST='x86_64-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-clang-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
elif [ ${MSYSTEM} == CLANGARM64 ]; then
        MSYSTEM_PREFIX='/clangarm64'
        MSYSTEM_CARCH='aarch64'
        MSYSTEM_CHOST='aarch64-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-clang-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
elif [ ${MSYSTEM} == UCRT64 ]; then
        MSYSTEM_PREFIX='/ucrt64'
        MSYSTEM_CARCH='x86_64'
        MSYSTEM_CHOST='x86_64-w64-mingw32'
        MINGW_CHOST="${MSYSTEM_CHOST}"
        MINGW_PREFIX="${MSYSTEM_PREFIX}"
        MINGW_PACKAGE_PREFIX="mingw-w64-ucrt-${MSYSTEM_CARCH}"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST MINGW_CHOST MINGW_PREFIX MINGW_PACKAGE_PREFIX
else
        MSYSTEM_PREFIX='/usr'
        MSYSTEM_CARCH="$(/usr/bin/uname -m)"
        MSYSTEM_CHOST="${MSYSTEM_CARCH}-pc-msys"
        export MSYSTEM_PREFIX MSYSTEM_CARCH MSYSTEM_CHOST
fi
```

**Comment by jeremyd2019** [comment]
> cmd `set MSYSTEM=MINGW64 && "C:\msys64\usr\bin\bash.exe" -l ` not set `/mingw64/bin` in `PATH` var first.

I think it's weirdness with how cmd handles whitespace (cmd has lots of backwards-compatible idiosyncrasies), try
`set MSYSTEM=MINGW64&& "C:\msys64\usr\bin\bash.exe" -l `

Don't know why that would matter to VSCode though.

**Comment by jeremyd2019** [comment]
> I found that it was caused by a case statement matching failure in the `etc/msystem` script. It should be a bug in the case statement. Replace it with an if statement to determine if it will work properly.
> 
> ```
> if [ ${MSYSTEM} == MINGW32 ]; then
> ```

You didn't quote `${MSYSTEM}` so bash is eating the trailing whitespace in this comparison, making it work when MSYSTEM is `MINGW64 ` (with trailing space)

**Comment by WittonBell** [comment]
OK, thank you!
