### ISSUE TITLE
[make] Is using the POSIX jobserver protocol

### ISSUE THREAD

**Issue by Alextopher** [msys2/MSYS2-packages#3877]
### Description / Steps to reproduce the issue

Run this `makefile` with `-j4`

```
all:
    +env | grep MAKEFLAGS
```

### Expected behavior

According to https://www.gnu.org/software/make/manual/html_node/Windows-Jobserver.html we expect `MAKEFLAGS` contain `--jobserver-auth=<named semaphore>` which should be accepted by `OpenSemephore`. 

### Actual behavior

```
$ make
env | grep MAKEFLAGS
MAKEFLAGS= -j4 --jobserver-auth=3,4
```

This is consistent with https://www.gnu.org/software/make/manual/html_node/POSIX-Jobserver.html the POSIX protocol.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

Maybe

**Comment by MehdiChinoune** [comment]
I think you know that MSYS2/CygWin is a POSIX platform.
The Windows-Jobserver you cited should apply to make on mingw (make-mingw32).

**Comment by Alextopher** [comment]
Sorry for the confusion I'm not that familiar with msys2.

The project I'm working on depends on which flavor of the make jobserver protocol will be received. I mistakenly thought `#ifdef __WIN32` would be enough, msys2-make is the edge case where that doesn't work.
