### ISSUE TITLE
gcc crtbegin.o

### ISSUE THREAD

**Issue by takulark** [msys2/MSYS2-packages#3926]
### Description / Steps to reproduce the issue

crtbegin.o to dll
__gcc_register_frame
__gcc_deregister_frame
EXPORTS.
Empty function, but should not be called from outside.
DWARF2_UNWIND_INFO
I don't think you need anything other than gcc with is valid.

### Expected behavior

-

### Actual behavior

-

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
Please explain the issue. It does not make any sense.

**Comment by takulark** [comment]
hacking a empty function easy as .

**Comment by Biswa96** [comment]
Happy hacking 🤗
