### ISSUE TITLE
[Bash bug] Building BaCon on MSYS2

### ISSUE THREAD

**Issue by iahung2** [msys2/MSYS2-packages#3962]
The problem was found by @sskras: https://github.com/msys2/MSYS2-packages/discussions/3960#discussioncomment-6729677

**Comment by sskras** [comment]
The issue probably should be moved to [msys2/msys2-runtime](https://github.com/msys2/msys2-runtime) repository.

**Comment by iahung2** [comment]
> The issue probably should be moved to [msys2/msys2-runtime](https://github.com/msys2/msys2-runtime) repository.

Please help me create the issue. As you can see, I'm not a shell expert and frankly speaking I know very little about shell scripting and completely nothing about the internals of MSYS2. I struggled to write the correct title and content for this issue (and still failed to do so). I don't know what to write at all!

**Comment by iahung2** [comment]
> The issue probably should be moved to [msys2/msys2-runtime](https://github.com/msys2/msys2-runtime) repository.

Done: https://github.com/msys2/msys2-runtime/issues/167

**Comment by sskras** [comment]
Actually admins of the repositories have the ability to move the issue without creating a new one, IIRC. :)

I documented my observations under the newest issue.

**Comment by sskras** [comment]
PS. After thinking more about this... the investigation might prove that the problem is in Bash. Such case would mean that this was the correct repository.

Sorry if for the confusion (if any).  Let's wait and see.

**Comment by iahung2** [comment]
@sskras BaCon also supports `zsh`:

https://www.basic-converter.org/#faq

Confirmed that everything is fine with `zsh` and `zsh` could be installed using `pacman`.

**Comment by iahung2** [comment]
`ksh93` should also work but MSYS2 doesn't have any packages for it.
