### ISSUE TITLE
LESS behavior changed in Git for Windows between v2.40 and 2.41

### ISSUE THREAD

**Issue by rcdailey** [msys2/MSYS2-packages#3978]
### Description / Steps to reproduce the issue

In Git for Windows v2.40.1, when I do `git log` (which uses `less`), my console clears when I quit and then the terminal prompt returns where it left off prior to that. I use these settings in my `.bashrc`:

```bash
export LESS="-RSic~ -x2"
export LESSHISTSIZE=0
export LESSCHARSET=UTF-8
```

Based on [my research](https://github.com/msys2/MSYS2-packages/commits/master/less), it looks like less build 633 was introduced along with Git for Windows v2.41, just based on the dates. I don't know for sure, as I don't see this specific packages mentioned in the GfW release notes.

Lastly I'll say that I'm not sure if this is the right place to report this. I considered opening the issue on the [less repo itself](https://github.com/gwsw/less/issues), but thought starting here might be better since I'm using Windows.

## Behavior in v2.40.1

I type in `git log` and I get a full screen log using `less`, as expected:
![image](https://github.com/mintty/mintty/assets/1768054/2d7c3eb9-63c5-4502-8aef-3415d758201f)

After that, I hit `q` to exit and my terminal prompt appears just below the last `git log` which I expect:
![image](https://github.com/mintty/mintty/assets/1768054/5b99e843-31f3-4edf-81be-54e655ede9a6)

## Behavior in v2.41.0

The `git log` screen appears as it does in the previous section, so I won't repeat that screenshot here. However, the way it looks when I do `q` to exit is much different:
![image](https://github.com/mintty/mintty/assets/1768054/df80233d-6ebf-4f5f-9697-068a32b54fdf)

Notice how the previous command history is missing. I also sometimes see the prompt appear towards the bottom of the terminal, with a huge gap of whitespace.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

**Comment by lazka** [comment]
I can't reproduce with msys git 2.42.0, but I can reproduce with g4w 2.42.0 (and I downgraded less there, but that didn't change anything). I'd suggest to open an issue here https://github.com/git-for-windows/git/issues

**Comment by rcdailey** [comment]
I very much appreciate you taking the time to test this for me and isolate the issue. Unfortunately, for reasons I won't get into, I'm not able to report issues on the gfw project. Hopefully someone else will run up against this and be able to report it in my stead.

I will go ahead and close this issue, since the problem isn't here. Thanks once again!
