### ISSUE TITLE
Missing something in PATH?

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#3979]
### Description / Steps to reproduce the issue

In MSYS2 (MinTTY):

```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

in CMD (not admin):

```
C:\Users\utente>echo %path%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\utente\AppData\Local\Microsoft\WindowsApps
```

where `C:\WINDOWS\System32\OpenSSH` belongs to Windows system `PATH` while `C:\Users\utente\AppData\Local\Microsoft\WindowsApps` belongs to the user account (`utente`) `PATH`.

There seems to be a few pieces missing in MSYS2. There is some special reason for this?

 In the past I seem to remember that MSYS2 completely inherited the Windows `PATH`.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
See https://www.msys2.org/wiki/MSYS2-introduction/#path

> For optimal usage, MSYS2 automatically strips your `PATH` environment variable, essentially only leaving `C:\Windows\System32` and few others. This behavior can be controlled by setting the variable `MSYS2_PATH_TYPE`...

**Comment by angelog0** [comment]
> controlled by setting the variable MSYS2_PATH_TYPE

but HOW? It is not explained how `MSYS2_PATH_TYPE` is to be used...

**Comment by angelog0** [comment]
May be some example could be useful

**Comment by Biswa96** [comment]
See the /etc/profile file for more information about `MSYS2_PATH_TYPE` variable.
