### ISSUE TITLE
rsync does not support compression

### ISSUE THREAD

**Issue by mkuzmin** [msys2/MSYS2-packages#398]
Calling rsync with `-z` option, I get an error:

```
> rsync -z host:/file .
This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.
```

Here are discussions on ArchLinux forums:
https://bugs.archlinux.org/task/41024
https://bbs.archlinux.org/viewtopic.php?id=183921

The issue is probably caused by `--without-included-zlib` build option.

**Comment by lazka** [comment]
This was fixed in #845 afaics
