### ISSUE TITLE
Installing Ruby in windows 10 Enterprise

### ISSUE THREAD

**Issue by MarkusAnthony** [msys2/MSYS2-packages#3995]
### Description / Steps to reproduce the issue

1) install ruby (rubyinstaller-devkit-3.2.2-1-x64.exe)
2) after ruby is installed a child process is launched to install MSYS2 and MINGW. It is during this process that I am having issues.

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain
 
Which components shall be installed? If unsure press ENTER [1,3]
 
> sh -lc true
'C:\WINDOWS\system32\drivers\etc\hosts' -> '/etc/hosts'
'C:\WINDOWS\system32\drivers\etc\protocol' -> '/etc/protocols'
'C:\WINDOWS\system32\drivers\etc\services' -> '/etc/services'
'C:\WINDOWS\system32\drivers\etc\networks' -> '/etc/networks'
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/B6F8D2FF5B49DD668E5579C156B71AD13A7DCADD.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from msys2.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signed 5 keys.
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
==> Disabling revoked keys in keyring...
  -> Disabled 4 keys.
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   5  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   5  signed:   7  trust: 0-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:   4  signed:   2  trust: 4-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2023-09-12
gpg: error retrieving '[alexey.pawlow@gmail.com](mailto:alexey.pawlow@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: F40D263ECA25678A
gpg: error retrieving '[david.macek.0@gmail.com](mailto:david.macek.0@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 790AE56A1D3CFDDC
gpg: error retrieving '[martellmalone@gmail.com](mailto:martellmalone@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: DA7EF2ABAEEA755C
gpg: error retrieving '[reiter.christoph@gmail.com](mailto:reiter.christoph@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 755B8182ACD22879
gpg: error retrieving '[icquinteiro@gmail.com](mailto:icquinteiro@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 9F418C233E652008
gpg: error retrieving '[mingw.android@gmail.com](mailto:mingw.android@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: BBE514E53E0D0813
gpg: error retrieving '[alexpux@gmail.com](mailto:alexpux@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 5F92EFC1A47D45A1
gpg: error retrieving '[david.macek.0@gmail.com](mailto:david.macek.0@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 974C8BE49078F532
gpg: error retrieving '[reiter.christoph@gmail.com](mailto:reiter.christoph@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866406965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=obJZyvoo0BDB7vblpO%2BNnxjNdUOsx%2FXh4huZv5cwmMU%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: FA11531AA0AA7F57
gpg: error retrieving '[me@martellmalone.com](mailto:me@martellmalone.com)' via WKD: No name
gpg: error reading key: No name
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866406965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=obJZyvoo0BDB7vblpO%2BNnxjNdUOsx%2FXh4huZv5cwmMU%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 794DCF97F93FC717
gpg: error retrieving '[martellmalone@gmail.com](mailto:martellmalone@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866406965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=obJZyvoo0BDB7vblpO%2BNnxjNdUOsx%2FXh4huZv5cwmMU%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: D595C9AB2C51581E
gpg: error retrieving '[mingw.android@gmail.com](mailto:mingw.android@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866406965%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=obJZyvoo0BDB7vblpO%2BNnxjNdUOsx%2FXh4huZv5cwmMU%3D&reserved=0)
gpg: keyserver refresh failed: General error
==> ERROR: Could not update key: 4DF3B7664CA56930
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch sed texinfo texinfo-tex wget mingw-w64-ucrt-x86_64-binutils mingw-w64-ucrt-x86_64-crt-git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gcc-libs mingw-w64-ucrt-x86_64-headers-git mingw-w64-ucrt-x86_64-libmangle-git mingw-w64-ucrt-x86_64-libwinpthread-git mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-tools-git mingw-w64-ucrt-x86_64-winpthreads-git pkgconf mingw-w64-ucrt-x86_64-pkgconf
warning: autoconf-wrapper-20221207-1 is up to date -- skipping
warning: autogen-5.18.16-4 is up to date -- skipping
warning: automake-wrapper-20221207-1 is up to date -- skipping
warning: diffutils-3.9-1 is up to date -- skipping
warning: file-5.44-5 is up to date -- skipping
warning: gawk-5.2.1-2 is up to date -- skipping
warning: grep-1~3.0-6 is up to date -- skipping
warning: libtool-2.4.7-3 is up to date -- skipping
warning: m4-1.4.19-2 is up to date -- skipping
warning: make-4.4.1-1 is up to date -- skipping
warning: patch-2.7.6-2 is up to date -- skipping
warning: sed-4.9-1 is up to date -- skipping
warning: texinfo-7.0.3-1 is up to date -- skipping
warning: texinfo-tex-7.0.3-1 is up to date -- skipping
warning: wget-1.21.3-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-binutils-2.40-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-crt-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-libs-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-headers-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libmangle-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libwinpthread-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-make-4.4-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-tools-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-winpthreads-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: pkgconf-1.9.4-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-pkgconf-1~1.8.0-2 is up to date -- skipping
there is nothing to do
Install MSYS2 and MINGW development toolchain succeeded

My next step would be to gem install nokogiri but I get:

C:\Ruby32-x64\ridk_use>gem install nokogiri
ERROR:  SSL verification error at depth 3: self-signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/CN=Avista-Corp-RootCA)
ERROR:  SSL verification error at depth 3: self-signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/CN=Avista-Corp-RootCA)
ERROR:  SSL verification error at depth 3: self-signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/CN=Avista-Corp-RootCA)
ERROR:  Could not find a valid gem 'nokogiri' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 peeraddr=151.101.193.227:443 state=error: certificate verify failed (self-signed certificate in certificate chain) (https://rubygems.org/specs.4.8.gz)
...

Are these detrimental errors or is there something else getting in my way?

### Expected behavior

Install correctly

### Actual behavior

Errors:

gpg: next trustdb check due at 2023-09-12
gpg: error retrieving '[alexey.pawlow@gmail.com](mailto:alexey.pawlow@gmail.com)' via WKD: General error
gpg: error reading key: General error
gpg: refreshing 1 key from hkps://[keyserver.ubuntu.com](https://nam04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fkeyserver.ubuntu.com%2F&data=05%7C01%7CMarkus.Rissmann%40avistacorp.com%7Ced782d21501444ed9fc808dba8c0a1aa%7C64c8d5efb6f743d8b84b8d044edc901d%7C0%7C0%7C638289320866250766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sF4amsT6QC5bmekqUj6RPzeuE5lxtbys404NZaw5%2Bpk%3D&reserved=0)
gpg: keyserver refresh failed: General error
...

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Enterprise 21H2

**Comment by MehdiChinoune** [comment]
Please report your issue to https://github.com/oneclick/rubyinstaller2 to make them rebase (If they didn't their installer on the latest MSYS2 installer.

**Comment by Biswa96** [comment]
rubyinstaller-devkit-3.2.2-1-x64.exe is not provided by msys2 project. The issue should be reported to the project which provides that installer.

For testing purpose, you can try the latest official msys2 installer from here https://www.msys2.org/
