### ISSUE TITLE
Git v2.42.0.windows.2 raises an error `LoadLibraryExW() failed with: Specified procedure not found`

### ISSUE THREAD

**Issue by KSR-Yasuda** [msys2/MSYS2-packages#4003]
### Description / Steps to reproduce the issue

Git v2.42.0.windows.2 fails on `remote update`.

It looks missing some library function.
What do I need?

```bash
# Git v2.42.0.2 Failure
% git version
git version 2.42.0.windows.2

% git remote update 2>&1 | nkf -w
Fetching origin
error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?
                                    # Saying "Specified procedure not found."

Fetching mine
error: LoadLibraryExW() failed with: 指定されたプロシージャが見つかりません。?

# The target repositories are accessed via HTTPS
# (https://github.com/simeji/winresizer.git).


# Downgrade Git to v2.42.0.1
% pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-git-2.42.0.1.a2e49ec355-1-any.pkg.tar.xz
loading packages...
warning: downgrading package mingw-w64-x86_64-git (2.42.0.2.2f819d1670-1 => 2.42.0.1.a2e49ec355-1)
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-git-2.42.0.1.a2e49ec355-1

Total Installed Size:  49.66 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                          [------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                        [------------------------------------------------------------] 100%
(1/1) loading package files                                                                             [------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                       [------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                     [------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) downgrading mingw-w64-x86_64-git                                                                  [------------------------------------------------------------] 100%

% git --version
git version 2.42.0.windows.1
yasuda@Kujira3 MINGW64 ~/.vim/bundle/winresizer (develop)

% git remote update
Fetching origin
Fetching mine
    # v2.42.0.windows.1 works fine.


# Pacman Status
% pacman -Qu
groff 1.22.4-4 -> 1.23.0-1 [ignored]
mingw-w64-x86_64-git 2.42.0.1.a2e49ec355-1 -> 2.42.0.2.2f819d1670-1
```

### Expected behavior

`git remote update` works successfully.

### Actual behavior

Fails with the error of `error: LoadLibraryExW()` above.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Microsoft Windows 10 Pro 22H2 [Version 10.0.19045.3324]

**Comment by KSR-Yasuda** [comment]
This is `strace` log of `git remote update`: [git.log.gz](https://github.com/msys2/MSYS2-packages/files/12491795/git.log.gz)

But it has freezed. It's until it has worked.

**Comment by KSR-Yasuda** [comment]
Also, I keep the libs below extracting by hand (setting in `${LD_LIBRARY_PATH}`),
to keep modules that need old libs work.

* `/usr/local/bin/msys-crypto-1.1.dll`
* `/usr/local/bin/msys-ssl-1.1.dll`
    - of `libopenssl-1.1.1.u-1-x86_64.pkg.tar.xz`

By pacman, `libopenssl` libraries are overwritten by v3 package:

* `/usr/bin/msys-crypto-3.dll`
* `/usr/bin/msys-ssl-3.dll`
    * of `git-for-windows/libopenssl 3.1.2-1`

**Comment by KSR-Yasuda** [comment]
> Also, I keep the libs below extracting by hand (setting in `${LD_LIBRARY_PATH}`), to keep modules that need old libs work.
> 
> * `/usr/local/bin/msys-crypto-1.1.dll`
> * `/usr/local/bin/msys-ssl-1.1.dll`
>   
>   * of `libopenssl-1.1.1.u-1-x86_64.pkg.tar.xz`

v2.42.0.windows.1 still works without these libs.
These are not related with.

**Comment by KSR-Yasuda** [comment]
Full `strace git remote update` log: [git_20230901_103134.log.gz](https://github.com/msys2/MSYS2-packages/files/12492041/git_20230901_103134.log.gz)

**Comment by KSR-Yasuda** [comment]
Posted an issue to `git-for-windows` repo.

**Comment by Biswa96** [comment]
This is not msys2 issue. You are using git-for-windows. Anyway, does `git remote update` command work? Are you sure that the error is not coming from `nkf` program?

**Comment by KSR-Yasuda** [comment]
Okay, I'll discuss this issue in https://github.com/git-for-windows/git/issues/4582.

> Are you sure that the error is not coming from nkf program?

It is not.
The command `nkf` is "Network Kanji Filter", Japanese character encode converter.
Without `nkf`, the error log `error: LoadLibraryExW()` was output in Shift_JIS.
Git bash console being UTF-8, output was garbled.
