### ISSUE TITLE
Add Libstemmer package to Msys2

### ISSUE THREAD

**Issue by Zacharymk1213** [msys2/MSYS2-packages#4011]
### Description / Steps to reproduce the issue

Libstemmer is needed to build libadwaita. This is needed for Gnome Text Editor

https://archlinux.org/packages/extra/x86_64/libstemmer/

### Expected behavior

Libstemmer would be in the repository.

### Actual behavior

Libstemmer isn't in the repository.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

**Comment by MehdiChinoune** [comment]
As explained in the PR, such packages are not allowed to be added to MSYS packages.
