### ISSUE TITLE
LLVM Not Compiling!

### ISSUE THREAD

**Issue by MrGeniusProgrammer** [msys2/MSYS2-packages#4040]
### Description / Steps to reproduce the issue

I am trying to compile cpp file that has llvm api headers. With the command `clang++ main.cpp`. As I downloaded the pacakage by `pacman -S llvm`.

main.cpp:
```
#include "stdlib.h"
#include <map>
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Verifier.h"

int main(int argc, char *argv[])
{
  std::unique_ptr<llvm::LLVMContext> TheContext;
  std::unique_ptr<llvm::Module> TheModule;
  std::unique_ptr<llvm::IRBuilder<>> Builder;
  std::map<std::string, llvm::Value *> NamedValues;

  return EXIT_SUCCESS;
}
```

### Expected behavior

I expected to compile.

### Actual behavior

But it was giving me errors like this:
```
undefined reference to `llvm::LLVMContext::~LLVMContext()'
undefined reference to `llvm::Module::~Module()'
undefined reference to `llvm::IRBuilderDefaultInserter::~IRBuilderDefaultInserter()'
undefined reference to `llvm::IRBuilderFolder::~IRBuilderFolder()'
undefined reference to `llvm::SmallVectorBase<unsigned int>::size() const'
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

No

**Comment by lazka** [comment]
The cygwin llvm was only added for bootstrapping and is out of date.

You should use the native mingw packages instead: https://packages.msys2.org/base/mingw-w64-clang

**Comment by MrGeniusProgrammer** [comment]
Thanks for messaging. You have to run it in bash terminal.
