### ISSUE TITLE
Cannot create symlinks in Win 11?

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#4056]
I have 
```
$ echo $MSYS
winsymlinks:nativestrict
```

but

```
$ touch foo
$ ln -sf foo bar
ln: failed to create symbolic link 'bar': Operation not permitted
```

the same if I run

```
$ touch a
$ MSYS=winsymlinks:nativestrict ln -s a b
ln: failed to create symbolic link 'b': Operation not permitted
```

the above works on Win 10

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22000

**Comment by Biswa96** [comment]
Did you check if development mode is enabled in settings? See https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging

**Comment by sskras** [comment]
The command line way to check this:
```sh
$ sudo secedit //export //cfg secpol.cfg

The task has completed successfully.
See log %windir%\security\logs\scesrv.log for detail info.

$ iconv -f UTF-16 secpol.cfg | awk '/^.Privilege Rights/ { GO=1; print; next } GO && /^\[/ { exit 5 } GO' | grep --color -e ^ -e SeCreateSymbolicLinkPrivilege
  ...
```

![image](https://github.com/msys2/MSYS2-packages/assets/7887758/58e05fe0-d661-4992-b504-8ee292b70d19)

**Comment by angelog0** [comment]
> Did you check if development mode is enabled in settings? See https://learn.microsoft.com/en-us/windows/apps/get-started/developer-mode-features-and-debugging

Ah, I forgot that.. it is a new PC.. thanks.. I close this..
