### ISSUE TITLE
Fortran is lost?

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#4057]
### Description / Steps to reproduce the issue

The last update has removed the Fortran language in MSYS2. I use it both on MSYS2 and MINGW64. Without Fortran in MSYS2 there are no reasons to continue use MSYS2 it self.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by MehdiChinoune** [comment]
I think It'already documented that MSYS environment is to provide tools required to build MinGW-w64 packages.
gcc-fortran is not needed for any MinGW-w64 package.

**Comment by angelog0** [comment]
Then you have to remove almost half packages (emacs, mutt, asciidoc, ...), if not more. But, at this point, why an user should use MSYS2/MinGW and not the old [Msys/MinGW](http://mingw.osdn.io/index.html) which still support Fortran? Just because it is (not verifyed, sorry) 32 bit?

**Comment by MehdiChinoune** [comment]
Feel free to use outdated packages.
MSYS2 has some differences with MSYS see https://www.msys2.org/wiki/History

**Comment by lazka** [comment]
@angelog0 just wondering, what were you using msys fortran for?

**Comment by sskras** [comment]
To second the @lazka's question:

@angelog0: hey, you still have `mingw64/mingw-w64-x86_64-gcc-fortran`! Does it have issues in MSYS2 environment?

**Comment by angelog0** [comment]
I have always found useful to work with both, MSYS2 and MINGW64, to compare results, find bugs, test command line options etc. 

You cannot justify its removal saying that MSYS2 is only to have a POSIX environment to build MINGW apps: there are many MSYS2 apps which are unrelated with this. Why removing Fortran? Usually when one builds GCC the build is done for the three basic languages. If I remember correctly by default the build of GCC produces C. C++ and Fortran. Anyway it is some time I do not build GCC and maybe things changed..

**Comment by sskras** [comment]
@angelog0, while I understand your frustration, the project developers are seemingly free to do whatever they want or have decided.

I think folks like you and me have two practical choices:

1. To create and **maintain their own repo** containing **MSYS2-based builds** of arbitrary software (e. Alpine email program in my case).
2. To **switch to different runtime** that also provides *nix-like environment for Windows, but makes **no artificial restrictions** on a set of POSIX-based software to be built here.
   
   I know of other two such runtimes:
   2a. Cygwin
   2b. [Midipix](https://midipix.org/)

I am sure you have heard of the first (2a). But I would like to [stress the Midipix](https://www.luciaillanes.de/en/projects#:~:text=Midipix%5B1%5D,for%20Windows&text=execution%20of,POSIX/Linux&text=instead,Windows%20NT%20executive) project (2b):

> **Midipix[[1]](http://www.midipix.org/) is a POSIX/Linux-compatible environment for Windows** XP/Server 2003 or later, facilitating cross-compilation and **execution of applications written for POSIX/Linux** without suffering substantial performance loss.
> 
> Unlike Cygwin[[2]](https://www.cygwin.com/), Midipix does not require interaction with the Windows environment subsystem in order to implement its system calls.
> 
> Unlike Interix[[3]](https://technet.microsoft.com/en-us/library/bb463204.aspx), Midipix is not an environment subsystem itself and does not introduce its own subsystem server and client DLL(s).
> 
> Neither virtualisation nor kernel-mode drivers are required in order to use Midipix: **instead, a small set of “runtime components” mediate communication between Musl, the libc chosen for this project, and the Windows NT executive** (NTOSKRNL.EXE.)

Current state of Midipix is that it:

- is still pre-alpha, albeit the software that builds, usually runs just perfectly;
- can be be built only from Linux at the moment;
- has no installer – it produces a `.zip` file that needs to be extracted into the new dir;
- uses quite old port of MinTTY (v2.8.1) which feels a lot faster than MSYS2-based one;
- bundles quite old GCC version 4.6.4;
- misses a bunch of syscalls yet;
- misses a lot of things in `/proc`;
- is driven by like 2 developers at the moment;
- was promised to have its' first release this year (although I estimate that to happen in 2024);
- has main communication happening on IRC channel #midipix on Libera.Chat.

I am currently testing the **2022.11.18**.20.22.52 build and it feels quite impressive to me:

![image](https://github.com/msys2/MSYS2-packages/assets/7887758/024f454e-d608-4295-af3c-dbc5d1dce403)

Subjectively it's like 3-6 times faster than Cygwin.

**Comment by angelog0** [comment]
> I am sure you have heard about Cygwin already.

I used Cygwin for almost ten years and switched to MSYS2 because [...]

I have also heard about Midipix...

**Comment by angelog0** [comment]
You do not respond why you have removed one of the three main pillars of GCC and not other apps that have nothing to do with the build of MINGW applications.

You cannot dismiss this discussion by saying that developers are free to remove software that they no longer deem necessary: it is an insult to those who have followed this project for nearly a decade!

**Comment by angelog0** [comment]
I close this. Do what you think

**Comment by MehdiChinoune** [comment]
> You do not respond why you have removed one of the three main pillars of GCC and not other apps that have nothing to do with the build of MINGW applications.

We are discussing this topic on discord. What criteria for MSYS2 packages, but what is sure is that gcc-fortran is not one them as It's already available as MinGW package.

**Comment by Kreijstal** [comment]
I think I got hit by this, as in, there is a python package that requires numpy + POSIX, you need fortran to get numpy, so this makes it impossible to build this package on msys enviroment, I guess cygwin would be the option, but :(

**Comment by Biswa96** [comment]
> there is a python package that requires numpy + POSIX, you need fortran to get numpy

Could you provide the link?
