### ISSUE TITLE
problem rebuilding MSYS perl package(s)

### ISSUE THREAD

**Issue by d-hoke** [msys2/MSYS2-packages#4065]
### Description / Steps to reproduce the issue

Attempting to rebuild of package perl-Algorithm-Diff (and other perl packages) fails, getting hung reporting problem with reopening shared memory in dofork, example output follows
...
[snip]
Checking if your kit is complete...
Looks good
      0 [main] perl 950 C:\msys64_B\usr\bin\perl.exe: *** fatal error in forked process - Can't reopen shared memory during fork, Win32 error 6
      0 [main] perl 948 dofork: child 950 - died waiting for dll loading, errno 11
Can't fork, trying again in 5 seconds at /usr/share/perl5/core_perl/ExtUtils/MM_Any.pm line 223.
      0 [main] perl 951 C:\msys64_B\usr\bin\perl.exe: *** fatal error in forked process - Can't reopen shared memory during fork, Win32 error 6
5070430 [main] perl 948 dofork: child 951 - died waiting for dll loading, errno 11
Can't fork, trying again in 5 seconds at /usr/share/perl5/core_perl/ExtUtils/MM_Any.pm line 223....
...

Steps to reproduce
installed msys2 from msys2-x86_64-20230718.exe
updated via pacman -Syuu and pacman -Syu (two commands seem to behave slightly differently?)
from a command prompt (in my case in msys64_B) opened MSYS shell via msys2_shell.cmd
...
cd /c/msys64_b
mkdir msys2
cd msys2
[respond to any prompts installing packages as needed]
pacman -S base-devel
pacman -S git
 git clone https://github.com/msys2/MSYS2-packages
cd MSYS2-packages
cd perl-Algorithm-diff
makepkg -sLf --needed --noconfirm
[expect errors similar to that indicated above to soon appear]
...

While perl-Algorithm-Diff was presented here, similar error seems to occur with various other perl-* packages.

The 'perl' package itself built for me without any errors.

----------------------
Additional notes
The machine being used has 32GB of memory, at no time in any attempt was more than 16GB in use.
The machine being used has i7-6820HQ cpu @ 2.70GHz
This was encountered attempting to do a local rebuild of all MSYS packages, during which some other 'transient' errors were encountered along the way, current driving command which seemed to avoid the transient errors ('pacman in use') was
`
for f in *; do if ! [[ -d $f ]] ; then continue; else echo $f; (echo "Processing $f";cd $f; ls; makepkg -sLf --needed --noconfirm; ls; echo "Finished processing $f"; sleep 5) ; fi ; done 2>&1 | tee dlh.bld.msys2.packages.txt
`

### Expected behavior

The attempted build should complete without errors.

### Actual behavior

The build process hangs indefinitely cycling repeatedly reporting the error.
[repeating similar to above]

`
[snip]
==> Extracting sources...
  -> Extracting Algorithm-Diff-1.201.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Checking if your kit is complete...
Looks good
      0 [main] perl 1706 C:\msys64_B\usr\bin\perl.exe: *** fatal error in forked process - Can't reopen shared memory during fork, Win32 error 6
      0 [main] perl 1704 dofork: child 1706 - died waiting for dll loading, errno 11
Can't fork, trying again in 5 seconds at /usr/share/perl5/core_perl/ExtUtils/MM_Any.pm line 223.

==> ERROR: Aborted by user! Exiting...
`

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

(if I had one, yes, don't know if I will pursue beyond reporting this.)

**Comment by stahta01** [comment]
`makepkg -sLf --needed --noconfirm`

Try not using the "L" (Log) option; it fixed this issue on one package that had the problem.

Tim S.
