### ISSUE TITLE
Call _beginthread(...) in C:\Program Files\Go\src\runtime\cgo

### ISSUE THREAD

**Issue by TimurIskandarov** [msys2/MSYS2-packages#4081]
The sqlite3 driver is not built https://github.com/mattn/go-sqlite3/issues/855

```
$ CGO_ENABLED=1 go install github.com/mattn/go-sqlite3
# runtime/cgo
gcc_libinit_windows.c: In function ‘_cgo_beginthread’:
gcc_libinit_windows.c:136:27: error: implicit declaration of function ‘_beginthread’; did you mean ‘_cgo_beginthread’? [-Werror=implicit-function-declaration]
  136 |                 thandle = _beginthread(func, 0, arg);
      |                           ^~~~~~~~~~~~
      |                           _cgo_beginthread
cc1: all warnings being treated as errors
```
It is called in the following files:
- `C:\Program Files\Go\src\runtime\cgo\gcc_libinit_windows.c\libcgo_windows.h`
- `C:\Program Files\Go\src\runtime\cgo\gcc_libinit_windows.c`

`gcc` (pacman -S gcc) searches for header files in directories:
```
 /usr/lib/gcc/x86_64-pc-msys/11.3.0/include
 /usr/lib/gcc/x86_64-pc-msys/11.3.0/include-fixed
 /usr/include
 /usr/lib/gcc/x86_64-pc-msys/11.3.0/../../../../lib/../include/w32api
```
`process.h` in `/usr/include`
`windows.h` -> `/usr/include`

This problem is not only related to the sqlite3 driver, it was also mentioned here https://github.com/golang/go/issues/59490#issuecomment-1569449033 and here https://stackoverflow.com/questions/75067559/how-to-fix-cgo-error-caused-by-race-flag

How can this be fixed? Maybe you need to somehow correct the names of the header files?

**Comment by Biswa96** [comment]
"C:\Program Files\Go" is not provided by MSYS2.

> gcc (pacman -S gcc) searches for header files in directories:

Use the mingw gcc.

**Comment by TimurIskandarov** [comment]
@Biswa96 mingw-w64-go build sqlite driver?

**Comment by Biswa96** [comment]
Please explain your question. I did not understand that.

**Comment by TimurIskandarov** [comment]
will mingw-w64-go build?

**Comment by Biswa96** [comment]
Feel free to try it.

**Comment by TimurIskandarov** [comment]
Got it, I'll try it and report back

**Comment by TimurIskandarov** [comment]
@Biswa96 `pacman -s mingw-w64-x86_64-gcc` works fine. I don't know why I didn't work out `pacman -S gcc`. Possibly due to `MSYSTEM` in `settings.json` VSCode.

**Comment by SongZihuan** [comment]
> [@Biswa96](https://github.com/Biswa96) `pacman -s mingw-w64-x86_64-gcc` works fine. I don't know why I didn't work out `pacman -S gcc`. Possibly due to `MSYSTEM` in `settings.json` VSCode. `pacman -s mingw-w64-x86_64-gcc` 正常工作。我不知道为什么我没有锻炼`pacman -S gcc` 。可能是由于`settings.json`中的`MSYSTEM` VSCODE。
> 
> ```
>     "terminal.integrated.profiles.windows": {
>         // Add profile MSYS2
>         "MSYS2": {
>             "path": "C:\\msys64\\usr\\bin\\bash.exe",
>             "args": ["--login", "-i"],
>             "env": {
>                 "MSYSTEM": "MINGW64",
>                 "CHERE_INVOKING": "1",
>                 "MSYS2_PATH_TYPE": "inherit"
>             },
>             "overrideName": true
>         },
>         "PowerShell": null,
>         "Git Bash": null,
>     },
>     "terminal.integrated.defaultProfile.windows": "MSYS2",
> ```

Thank you, you are right. The above problem will occur when compiling gcc under Msys2 system, but there will be no problem if Mingw64 (or Mingw64 subsystem of Msys2) is used.
