### ISSUE TITLE
cygrunsrv depends on python2 but does not use it

### ISSUE THREAD

**Issue by samhocevar** [msys2/MSYS2-packages#410]
There might be historical reasons for this, but today `cygrunsrv` no longer requires Python. Since I use MinGW Python instead of MSYS2’s, it would be nice if [the dependency](https://github.com/Alexpux/MSYS2-packages/blob/master/cygrunsrv/PKGBUILD) could be dropped. Thanks!

**Comment by jcrben** [comment]
@lazka this can be closed
