### ISSUE TITLE
[subversion] subversion package for msys2 have libcrypt missing dependency

### ISSUE THREAD

**Issue by alesandro87** [msys2/MSYS2-packages#4110]
### Description / Steps to reproduce the issue

subversion package for msys2 have libcrypt missing dependency

1. install subversion pacman -S subversion
2. start svn 

install  libcrypt-2.1-5 package solve the issue 

### Expected behavior

$ svn
Type 'svn help' for usage.

### Actual behavior

$ svn
C:/msys64/usr/bin/svn.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

**Comment by lazka** [comment]
svn depends on [libxcrypt](https://packages.msys2.org/base/libxcrypt) for some time now. Make sure your installation is updated: https://www.msys2.org/docs/updating/

**Comment by lazka** [comment]
Thanks for the report.

A `pacman -Suy` should fix the issue and libcrypt can be removed again `pacman -R libcrypt`
