### ISSUE TITLE
Please upgrade msys/clang package

### ISSUE THREAD

**Issue by iahung3** [msys2/MSYS2-packages#4182]
It has been stuck at version 11.0.0-5 for too long. Yes, I know that on Cygwin, the llvm and clang packages have even become unmaintained. But we maintain our own version without depending on Cygwin, isn't it? The Cygwin version is stuck at 8.0.1, but we have 11.0.0–5.

**Comment by lazka** [comment]
Afair this was only used for cross compiling the mingw clang, and isn't really useful beside of that, since llvm doesn't support cygwin.

**Comment by iahung3** [comment]
> llvm doesn't support cygwin.

I don't know about that. I test my code (C++11) with all clang versions provided by MSYS2, including msys/clang. I think I will simply remove msys/clang from the test. Thank you for your information.

**Comment by lazka** [comment]
yeah, that sounds like a good idea. Sorry for the package confusion it's not obvious what should work and what shouldn't here.

**Comment by lazka** [comment]
Why did you reopen?

**Comment by iahung3** [comment]
> Why did you reopen?

I don't know. Maybe I clicked the wrong button.
