### ISSUE TITLE
zlib use in binutils ?

### ISSUE THREAD

**Issue by ansoandrieu** [msys2/MSYS2-packages#4218]
from binutils' PKGBUILD file I see that zlib is listed as a dependency, so I guess the intent is to use the zlib package during the binutils build.  But I'm afraid that's not the case: the binutils contains its own copy of zlib within its sources. The `configure` needs to be invoked with the `--with-system-zlib` flag for the external zlib to be used during the build.

I see this in the current binary package:
```sh
# strings /bin/ar.exe  | grep Adler
 deflate 1.2.12 Copyright 1995-2022 Jean-loup Gailly and Mark Adler
 inflate 1.2.12 Copyright 1995-2022 Mark Adler
```

1.2.12 is the version of the embedded zlib in binutils.
The trouble is that this zlib version has some CVE attached to it and thus the binutils binaries get flagged by some security scanning tools.

**Comment by Biswa96** [comment]
Should mingw and cross binutils also have this change?

**Comment by lazka** [comment]
probably
