### ISSUE TITLE
pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain

### ISSUE THREAD

**Issue by Ascendant-7** [msys2/MSYS2-packages#4221]
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gcc-ada-13.1.0-6-any.pkg.tar.zst' from mirror.msys2.org : SSL connection timeout
error: failed retrieving file 'mingw-w64-ucrt-x86_64-gdb-13.1-4-any.pkg.tar.zst' from mirror.msys2.org : SSL connection timeout
error: failed retrieving file 'mingw-w64-ucrt-x86_64-crt-git-10.0.0.r258.g530c58e17-2-any.pkg.tar.zst' from mirror.msys2.org : SSL connection timeout
warning: too many errors from mirror.msys2.org, skipping for the remainder of this transaction
error: failed retrieving file 'dos2unix-7.5.0-1-x86_64.pkg.tar.zst' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed retrieving file 'make-4.4.1-1-x86_64.pkg.tar.zst.sig' from repo.msys2.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
warning: failed to retrieve some files
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
![Screenshot (114)](https://github.com/msys2/MSYS2-packages/assets/152673822/391f6b24-9d34-4bd2-a507-e93bcf8f24f3)

I was trying to get c++ on my visual studio code. please help.

**Comment by Biswa96** [comment]
That's network issue from your side or the mirror is slow. Please wait some time for the mirror to catch up or change the default mirror priority list in /etc/pacman.d/mirrorlist* files.

**Comment by Ascendant-7** [comment]
> change the default mirror priority list in /etc/pacman.d/mirrorlist* files.

thank you, senior. Yes, it must have been a network issue. I was hesitant to run the install command again, but it worked.

**Comment by AkhinurASomaya** [comment]
> > change the default mirror priority list in /etc/pacman.d/mirrorlist* files.
> 
> thank you, senior. Yes, it must have been a network issue. I was hesitant to run the install command again, but it worked.

what command did you use? i am facing the same error.

**Comment by Biswa96** [comment]
> what command did you use? i am facing the same error.

OP meant that he ran the same command after that error.
