### ISSUE TITLE
git push and daemon failed, show can not load ws2_32.dll

### ISSUE THREAD

**Issue by josephsmeng** [msys2/MSYS2-packages#425]
recent update import an bug for some network specified job for 64bit msys runtime,
for example, command like 

> git daemon --verbose --export-all --reuseaddr --enable=receive-pack --base-path=.

and

> git push origin AA:BB 

will cause an error, show 

> unable to load C:\Windows\system32\ws2_32.dll, Win32 error 1001

after uninstall msys2-64bit and install msys2-32bit this problem will not happend,

so there maybe some wrong about recent update for 64 bit msys2 runtime.

**Comment by Kadigan** [comment]
I am getting a similar error with pacman.exe (see https://github.com/jb-alvarado/media-autobuild_suite/issues/252 for details) like so

          0 [main] pacman 1820 E:\autobild-testing\msys64\usr\bin\pacman.exe: *** fatal error - unable to load C:\Windows\system32\ws2_32.dll, Win32 error 1001

Connected?

**Comment by josephsmeng** [comment]
https://github.com/jb-alvarado/media-autobuild_suite/issues/252#issuecomment-174015977

**Comment by Kadigan** [comment]
Yeah, I found that problem when I was attempting to use that guy's software suite. I just posted it here to possibly find the link between issues and aid in gathering cases.
