### ISSUE TITLE
pkgconf uses unix paths

### ISSUE THREAD

**Issue by ABBAPOH** [msys2/MSYS2-packages#4258]
### Description / Steps to reproduce the issue

Hello, I am the developer of the Qbs build system. We are using the pkg-config binary to extract the location of the .pc files which we later use to build stuff. We extract the location like this:
$ pkg-config --variable=pc_path pkg-config
This works on Unix systems and with choco installation, but fails with msys.

### Expected behavior

The original pkg-config binary installed e.g. from choco uses Windows file paths:
$ pkg-config --variable=pc_path pkg-config
C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\pkg-config-lite-0.28-1\lib/pkgconfig;C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\pkg-config-lite-0.28-1\share/pkgconfig

### Actual behavior

The pkgconf binary installed via pacman, however, uses Unix filepaths:
$ pkgconf.exe --variable=pc_path pkg-config
/usr/lib/pkgconfig:/usr/share/pkgconfig

I found several issues in the pkgconf repo:
https://github.com/pkgconf/pkgconf/issues/72
https://github.com/pkgconf/pkgconf/issues/234
However, it is not clear whether it should return Windows or Unix paths
For us, it would be much easier if pkgconf will return windows paths - that would remove the fuss of calling cygpath (which currently is not working properly with the Unix separator:

$ cygpath -m  $(pkgconf.exe --variable=pc_path pkg-config)
C:/Developer/msys64/usr/lib/pkgconfig/usr/share/pkgconfig

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

### Are you willing to submit a PR?

nope

**Comment by Biswa96** [comment]
Are you using mingw pkgconfig? What is the output of `type pkgconf` ?

**Comment by ABBAPOH** [comment]
I see, so there are different pkg-conf packages?
I was using [pkgconf ](https://packages.msys2.org/package/pkgconf) which uses the unix path - I assume this is used with native [gcc](https://packages.msys2.org/package/gcc)
The [mingw](https://packages.msys2.org/package/mingw-w64-x86_64-pkgconf) version uses relative paths - we can use that, thanks.
Out of curiousity (I am not familiar with msys2, last time I used was a decade ago) - are those "native" msys tools use unix paths internally and what is needed to build an app in order to do so? Simply configure e.g. cmake environment using native gcc?

**Comment by Biswa96** [comment]
I apologize for any confusion, but I'm having difficulty understanding your question. Could you please rephrase it for me?

**Comment by ABBAPOH** [comment]
No worries. Do I understand correctly that in order to build my app (e.g. qbs) as a msys app (that is able to work with unix paths), I would need to use the Cygwin runtime lib?

**Comment by Biswa96** [comment]
Did you mean Qt Build Suite? If the program supports native Windows platform, I would suggest to use mingw toolchain.
If you want to build a program for msys or cygwin environment, you have to build every dependencies there.

**Comment by ABBAPOH** [comment]
Thanks for the clarification.
I think, the issue can be closed now - I simply misused the pkgconf package.
