### ISSUE TITLE
ccache 4.8.3: segfaults

### ISSUE THREAD

**Issue by jannick0** [msys2/MSYS2-packages#4311]
The current MSYS2-package `ccache` 4.8.3 and previous versions are useless, since `ccache` segfaults or - even worse - hangs.

Simple example to produce a segfault:
```bash
#! /usr/bin/bash
echo 'int main() { return 0; }' > t.c
ccache gcc -c -o t.o t.c
``` 

In previous versions `ccache` hung for the example above. 

NB: `CCACHE` 4.8.3 package checks first segfault, then hang until eternity (`PKGBUILD`'s function `CHECK` added in #4310).

**Comment by lazka** [comment]
It has never worked for me as far as I can rememeber

**Comment by jannick0** [comment]
Why not dropping the package then?

**Comment by lazka** [comment]
It would be nice to have, so I was hoping someone would look into it at some point :)

**Comment by jannick0** [comment]
Well, not me for now. :)  But what about a warning that the package should not be used after installation shouted by `POST_INSTALL`? ... for the time being. :)

**Comment by Biswa96** [comment]
> But what about a warning that the package should not be used after installation shouted by `POST_INSTALL`?

Most of the users are probably using mingw ccache package. The _shout_ will go into void.

**Comment by jannick0** [comment]
The warning about a heavily broken package would go out to users of `MSYS2`'s `ccache` in the `MSYS2` shell - which is the natural thing to do in that shell.  Your argument advocates for removing `ccache` as proposed in the first place.

**Comment by lazka** [comment]
With #4336 we are now back to ccache just hanging endlessly, which is what happened before as far back as I remember.

**Comment by Kreijstal** [comment]
So tried to check what was going on,
Ok, so what I've discovered is that ccache tests symlinks, and Msys implements them as copying. Which confuses the test suite.
But what I discovered as well is that the test suite hangs forever as well, it gets stuck here https://github.com/ccache/ccache/blob/251f24409f80a711ca96ccd2288961cb4eb68aad/unittest/test_util_LockFile.cpp#L110
