### ISSUE TITLE
[new] perl-Module-Starter

### ISSUE THREAD

**Issue by goyalyashpal** [msys2/MSYS2-packages#4317]
* i was referring this SO answer [new-perl-module-distro] and this [perlmonk answer]
* these suggest using [`module-starter`][module-starter]
* `pacman -Ss`ing around, i found [msys2 perl-modules] containing the [perl-ExtUtils-MakeMaker], and [perl-Module-Build]
* but MakeMaker seems to be not for this purpose (there's no `exe`-cutable file to it), and Module-Build is old (per the SO answers)?

so, suggestion is to add the package [`module-starter`][module-starter]

homepage: https://github.com/xsawyerx/module-starter

[new-perl-module-distro]: https://stackoverflow.com/q/1495685/#1496099 "how-do-i-start-a-new-perl-module-distribution"
[perlmonk answer]: https://www.perlmonks.org/?node_id=806110#:~:text=Compatibility%20with-,module%2Dstarter,-and%20CPAN. ""

[module-starter]: https://metacpan.org/dist/Module-Starter/view/bin/module-starter ""
[msys2 perl-modules]: https://packages.msys2.org/groups/perl-modules "msys2 perl-modules"
[perl-ExtUtils-MakeMaker]: https://packages.msys2.org/package/perl-ExtUtils-MakeMaker "ExtUtils-MakeMaker"
[perl-Module-Build]: https://packages.msys2.org/package/perl-Module-Build "perl-Module-Build"

**Comment by Biswa96** [comment]
"the main focus of MSYS2 is to provide a build environment for native Windows software and the Cygwin-using parts are kept at a minimum" - https://www.msys2.org/

perl-Module-Starter would not be required for any other msys2 packages. Please feel free to create your own package.
