### ISSUE TITLE
Bash doesn't store new history (bash should overwrite the oldest one in .bash_history) after storing about 400 lines in .bash_history

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/MSYS2-packages#4319]
### Description / Steps to reproduce the issue

1. collect about 400 lines command history and store them in .bash_history
2. start a new shell and type some commands then exit
3. start a new shell again and type history

### Expected behavior

New history can be stored in .bash_history

### Actual behavior

New history cannot be stored in .bash_history

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348 WIN-SERVER 3.4.10.x86_64 2023-11-30 06:09 UTC x86_64 Msys

**Comment by Biswa96** [comment]
There is a limit of maximum number of lines contained in the history file. That limit can be change like this https://askubuntu.com/questions/307541/how-to-change-history-size-for-ever

**Comment by ArchGuyWu** [comment]
> There is a limit of maximum number of lines contained in the history file. That limit can be change like this https://askubuntu.com/questions/307541/how-to-change-history-size-for-ever

I know the limit, but why it didn't remove the older history?

**Comment by ArchGuyWu** [comment]
I asked ChatGPT and two Arch users, they all said that new history will continue to be stored in .bash_history and the oldest one will be overwritten.
