### ISSUE TITLE
pacman command shows invalid crypto engine

### ISSUE THREAD

**Issue by Abdoalaa120** [msys2/MSYS2-packages#4324]
### Description / Steps to reproduce the issue

![~ 1_3_2024 11_55_23 PM](https://github.com/msys2/MSYS2-packages/assets/134527346/ea83ff88-4ac6-4485-9b58-79e83e78976a)

### Expected behavior

![Untitled - Google Chrome 1_4_2024 12_04_42 AM](https://github.com/msys2/MSYS2-packages/assets/134527346/f093468a-0a7e-4333-bf4d-2a98253a4d14)

### Actual behavior

![~ 1_3_2024 12_55_52 PM](https://github.com/msys2/MSYS2-packages/assets/134527346/08398f65-b806-4e0e-826e-fb45ec816efe)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows 10 Home Single Language

### Are you willing to submit a PR?

yes

**Comment by MehdiChinoune** [comment]
Your problem with people like you is that you check something without verification.
Your MSYS2 installation is out-of-date.

**Comment by lazka** [comment]
> Your problem with people like you is that you declare something without verification.

Please stop this. No need to confront users like that.

**Comment by MehdiChinoune** [comment]
> Please stop this. No need to confront users like that.

Sorry, but I couldn't hold myself when I see such behaviours. We added that box for users to check if their installations are up-to-date, yet they ignore it.

**Comment by lazka** [comment]
It looks to me like the screenshots are from two different machines, so maybe an outdated working one, and a potentially new one which doesn't work.

Could be Antivirus interfering.

**Comment by Abdoalaa120** [comment]
okay i 'll  try it
