### ISSUE TITLE
Proposal: Add a simple PKGBUILD for self-test

### ISSUE THREAD

**Issue by fracting** [msys2/MSYS2-packages#433]
When changing CI scripts ( .drone.yml / drone/build.sh ), it would be great to see if the CI scripts still works fine.

My proposal is adding a very small and simple PKGBUILD in the ./drone directory, and anytime .drone.yml or drone/\* is touched, we can trigger the building on that selftest PKGBUILD.

Do you like this idea? Any comment on what the selftest PKGBUILD should like?

If you like I can send a pull request.

(see also this example: https://github.com/Alexpux/MSYS2-packages/pull/432
We shouldn't let this pull request fail on CI server anyway, again it's my fault :D )

**Comment by Biswa96** [comment]
Drone gone 👋
