### ISSUE TITLE
[mpdecimal] Version 4.0.0 fully supports MSYS2/MinGW

### ISSUE THREAD

**Issue by skrah** [msys2/MSYS2-packages#4361]
### Description / Steps to reproduce the issue

This issue is purely informational to save work for the `MSYS2` developers. The existing `mpdecimal` patches have been fully integrated into `mpdecimal 4.0.0` and `MSYS2/MingGW`  are officially supported platforms from now on. This includes running the large test suite on `MSYS2/MingGW` :

https://www.bytereef.org/mpdecimal/changelog.html

Note that the soversion should be `4`, it is now synced with the major version.

### Expected behavior

N/A

### Actual behavior

N/A

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

Windows-10

**Comment by Biswa96** [comment]
mpdecimal is already available in mingw packages, see https://packages.msys2.org/base/mingw-w64-mpdecimal

**Comment by sskras** [comment]
I think the point made is being not about availability of the package but rather about the upstreamed patches:
https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-mpdecimal/mpdecimal-2.5.0-msys-mingw.patch

**Comment by Biswa96** [comment]
Thanks for the clarification. For unknown reason, it seems that every repository uses version 2.x.x of mpdecimal except macports. See https://repology.org/project/mpdecimal/versions

**Comment by skrah** [comment]
@Biswa96 Version 4.0.0 was just released yesterday, so I guess it will take some time before distributions pick it up.
