### ISSUE TITLE
mkdir: cannot create directory ‘’: No such file or directory

### ISSUE THREAD

**Issue by elakapmain** [msys2/MSYS2-packages#4427]
### Description / Steps to reproduce the issue

This is a fresh install. I haven't done anything with MSYS2 before today. I just want to compile and run C code from VS Code. The only step needed to reproduce is installing on my end.

I am new to this stuff, so I have no idea what I am doing, but after reinstalling on my C:\ and G:\ drive, I have run out of options. I cannot find good search results online.

### Expected behavior

Normal installation, no errors in output.

### Actual behavior

Starting MSYS starts with this:
```
mkdir: cannot create directory ‘’: No such file or directory
gpg: error running '/usr/lib/gnupg/keyboxd': probably not installed
gpg: failed to start keyboxd '/usr/lib/gnupg/keyboxd': Configuration error
gpg: can't connect to the keyboxd: Configuration error
gpg: error opening key DB: No Keybox daemon running
chmod: cannot access '/trustdb.gpg': No such file or directory
/usr/bin/pacman-key: line 244: ((: >= 0 : syntax error: operand expected (error token is ">= 0 ")
gpg: error running '/usr/lib/gnupg/keyboxd': probably not installed
gpg: failed to start keyboxd '/usr/lib/gnupg/keyboxd': Configuration error
gpg: can't connect to the keyboxd: Configuration error
gpg: error opening key DB: No Keybox daemon running
gpg: keydb_search_first failed: Input/output error
==> Generating pacman master key. This may take some time.
gpg: Generating pacman keyring master key...
gpg: error running '/usr/lib/gnupg/keyboxd': probably not installed
gpg: failed to start keyboxd '/usr/lib/gnupg/keyboxd': Configuration error
gpg: can't connect to the keyboxd: Configuration error
gpg: error opening key DB: No Keybox daemon running
gpg: error running '/usr/lib/gnupg/keyboxd': probably not installed
gpg: failed to start keyboxd '/usr/lib/gnupg/keyboxd': Configuration error
gpg: can't connect to the keyboxd: Configuration error
gpg: error opening key DB: No Keybox daemon running
gpg: key generation failed: Input/output error
gpg: Done
==> Updating trust database...
gpg: no need for a trustdb check
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
==> ERROR: You do not have sufficient permissions to read the pacman keyring.
==> Use 'pacman-key --init' to correct the keyring permissions.
```

Running `pacman-key --init` just spits out the same looking errors, no progress is made. I cannot use `pacman -Syuu` either, it has no output.

### Verification

- [x] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

**Comment by Biswa96** [comment]
Please make sure antivirus programs like Windows Defender or other listed here https://cygwin.com/faq/faq.html#faq.using.bloda are not interfering with msys2 processes. Try to exclude msys2 installation directory from antivirus realtime scanning.

**Comment by Biswa96** [comment]
I can not suggest any proper solution because it is not related to msys2 directly. The latest msys2 installer is working fine in my system and in other thousands CI runs.

**Comment by Biswa96** [comment]
By the way, did you try to uninstall and re-install msys2 after adding that exclusion?
