### ISSUE TITLE
Upgrade libmariadbclient

### ISSUE THREAD

**Issue by silverqx** [msys2/MSYS2-packages#4428]
### Description / Steps to reproduce the issue

Hi, currently there is `libmariadbclient` from MariaDB 10.8, that version is already 9 months after [end-of-life](https://endoflife.date/mariadb), but a bigger problem is that even v11.2 still contains TLS bugs (v10.8.8 is far beyond it).

Would be possible to upgrade it to `v11.3.2`, it contains a lot of TLS and SSL-related fixes that are very important. v11.4 will contain zero SSL configuration that was planned for v11.3 but it didn't make it into this release and was postponed until v11.4.

### Expected behavior

The libmariadbclient from the latest MariaDB v11.3.2

### Actual behavior

Too old version.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

### Are you willing to submit a PR?

I don't know how, I know nothing about MSYS2 packages ecosystem.

**Comment by MehdiChinoune** [comment]
libmariadbclient package on MSYS2 is what's called mariadb-connector-c by MariaDB.
It's at 3.3.8 which was released on Nov 1, 2023.
I will try to update to 3.3.9, but we could do nothing about Whether It's from 10.x or 11.x. You should report that to MariaDB maintainers.

**Comment by silverqx** [comment]
I currently checked it, and you are right, I thought that it was compiled from the MariaDB server tree but it has its own repo and the latest version is v3.3.9, would be great to upgrade it to this latest version. Everything is clear for me now after I have found [PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-libmariadbclient/PKGBUILD). 🙂

**Comment by MehdiChinoune** [comment]
unfortunately while they tagged 3.3.9 in their repo, It's not available from their server https://mariadb.org/download/?t=connector&p=connector-c. The latest is 3.3.8

**Comment by silverqx** [comment]
You are right, so we are at the latest release, thx for your asap assistance 👌
