### ISSUE TITLE
`meson build` fails on MSYS windows 11

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MSYS2-packages#4449]
### Description / Steps to reproduce the issue

```
pacman -S --needed --noconfirm meson gcc ninja git
git clone https://github.com/bearddan2000/dev-cpp-cli-ninja-meson-multi-file-hello-world.git example
cd example
meson build
```

this hangs forever on meson sanity check 
```
/usr/lib/python3.11/site-packages/mesonbuild/utils/universal.py 
>        o, e = p.communicate(write)
```

### Expected behavior
Should find any compiler, and in this case, error, because a file is not found, but it never finishes, gets stuck infinitely

### Actual behavior

it gets stuck in an infinite loop, this doesn't happen with cygwin.

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

**Comment by Kreijstal** [comment]
Weird, just checked with an up to date version on windows 8 and it worked. Something is going on here

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system with both Windows 10 and 11. Please make sure 

The meson.build file is incorrect in that project. I got error as following.

```
meson.build:5:0: ERROR: File main.cpp does not exist.
```

The meson.build file has to be modified as following.

```diff
diff --git a/meson.build b/meson.build
index 0088be2..dfc1d50 100755
--- a/meson.build
+++ b/meson.build
@@ -3,6 +3,6 @@ project('workspace', 'cpp',
   default_options : ['warning_level=3', 'cpp_std=c++14'])
 
 executable('main',
-           'main.cpp',
-           'greeting.cpp',
-           install : true)
\ No newline at end of file
+           'bin/main.cpp',
+           'bin/greeting.cpp',
+           install : true)
```

**Comment by Kreijstal** [comment]
> I can not reproduce the issue in my system with both Windows 10 and 11. Please make sure other 3rd party programs are not interfering with msys2 process, more here https://cygwin.com/faq/faq.html#faq.using.bloda
> 
> The meson.build file is incorrect in that project. I got error as following.
> 
> ```
> meson.build:5:0: ERROR: File main.cpp does not exist.
> ```
> 
> The meson.build file has to be modified as following.
> 
> ```diff
> diff --git a/meson.build b/meson.build
> index 0088be2..dfc1d50 100755
> --- a/meson.build
> +++ b/meson.build
> @@ -3,6 +3,6 @@ project('workspace', 'cpp',
>    default_options : ['warning_level=3', 'cpp_std=c++14'])
>  
>  executable('main',
> -           'main.cpp',
> -           'greeting.cpp',
> -           install : true)
> \ No newline at end of file
> +           'bin/main.cpp',
> +           'bin/greeting.cpp',
> +           install : true)
> ```

Don't be confused.
Yes correct, the meson build is incorrect, and the desired outcome is that it errors, that is not the bug, the bug is that it gets stuck in infinite loop, however what you said is that on your windows 11 you could not manage to reproduce it, aka it errors successfully, I have to see what exactly is going on with this system, as I couldn't reproduce it on another Windows 8 machine. I can tell you this, it seems it is getting stuck on Popen subprocess communication. I'll update it once I manage to point it down, but this is strange that it doesn't work here.

**Comment by Kreijstal** [comment]
Okay, I managed to pinpoint the issue, it seems it gets stuck here
```
 ccache cc sanitycheckc.c -o santiycheck.exe -D_FILE_OFFSET_BITS=64
 ```
 where sanitycheck.c is
```
 int main(void) { int class=0; return class; }
```
doesn't error, never returns

**Comment by Biswa96** [comment]
msys2 ccache does not work, see #4311
