### ISSUE TITLE
pkgconf can't find glib2?

### ISSUE THREAD

**Issue by Kreijstal** [msys2/MSYS2-packages#4467]
### Description / Steps to reproduce the issue

install glib2 using `pacman -S glib2`
execute
`pkg-config --exists --print-errors glib-2.0`

### Expected behavior

pkgconf should find glib2

### Actual behavior

we get 
```
topkek@ayylmai MSYS ~/git/pango-1.90.0
$ pkg-config --exists --print-errors glib-2.0
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'glib-2.0', required by 'virtual:world', not found
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

**Comment by Biswa96** [comment]
Did you install the glib2-devel package? The pkgconfig files are in that package, see https://packages.msys2.org/package/glib2-devel?repo=msys&variant=x86_64

**Comment by Kreijstal** [comment]
user error!
