### ISSUE TITLE
"Error: clangarm64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown" when using pacman command

### ISSUE THREAD

**Issue by Pldm24** [msys2/MSYS2-packages#4482]
### Description / Steps to reproduce the issue

Whenever i want to use pacman command (I need pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain), it says "error: clangarm64: key "5F944B027F7FE2091985AA2EFA11531AA0AA7F57" is unknown :: Import PGP key 5F944B027F7FE2091985AA2EFA11531AA0AA7F57? [Y/n]". If i choose yes, console freezes for a couple of minutes and outputs another error. If i choose no, nothing happens.

### Expected behavior

![cpp-install-MSYS2-toolchain](https://github.com/msys2/MSYS2-packages/assets/109288168/9284f053-6e5c-4f27-a940-d4ef9efe81e7)

### Actual behavior

![Снимок экрана (10)](https://github.com/msys2/MSYS2-packages/assets/109288168/333c9e7b-d44d-4a50-9c99-3036a7c1883a)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

**Comment by Biswa96** [comment]
Did you use the latest installer from official web page https://www.msys2.org/ ?

**Comment by Pldm24** [comment]
> Did you use the latest installer from official web page https://www.msys2.org/ ?

Yes.

**Comment by Biswa96** [comment]
Try to run `pacman-key --init; pacman-key --populate` first.

**Comment by Pldm24** [comment]
> Try to run `pacman-key --init; pacman-key --populate` first.

![Снимок экрана (11)](https://github.com/msys2/MSYS2-packages/assets/109288168/deb7de3d-7a1e-43ea-a64f-5b1efdd9dab7)

**Comment by vagor77** [comment]
> Problem is still there.

Had exactly the same problem. Nothing helped. no real information on the problem. Exactly the same errors!

Solved like this:
1) Deleted all, reboot
2) disable antivirus: firewall, scanning, everything.
3) installed msys2 again
4) it works!

Let me know if it works for you and your antivirus :-)

**Comment by Biswa96** [comment]
> 2\. disable antivirus: firewall, scanning, everything.

It is not recommended to disable antivirus or firewall completely which would make the system more vulnerable to viruses. Instead, it is suggested to disable real-time scanning in msys2 installation directory when required.

**Comment by Pldm24** [comment]
> > Problem is still there.
> 
> Had exactly the same problem. Nothing helped. no real information on the problem. Exactly the same errors!
> 
> Solved like this:
> 
> 1. Deleted all, reboot
> 2. disable antivirus: firewall, scanning, everything.
> 3. installed msys2 again
> 4. it works!
> 
> Let me know if it works for you and your antivirus :-)

I disabled antivirus, and it worked fine. I did it a while ago, so your answer is not actual anymore.

**Comment by vagor77** [comment]
> > > Problem is still there.
> > 
> > 
> > Had exactly the same problem. Nothing helped. no real information on the problem. Exactly the same errors!
> > Solved like this:
> > 
> > 1. Deleted all, reboot
> > 2. disable antivirus: firewall, scanning, everything.
> > 3. installed msys2 again
> > 4. it works!
> > 
> > Let me know if it works for you and your antivirus :-)
> 
> I disabled antivirus, reinstalled msys2 from scratch and it worked fine. I did it a while ago, so your answer is not actual anymore.

Good you resolved, this. Could be good if would publish the solution.
Because a lot of people still have the same problem and there are no solution published anywhere.

**Comment by necrovamp** [comment]
> Try to run `pacman-key --init; pacman-key --populate` first.

this fixed it for me, thank you

**Comment by kiotex** [comment]
On my PC, disabling the Sophos antivirus software solved the problem. Thank you.

**Comment by shackra** [comment]
not recommended, but changing `/etc/pacman.conf`:

```
SigLevel           = Never
LocalFileSigLevel  = Optional
```

Should bypass the GnuPG layer that is broken.

EDIT:

Even with that, `pacman` won't work correctly:

```
$ pacman -S git mingw-w64-ucrt-x86_64-gcc
resolving dependencies...
looking for conflicting packages...

Packages (53) heimdal-7.8.0-5  heimdal-libs-7.8.0-5  libcbor-0.12.0-1  libedit-20240808_3.1-1  libfido2-1.16.0-1  mingw-w64-ucrt-x86_64-binutils-2.46-2  mingw-w64-ucrt-x86_64-crt-13.0.0.r560.g3197fc7d6-1  mingw-w64-ucrt-x86_64-gcc-libs-15.2.0-13
              mingw-w64-ucrt-x86_64-gettext-runtime-1.0-1  mingw-w64-ucrt-x86_64-gmp-6.3.0-2  mingw-w64-ucrt-x86_64-headers-13.0.0.r560.g3197fc7d6-1  mingw-w64-ucrt-x86_64-isl-0.27-1  mingw-w64-ucrt-x86_64-libiconv-1.19-1
              mingw-w64-ucrt-x86_64-libwinpthread-13.0.0.r560.g3197fc7d6-1  mingw-w64-ucrt-x86_64-mpc-1.3.1-2  mingw-w64-ucrt-x86_64-mpfr-4.2.2-1  mingw-w64-ucrt-x86_64-tzdata-2026a-1  mingw-w64-ucrt-x86_64-windows-default-manifest-6.4-4
              mingw-w64-ucrt-x86_64-winpthreads-13.0.0.r560.g3197fc7d6-1  mingw-w64-ucrt-x86_64-zlib-1.3.2-2  mingw-w64-ucrt-x86_64-zstd-1.5.7-1  openssh-10.2p1-2  perl-Authen-SASL-2.2000-1  perl-Clone-0.48-1  perl-Convert-BinHex-1.125-2  perl-Encode-Locale-1.05-2
              perl-Error-0.17030-1  perl-File-Listing-6.16-1  perl-HTML-Parser-3.83-2  perl-HTML-Tagset-3.24-1  perl-HTTP-Cookies-6.11-1  perl-HTTP-Daemon-6.16-1  perl-HTTP-Date-6.06-1  perl-HTTP-Message-7.01-1  perl-HTTP-Negotiate-6.01-3  perl-IO-HTML-1.004-2
              perl-IO-Socket-SSL-2.098-1  perl-IO-Stringy-2.113-3  perl-LWP-MediaTypes-6.04-2  perl-MIME-tools-5.517-1  perl-MailTools-2.22-1  perl-Net-HTTP-6.24-1  perl-Net-SMTP-SSL-1.04-2  perl-Net-SSLeay-1.94-3  perl-TermReadKey-2.38-7  perl-TimeDate-2.34-1
              perl-Try-Tiny-0.32-1  perl-URI-5.34-1  perl-WWW-RobotRules-6.02-3  perl-http-cookiejar-0.014-1  perl-libwww-6.81-1  git-2.53.0-1  mingw-w64-ucrt-x86_64-gcc-15.2.0-13

Total Download Size:    80.90 MiB
Total Installed Size:  606.63 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 mingw-w64-ucrt-x86_64-gcc-15.2.0-13-any
 git-2.53.0-1-x86_64                                                                                                                   0.0   B  0.00   B/s 00:00 [---------------------------------------------------------------------------------------------------]   0%
 mingw-w64-ucrt-x86_64-headers-13.0.0.r560.g3197fc7d6-1-any                                                                            0.0   B  0.00   B/s 00:00 [---------------------------------------------------------------------------------------------------]   0%
 mingw-w64-ucrt-x86_64-binutils-2.46-2-any                                                                                             0.0   B  0.00   B/s 00:00 [---------------------------------------------------------------------------------------------------]   0%
 mingw-w64-ucrt-x86_64-crt-13.0.0.r560.g3197fc7d6-1-any                                                                                0.0   B  0.00   B/s 00:00 [---------------------------------------------------------------------------------------------------]   0%
 Total ( 0/53)   
```
