### ISSUE TITLE
CI script does not build multiple package for a single push with multiple commit

### ISSUE THREAD

**Issue by fracting** [msys2/MSYS2-packages#449]
Currently we are using 

```
files=($(git show --pretty=format: --name-only $(git log -1 --pretty=format:%P | cut -d' ' -f1)..HEAD | sort -u))
```

to detect multiple package in a single pull request, this works fine.

However, if the project maintainer push multiple commits in one time, the above command line show only the last touched package.

@renatosilva any idea how could we improve that?

Thanks!

**Comment by Biswa96** [comment]
Now, GitHub Actions CI can build multiple package for a single push with multiple commit.
