### ISSUE TITLE
What about `mingw-w64-cross-clang-toolchain`?

### ISSUE THREAD

**Issue by iahung3** [msys2/MSYS2-packages#4511]
Can it be updated to newer version? It's not the same as `msys/clang`: https://github.com/msys2/MSYS2-packages/issues/4182

I noticed that `mingw-w64-cross-toolchain` was updated to latest GCC.

**Comment by jeremyd2019** [comment]
It actually is.  clang is inherently a cross compiler, so the cross-clang just provides the compiler-rt for the target and wrapper scripts.  The cross-clang toolchain was only ever used to bootstrap the CLANG* msystems, and should really not be used by anybody else IMO.
