### ISSUE TITLE
Acquiring gcc / g++ to run C/C++ files

### ISSUE THREAD

**Issue by ZeitHeld** [msys2/MSYS2-packages#4543]
Hey uhh, for my university I am required to run c++ files with VSCode. Though it told me that it could not find the command `g++`
now I tried to fix that issue, following a bit along by researching on google.
I found and followed the top answer of [this stackoverflow issue](https://stackoverflow.com/questions/51296010/new-to-c-compiling-in-visual-studio-code-error-gcc-not-recognized) as well as mostly things from issue #1190 I think that I could now get around the issue of it not being satisfied.
Now I get stumped on step 10 / 11 from the stackoverflow question. Because each time I try to run `gcc --version` I'll just get the respond `-bash: gcc: command not found`

Additionally, I also added  `C:\msys64\mingw64\bin` to my Environment Variable `Path`

I'm pretty much clueless right now, did I made any oversights? Can I be helped?

**Comment by Biswa96** [comment]
Could you follow this guide https://code.visualstudio.com/docs/cpp/config-mingw ?

**Comment by ZeitHeld** [comment]
It did something, but it did not fix the issue.
I don't know though if trying to re-install MSYS2 might solve it. Since I think that it should kinda update on it's own? Or at least that it shouldn't be an issue?

(and I would need to do the steps again and maybe other things why I have this for)

**Comment by ZeitHeld** [comment]
I tried that and it turns out somehow using VSCode now does work!

only issue being with the code ig as it does not let me use scanf properly. But Hello World does work fine

Thank you!
