### ISSUE TITLE
SSH failing to find config and identities in user home

### ISSUE THREAD

**Issue by RivenSkaye** [msys2/MSYS2-packages#4544]
### Description / Steps to reproduce the issue

SSH is unable to load identities and config stored in the usual `~/.ssh` directory at all for me. Changing `~/.ssh/config` is making no difference even when _not_ using tokens in the path and instead using the system username. When running `ssh-keygen` it expands the default directory to `//.ssh/`, and for a few other commands it's pointing up to `/.ssh/` where I can confirm the expected modifications to e.g. `known_hosts` are happening. Some `stat` calls into looking around, it seems to be caused by some update after 2022-09-05 (creation and modification dates listed for `stat ~/.ssh/known_hosts{,.old}`) and it took me until now to notice because I'm only now setting up a new host for which I needed new keys (the others are local network hosts that take password auth)

### Expected behavior

the SSH family of tools working from `~/.ssh/`

### Actual behavior

the same tools modifying files in the msys root directory.

Running `ssh -G .` to dump the config lists one notable entry - `~` is being considered an escape char. I wonder if that causes issues...
Considering it's checking the wrong directory, these are the defaults for the current package version.
[ssh_-G.log](https://github.com/msys2/MINGW-packages/files/15024276/ssh_-G.log)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

If I can figure out why things break, sure

**Comment by Biswa96** [comment]
> I'm facing this problem trying to SSH into a machine on the network.

I am also using msys2 ssh to log into Android + termux sshd in same network. It does not cause any issue.

Did you check if ssh finds the config file path correctly? Or, is the config file syntax correct?

**Comment by sskras** [comment]
@RivenSkaye commented [14 minutes ago](https://github.com/msys2/MSYS2-packages/issues/4544#issuecomment-2063817365):

> I'm facing this problem trying to SSH into a machine on the network. Using keys that I know are valid, and they work when I add `-i /home/riven/.ssh/id_ed25519`.

I tried comparing this to the output of `ssh -G vps1128235` on my box:

![image](https://github.com/msys2/MSYS2-packages/assets/7887758/cc3f778c-219c-41e2-a7ea-7bd167e14a86)

... and the first three lines comes as a surprise:
```diff
-host .
-user Unknown+User
-hostname .
+host vps1128235
+user sskras
+hostname vps1128235
```

What do your `$USER` and `$HOME` variables say? Mine follows:
```sh
$ echo $USER $HOME
saukrs /home/saukrs
```

Also it's interesting to know whether you have `/etc/passwd` DB present in your setup:
```sh
$ ls -l /etc/passwd
-rw-r--r-- 1 saukrs None 2074 Apr  7 14:51 /etc/passwd
```

**Comment by RivenSkaye** [comment]
SSH just... doesn't load it. The config file is fine, and the cheapest imaginable hack (`ln -s ~/.ssh /.ssh`) makes everything magically work as intended. `$USER` and `$HOME` return the expected output. Excuse the name, this is my work box (which I'm having the issue on) so unfortunately the name is my actual one. Just a first name though, so no worries on doxxing.
![image](https://github.com/msys2/MSYS2-packages/assets/14993038/1b98ade1-ce13-4f72-aa3e-8e93ad497183)

The info listing on passwd looks weird too... Makes me wonder if recursively `chown`ing stuff could fix this...
![image](https://github.com/msys2/MSYS2-packages/assets/14993038/0b1449a4-8059-4a4b-afaa-d87ee2084de6)

**Comment by sskras** [comment]
SSH client seemingly picks up `Unknown+User` as the username for some reason.

Maybe it's worth to revisit your `~/.ssh/config` file?

Also, what does these 3 command say to you (if only they does not disclose sensitive data)?
```sh
$ id
uid=197614(saukrs) gid=197121(None) groups=197121(None),545(Users),4(INTERACTIVE),66049(CONSOLE LOGON),11(Authenticated Users),15(This Organization),113(Local account),4095(CurrentSession),66048(LOCAL),262154(NTLM Authentication),401408(Medium Mandatory Level)

$ getent passwd $USER
saukrs:*:197614:197121:U-DESKTOP-O7JE7JE\saukrs,S-1-5-21-3533002965-4122658273-1040882531-1006:/home/saukrs:/usr/bin/bash

$ echo $USERNAME
saukrs
```

**Comment by RivenSkaye** [comment]
![image](https://github.com/msys2/MSYS2-packages/assets/14993038/1abc5de1-1c7f-405f-ae72-d1893e04570c)
The only remotely relevant thing I can find is a script setting `$USER=$(logname)`, but it's not touching `$USERNAME` itself.
The `~/.ssh/config` itself is fine; I only started mangling it after this issue popped up for me, solely to try and have it point to the identity files. As such, those are the only entries in there

**Comment by sskras** [comment]
> The only remotely relevant thing I can find is a script setting `$USER=$(logname)`

So `id -un` returns the wrong ID (and the wrong name). But `logname` return the right name. To be double sure, it maybe worth running this:
```sh
$ logname
saukrs

$ id -u
197614

$ id -un
saukrs
```

I would also check what does `mkpasswd` generates for your current user:
```sh
$ mkpasswd -c
saukrs:*:197614:197121:U-DESKTOP-O7JE7JE\saukrs,S-1-5-21-3533002965-4122658273-1040882531-1006:/home/saukrs:/usr/bin/bash
```

... and the fulll version of MSYS2:
```sh
$ uname -a
MSYS_NT-10.0-19044 DESKTOP-O7JE7JE 3.4.10.x86_64 2023-12-22 10:06 UTC x86_64 Msys
```

> I only started mangling it after this issue popped up for me

So ... when did that change happen? By chance, did you update MSYS2 of your Windows before that?

**Comment by RivenSkaye** [comment]
> To be double sure ...

That gives me the expected output - username, ID, Unknown+User
> `mkpasswd`

That gives... yet other output. Notice the use of capital letters on the name
`Martin:*:1049797:1049089:U-<DOMAIN NAME OMITTED>\Martin,S-1-5-21-1265852941-3674232667-1720454753-1221:/home/Martin:/usr/bin/bash`
> `cat /etc/nsswitch.conf`

```
   1   │# Begin /etc/nsswitch.conf
   2   │
   3   │ passwd: files #db
   4   │ group: files #db
   5   │
   6   │ db_enum: cache builtin
   7   │
   8   │ db_home: cygwin desc
   9   │ db_shell: cygwin desc
  10   │ db_gecos: cygwin desc
  11   │
  12   │ # End /etc/nsswitch.conf
```
> `uname -a`

`MSYS_NT-10.0-19045 DESKTOP-2M2MTV7 3.4.10.x86_64 2024-04-08 18:11 UTC x86_64 Msys`

I wonder if this has anything to do with the account being a domain account. We have set desks but the accounts and systems are managed through a domain to handle perms, group policies for network mounts, etc. and that might be what breaks stuff like usernames and whatnot...

**Comment by sskras** [comment]
> the last timestamps on `~/.ssh/known_hosts` are from 2022. I just never noticed because I usually SSH with username/password for the few systems in the network where it's relevant

So this regressed during the last year and a half for you, I presume. Should the regression have occur on the MSYS2 side, users would be complaining already, I guess.  Unless it's very recent, which we doubt. Right?

> I wonder if this has anything to do with the account being a domain account. We have set desks but the accounts and systems are managed through a domain to handle perms, group policies for network mounts, etc. and that might be what breaks stuff like usernames and whatnot...

I guess so. Probably some Windows update or an update in some group policy happened. Found this:

> @legends2k commented [on Feb 12, 2015](https://github.com/msys2/MSYS2-packages/issues/138#issuecomment-74079347)
> 
> > Disabling **db** from both **passwd** and **group** fixed the issue but led to my username being unrecognised (bash prompt showed me as _Unknown+User_).

The fact that you are setting `$USER` via `logname` suggests you were getting `Unknown+User` also in your prompt. And just worked around that.

> > `mkpasswd`
> 
> That gives... yet other output. Notice the use of capital letters on the name `Martin:*:1049797:1049089:U-<DOMAIN NAME OMITTED>\Martin,S-1-5-21-1265852941-3674232667-1720454753-1221:/home/Martin:/usr/bin/bash`

As is [suggested in the issue](https://github.com/msys2/MSYS2-packages/issues/138#issuecomment-101715497) I mentioned above, the workaround (or rather finishing the old workaround) is probably to:

* 1, put this line into `/etc/passwd`
  
   ... by either appending it, or by replacing some old line that might be describing your current Windows account. Hard to say without looking into the file contents. Maybe just insert it as the 1st line and be done without an analysis.

> > `cat /etc/nsswitch.conf`
> 
> ```
>    1   │# Begin /etc/nsswitch.conf
>    2   │
>    3   │ passwd: files #db
>    4   │ group: files #db
>    5   │
>    6   │ db_enum: cache builtin
>    7   │
>    8   │ db_home: cygwin desc
>    9   │ db_shell: cygwin desc
>   10   │ db_gecos: cygwin desc
>   11   │
>   12   │ # End /etc/nsswitch.conf
> ```

* 2, uncomment `db` in the `passwd: files #db` then.

**Comment by RivenSkaye** [comment]
I didn't uncomment the `db` in `nsswitch.conf` as the linked issue recommends commenting it out. But regenerating `passwd` with the current user active and removing the scripted line to set the username value is providing me with at least proper `id` output as well as `getent` working correctly. Let me remove the SSH symlink and test it again just to make sure

**Comment by RivenSkaye** [comment]
Issue solved - I do wonder why this doesn't work OOTB though, as at some point it seems like the installer _did_ generate `/etc/passwd` with mostly correct contents as well as having the db entries in `nsswitch.conf` commented out (which might be a global default, not sure).

Thanks again @sskras!

**Comment by Biswa96** [comment]
I do not have `/etc/passwd` in msys2 installation but ssh works just fine.

**Comment by sskras** [comment]
@Biswa96) commented [1 minute ago](https://github.com/msys2/MSYS2-packages/issues/4544#issuecomment-2066472923)

> I do not have `/etc/passwd` in msys2 installation but ssh works just fine.

Most probably because you never ran your MSYS2 setup on a domain-controlled Windows installation.

**Comment by sskras** [comment]
@RivenSkaye commented [3 hours ago](https://github.com/msys2/MSYS2-packages/issues/4544#issuecomment-2066176192):

> I didn't uncomment the `db` in `nsswitch.conf` as the linked issue recommends commenting it out. 

I seemingly mixed things up. Thanks for checking and clarifying.

> Issue solved - I do wonder why this doesn't work OOTB though, as at some point it seems like the installer _did_ generate `/etc/passwd` with mostly correct contents as well as having the db entries in `nsswitch.conf` commented out (which might be a global default, not sure).

Congrats :)

If you would do a clean installation of MSYS2 on your Windows machine, maybe this would work out of the box. This can be tested, but is that worth it? :)

**Comment by RivenSkaye** [comment]
It most certainly could be worth checking, as it'd allow for automating this kinda thing _if_ we can find a stable way to determine the user is a domain/AD user rather than a local user.

Interesingly, the only thing about git that broke from all this (and probably the reason why it didn't break before) is that it fell back to the user ID when the username was unknown. First push I did asked me to select the credential store to use so I selected the one named after my user ID and everything worked again
