### ISSUE TITLE
[docx2txt] Windows can't find executable because file does not have .exe extension

### ISSUE THREAD

**Issue by aandrejevas** [msys2/MSYS2-packages#4572]
### Description / Steps to reproduce the issue

1. pacman -S docx2txt
2. open cmd
3. write "docx2txt" to console (make sure /usr/bin is in path)
4. A message comes up saying that "docx2txt" is not recognized as a command. I think it is because docx2txt file does not have an .exe extension.

### Expected behavior

![image](https://github.com/msys2/MSYS2-packages/assets/53169542/b867365d-5fa0-4ff0-a2b1-77367de287bf)

### Actual behavior

![image](https://github.com/msys2/MSYS2-packages/assets/53169542/fbd39dd0-cbee-44bf-b141-36cf05143300)

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-22631

**Comment by ognevny** [comment]
it doesn't have an `.exe` extension, as this is a perl script. so it can't be invoked directly in cmd

**Comment by aandrejevas** [comment]
![image](https://github.com/msys2/MSYS2-packages/assets/53169542/337a8cdc-30e9-472a-b405-b5b6022b02da)
If it is a perl script only, then why there even is a file without an extension?
And I can invoke it directly in msys console, not in cmd.

**Comment by ognevny** [comment]
because msys console can run perl scripts directly

**Comment by sskras** [comment]
@ognevny commented [8 hours ago](https://github.com/msys2/MSYS2-packages/issues/4572#issuecomment-2089460226):

> it doesn't have an `.exe` extension, as this is a perl script. 

@aandrejevas commented [2 hours ago](https://github.com/msys2/MSYS2-packages/issues/4572#issuecomment-2090062877):

> If it is a perl script only, then why there even is a file without an extension in the package? 

Actually these are two different scripts:
```sh
$ ls -l /usr/bin/docx2txt*
-rwxr-xr-x 1 saukrs None  3363 Mar  6  2023 /usr/bin/docx2txt
-rwxr-xr-x 1 saukrs None 21572 Mar  6  2023 /usr/bin/docx2txt.pl

$ file /usr/bin/docx2txt*
/usr/bin/docx2txt:    Bourne-Again shell script, ASCII text executable
/usr/bin/docx2txt.pl: Perl script text executable
```

@ognevny wrote:

> so it can't be invoked directly in cmd

By prepending array in `PATHEXT` env-var with `.` it can be invoked, just not as an executable:

![image](https://github.com/msys2/MSYS2-packages/assets/7887758/97177ff7-ed00-499e-b5cb-ed04946b9511)

But maybe that could be fixed by adding a proper FType, just like it's done for `.exe` files:
```sh
$ cmd //c ftype exefile
exefile="%1" %*
```

I'm just unsure how that would work with pipes.

**Comment by sskras** [comment]
PS. I added a new (empty) extension to `PATHEXT`, a new FType and a new association for `.` (extensionless) files:
```
C:\msys64\usr\bin> sudo ftype ExtensionlessProgram=C:\msys64\usr\bin\bash.exe %1
ExtensionlessProgram=C:\msys64\usr\bin\bash.exe %1

C:\msys64\usr\bin> sudo assoc .=ExtensionlessProgram
.=ExtensionlessProgram

C:\msys64\usr\bin> set PATHEXT=%PATHEXT%;.

C:\msys64\usr\bin> .\docx2txt
C:\msys64\usr\bin\docx2txt: line 46: dirname: command not found
C:\msys64\usr\bin\docx2txt: line 50: cat: command not found

C:\msys64\usr\bin>
```

... but that hack didn't work. Bash seemingly doesn't get it's environment initialized properly (at least `PATH`) that way.

This rises idea about creating a specific binary wrapper which would:

- initialize the MSYS2 environment transparently
- identify the appropriate interpreter for a given file (Bash for `docx2txt`, Perl for `docx2txt.pl`)
- properly run the child process

That would be a nice integration into Windows ecosystem.
