### ISSUE TITLE
mingw32/clang32: cannot install perl package

### ISSUE THREAD

**Issue by madebr** [msys2/MSYS2-packages#4587]
### Description / Steps to reproduce the issue

When using the [msys2/setup-msys2](https://github.com/msys2/setup-msys2) action, installing perl fails for mingw32 and clang32.

- mingw32: mingw-w64-i686-perl ([log](https://github.com/libsdl-org/SDL/actions/runs/8990411373/job/24695670626))
- clang32: mingw-w64-clang-i686-perl ([log](https://github.com/libsdl-org/SDL/actions/runs/8990411373/job/24695672596))

### Expected behavior

Both packages install, and ci continues to build our project

### Actual behavior

```
   error: target not found: mingw-w64-i686-perl
```

```
   error: target not found: mingw-w64-clang-i686-perl
```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

10.0.20348

**Comment by 1480c1** [comment]
Seems they were disabled in https://github.com/msys2/MINGW-packages/pull/20085 because they failed to build.

**Comment by madebr** [comment]
Thanks, we only use perl for documentation generation so there is no real harm when it is not available.
