### ISSUE TITLE
msys2-runtime-devel: missing debug info

### ISSUE THREAD

**Issue by jeremyd2019** [msys2/MSYS2-packages#4595]
msys2-runtime-devel-3.5.3-2 is missing msys-2.0.dbg.  It also seems to be missing from msys2-runtime-3.4-devel-3.4.10-1, so I kind of suspect binutils, though I haven't looked into it at all.

**Comment by jeremyd2019** [comment]
Looking at repo.msys2.org, it looks like msys2-runtime-devel got notably smaller here:
[msys2-runtime-devel-3.4.2-2-x86_64.pkg.tar.zst](https://repo.msys2.org/msys/x86_64/msys2-runtime-devel-3.4.2-2-x86_64.pkg.tar.zst)     16-Dec-2022 08:11      5M
[msys2-runtime-devel-3.4.3-1-x86_64.pkg.tar.zst](https://repo.msys2.org/msys/x86_64/msys2-runtime-devel-3.4.3-1-x86_64.pkg.tar.zst)     16-Dec-2022 22:23    361K

I can't believe nobody noticed lack of debugging info since then though.  I know I was debugging the runtime since then.  I must be missing something.

I did notice this because Iwasn't getting any symbols in gdb for msys-2.0.dll today, for 3.5.3-2

**Comment by lazka** [comment]
I think this was removed in https://cygwin.com/git/?p=newlib-cygwin.git;a=commit;h=99bb3e937a0fdbc1e3acbdc7cefb31e54a89a6ac and subsequently in https://github.com/msys2/msys2-runtime/pull/125

So to have debug info we'd need to create it like for every other package I guess? `options=(debug strip)`

**Comment by jeremyd2019** [comment]
Hmm, I think I must have been using msys2-runtime-3.3 (on i686) when I was debugging the runtime lately.

**Comment by jeremyd2019** [comment]
This is probably not the best place, but I noticed yesterday that windbgx (the ms store version of windbg) appeared to be making use of symbols from msys-2.0.dll when the debug info was not split (using the install.zip from the workflow on msys2-runtime), while it doesn't seem to handle the gnu debuglink thing.
