### ISSUE TITLE
error: msys: key "FA11531AA0AA7F57" is unknown

### ISSUE THREAD

**Issue by pyousefi** [msys2/MSYS2-packages#4601]
### Description / Steps to reproduce the issue

chocolaty install of msys2 on Windows 10 Pro: msys2 v20240507.0.0 [Approved]

Open msys2 and do anything with core:
$pacman -Q
$update-core

### Expected behavior

List pacman packages or update msys2 core libraries

### Actual behavior

error: msys: key "FA11531AA0AA7F57" is unknown

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0

### Are you willing to submit a PR?

yes

**Comment by Biswa96** [comment]
Please try with the installer from here https://www.msys2.org/
