### ISSUE TITLE
collect2.exe: error: ld returned 116 exit status

### ISSUE THREAD

**Issue by wv1124** [msys2/MSYS2-packages#4617]
### Description / Steps to reproduce the issue

win11
1. install msys2
2. pacman -S --needed base-devel mingw-w64-ucrt-x86_64-toolchain
3. add E:\msys64\usr\bin, E:\msys64\ucrt64\bin to path.
4. main.cpp
```
#include <iostream>
using namespace std;
int main(void)
{
    cout << "test";
    return 0;
}
```
5. open windows power shell
6. ```g++ .\main.cpp -o main```
7. collect2.exe: error: ld returned 116 exit status

more refer: 
https://stackoverflow.com/questions/78477174/collect2-exe-error-ld-returned-116-exit-status-when-using-g-with-git-bash/78521930#78521930

g++ --version
g++.exe (Rev6, Built by MSYS2 project) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

 gcc --version
gcc.exe (Rev6, Built by MSYS2 project) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Expected behavior

compile success

### Actual behavior

collect2.exe: error: ld returned 116 exit status

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

**Comment by MehdiChinoune** [comment]
Please, update your installation before filling any bug.
(`I have verified that my MSYS2 is up-to-date before submitting the report`)

**Comment by jeremyd2019** [comment]
> 3. add E:\msys64\usr\bin, E:\msys64\ucrt64\bin to path.

Kind of a wild guess based on limited information, but if you put both on the PATH, you should put ucrt64\bin first.  Otherwise you could be accidentally using eg msys binutils with ucrt64 gcc, and I'm sure that would be a recipe for disaster.

**Comment by Koehle** [comment]
I had the same problem and the solution for me was a change in the Windows system environment variables.

In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.

Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.

At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.

After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

Translated with DeepL.com (free version)

**Comment by xYanOne** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

you are right！！！thank u very much！i had succeed by your way：）

**Comment by ashokkr14** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

Thanks, worked for me !

**Comment by Tanio253** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

Very nice, it worked for me!

**Comment by coder1883** [comment]
how do you move the path to MSYS2 to top

**Comment by Koehle** [comment]
> how do you move the path to MSYS2 to top

First you need to open the system environment variables.

The following article shows how to do this, for example:
https://www.thewindowsclub.com/how-to-add-edit-a-path-variable-in-windows

When the "Environment Variables" window is displayed, you can see the "System Variables" in the lower half.
There is a variable called "Path".
Select this variable by clicking on it and then click on the "Edit..." button.
A new window opens and all “Path” entries are displayed in it.
There are buttons on the right-hand side of the window that you can use to move the individual entries up or down.

**Comment by Jun-yuChen** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

This works for me, thanks.

**Comment by Abhijitdrag** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

it work for me

**Comment by AhmadTariq16** [comment]
> I had the same problem and the solution for me was a change in the Windows system environment variables.
> 
> In my case, only the path “C:\msys64\ucrt64\bin” and its position relative to the other system environment variables was relevant.
> 
> Meld, PuTTY, TortoiseGit and Git are installed on my computer and their paths were also entered in the environment variables.
> 
> At first I had entered the path “C:\msys64\ucrt64\bin” after the entries for Meld, PuTTY etc. and had the error described.
> 
> After I moved the path to MSYS2 to the top, i.e. before the paths of the other programs, compiling the source code worked without the error.

Thank you, this worked for me.
But any idea why changing the position of environment variables solves the issue?
