### ISSUE TITLE
`pacman -S git` succeeded but "git.exe" is not installed

### ISSUE THREAD

**Issue by felixf4xu** [msys2/MSYS2-packages#4620]
### Description / Steps to reproduce the issue

I tried to install git via pacman like this:
```shell
pacman -S git
```
I got
>warning: git-2.45.1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
Packages (1) git-2.45.1-1
Total Installed Size:  37.43 MiB
Net Upgrade Size:       0.00 MiB
:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                                                  [#############################################] 100%
(1/1) checking package integrity                                                [#############################################] 100%
(1/1) loading package files                                                     [#############################################] 100%
(1/1) checking for file conflicts                                               [#############################################] 100%
(1/1) checking available disk space                                             [#############################################] 100%
:: Processing package changes...
(1/1) reinstalling git                                                          [#############################################] 100%

### Expected behavior

there should be "C:\msys64\usr\bin\git.exe"

### Actual behavior

 but I can't find it

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### Are you willing to submit a PR?

yes

**Comment by ognevny** [comment]
is `git` runnable in any msys2 shell?

**Comment by felixf4xu** [comment]
![image](https://github.com/msys2/MSYS2-packages/assets/84662027/7753a94d-8f6c-47f2-afb0-001a5e392881)

**Comment by ognevny** [comment]
try to remove all pre installed packages (`pacman -Scc` or `paccache -r`) then rerun `pacman -S git`. but I'm not sure that it can help

**Comment by lazka** [comment]
You can run `pacman -Qkk git` to check if all files are there

**Comment by felixf4xu** [comment]
`pacman -Scc` did not help,

`pacman -Qkk git`:

>git: 791 total files, 0 altered files

**Comment by sskras** [comment]
For me it works:
```sh
saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ pacman -Qkk git
git: 791 total files, 0 altered files

saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ git -v
git version 2.42.0
```

My MSYS2 setup:
```sh
saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ pacman -Q git
git 2.42.0-2

saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ pacman -Qi git
Name            : git
Version         : 2.42.0-2
Description     : The fast distributed version control system
Architecture    : x86_64
URL             : https://git-scm.com/
Licenses        : GPL2
Groups          : VCS
Provides        : git-core
Depends On      : curl  libpcre2_8  libexpat  libintl  nano  openssh  openssl  perl-Error  perl>=5.14.0  perl-Authen-SASL  perl-libwww  perl-MIME-tools  perl-Net-SMTP-SSL  perl-TermReadKey
Optional Deps   : python: various helper scripts [installed]
                  subversion: git svn [installed]
Required By     : mingw-w64-x86_64-delta
Optional For    : None
Conflicts With  : None
Replaces        : git-core
Installed Size  : 36.68 MiB
Packager        : CI (msys2/msys2-autobuild/f368fb49/5960502489)
Build Date      : 24 Aug 2023 10:17:26
Install Date    : 29 Aug 2023 15:39:53
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature


saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ type git
git is /usr/bin/git

saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ type git.exe
git.exe is /usr/bin/git.exe

saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ echo "${PATH//:/$'\n'}" | grep "^$(dirname $(type -p git))$"
/usr/bin

saukrs@DESKTOP-O7JE7JE MSYS /D/Downloads/_debug
$ ls -l /usr/bin/git
-rwxr-xr-x 141 saukrs None 3497972 Aug 24  2023 /usr/bin/git
```

So `/usr/bin/git` (`/usr/bin/git.exe`) is present on disk, and `/usr/bin` is included in my `PATH`. I wonder if the same is true on your setup.

**Comment by elieux** [comment]
Have you checked the actual file (/usr/bin/git.exe)? I was gonna say it's maybe an antivirus deleting your file, but then Pacman says all files are present. In this case I think it's most likely that the shell has just cached the "not found" result and you need to start a new one (or use the command to clear the cache).

**Comment by felixf4xu** [comment]
thanks everyone for debugging the issue with me, now I have git.exe in C:\msys64\usr\bin

 I don't know which of the steps above worked, though.
