### ISSUE TITLE
ssh can't run because of missing msys-crypto-3.dll

### ISSUE THREAD

**Issue by felixf4xu** [msys2/MSYS2-packages#4621]
### Description / Steps to reproduce the issue

```
pacman -S openssh
```
>resolving dependencies...
looking for conflicting packages...
Packages (1) openssh-9.7p1-1
Total Installed Size:  5.74 MiB
:: Proceed with installation? [Y/n] Y
(1/1) checking keys in keyring                               [###############################] 100%
(1/1) checking package integrity                             [###############################] 100%
(1/1) loading package files                                  [###############################] 100%
(1/1) checking for file conflicts                            [###############################] 100%
(1/1) checking available disk space                          [###############################] 100%
:: Processing package changes...
(1/1) installing openssh                                     [###############################] 100%

```sh
 ssh.exe
```

>C:/msys64/usr/bin/ssh.exe: error while loading shared libraries: msys-crypto-3.dll: cannot open shared object file: No such file or directory

then 

`ldd /usr/bin/ssh.exe`

        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7ffbbc8b0000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7ffbbba00000)
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7ffbb9bd0000)
        msys-z.dll => /usr/bin/msys-z.dll (0x522fe0000)
        msys-gssapi-3.dll => /usr/bin/msys-gssapi-3.dll (0x42f53c0000)
        msys-2.0.dll => /usr/bin/msys-2.0.dll (0x180040000)
        msys-com_err-1.dll => /usr/bin/msys-com_err-1.dll (0x6219420000)
        msys-heimntlm-0.dll => /usr/bin/msys-heimntlm-0.dll (0x31fe970000)
        msys-asn1-8.dll => /usr/bin/msys-asn1-8.dll (0x6c901d0000)
        msys-crypto-3.dll => not found

### Expected behavior

I checked [libxcrypt](https://packages.msys2.org/package/libxcrypt?repo=msys&variant=x86_64) and it only has

>Files: /usr/bin/msys-crypt-2.dll

in the same folder (C:\msys64\usr\bin), I also have `msys-crypto-1.1.dll`

### Actual behavior

msys-crypto-3.dll => not found

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22631

### Are you willing to submit a PR?

yes

**Comment by Biswa96** [comment]
Are you using msys2 packages in git-for-windows or vice-versa? Did you update the packages?

**Comment by felixf4xu** [comment]
![image](https://github.com/msys2/MSYS2-packages/assets/84662027/eb3c71cb-9f94-4900-ab6e-839c09450e04)

After I manually installed `libopenssl`, it's fixed.

It's strange that `libopenssl` is required by `openssl-devel` and then required by `openssh`, why it's not installed (or upgraded) during my installation of `openssh`?

The screenshot above was run after installation of openssh, it showed that libopenssl is not installed, strange. 

If the dependency worked, it should show `libopenssl` is already installed after the installation of `openssh`, that's my understanding.

Yes, I tried to upgrade pacman before (to fix some other git.exe issue)

**Comment by Biswa96** [comment]
> why it's not installed (or upgraded) during my installation of `openssh`?

openssh depends on openssl. openssl depends on libopenssl. It should be already installed.

**Comment by felixf4xu** [comment]
just as a comment, I should run `pacman -Syu` to upgrade all the packages to avoid the issues.

**Comment by Biswa96** [comment]
> I should run `pacman -Syu` to upgrade all the packages to avoid the issues.

`pacman -Syu` will just update the packages if there is any update. It is not related to this issue. Only antivirus or antimalware like programs mess with msys2 files.

**Comment by jeremyd2019** [comment]
> > I should run `pacman -Syu` to upgrade all the packages to avoid the issues.
> 
> `pacman -Syu` will just update the packages if there is any update. It is not related to this issue. Only antivirus or antimalware like programs mess with msys2 files.

It could be related, if the installed packages are *really* old (say, if libopenssl didn't yet include msys-crypto-3.dll but msys-crypto-1.1.dll instead).  You really do need to update everything before installing new packages...
