### ISSUE TITLE
Unable to obtain the specified library( libpng )

### ISSUE THREAD

**Issue by sskyNS** [msys2/MSYS2-packages#4696]
### Description / Steps to reproduce the issue

$ pacman -S mingw-w64-x86_64-libpng
error: target not found: mingw-w64-x86_64-libpng

### Expected behavior

pacman -S mingw-w64-x86_64-libpng

### Actual behavior

$ pacman -S mingw-w64-x86_64-libpng
error: target not found: mingw-w64-x86_64-libpng

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

windowX64

### Are you willing to submit a PR?

yeah

**Comment by mmuetzel** [comment]
This is working for me.

Did you actually verify that your MSYS2 is up-to-date (run `pacman -Syu` potentially twice)? Or did you just check that box without verifying it?

**Comment by Biswa96** [comment]
Did you run `pacman -Syyu`before that command?

**Comment by mmuetzel** [comment]
I believe you are reporting that to the wrong repository.
This is about MSYS2. A build environment and package management for MinGW.
There is no package called `switch-libpng` in MSYS2 afaict.

Also that `ld.exe` doesn't seem to come from MSYS2.

What are you trying to do? Where did you get your build tools from?
