### ISSUE TITLE
add python-virtualenv package

### ISSUE THREAD

**Issue by shoober420** [msys2/MSYS2-packages#4698]
### Description / Steps to reproduce the issue

Please add the python-virtualenv package. The python and python-pip are already available, please consider adding python-virtualenv as well for a more complete python build environment under MSYS2.

### Expected behavior

Build Completion

### Actual behavior

Build errors when compiling packages that require python-virtualenv (https://github.com/zeldaret/mm).

make init
rm -f -r
rm -f -r build/n64-us/assets
rm -f -r assets/text/*.h
rm -f -r .extracted-assets.json
rm -f -r build/n64-us
rm -f -r asm data extracted
make -C tools clean
make[1]: Entering directory '/home/RavenWolf_-/mm/tools'
rm -f vtxdis
make -C ZAPD clean
make[2]: Entering directory '/home/RavenWolf_-/mm/tools/ZAPD'
rm -rf build ZAPD.out
make -C lib/libgfxd clean
make[3]: Entering directory '/home/RavenWolf_-/mm/tools/ZAPD/lib/libgfxd'
rm -f gfxd.o uc_f3d.o uc_f3db.o uc_f3dex.o uc_f3dexb.o uc_f3dex2.o libgfxd.a
make[3]: Leaving directory '/home/RavenWolf_-/mm/tools/ZAPD/lib/libgfxd'
make -C ZAPDUtils clean
make[3]: Entering directory '/home/RavenWolf_-/mm/tools/ZAPD/ZAPDUtils'
rm -rf build ZAPDUtils.a
make[3]: Leaving directory '/home/RavenWolf_-/mm/tools/ZAPD/ZAPDUtils'
make -C ExporterTest clean
make[3]: Entering directory '/home/RavenWolf_-/mm/tools/ZAPD/ExporterTest'
rm -rf build ExporterTest.a
make[3]: Leaving directory '/home/RavenWolf_-/mm/tools/ZAPD/ExporterTest'
make[2]: Leaving directory '/home/RavenWolf_-/mm/tools/ZAPD'
make -C fado clean
make[2]: Entering directory '/home/RavenWolf_-/mm/tools/fado'
rm -f -r build fado.elf
make[2]: Leaving directory '/home/RavenWolf_-/mm/tools/fado'
make -C buildtools clean
make[2]: Entering directory '/home/RavenWolf_-/mm/tools/buildtools'
rm -f mkdmadata mkldscript reloc_prereq
make[2]: Leaving directory '/home/RavenWolf_-/mm/tools/buildtools'
make[1]: Leaving directory '/home/RavenWolf_-/mm/tools'
make venv
make[1]: Entering directory '/home/RavenWolf_-/mm'
test -d .venv || python3 -m venv .venv || { rm -rf .venv; false; }
.venv/Scripts/python3 -m pip install -U pip
/bin/bash: line 1: .venv/Scripts/python3: No such file or directory
make[1]: *** [Makefile:368: venv] Error 127
make[1]: Leaving directory '/home/RavenWolf_-/mm'
make: *** [Makefile:392: init] Error 2

https://github.com/msys2/MINGW-packages/issues/21165#issuecomment-2169076512

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-26236

### Are you willing to submit a PR?

Yes

**Comment by MehdiChinoune** [comment]
Only MSYS2 packages required for MINGW-packages are added.
MSYS python-virtualenv is not required by any MINGW-packages.
Consider using one of the MINGW environments (UCRT64 or CLANG64)

**Comment by shoober420** [comment]
Unfortunately, trying to compile when using clang64 or ucrt64 with  all python-virtualenv packages installed gives the same build error.
