### ISSUE TITLE
unable to install packages 

### ISSUE THREAD

**Issue by Gaurav-2248** [msys2/MSYS2-packages#4772]
### Description / Steps to reproduce the issue

error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied

### Expected behavior

it should have shown available packages to install

### Actual behavior

showing errors:

error: failed to init transaction (unable to lock database)
error: could not lock database: Permission denied

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

uname

**Comment by Gaurav-2248** [comment]
cant install mingw

**Comment by Biswa96** [comment]
Use latest installer from msys2.org and exclude msys2 installation directory from realtime scanning in antivirus.
