### ISSUE TITLE
AUR packages support in MSYS?

### ISSUE THREAD

**Issue by dmikushin** [msys2/MSYS2-packages#4774]
Dear all,

I'm sorry that I understand very little in pacman-based packaging. I think the AUR repository of ArchLinux is of great value, and can enable a lot more uses of MSYS2. I understand that the use of AUR is blocked at least by name prefixes used by MSYS2. Is there any other issue beyond that? I also understand that some AUR packages cannot be compatible with MSYS2, e.g. those dependent on Linux kernel. But overall, how does this situation look to you? Is AUR worth to have, why it is still not supported, what needs to be done? Thanks!

**Comment by Biswa96** [comment]
AUR packages are for ArchLinux. If you can port those packages to native Windows platform those packages can be installed in msys2/mingw environment.

**Comment by dmikushin** [comment]
@Biswa96 I understand that AUR packages belong to ArchLinux, not to MSYS2. But do you agree it is an advantage to have the AUR packages transparently build-able in MSYS2? What sort of porting might be required?

**Comment by Biswa96** [comment]
> What sort of porting might be required?

Imagine porting a Linux specific software to BSDs. Similarly, the project needs to support native Windows platform or it's need to be ported to.

AUR is just a repository. One can create that kind of repository for msys2 also. There is no restriction.

**Comment by dmikushin** [comment]
Right, so I think you mean the porting work, that must fill the gap between Cygwin and MSYS2 and adapt the AUR packages for some native Windows system headers.

I wonder though why having the direct support of AUR in MSYS2 is not of your interest. Instead of many similar repositories, supporting one generic community repository seems to be a win for everyone, and eventually may lead to creation of a universal userspace spanned across a variety of kernels.
