### ISSUE TITLE
[libxml2] etc/xml/catalog:1: parser error : Document is empty

### ISSUE THREAD

**Issue by superbonaci** [msys2/MSYS2-packages#4786]
### Description / Steps to reproduce the issue

Install package in MSYS2 CLANG64.

### Expected behavior

Install package

### Actual behavior

$ pacman -S libxml2
resolving dependencies...
looking for conflicting packages...

Packages (1) libxml2-2.13.2-3

Total Download Size:   0.47 MiB
Total Installed Size:  1.18 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 libxml2-2.13.2-3-x86_64                                       485.1 KiB   443 KiB/s 00:01 [#########] 100%
(1/1) checking keys in keyring                                                             [#########] 100%
(1/1) checking package integrity                                                           [#########] 100%
(1/1) loading package files                                                                [#########] 100%
(1/1) checking for file conflicts                                                          [#########] 100%
(1/1) checking available disk space                                                        [#########] 100%
:: Processing package changes...
(1/1) installing libxml2                                                                   [#########] 100%
etc/xml/catalog:1: parser error : Document is empty

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### Are you willing to submit a PR?

No

**Comment by ognevny** [comment]
> Install package in MSYS2 CLANG64.
>
> $ pacman -S libxml2
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (1) libxml2-2.13.2-3

that's not CLANG64 package, the correct will be `mingw-w64-clang-x86_64-libxml2`

**Comment by superbonaci** [comment]
What's the difference, is that explained in the website?

**Comment by ognevny** [comment]
difference between environments https://www.msys2.org/docs/environments/

MSYS environment is an Cygwin in fact and usually used only for core packages (like `pacman`). it's recommended to use MINGW environments, which is more native for Windows

**Comment by superbonaci** [comment]
Thanks.
