### ISSUE TITLE
[db] installing libdb (6.2.32-5) breaks dependency

### ISSUE THREAD

**Issue by imperywun** [msys2/MSYS2-packages#4792]
### Description / Steps to reproduce the issue

pacman -S libdb don't install

### Expected behavior

I need install libdb package.

### Actual behavior

User@PCDESKTOP MSYS ~ /* and */ User@PCDESKTOP MINGW64 ~
$ pacman -S libdb
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libdb (6.2.32-5) breaks dependency 'libdb=5.3.28' required by db

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

**Comment by Biswa96** [comment]
> installing libdb (6.2.32-5) breaks dependency 'libdb=5.3.28' required by db

db depends on the same version of libdb, see https://github.com/msys2/MSYS2-packages/blob/master/db/PKGBUILD

Please update all the packages with `pacman -Syu` command before installing libdb.
