### ISSUE TITLE
mercurial hg --version not working

### ISSUE THREAD

**Issue by stahta01** [msys2/MSYS2-packages#4839]
### Description / Steps to reproduce the issue

Step 1. Install mercurial
Step 2. Run "hg --version"

### Expected behavior

Return the version inforomation

### Actual behavior

python related error message displayed

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

Tried to submit upgrade to 6.8.1 and the CI rejected with weird build error

**Comment by lazka** [comment]
See #4836
