### ISSUE TITLE
[git] git diff '--exit-code' and '--quiet' not working right

### ISSUE THREAD

**Issue by moskensoap** [msys2/MSYS2-packages#4843]
### Description / Steps to reproduce the issue

1. In any git repository, add a new file and stage it.
```
touch hello.c
git add hello.c
```
2.  To verify the staging, run:
```
git status
```
3.  Test the `--exit-code` and `--quiet` options with `git diff` in `MSYS bash`:
```
git diff --staged --exit-code

echo $?
```
```
git diff --cached --quiet

echo $?
```

### Expected behavior

According to the man page for `git diff`:
```
       --exit-code
           Make the program exit with codes similar to diff(1). That is, it exits with 1 if there were differences and
           0 means no differences.

       --quiet
           Disable all output of the program. Implies --exit-code. Disables execution of external diff helpers whose
           exit code is not trusted, i.e. their respective configuration option diff.trustExitCode or
           diff.<driver>.trustExitCode or environment variable GIT_EXTERNAL_DIFF_TRUST_EXIT_CODE is false.
```
Thus, `echo $?` should return 1 when a new file is staged.

### Actual behavior

However, the following commands produce unexpected results:

```
$ git diff --staged --exit-code
diff --git a/hello.c b/hello.c
new file mode 100644
index 0000000..979a1cd
--- /dev/null
+++ b/hello.c
@@ -0,0 +1 @@
+int main(){}

$ echo $?
0

$ git diff --cached --quiet

$ echo $?
0

```

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MSYS_NT-10.0-19045

### Are you willing to submit a PR?

I tried to figure out what was wrong, but I failed.

**Comment by lazka** [comment]
I can't reproduce. Both commands exit with 1 here.

**Comment by moskensoap** [comment]
Thank you so much for suggesting `$ which git`; it really sparked my thinking.

I realized that I was using another [git.bat](https://github.com/Microsoft/vscode/issues/4651) script to trick `MSYS2's Git` into working in VSCode, but it returns the **exit code** of running `git.bat` instead of the original `/usr/bin/git.exe`.

1. I will modify the `git.bat` to pass the exit code of the invoked `/usr/bin/git` back.
2. Before testing and resolving the issue, I will delete any custom scripts or executables to ensure a clean environment.

Thanks again for your help!
```
@echo off
setlocal

rem If you don't add path for msys2 into %PATH%, enable following line.
rem set PATH=c:\msys64\usr\bin;%PATH%

if "%1" equ "rev-parse" goto rev_parse

rem Run git command and capture its exit code
git %*
set EXIT_CODE=%ERRORLEVEL%
goto end

:rev_parse
rem Run git command silently, capture its exit code, and discard output
git %* >nul 2>&1
set TEMP_EXIT_CODE=%ERRORLEVEL%

rem Process the output with cygpath
for /f %%1 in ('git %*') do cygpath -w %%1

rem Restore the original git exit code
set EXIT_CODE=%TEMP_EXIT_CODE%

:end
rem Return the exit code of the git command
exit /b %EXIT_CODE%

```
