### ISSUE TITLE
ansible-vault requires the cryptography library in order to function

### ISSUE THREAD

**Issue by ArchGuyWu** [msys2/MSYS2-packages#4852]
### Description / Steps to reproduce the issue

ansible-vault encrypt_string

### Expected behavior

It works.

### Actual behavior

ERROR! ansible-vault requires the cryptography library in order to function

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-20348

**Comment by lazka** [comment]
cryptography requires rust, and rust doesn't support cygwin, so this isn't possible.
