### ISSUE TITLE
bash package in queue for upgrade but not uploaded 

### ISSUE THREAD

**Issue by angelog0** [msys2/MSYS2-packages#4853]
They are almost two weeks that `bash 5.2.032` is in [queue ](https://packages.msys2.org/queue) for upgrade but it is not uploaded. It oscillates between _Ready for upload_ and _waiting for dependencies_ 

Why this occurs?

Someone forgot to _push_ the button?

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-19045

**Comment by Biswa96** [comment]
> Someone forgot to _push_ the button?

Someone forgot to have patience or forgot how to use staging repository for testing 🙂

i.e. The core packages are kept some time in staging repository for testing. If you want to test the package you can enable staging repository in pacman.conf as explained here https://packages.msys2.org/queue
