### ISSUE TITLE
Can't install parallel

### ISSUE THREAD

**Issue by superbonaci** [msys2/MSYS2-packages#4868]
### Description / Steps to reproduce the issue

No idea why but fails:

```
$ pacman -S parallel
resolving dependencies...
looking for conflicting packages...

Packages (1) parallel-20231122-1

Total Installed Size:  4.57 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                                                     [####] 100%
(1/1) checking package integrity                                                                                                                                   [####] 100%
(1/1) loading package files                                                                                                                                        [####] 100%
(1/1) checking for file conflicts                                                                                                                                  [####] 100%
error: failed to commit transaction (conflicting files)
parallel: /usr/bin/parallel exists in filesystem
Errors occurred, no packages were upgraded.
```

### Expected behavior

install

### Actual behavior

no install

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

MINGW64_NT-10.0-22621

### Are you willing to submit a PR?

NO

**Comment by superbonaci** [comment]
Not owned by any package, could have been installed by installer:

```
$ pacman -Qo /usr/bin/parallel
error: No package owns /usr/bin/parallel
```

**Comment by ognevny** [comment]
> - [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

did you actually do what updating page tells to do?

**Comment by superbonaci** [comment]
Not sure which part, any idea?

**Comment by Biswa96** [comment]
Just remove the `/usr/bin/parallel` file and run `pacman -Syyu` again.

```
$ pacman -Qo /usr/bin/parallel
/usr/bin/parallel is owned by parallel 20231122-1
```

**Comment by superbonaci** [comment]
I renamed `/usr/bin/parallel` to `/usr/bin/parallel.bak` but that's a bug, why is there in the first place?

**Comment by Biswa96** [comment]
> I renamed `/usr/bin/parallel` to `/usr/bin/parallel.bak` but that's a bug, why is there in the first place?

That's you have to figure out. It is not related to msys2.

**Comment by mesvam** [comment]
moreutils installs an exe at `/usr/bin/parallel.exe`, parallel installs a perl script to `/usr/bin/parallel`. These seem to conflict since MSYS2 strips the `.exe`. When I install `parallel` first, then `moreutils` it works fine, but not the other way around

related? https://www.msys2.org/wiki/Devtopics/#fix-pacman-errors-wrt-conflicts-in-binfoo-vs-binfooexe

**Comment by superbonaci** [comment]
I think the issue is that the program adds automatically the .exe extension even if not wanted.

**Comment by mesvam** [comment]
@Biswa96 can we reopen this since it's still a problem? two packages with conflicting files doesn't seem right...
