### ISSUE TITLE
[coreutils] uname from MSYS2 says that ARM64 processor is X64

### ISSUE THREAD

**Issue by brunvonlope** [msys2/MSYS2-packages#4960]
### Description / Steps to reproduce the issue

Running the `uname -m` command on CLANGARM64 shell gives wrong output 

### Expected behavior

aarch64

### Actual behavior

x86_64

### Verification

- [X] I have verified that my MSYS2 is up-to-date before submitting the report (see https://www.msys2.org/docs/updating/)

### Windows Version

10.0.26100.0

**Comment by brunvonlope** [comment]
@Wormnest @hmartinez82 ping

**Comment by Biswa96** [comment]
This is expected result. The cygwin process is x86_64 architecture.

**Comment by brunvonlope** [comment]
Closing as expected. Multi arch MSYS2 would be welcome anyway

**Comment by Biswa96** [comment]
If you want to check something related to CLANGARM64 there are some other ways to do it.

**Comment by brunvonlope** [comment]
> If you want to check something related to CLANGARM64 there are some other ways to do it.

@Biswa96 I would like to check the CPU architecture without using the well know internal MSYS2 variables

**Comment by Biswa96** [comment]
Where do you want to check CPU architecture? in a program or in a script?

**Comment by brunvonlope** [comment]
Script

> Where do you want to check CPU architecture? in a program or in a script?

.sh script

**Comment by Biswa96** [comment]
What does `PROCESSOR_ARCHITECTURE` environment variable show?

**Comment by brunvonlope** [comment]
That variable isn't reliable: https://gitlab.gnome.org/GNOME/gimp/-/issues/12185

I later found in a MS Learn page that this is valuated to AMD64 (x64) no matter what.

We can figure out with Wmi cmdlets but they don't work on bash, of course.

**Comment by Biswa96** [comment]
@jeremyd2019 might have some idea.

**Comment by driver1998** [comment]
`PROCESSOR_IDENTIFIER` will still starts with `ARM64` even though `PROCESSOR_ARCHITECTURE` is valuated to `AMD64`.

Also one way to workaround it: 
```
cmd.exe /c "start /wait /b /machine arm64 cmd.exe /c echo %PROCESSOR_ARCHITECTURE%"
```
