### ISSUE TITLE
Icon/logo improvements

### ISSUE THREAD

**Issue by elieux** [msys2/MSYS2-packages#568]
@kusma suggested that the current icons are not ideal.

I think the _white italic M on purple background_ (as seen on the 16x16 variant) is the actual logo of MSYS2 in terms of user recognition, so there should be no problem in changing the other features of the (larger) icons.

> it looks like it says "M2sys" rather than "MSYS2"
> the way the number two partially overlaps the M, it's shape is hard to make out
> the position of the 2 didn't have to be put above "sys"

The M2sys layout comes from the [original Msys icon](https://www.google.com/search?q=msys.ico&tbm=isch). We could move the "2" to to bottom-left corner maybe.

> Also, there's something funky going on with the first 's' in "sys"

The funky "s" may be an aliasing issue, or may have come from the original as well. If the "s" can be fixed, I would not be opposed.

> the color-choice is rather... special
> it's the combination of the purple background and the orange 2 that creates an issue
> The luminosity of those colors are way too similar to quickly be told apart.

I've grown fond of the purple background. I don't care about the orange in the "2". I think it was supposed to be of somewhat intense color to make it stand out.

https://github.com/elieux/msys2-launcher/ mingw{32,64}.ico

> Those are a bit better
> The bigger difference in hue makes the background-clash less of a problem
> But I'm not really loving that orange stroking, it makes the edges look a bit more fuzzy than they should need to...
> It works OK-ish on the blue background, but on the other one it blends a bit too much in

**Comment by elieux** [comment]
The capitalization (or lack thereof) of "sys" in the logo could be fixed as well. We want to be known as **MSYS2** after all.

**Comment by hcorion** [comment]
Of course, there is also the icons for mingw64 and mingw32, I think the reason we only use the M is because it is the first letter in msys and mingw. Just my two cents.

**Comment by dscho** [comment]
I guess this ticket can be closed now, as there is now too much "brand recognition" associated with the logo.

**Comment by sskras** [comment]
Again, not **completed** but rather **not planned** (or rather Too Late / FAILED:)
