### ISSUE TITLE
[WinXP] Doesn't work when installed on drive D:\ 

### ISSUE THREAD

**Issue by Forkest** [msys2/MSYS2-packages#603]
The symptoms are just like in #567, on `pacman -Sy pacman` it silently fails with these messages:

```
error: cannot remove /usr/bin/pacman.exe (Permission denied)
warning: warning given when extracting /usr/bin/pacman.exe (Could not unlink)
```

And despite them the package is considered installed after this, when in fact the binary is the old one.

The same kind of problem appear when trying to update anything else.

**Comment by DavidEGrayson** [comment]
My MSYS2, which I installed some time last year, is installed in `D:/msys64` and things work fine for me

**Comment by Forkest** [comment]
I use 32-bit version on Windows XP, perhaps this matters.

**Comment by mati865** [comment]
Win 10 here, MSYS2 installed `D:/msys64` and no problems here.

**Comment by wiiaboo** [comment]
Make sure that drive's file system is NTFS. A lot of packages use hard links which don't work with FAT32/exFAT drives.

**Comment by Forkest** [comment]
Of course it's NTFS, it's just a non-system partition of the same drive, nothing non-standard. Thanks for the try though.

**Comment by EchoOfSoul** [comment]
`D:/msys32` and no problems occures so far

**Comment by Forkest** [comment]
Thanks for the feedback. So it looks like the problem is with Windows XP, I'll update the title.

Meanwhile I tried to update everything on C: and then move msys32 to D:, but to no avail.
pacman --debug and --verbose didn't add anything useful too.

**Comment by mati865** [comment]
You could try to change permissions (maybe there is read only mark) for msys directory. If this doesn't help temporary turn off antivirus.

**Comment by EchoOfSoul** [comment]
there is an `old sf wiki` to try [re-installing](https://sourceforge.net/p/msys2/wiki/MSYS2%20re-installation/)

**Comment by Forkest** [comment]
I've unchecked indeterminate-state "Read only" on "msys32" and applied it all to files and subdirectories, it led to no changes with pacman, and it's indeterminate again when I open Properties next time. But I suppose there's no problem with permissions: first, it works Ok when moved to C:\, second, actually all other files except running executables are updating successfully.

Re-installation of core packages by that procedure says that everything is up to date. And I have nothing else to do there, since I don't have any custom packages installed (pacman doesn't work), it's a fresh new install.

I believe I opened an issue in a wrong repository, perhaps it should've been [msys2-pacman](https://github.com/alexpux/msys2-pacman/issues).

**Comment by hiroakit** [comment]
@Forkest @Alexpux @lazka 

Would you like to close this issue?

**Comment by hiroakit** [comment]
Thank you labeling.

**Comment by Forkest** [comment]
Latest versions do not work on WinXP anymore anyway.
