### ISSUE TITLE
msys2-i686-20160719 not installing

### ISSUE THREAD

**Issue by jpsdr** [msys2/MSYS2-packages#657]
Hello.

When i start msys2-i686-20160719.exe, nothing happens.
When i start msys2-i686-20160205.exe, install is doing properly.
I'm under Windows XP x86. Has Windows XP support been dropped for the MSYS2 installer package ?

**Comment by Alexpux** [comment]
Well we use Qt Installer Framework for our installers and maybe XP is not supported anymore. Try to get more info about failure

**Comment by jpsdr** [comment]
I have no faillure information to provide, it's just that nothing happens. I double-click the installer, and.... .... .... .... .... .... nothing. Nothing in task manager, nothing anywhere.

**Comment by jpsdr** [comment]
The PC with Windows XP was my PC at work. Just tested with my PC at home, under Windows 7 x86 and Windows 7 x64, with the x86 and x64 installer for Windows 7 x64, same behavior. When i start the installer, absolutely nothing happens.

**Comment by mati865** [comment]
The same on Win 10 64-bit.
The only error I could catch:
```
Cannot open file "C:\Users\mati865\Downloads\installer.dat" for reading: No such file or directory
```

**Comment by Alexpux** [comment]
Ok will see tomorrow maybe

**Comment by jpsdr** [comment]
When you look at the size of the previous installers (around 50MB-60MB), the size of the actual .tar.xz (around 40MB) and the size of the actual installer (around 25MB), you can guess that, maybe, something is missing within the installer (like the data to install...).

**Comment by murdak** [comment]
I have the same issue on my Windows 10 64 bit using the 201607 installer.
The 201602 installer is working fine but it has some minor bugs like the shortcut is wrong and some errors during updating of packages.

**Comment by ianweatherhogg** [comment]
My experiences:

1 - `msys2-x86_64-20160205` worked (Lenovo T420 Windows 10 64 Pro - fresh Windows 10 ISO installed on HDD)
2 - `msys2-x86_64-20160205` failed (same machine as above, post upgrade from Windows 7 to Windows 10). I cannot be 100% here since I've since rerolled the HDD but I'm pretty sure it was this version which failed.
3 - `choco install msys2` failed all the time (it's using version: `msys2-x86_64-20150916` [link](https://github.com/userzimmermann/choco-packages/blob/master/msys2/CHANGES.md))
4 - Have not tried `msys2-x86_64-20160719` (I've only just realised the [distrib](http://repo.msys2.org/distrib/x86_64/) link exits)
5 - `msys2-x86_64-20160205` worked on an upgraded Windows 7 64 Home to Windows 10 (HDD NOT rerolled with fresh Windows 10 ISO) - on an HP laptop I had laying around.

**Comment by krcools** [comment]
I run Windows 10, 64bit. I experience the same issue as the OP. The 20160205 installer works as expected.

**Comment by elieux** [comment]
Thanks, people. We know the new installers don't work.

**Comment by mati865** [comment]
Would you like to try new installer https://msys2.github.io?

**Comment by jpsdr** [comment]
Hello

> Would you like to try new installer https://msys2.github.io?

It's still not working properly.
I've tested the x86 version, totaly uninstalled my previous version, and 
use installer to install on G:\msys32
(Yes, i'm not installing it on C drive).
The first thing i've noticed, it's that previously during the 1rst 
launch, a lot of things are done,
ending with a message asking to close the bash windows and restart it. 
Here, nothing...

I've first done "pacman -Syuu", it updated the database, but nothing 
installed, normal.

Then, i've done the following :

pacman -S --needed make autoconf autogen diffutils git p7zip patch perl 
python2 ruby subversion yasm wget mingw-w64-i686-gcc 
mingw-w64-i686-gettext mingw-w64-i686-crt-git mingw-w64-i686-libtool 
mingw-w64-i686-libjpeg-turbo mingw-w64-i686-libpng 
mingw-w64-i686-libxml2 mingw-w64-i686-tools-git mingw-w64-i686-glib2 
pkg-config mingw-w64-i686-cmake


Result was a big faillure :

(106/106) vérification des clés dans le trousseau 
[#####################] 100%
(106/106) vérification de l’intégrité des paquets 
[#####################] 100%
(106/106) chargement des fichiers des paquets 
[#####################] 100%
(106/106) analyse des conflits entre fichiers 
[#####################] 100%
erreur?: la validation de la transaction a échoué (conflit de fichiers)
mingw-w64-i686-libiconv?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-gmp?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-libwinpthread-git?: /mingw32 est déjà présent dans le 
système de fichiers
mingw-w64-i686-gcc-libgfortran?: /mingw32 est déjà présent dans le 
système de fichiers
mingw-w64-i686-gcc-libs?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-bzip2?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-zlib?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-binutils?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-headers-git?: /mingw32 est déjà présent dans le système 
de fichiers
mingw-w64-i686-crt-git?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-isl?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-mpfr?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-mpc?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-windows-default-manifest?: /mingw32 est déjà présent dans 
le système de fichiers
mingw-w64-i686-winpthreads-git?: /mingw32 est déjà présent dans le 
système de fichiers
mingw-w64-i686-gcc?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-expat?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-gettext?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libtool?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libjpeg-turbo?: /mingw32 est déjà présent dans le système 
de fichiers
mingw-w64-i686-libpng?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-xz?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-libxml2?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-tools-git?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-wineditline?: /mingw32 est déjà présent dans le système 
de fichiers
mingw-w64-i686-pcre?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-libffi?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-glib2?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-c-ares?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libidn?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libmetalink?: /mingw32 est déjà présent dans le système 
de fichiers
mingw-w64-i686-libtasn1?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-p11-kit?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-ca-certificates?: /mingw32 est déjà présent dans le 
système de fichiers
mingw-w64-i686-openssl?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libssh2?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libtre-git?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-libsystre?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-nettle?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-gnutls?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-rtmpdump-git?: /mingw32 est déjà présent dans le système 
de fichiers
mingw-w64-i686-jansson?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-nghttp2?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-curl?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-jsoncpp?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-lz4?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-lzo2?: /mingw32 est déjà présent dans le système de fichiers
mingw-w64-i686-libarchive?: /mingw32 est déjà présent dans le système de 
fichiers
mingw-w64-i686-cmake?: /mingw32 est déjà présent dans le système de fichiers
Des erreurs se sont produites, aucun paquet n’a été mis à jour.
=> Errors occured, no pack has been updated

est déjà présent dans le système de fichiers => is already present in 
the system file


----------------------------------------------------
And to boldly go where no man has gone before...
http://jpsdr.free.fr
https://github.com/jpsdr

**Comment by Alexpux** [comment]
You must completely remove msys folder from previous installation. Seems you done new MSYS2 install in already present folder with packages

**Comment by jpsdr** [comment]
Le 22/09/2016 à 19:47, Алексей a écrit :
> You must completely remove msys folder from previous installation. Seems
> you done new MSYS2 install in already present folder with packages
No... The previous msys folder has been totaly removed.
I've even tried it twice.
And each time, of course, the folder was totaly removed.

----------------------------------------------------
And to boldly go where no man has gone before...
http://jpsdr.free.fr
https://github.com/jpsdr

**Comment by Alexpux** [comment]
Does your "G" drive have NTFS partition?

**Comment by jpsdr** [comment]
> Does your "G" drive have NTFS partition?
Yes.

----------------------------------------------------
And to boldly go where no man has gone before...
http://jpsdr.free.fr
https://github.com/jpsdr

**Comment by Alexpux** [comment]
As workaround pass "--force" to pacman

**Comment by jpsdr** [comment]
Le 23/09/2016 à 19:29, Алексей a écrit :
> As workaround pass "--force" to pacman
My workaround has been to restore the msys2 directory i've saved/created 
from the 20160719 package, and with it, everything worked fine again.

----------------------------------------------------
And to boldly go where no man has gone before...
http://jpsdr.free.fr
https://github.com/jpsdr
