### ISSUE TITLE
git is broken: "fatal: cannot use .git/info/exclude as an exclude file"

### ISSUE THREAD

**Issue by tom-hines** [msys2/MSYS2-packages#748]
Hello.  git seems to be broken for me.  There are at least two problems.  The first is that it creates an exclude file in dos format, and then later complains about it.  No idea what the 2nd problem is.  This happens in both MSYS and MINGW64 shells.  Here is an excerpt:

```
$ pacman -Q git
git 2.10.1-1

$ git init
Initialized empty Git repository in /home/tom/tmp/ftgl-2.1.3~rc5/.git/

$ git add .
fatal: cannot use .git/info/exclude as an exclude file

$ dos2unix .git/info/exclude
dos2unix: converting file .git/info/exclude to Unix format...

$ git add .
error: short read: No such file or directory
error: docs/images/metrics.png: failed to insert into database
error: unable to index file docs/images/metrics.png
fatal: adding files failed
```

**Comment by mati865** [comment]
Could be related to https://github.com/Alexpux/MSYS2-packages/issues/735
Is git 2.10.2 from https://git-scm.com affected?

**Comment by tom-hines** [comment]
[https://git-scm.com](https://git-scm.com) git 2.10.2 works.  How do I get MSYS2 git 2.10.2?

**Comment by forgottenswitch** [comment]
> This happens in both MSYS and MINGW64 shells.
It would be clearer to show `which git` output in both.
There are tree git-s: [msys2 git](https://github.com/Alexpux/MSYS2-packages/tree/master/git), [mingw-stable](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-git), [mingw-latest](https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-git-git)

**Comment by mati865** [comment]
You can compile it form this PR https://github.com/Alexpux/MSYS2-packages/pull/741 and tell us if it helps.

**Comment by totszwai** [comment]
This is still happening, this messes up my linux environment.
I originally created a directory tree for my linux setup had all the repos checked out, then I accidentally ran some `git` commands under MSYS2 environment, ever since then I get this error...

As a workaround, I had to go a `git pull` on all of my repos in a linux shell, then perform a `wsl --shutdown` in order to get it working again.

**Comment by Biswa96** [comment]
This issue can not be reproduced. Please make sure all packages are updated. Also make sure that you are not using msys2 packages in git-for-windows environment or vice-versa.
