### ISSUE TITLE
Realpath not consistent with other systems

### ISSUE THREAD

**Issue by nunziotocci** [msys2/MSYS2-packages#763]
This file:
```
#include <stdio.h>
#include <stdlib.h>

#include <limits.h>

char buf[PATH_MAX + 1];
char *res = NULL;

int main(int argc, char **argv) {
	res = realpath("./doesntexist", buf);
	if (res != NULL) {
		printf("%s\n", buf);
	} else {
		printf("%s\n", buf);
		perror("realpath");
		exit(EXIT_FAILURE);
	}
	return 0;
}

```
When run on a mac has this output:
```
/Users/nunzio/doesntexist
realpath: No such file or directory
```
But on MSYS2, it has this output:
```

realpath: No such file or directory
```

This is preventing me from porting https://github.com/workflowproducts/postage to MSYS2.

**Comment by elieux** [comment]
I know this is pretty old, but https://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html says:

> char *realpath(const char *restrict file_name, char *restrict resolved_name);

> The realpath() function shall fail if:
> [ENOENT]
> A component of file_name does not name an existing file or file_name points to an empty string.

> If the resolved_name argument is not a null pointer and the realpath() function fails, the contents of the buffer pointed to by resolved_name are undefined.

**Comment by nunziotocci** [comment]
Hmm, I didn't know that was undefined behavior. I ended up porting the program straight to MSVC using pieces of OpenBSD's POSIX compatibility code.

If this isn't actually a bug, go ahead and close the issue. I'm good at this point.
