### ISSUE TITLE
please add zstd package

### ISSUE THREAD

**Issue by inikep** [msys2/MSYS2-packages#774]
Zstd, short for Zstandard, is a fast lossless compression algorithm, targeting real-time compression scenarios at zlib-level compression ratio.

Zstd is already included in most important Linux/*BSD distributions:
https://github.com/facebook/zstd/issues/320

Zstd works fine with MinGW/MSYS2 (just use `make`) and official Windows binaries were compiled with MinGW/MSYS2:
https://github.com/facebook/zstd/releases/download/v1.1.2/zstd-v1.1.2-win64.zip

Please add zstd package to MSYS2.

**Comment by XVilka** [comment]
Already done: https://github.com/msys2/MSYS2-packages/tree/master/zstd

**Comment by inikep** [comment]
Thanks
