### ISSUE TITLE
Add option to disable path mangling when calling non-msys2 binaries

### ISSUE THREAD

**Issue by gintas** [msys2/MSYS2-packages#84]
MSYS2 binaries automatically mangle arguments when calling non-MSYS binaries, applying a set of heuristics. Heuristic transformations are ugly; not being able to disable the heuristic transformations is just nasty. I've run into a few cases already in a just few days where the path mangling was causing trouble, and it is particularly annoying to have to work around.

For reference, the arguments are mangled here:

https://github.com/Alexpux/Cygwin/blob/6e95f9f5eab763ba36c8d5c62a22a4db9cca1d7f/winsup/cygwin/spawn.cc#L416

How about making it possible to disable the mangling by setting an environment variable? Something like CYGWIN_DISABLE_ARGUMENT_MANGLING=1. The environment variable would be accessible from anywhere in the code and thus should be unintrusive regarding the rest of the cygwin code, the patch should be just a couple lines.

**Comment by LubosPintes** [comment]
I have one question concerning this:
I have my path set up so that I can use git with another tools from MSYS2.
Recently I tried magit, and it always failed with "xxx is not a directory", because paths are mangled and Emacs is confused.
No matter what I did, it always failed.

Now I suppose that I just cannot use git from MSYS2 with magit, is this true?
Note I don't want to use Emacs from MSYS2, because I made my Emacs "portable", that only means I configured "home" directory to be under emacs\home.

**Comment by DavidEGrayson** [comment]
## [Documentation for MSYS2_ARG_CONV_EXCL](https://sourceforge.net/p/msys2/wiki/Porting/)

If you are landing on this page because it's the top Google hit for `MSYS2_ARG_CONV_EXCL` and you are looking for documentation, go here:

https://sourceforge.net/p/msys2/wiki/Porting/

**Comment by 573** [comment]
@DavidEGrayson https://sourceforge.net/p/msys2/wiki/Porting/ is behind an auth wall.

**Comment by mati865** [comment]
@573 moved here https://github.com/msys2/msys2/wiki/Porting

**Comment by parleer** [comment]
Example of MSYS incorrectly mangling paths:

docker run --rm mysql:5.7 /usr/bin/mysqldump --host=hostname--user=user--password=password-v dbname > db.sql


And pretty much any other command involving docker. Docker containers expect real POSIX paths, but docker on windows is not an MSYS executable, so paths are getting mangled and the container doesn't know what to do.

Example error:

/usr/local/bin/docker-entrypoint.sh: line 215: /C:/Program Files/Git/usr/bin/mysqldump: No such file or directory

**Comment by mingwandroid** [comment]
There's no correct or incorrect about this I am sorry to say. At least not in general. It's a simple set of rules that are followed. This thread also explains how to disable conversion. Did I miss somethig?

**Comment by mbacs** [comment]
# Here is a perfect example for  the option to disable path mangling.
# All other Amazon ssm parameter management commands seem to work.
# For AWS SSM, , the path is NOT a file path. It is an AWS SSM Parameter path.

$ aws ssm get-parameter  --name "/subfolder/PARAMETER1" --with-decryption
An error occurred (ParameterNotFound) when calling the GetParameter operation:

# To AWS SSM get-parameter work, change to mangled form. 
# This is now different than AWS CLI on any other platform including CMD and PowerShell. 
$ aws ssm get-parameter  --name "//subfolder\PARAMETER1" --with-decryption                                                           {
    "Parameter": {
        "Name": "/subfolder/PARAMETER1",
        "Type": "SecureString",
        "Value": "TestSetParameter",
        "Version": 2,
        "LastModifiedDate": 1564611241.75,
        "ARN": "arn:aws:ssm:us-west-2:999999999999:parameter/subfolder/PARAMETER1"
    }
}
