### ISSUE TITLE
mingw64/mingw-w64-x86_64-devhelp is 4 years behind

### ISSUE THREAD

**Issue by liberforce** [msys2/MSYS2-packages#875]
Current version is 3.8.2-2, which is 4 years old (may 2013).
Last stable version is 3.24.0, releases a month ago.

Is there something blocking the upgrade (appart from manpower) ?

**Comment by elieux** [comment]
Doesn't look like anything's blocking it.

**Comment by lazka** [comment]
My guess is it has something to do with https://github.com/Alexpux/MINGW-packages/issues/1089

**Comment by sskras** [comment]
> mingw64/mingw-w64-x86_64-devhelp package was removed.

Any reason of doing so (or at least commit of the removal) ?

**Comment by lazka** [comment]
https://github.com/msys2/MINGW-packages/pull/5375

Webkgitgtk stopped building in 2018 and is no longer supported by upstream since 2016

**Comment by sskras** [comment]
Thank you @lazka!
