### ISSUE TITLE
Building cmake 3.8.1 on msys2

### ISSUE THREAD

**Issue by Partha1b** [msys2/MSYS2-packages#911]
I am trying to build cmake 3.8.1 (the latest version) because I can't simply use the Windows version available at cmake.org. I get error like
```
/bin/sh: /Z/foss/cmake/cmake-3.8.1-win32-x86/bin/cmake.exe: No such file or
  directory
```

My cmake is loaded on my Z: drive and mounted at /usr/cmake.

Anyway, while trying to build cmake, I can't get passed the error:
```
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
Z:/src/gnome/cmake-3.8.1
CMake Error: Error executing cmake::LoadCache(). Aborting.
```
Needless to say, my source folder is /usr/src/gnome/cmake-3.8.1 (Z:/src is mounted on /usr)
 My environment:
```
$ uname -a
MSYS_NT-10.0 Partha-gigabyte 2.6.0(0.304/5/3) 2016-09-07 20:45 x86_64 Msys
```
My commandline:
```
CFLAGS="-O3 -ffast-math -ftree-vectorize" CXXFLAGS="-O3 -ffast-math -ftree-vectorize -std=c++14" ./bootstrap --prefix=/opt/cmake --no-qt-gui --system-zlib --system-bzip2 --system-curl --system-expat --system-liblzma &&make && make install
```
I made 2 patches to get to the above error:

1. In files Source/cmFileCommand.cxx 
Added @Line 19
```
#if defined(_WIN32)
#include <wchar.h>
#include <winnls.h>
#endif
```
and in File ./Source/kwsys/EncodingCXX.cxx, replaced all occurrences (4) of KWSYS_ENCODING_DEFAULT_CODEPAGE with LOCALE_IDEFAULTCODEPAGE

Thanks,
Partha

**Comment by gena01** [comment]
Since latest cmake package 3.9.6 is available should this one be closed?

**Comment by mfld-fr** [comment]
Same comment as now `cmake` package is 3.17.x ?

**Comment by Partha1b** [comment]
My apologies. I had no idea this was still open. Please close.

**Comment by mfld-fr** [comment]
Thanks @Partha1b !
