### ISSUE TITLE
[Package request] Neovim

### ISSUE THREAD

**Issue by dukebarman** [msys2/MSYS2-packages#955]
Would it be possible to add neovim package? https://wiki.archlinux.org/index.php/Neovim

**Comment by ErichDonGubler** [comment]
Honestly, it's pretty easy to make a PKGBUILD -- we just need one that can actually build `neovim`, and then have a PR made for it!

**Comment by ErichDonGubler** [comment]
A good template to build from would probably be the [Arch Linux PKGBUILD for `neovim`](https://www.archlinux.org/packages/community/x86_64/neovim/) -- some tweaks will probably get it working, dependent package availability notwithstanding.

**Comment by XVilka** [comment]
Neovim itself is pretty simple. Problems start with its endless dependencies...

**Comment by Logarithmus** [comment]
@dukebarman me and my friend have just successfully built `libtermkey`, which is one of the dependencies for `nvim`
